cowprotocol/services

- .github/workflows/deploy.yaml
- Cargo.lock
- LICENSE-MIT
- README.md
- crates/alerter/src/main.rs
- crates/contracts/Cargo.toml
- crates/contracts/src/bin/vendor.rs
- crates/e2e/Cargo.toml
- crates/model/Cargo.toml
- crates/model/src/order.rs
- crates/orderbook/Cargo.toml
- crates/shared/Cargo.toml
- crates/shared/src/lib.rs
- crates/shared/src/sources/balancer_v2/swap.rs
- crates/solver/Cargo.toml
- crates/solver/src/in_flight_orders.rs
- crates/solver/src/settlement.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/solver/baseline_solver.rs
- crates/testlib/Cargo.toml
- docker/Dockerfile.binary
This PR just "Cow-ifies" the repository. It tries to:
- Replace references to GPv2 into Cow Protocol
- Replace URLs to the new `cow.fi` ones
- Replace issue links to the ones created in this repo.
- Update dependencies to use the github.com/cowprotocol org forks
- Contract vendoring with new repo pacakges (**Note**, the `@cowprotocol/token@1.1.0` package is not deployed on NPM pending https://github.com/cowprotocol/token/pull/1 - feel free to review that PR as well 😄).
CI - no code or logic changes, just metadata things.
<details><summary>Run the vendoring script to make sure that the contract sources are correct.</summary>
```
% cargo run -p contracts --features bin --bin vendor
[2022-04-07T09:52:59Z INFO  vendor] vendoring contract artifacts to …
```
> Cow-ify repository

- crates/alerter/Cargo.toml
- crates/alerter/src/main.rs
#132 introduced regressions that caused the order alerter to constantly fail to retrieve orders. This is because the public API URL contains `/$network` path prefix that wasn't supported by the alerter.
This PR adds support for this. Basically, it just `join`s instead of replacing the path entirely with `set_path`.
Run the alerter and see it make successful API requests:
```
% cargo run -p alerter -- --min-order-age 1 --time-without-trade 1
Finished dev [unoptimized + debuginfo] target(s) in 0.09s
Running `target/debug/alerter --min-order-age 1 --time-without-trade 1`
2022-04-07T11:24:09.456Z  INFO alerter: running alerter with Arguments {
time_without_trade: 1s,
min_order_age: 1s,
min_alert_interval: 1799.99997952s,
errors_in_a_row_before_alert: 5,
orderbook_api: …
```
> Support base URL with path

- crates/shared/src/bad_token/trace_call.rs
At the moment the vast majority of tokens get rejected by the `TraceCallDetector` because of `no pool` or `transaction failed`. `no pool` is self explanatory but `transaction failed` can indicate an error during transfer into or out of the settlement contract.
To better debug why a token got rejected by the `TraceCallDetector` it makes sense to provide as much information as possible for `transaction failed` errors.
This could help us identify some low hanging fruit for supporting more tokens (reduce number of false positives).
This PR does 2 things:
1. Add the underlying error message when a transfer fails.
2. Have unique error logs for errors during transfer in and transfer out of the settlement contract.
manual test with a token that just returned `transaction failed` before:
``` …
```
> Improve error logging for TraceCallDetector

- crates/shared/src/lib.rs
- crates/shared/src/univ3_router_api.rs
Api for https://github.com/cowprotocol/univ3-api which will be used as a solver.
CI
> Add univ3 router api

- crates/solver/src/driver.rs
- crates/solver/src/metrics.rs
This PR introduces difference between positive gas saved (actual gas saved) and negative gas saved (gas wasted).
Negative gas saved happens when transaction with access lists gets reverted.
What I actually want is to work with `[metric_name]_sum` values, for which, I cant apply rate function in case of negative values.
https://prometheus.io/docs/practices/histograms/
This way I think we have the most flexibility.
> Make difference between gas saved and gas wasted

- crates/shared/src/univ3_router_api.rs
- crates/solver/src/settlement.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/uni_v3_router_solver.rs
- crates/solver/src/solver/univ3_router_solver.rs
Next step is to integrate this with the command line arguments.
Manually ran the ignored test
> Add univ3-router solver

- crates/shared/src/price_estimation/competition.rs
Add some extra logging so we get visibility on the intermediate results in addition to the winner.
CI
> Log intermediate competition price estimator results

- crates/shared/src/http_client.rs
- crates/shared/src/http_solver.rs
- crates/shared/src/lib.rs
Part of https://github.com/cowprotocol/services/issues/151 .
A large response could exhaust our memory. We protect against this by limiting the size of the response to 10 MB.
new unit test
> Limit http solver response size

- crates/solver/src/settlement/settlement_encoder.rs
Fixes https://github.com/cowprotocol/services/issues/163
@josojo wrote
> I think we should make sure that the for a partially fillable order the "executed amount <= sell amount" and for a killorfill order "executed amount== sell_amount".
But I think for buy orders the executed amount refers to the buy amount.
Adapted the existing tests which showed that the verification worked
> Verify order executed amount in settlement encoder

- crates/e2e/tests/e2e/services.rs
- crates/orderbook/src/main.rs
- crates/orderbook/src/orderbook.rs
Fixes #129
The "Matched Orders" panel in Grafana currently includes liquidity orders. If there are many liquidity orders the graph for matched orders declines significantly making it seem like our service is experiencing issues.
This can be solved by introducing a metric which only tracks how many user orders have been created. If we use this metric in the Grafana panel the "Matched Orders" graph will better reflect the user experience of the service.
Local test submitting 1 user order and 1 liquidity order.
New metric counting user orders:
```
gp_v2_api_orderbook_user_orders_created 1
```
Metric we previously in the Grafana panel
```
gp_v2_api_api_requests_complete{method="v1/create_order",status_code="201"} 2
```
This shows that the new metrics is working and ignores liquidity orders.
> Drop liquidity orders from matched orders metric

- .github/workflows/cla.yaml
This PR adds a workflow for verifying CLA signatures for external contributors.
I detailed the [steps for integrating here](https://github.com/cowprotocol/cla/blob/main/README.md#github-action-setup) for other projects to use.
Basically, this workflow will first:
- Fetch the collaborators (AFAICT team members that we have added to the repo) with the GitHub API.
- Add them and `*[bot]` to the list of "allowed" GitHub users that don't need to sign the CLA.
- Use the [`contributor-assistant/github-action`](https://github.com/contributor-assistant/github-action) action to verify the CLA is signed. I used this action as it seemed to be, by far, the most popular one in the market place and keeps the signature file in-tree.
~~Checkout the CLA file that was created.~~ It turns out that the …
> Add CLA Verification Worflow

- .github/workflows/cla.yaml
- COPYRIGHT.md
- crates/testlib/Cargo.toml
This PR does a few things:
- It adds a `COPYRIGHT.md` notice to our repo.
- Relicenses the `testlib` to be MIT (matches our other "library" crates).
- Fixes the CLA workflow. There were some differences in the private repo I tested with and this public repo.
Check the CLA bot working in another public repo: https://github.com/cowprotocol/hdnode/runs/6194783177?check_suite_focus=true for https://github.com/cowprotocol/hdnode/pull/7
Also check that the CLA workflow matches the one from the instructions https://github.com/cowprotocol/cla#github-action-setup
> Add copyright notice and fix CLA workflow

- COPYRIGHT.md
Just fixes an issue with the link to the GPL license in the `COPYRIGHT.md` file.
> Fix Link to GPL License

- crates/shared/src/maintenance.rs
I was looking at logs and reading about [tracing::span ](https://docs.rs/tracing/latest/tracing/index.html). The spans are nice because they give context to why log messages are emitted. We already use them for for handling api requests so we know whether a log message originates from the process of handling a request and we give requests an id.
Likewise by adding a span here we will see which lower level log messages originate from maintenance.
I might add spans to a couple of other places in the future that I'm still thinking about.
run and observe the extra information (should be visible in CI)
> Use tracing span for maintenance

- crates/shared/src/maintenance.rs
Looking at Kibana I realized the hash adds too much visual noise for
little benefit when it is prepended to every log message so I'm changing
this to just say block=1234 and adding back the previous log message
showing the hash.
observe changed output
> Shorten maintenance span

- crates/shared/src/arguments.rs
- crates/shared/src/http_client.rs
Fixes #180
In order to see how often we need to use the back off strategy for paraswap we need to have some metrics for it.
<details>
<summary>Metrics after manual test</summary>
```
gp_v2_api_rate_limiter_rate_limited_requests{endpoint="paraswap"} 16
gp_v2_api_rate_limiter_requests_dropped{endpoint="paraswap"} 18
gp_v2_api_rate_limiter_successful_requests{endpoint="paraswap"} 5
```
</details>
> Add metrics to rate limiting

- crates/solver/src/driver.rs
> Add span to driver runs

- rust-toolchain
Fixes #issue.
added rust-toolchain file in order to run `cargo build` outside of docker and use the right version as the docker image would
run `cargo build`and `rustup show`to view that the same settings as by the docker image are used
Optionally add notes, suggestions and warnings for the releaser. They will be included in the release changelog.
> added toolchain

- crates/model/src/bytes_hex.rs
- crates/model/src/lib.rs
- crates/shared/src/balancer_sor_api.rs
- crates/shared/src/lib.rs
- crates/shared/src/oneinch_api.rs
- crates/shared/src/paraswap_api.rs
- crates/shared/src/solver_utils.rs
- crates/shared/src/univ3_router_api.rs
- crates/shared/src/zeroex_api.rs
- crates/solver/src/liquidity/zeroex.rs
- crates/solver/src/settlement_access_list.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/solver/balancer_sor_solver.rs
- crates/solver/src/solver/paraswap_solver.rs
- crates/solver/src/solver/zeroex_solver.rs
We use `web3::Bytes` in a couple of places solely because it serializes to 0x prefixed hex string which we want in some apis. This behavior is not documented so we shouldn't rely on it. This PR introduces a custom serialization module with the same functionality.
CI, unit tests
> Provide module for Vec<u8> to hex string serialization

- crates/orderbook/openapi.yml
Part of https://github.com/cowprotocol/services/issues/127
This is the openapi documentation for the public route showing solver competition information.
CI
> Document solver competition information route

- crates/solver/src/liquidity/zeroex.rs
During oncall, it occured to me that the 0x liquidity fetching was generating noisy error messages like this:
https://cowservices.slack.com/archives/C0371SB243E/p1651405247972289
Tried to fix it with a different error handling.
> Less error debugs for 0x api call failure

- Cargo.lock
- crates/e2e/tests/e2e/services.rs
- crates/model/src/lib.rs
- crates/model/src/solver_competition.rs
- crates/orderbook/Cargo.toml
- crates/orderbook/src/api.rs
- crates/orderbook/src/api/get_solver_competition.rs
- crates/orderbook/src/api/post_solver_competition.rs
- crates/orderbook/src/lib.rs
- crates/orderbook/src/main.rs
- crates/orderbook/src/solver_competition.rs
Part of https://github.com/cowprotocol/services/issues/127 .
This is waiting on https://github.com/cowprotocol/services/pull/185 to know the exact interface.
Next PR will make use of the post endpoint in the driver.
new unit tests
> Create solve competition api

- crates/shared/src/conversions.rs
- crates/solver/src/driver.rs
- crates/solver/src/in_flight_orders.rs
- crates/solver/src/settlement.rs
- crates/solver/src/solver/naive_solver/multi_order_solver.rs
Fixes #123
The driver currently filters out all solvable orders for which it knows that a trade referring to it is in-flight at the moment.
This is overly pessimistic for partially fillable orders because you could issue many trades using liquidity from that order as long as they don't exceed the executable amount from that order.
The improved approach is to sum up the executed amounts of all in-flight trades for a partially filled order and add that to the last "confirmed" executed amount of that order. "Confirmed" in this case means the `executed_(buy|sell|fee)_amount` fields from the order metadata. Data within that field gets calculated by our database and should probably be used as the source of truth in case trades for the same order show up across multiple auctions.
If a partially …
> Scale down in-flight partially fillable orders

- crates/e2e/tests/e2e/services.rs
- crates/model/src/order.rs
- crates/orderbook/openapi.yml
- crates/orderbook/src/api/order_validation.rs
- crates/orderbook/src/api/post_quote.rs
- crates/orderbook/src/database/orders.rs
- crates/orderbook/src/main.rs
- crates/orderbook/src/orderbook.rs
- crates/shared/src/arguments.rs
- crates/solver/src/liquidity/order_converter.rs
- crates/solver/src/main.rs
- crates/solver/src/settlement_simulation.rs
- database/sql/V020__extend_orders_with_is_liquidity_order.sql
Fixes #176
Whether an order is a liquidity order currently depends on the `--liquidity-order-owners` argument. If the owner of an order is in that list the order is considered a liquidity order. This is a bit awkward because the arguments for the order book and driver might get out of sync. This could cause the order book to consider an order a liquidity order whereas the driver considers it a user order.
To make the type of an order consistent across restarts of the order book its value needs to get stored in the database.
Eventually we should move away from allow-listing individual addresses and extending the API such that each user can decide whether to create a liquidity order or a normal order.
To not make a gigantic PR while breaking the current behavior (deciding for the user …
> Store `is_liquidity_order` in the database

- crates/solver/src/settlement_access_list.rs
If one of the access list estimators returns global `Ok` result, but with `Err` for each individual transaction, then it is meaningful to try with other access list estimators rather then returning the result.  
For example, this happens for `Web3` access list estimator when node does not support `eth_createAccessList` method.
I think this change needs to be part of the `PriorityAccessListEstimating` rather then part of the `NodeAccessList`, because this type of result (global `Ok` result, but with `Err` for each individual transaction) is perfectly valid from the `NodeAccessList` point of view (we asked the node something and it returned a valid batch response).
> fix priority access list estimator

- crates/shared/src/price_estimation/gas.rs
Looking into simulations of settlements with `ZeroExInteraction`s revealed that the gas model for those is way too high. Since the approach to estimate those interactions was based off of existing estimation methods for other AMM interactions I estimated them all again with the same (hopefully more accurate) approach.
AFAIK the previous approach for gas cost estimation was to find a transactions which only had a single interaction of the type we are interested in and use that. For some interactions the min over a long period of time was used for some only a few samples were looked at. Also note that the `UnwrapWethInteraction` used the median value whereas every other interaction used the minimum.
The new approach is to use the `ethereum.traces` table which contains tracks `gas_used` for …
> Update gas model

- crates/solver/src/driver.rs
- crates/solver/src/orderbook.rs
Part of https://github.com/cowprotocol/services/issues/127 .
There are some minor todos that I don't want to be blocking the main part of this PR so I want to merge this part first.
CI and manual verification that this works
> Send solver competition info to api from driver

- crates/solver/src/settlement_submission/submitter.rs
In order to make debugging and oncall activity easier, I find it nice if activating the filter `log is not 'DEBUG'` in Kibana shows me a good summary overview of what is happening in the system on each runloop. Then, if I actually want to debug a specific loop, I can select the correct time range and drill down (also by showing DEBUG logs).
I feel like generally this is the case at the moment. However, upon sending the solution submission I see a lot of noisy alerts and am not really sure these are needed to be show on every run by default (see screenshot)
I therefore propose to downgrade the verbosity of these logs to debug. cc @sunce86 if those logs are still needed (I generally don't mind verbose logs to make debugging easier, but we should make sure they don't make other maintenance …
> Reduce log level of noisy debug messages

- crates/orderbook/src/api/create_order.rs
This PR adds logging of the newly created order's `Uid`.
Using this `Uid` and the log timestamp we can connect the `orderbook::api::request_summary` log with the order logs in the solver.
Tried to find the cleaner way to add this log directly to the orderbook, but once the response is wrapped into `ApiReply` it becomes cumbersome to extract the needed `Uid`.
> Add log for order created uid

- crates/solver/src/settlement_submission/submitter.rs
- crates/solver/src/settlement_submission/submitter/custom_nodes_api.rs
- crates/solver/src/settlement_submission/submitter/eden_api.rs
Some minor log changes that would have helped be debug submission errors.
Mostly just adds additional context to existing settlement submission logs.
Additionally, I demoted a bunch of `info` logs to `debug` logs to make it easier to follow over-all driver log output with `not log: "DEBUG"` filter on the logs.
> Minor submission logging improvements

- crates/shared/src/bad_token/trace_call.rs
We had some panics in prod because the [NOT token](https://etherscan.io/address/0x0027449bf0887ca3e431d263ffdefb244d95b555) uses maxuint256 for all user balances, which causes a panic when checking if the token is unsupported.
These changes fix the panic.
Updated ignored unit test:
```
$ cargo test -p shared mainnet_tokens -- --nocapture --ignored
[...]
token 0x0027449bf0887ca3e431d263ffdefb244d95b555 is Ok(Bad { reason: "token total supply does not fit a uint256" })
[...]
```
Also, compare the output of the test with its output on `main` to check that no other changes were introduced:
```
$ diff before after
104a105
> token 0x0027449bf0887ca3e431d263ffdefb244d95b555 is Ok(Bad { reason: "token total supply does not fit a uint256" })
107c108
< test result: ok. 1 passed; 0 failed; 0 …
```
> Fix overflow in bad token detection

- crates/solver/src/driver.rs
- crates/solver/src/driver/solver_settlements.rs
- crates/solver/src/solver/http_solver.rs
- crates/solver/src/solver/http_solver/settlement.rs
One small step towards #209
This PR adds some additional logging around received solutions. Specifically it will:
- Log **all** settlements from any solver before filtering
- Log settlements that are considered for the settlement competition (pre-simulation)
- Adds more context for why HTTP responses from solvers may be ignored
This is a kind of _"low effort"_ additional logging as it does not always specifically give reasons as to why specific solutions are being filtered (we just count if any solutions are being filtered per solver) and is a little brittle (boiler plate for each additional "filter" we add, doesn't solve a bit of "spaghetti" from filtering settlements at various point in the run loop). Still it is an improvement over what we have now since external solvers provide a …
> Additional settlement logging

- crates/solver/src/driver.rs
I noticed when debugging settlement failures that we weren't logging with the `auction` span when reporting errors (i.e. simulating on the original block and generating a Tenderly link with the failed simulation).
This is because we offload the simulation and reporting to a separate Tokio-rs task so that we can already start the next auction without delaying for informative error reporting (which is, IMO a very good thing). However, this makes it hard to tie the simulation errors with what auction it belongs to without looking at surrounding logs.
Luckily it is very easy to so - `Span::current()` allows us to instrument a separate task using the span of the currently executing task.
Additionally, I promoted the `auction` span to be at the `INFO` level. This makes it so filtering logs like …
> Attach span to error reporting span

- crates/shared/src/http_solver/model.rs
- crates/solver/src/solver/http_solver.rs
- crates/solver/src/solver/http_solver/settlement.rs
Now that we have external solvers, we will start requiring them to provide execution/calldata for AMM interactions that they internalize.
This PR changes the `exec_plan` that is returned from HTTP solvers to instead use an enum to indicate whether or not it is "internal" or to be included in the execution plan. Currently, all we do with "internal" interactions is to skip them when adding them to the solution and logging a message indicating that it was internalized.
Once we start recording settlement competitions in the database, we need to make sure that these internalized AMM interactions get stored somewhere so that they can be verified at a later date. For this, some additional refactoring is necessary in order to make encoding interactions into settlements easier.
One additional …
> Allow interactions to be internal

- crates/solver/src/driver.rs
This PR just randomizes the rated settlements before "stable"-sorting them. This makes it so in case of a tie in the objective value, solvers are treated equally.
CI and Rust compiler.
> Randomize Winner on Objective Value Tie

- crates/orderbook/src/main.rs
- crates/shared/src/http_solver.rs
- crates/shared/src/price_estimation/quasimodo.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/http_solver.rs
This PR adds a new field to `SolverConfig` to allow configuring Quasimodo for different environments. Specifically, requests to Quasimodo from the solver should use a different objective then when requesting price estimates (when solving, Quasimodo defaults to optimizing with capped surplus, which we don't want for price estimates).
Run the orderbook locally and see the new parameter:
```
% cargo run -p orderbook -- --price-estimators Quasimodo --log-filter shared::http_solver=trace
...
2022-05-25T13:26:42.718Z TRACE shared::http_solver: request url=https://.../solve?instance_name=2022-05-25_13%3A26%3A42.718259_UTC_Ethereum___Mainnet_1_0&time_limit=2&max_nr_exec_orders=100&use_internal_buffers=false&objective=surplusfeescosts body=...
...
```
> Add `objective` Flag And use `SuplusFeesCosts` for Price Estimates

- crates/model/src/lib.rs
- crates/model/src/order.rs
- crates/model/src/quote.rs
- crates/orderbook/openapi.yml
- crates/orderbook/src/api/create_order.rs
- crates/orderbook/src/api/get_fee_and_quote.rs
- crates/orderbook/src/api/post_quote.rs
- crates/orderbook/src/fee.rs
Partially fulfills #170 
This PR adds the ability to set the `quoteId` parameter while creating Orders. This way the order can be linked to a quote and enable providing more metadata when analyzing order slippage.
Currently, it doesn't involve interaction with the Database i.e. Storing or retrieving the `quoteId`. This will be a part of a separate PR.
Also `api/v1/quote` now also returns an ID. Currently, implemented as a counter which gets reset on orderbook restarts.
<details>
<summary>Screenshot</summary>
</details>
* Use the [custom-order-ui ](https://github.com/cowprotocol/custom-order-ui) to place a new order and add the `Quote ID` parameter
* Review the logs to see `quoteId` visible
Users can now pass an optional parameter `quoteId` while creating orders for easier debugging.
> Add `quoteId` parameter to orders

- crates/shared/src/http_solver/model.rs
Fixes regression introduced in https://github.com/cowprotocol/services/pull/195#discussion_r885411037
It turns out some of our solvers were sending single interactions without an execution plan. This used to be allowed and was disallowed in the aforementioned PR, breaking backwards compatibility.
CI
> Interactions no longer require an execution plan

- crates/orderbook/openapi.yml
Just tag some old APIs as deprecated so we can start the process of getting rid of them and relieve some maintenance burden.
CI - it tests that the OpenAPI spec is valid.
There are some new API deprecations that we need to communicate with the community.
> Deprecate some old APIs

- crates/orderbook/src/main.rs
- crates/shared/src/arguments.rs
- crates/shared/src/price_estimation/zeroex.rs
- crates/shared/src/zeroex_api.rs
- crates/solver/src/main.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/zeroex_solver.rs
Fixes #243 
This PR extends the 0x API implementation to allow setting excluded sources for `/swap` and `/quote` queries and adds configuration options in the driver and orderbook for setting these excluded sources.
Added a new test to see if 0x takes different routes when buying SNX for route (i.e. it doesn't use the "bad" Balancer pool):
```
% cargo test -p shared -- --ignored --nocapture zeroex_api::tests::excluded_sources
Finished test [unoptimized + debuginfo] target(s) in 0.10s
Running unittests src/lib.rs (target/debug/deps/shared-5653717641331484)
running 1 test
[crates/shared/src/zeroex_api.rs:526] &swap = Ok(
SwapResponse {
price: PriceResponse {
sell_amount: 1000000000000000000000,
buy_amount: 508509876034390373504047,
allowance_target: …
```
> 0x Excluded Sources Configuration

- crates/orderbook/src/main.rs
- crates/shared/src/arguments.rs
- crates/shared/src/price_estimation/quasimodo.rs
- crates/shared/src/sources/balancer_v2/pool_fetching.rs
- crates/solver/src/main.rs
Fixes https://github.com/cowprotocol/services/issues/242 .
Used the new manual pool fetching test to see that this pool no longer gets returned
> Allow deny listing balancer pools

- crates/solver/src/main.rs
Fixes https://github.com/cowprotocol/services/issues/222.
Added at a `SolutionSubmitter` level rather than on a lower `Submitter` level, so we can have metrics for both strategies at the same time and evaluate success.
> Enable parallel flashbots strategies

- crates/alerter/src/main.rs
Part of https://github.com/cowprotocol/services/issues/254
As commented here https://github.com/cowprotocol/services/blob/29cee54830831726bec5e4120867292fd2dff4b2/crates/solver/src/solver/single_order_solver.rs#L120 we previously discovered that sometimes these apis do not respect the input amount. This updates the alerter with the same check.
I found this when going through alerts that the alerter emitted and manually checking the solver logs for this order which lead to a false positive alert before.
CI
> Make amount check more strict

- crates/solver/src/settlement_submission/submitter.rs
- crates/solver/src/settlement_submission/submitter/custom_nodes_api.rs
- crates/solver/src/settlement_submission/submitter/eden_api.rs
- crates/solver/src/settlement_submission/submitter/flashbots_api.rs
This PR fixes gas price for cancelling transactions. 
This has become extremely relevant now we have https://github.com/cowprotocol/services/pull/235 merged.
Also, some cleanup of `CancelHandle` since not needed anymore (all strategies are canceled using the noop transaction - no previous submitted transaction handle is needed).
> Fix cancelling of transactions

- crates/solver/src/liquidity.rs
- crates/solver/src/liquidity/zeroex.rs
Fixes #238 
This PR should resolve the memory issues that we face when we have too many orders by reducing the set of collected orders.
We do this by distributing our orders into buckets, where the key for each bucket is an ordered pair of tokens. We then reduce these buckets by taking only 5 best priced and 5 biggest volume orders from the list.
* Apply this diff
<details><summary>Fake Order diff</summary>
```
diff --git a/crates/shared/src/zeroex_api.rs b/crates/shared/src/zeroex_api.rs
index 8256ce9..aa4b8c9 100644
--- a/crates/shared/src/zeroex_api.rs
+++ b/crates/shared/src/zeroex_api.rs
@@ -440,7 +440,7 @@ impl DefaultZeroExApi {
.text()
.await
.map_err(ZeroExResponseError::TextFetch)?;
-        tracing::debug!("Response from 0x API: {}", response_text);
+        // …
```
> Stricter 0x liquidity order filtering

- crates/orderbook/src/main.rs
- crates/shared/src/price_estimation/quasimodo.rs
When using Quasimodo in PriceEstimator mode we weren't passing metadata (like gas price, network, etc). While not strictly required, it feels more correct to pass it. Also as we are potentially onboarding external solvers as price estimators (like the yearn solver to deal give prices for "exotic" tokens that are otherwise not supported) we need to comply with a more unified interface.
Checking that both with https://xdai.barn.seasolver.dev as well as with the Quasimodo staging address we can still get price estimates.
> [Trivial] add metadata to Quasimodo request when estimating price

- crates/e2e/tests/e2e/services.rs
- crates/orderbook/src/api.rs
- crates/orderbook/src/api/post_solver_competition.rs
- crates/orderbook/src/lib.rs
- crates/orderbook/src/main.rs
- crates/shared/src/arguments.rs
- crates/solver/src/main.rs
- crates/solver/src/orderbook.rs
In https://github.com/cowprotocol/services/pull/188 we originally had an authorization header for this route as we only want it to be POSTable from the driver pod. In the PR we decided it would be better to handle this on the nginx ingress level. This turned out to not work and while devops is investigating other solutions we should add our own authentication back.
CI
> Add authorization to competition info post

- crates/e2e/tests/e2e/services.rs
- crates/orderbook/src/api.rs
- crates/orderbook/src/api/create_order.rs
- crates/orderbook/src/api/get_fee_and_quote.rs
- crates/orderbook/src/api/get_fee_info.rs
- crates/orderbook/src/api/post_quote.rs
- crates/orderbook/src/lib.rs
- crates/orderbook/src/main.rs
- crates/orderbook/src/order_quoting.rs
- crates/orderbook/src/order_validation.rs
- crates/orderbook/src/orderbook.rs
This PR just trivially moves code around into new modules to accommodate upcoming changes to quotes (so that they get stored in the database alongside fees).
1. Refactor order quoting component outside of the `api::post_quote` module into its own thing. The motivation here is that we will move fee computation and quote storing into the `order_quoting` tree.
2. Move `order_validation` outside of `api::` - it was the only submodule that wasn't dedicated to API routes, and was a bit unintuitive for me to find.
CI. Code just moved. 0 logic changes.
> Refactor modules

- crates/model/src/order.rs
- crates/model/src/signature.rs
- crates/orderbook/src/database/orders.rs
- crates/solver/src/encoding.rs
Following up the changes made in #268 #250 this PR adds the EIP-1271 signing scheme to:
- model - Signature
- model - SigningScheme
- orderbook - DbSigningScheme
- solver - encode_trade
**NOTE:** EIP-1271 won't be available for Orders yet as there is currently a match  allowing only a certain signatures:
https://github.com/cowprotocol/services/blob/8f1ad7730b160a25dd66ad844b657089e0d05daa/crates/orderbook/src/api/order_validation.rs#L346-L351
cc @nlordell another small PR to add the EIP-1271 signature before tiding everything together
> EIP-1271 signing scheme

- crates/e2e/tests/e2e/eth_integration.rs
- crates/e2e/tests/e2e/onchain_settlement.rs
- crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
- crates/e2e/tests/e2e/vault_balances.rs
- crates/solver/src/main.rs
- crates/solver/src/settlement_submission.rs
- crates/solver/src/settlement_submission/submitter/eden_api.rs
At the moment our the alert for transaction submission errors is quite noisy because we log many errors coming from eden which seem to be false positives.
For the custom nodes submitting transactions to the public mempool we ignore a number of [error messages](https://github.com/cowprotocol/services/blob/79cba9c4817497ab0a1256f595021dd017062833/crates/solver/src/settlement_submission/submitter/custom_nodes_api.rs#L15-L22) which can be caused by another custom node submitting the transaction to the mempool faster.
Since we learned at some point that the eden mempool also contains messages from the public mempool it seems reasonable to ignore the corresponding eden error messages as well.
To see how big of an impact this change would make I analyzed the logged errors over a period from …
> Log fewer eden submission errors

- crates/orderbook/src/main.rs
- crates/shared/src/bad_token/mod.rs
- crates/shared/src/bad_token/token_owner_finder.rs
- crates/shared/src/bad_token/trace_call.rs
In preparation of adding a new TokenOwnerFinder (for the exotic yearn tokens on xDAI), I thought it may make sense to refactor that TokenOwnerFinding and separate it from the remaining trace_call module into its own module. Otherwise I feel it may become quite big. @vkgnosis please let me know if you think another factoring makes more sense.
No logic changes, just CI
> Seperate TokenOwnerFinding module

- crates/solver/src/main.rs
This change makes it easier to understand which transaction node is failing on startup.
Without this change, it could be unclear which submission node is failing for some error types ([example](https://cowservices.slack.com/archives/C0371SB243E/p1655301131999599)).
See the new panic:
```
cargo run -p solver -- --orderbook-url "https://barn.api.cow.fi/mainnet/api" --node-url ""https://mainnet.infura.io/v3/$INFURA_KEY"" --transaction-submission-nodes http://bad.node/bad/path --solver-account 0x0000000000000000000000000000000000000000
[...]
2022-06-16T10:49:27.815Z ERROR shared::tracing: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unable to retrieve network id on startup using the submission node at http://bad.node/bad/path
Caused by:
failed to send request: error …
```
> Verbose error message on node startup failure

- crates/orderbook/src/api/post_solver_competition.rs
- crates/orderbook/src/solver_competition.rs
- crates/solver/src/driver.rs
We have a default of 16 KiB limit which is likely exceeded when there
are several solutions with calldata causing the solver competition
endpoint to not accept the data from the driver.
CI and manual test after merging. Would be easier to diagnose if https://github.com/cowprotocol/services/pull/279 got merged first.
> Give solver competition endpoint larger size limit

- Cargo.lock
- crates/orderbook/Cargo.toml
- crates/orderbook/src/conversions.rs
- crates/orderbook/src/database/orders.rs
- crates/shared/Cargo.toml
Sqlx has a new breaking version so I wenth through the changelog to make
sure nothing would adversely affect us and updated. One consequence is
that we no longer need to depend on two versions of num.
CI
> Update sqlx dependency (and compatible versions)

- crates/e2e/tests/e2e/services.rs
- crates/orderbook/openapi.yml
- crates/orderbook/src/fee.rs
- crates/orderbook/src/main.rs
This [slack thread](https://cowservices.slack.com/archives/C036JAGRQ04/p1655373828067479?thread_ts=1655371868.842249&cid=C036JAGRQ04) showed that it's problematic to allow users to create orders using fee estimates coming from the `fast` price estimator.
Instead users should have to use quotes coming from an `optimal` estimate.
A very simply fix should be to simply not store `FeeData` coming from the `MinFeeCalculator` using the `fast` price estimator.
If a user would then try to create an order using a quote from the `fast` endpoint the orderbook would not find the `FeeData` in the DB, compute it from scratch with the `optimal` price estimator and reject the order if the fee measurements conflict.
Unit test verifying that `MinFeeCalculator` can be configured such that it doesn't store …
> Prevent storing fast fee estimates

- crates/shared/src/bad_token/trace_call.rs
This error is not serious enough to warrant an error log.
The context is that in today's prod release we saw that we were getting this error log a lot from the Blockscout TokenOwnerFinding implementation.
CI
> Change token owner finding error log to warning

- crates/orderbook/src/database.rs
- crates/orderbook/src/database/fees.rs
- crates/orderbook/src/database/orders.rs
- database/sql/V021__store_full_quotes.sql
This PR applies a new migration to our Postgres database in order to get it ready for storing full quotes.
Additionally, it modifies the components used for storing min fee measurements and retrieving order fee parameters to use "dummy" values in the meantime, so that they can continue to work with the new database schema (and keep the PRs as short as possible). I also felt that there are enough important details that I didn't want to get lost in larger changes (see 👇).
There are a couple of notable changes that merit some additional discussion:
- We populate `{buy,sell}_amount` values with `0` for existing order quotes. This means that we should be able to distinguish between orders with stored fee parameters "pre-quote-storage" and "post-quote-storage". Some alternatives:
* Allow `NULL` …
> Alter Database Schema for quote storage

- crates/model/src/quote.rs
- crates/orderbook/src/database.rs
- crates/orderbook/src/database/fees.rs
- crates/orderbook/src/database/instrumented.rs
- crates/orderbook/src/database/orders.rs
- crates/orderbook/src/database/quotes.rs
- crates/orderbook/src/order_quoting.rs
This PR implements `QuoteStoring` for Postgres. Additionally, it modifies `MinFeeStoring` implementation to be implemented in function of the new `QuoteStoring`.
Added new test cases. Tests for `MinFeeStoring` implemented in function of `QuoteStoring` continue to pass.
> Implemented quote storage for Postgres

- crates/e2e/tests/e2e/services.rs
- crates/orderbook/src/api/create_order.rs
- crates/orderbook/src/main.rs
- crates/orderbook/src/order_quoting.rs
- crates/orderbook/src/order_validation.rs
This PR builds on #297 and implements order creation in function of the new `OrderQuoting` component.
At this point, the legacy `OrderQuoterLegacy` and `MinFeeCalculator` should no longer be used and can be removed (follow up PR to not make this harder to review).
Added new unit test cases to verify the new `get_quote_and_check_fee` logic (that replaced `MinFeeStoring::get_unsubsidized_min_fee`). Existing unit tests continue to work.
> Use new quoting component for order creation

- crates/orderbook/src/database/instrumented.rs
- crates/orderbook/src/database/orders.rs
- crates/orderbook/src/order_validation.rs
- crates/orderbook/src/orderbook.rs
This PR changes the `OrderStoring` implementation to actually store the quote data instead of just the fee parameters.
While the database schema was changed in #295 to allow for order quotes to get stored alongside orders, the `OrderStoring` implementation did not, at the time, make use of this and stored dummy `0` values (there was additional "wiring" that was needed in order to make the quote data available).
Added new unit tests to make sure data is stored.
I also did some manual testing to verify that order creation is working as expected.
1. Run the orderbook on Rinkeby:
```
% cargo run -p orderbook -- --skip-trace-api true --skip-event-sync --node-url $RINKEBY
```
2. Run the attached script:
```
% ./quoteids.sh
```
3. Restart the orderbook with the account as a liquidity owner:
``` …
```
> Store quote data with order

- crates/shared/src/rate_limiter.rs
While checking up on the grafana panel for the rate limiters I saw that they didn't display data for all the configured rate limiters.
In order to display the percent of "bad" requests (dropped or too slow) I would have to create a query like this:
`(rate_limited + dropped) / (rate_limited + dropped + success)` (basically requests_bad / requests_total)
The problem is that grafana won't draw the graph if one of the metrics in the query doesn't have a value because it hasn't been initialized yet.
To get around this fact I decided to `reset()` the metric counters to populate each counter with 0.
Now the legend and graphs can be drawn even if no request has been made through the `RateLimiter`.
Note that the `Baseline_estimator` has a graph although it doesn't even use a `RateLimiter`, yet. I …
> Init rate limiting metrics

- crates/shared/src/arguments.rs
Prints the CLI argument for the paraswap rate limiting strategy the same way we print the price estimator strategy:
Before:
```
...
disabled_paraswap_dexs: ["ParaSwapPool4"]
paraswap_rate_limiter: Some(RateLimitingStrategy { drop_requests_until: Instant { t: 324338013644 }, times_rate_limited: 0, back_off_growth_factor: 2.0, min_back_off: 1s, max_back_off: 5s })
zeroex_url: None
...
```
After:
```
...
disabled_paraswap_dexs: ["ParaSwapPool4"]
paraswap_rate_limiter: RateLimitingStrategy{ min_back_off: 1s, max_back_off: 5s, growth_factor: 2.0 }
zeroex_url: None
...
```
> Pretty print paraswap rate limiting CLI argument

- Cargo.lock
- crates/autopilot/Cargo.toml
- crates/autopilot/src/arguments.rs
- crates/autopilot/src/lib.rs
- crates/autopilot/src/main.rs
- docker/Dockerfile.binary
Has been discussed in https://github.com/cowprotocol/services/issues/175 and https://github.com/cowprotocol/services/issues/230 .
Currently does nothing except export a metric. Once it is integrated into kubernetes I will start moving functionality from Orderbook into it.
One design idea is that this can automatically be run by the orderbook (and the e2e tests) which is why it exports the main function in its library. I'm not yet sure what the best approach for that is with regards to its command line arguments. It seems like for anything that we want configurable (not default) we would need to duplicate them into the orderbook arguments. Or maybe there is some advanced Clap use that makes this easier (subcommands?). Anyway I don't want the details of this to delay other changes so will …
> Introduce initial autopilot binary

- crates/e2e/tests/e2e/services.rs
- crates/orderbook/src/main.rs
- crates/shared/src/price_estimation/baseline.rs
Implements rate limiting logic for the `BaselinePriceEstimator`.
I think it's a little unclear how rate limiting an estimator which does a single request for multiple queries should work.
I ended up only rate limiting the 2 parallelized requests which query all the data needed to calculate the price estimates.
I think this is most likely what we want given the fact that those requests are probably what take most of the time and their execution times are what's not under our control when processing price estimates.
CI
> Rate limit BaselinePriceEstimator

- crates/solver/src/driver.rs
I like to debug a sudden increase of failed settlement simulations with this [Kibana query](https://logs.cow.fi/goto/768c7fa0-f382-11ec-97dd-b383b91e99a0).
In case we only get an alert for a single solve I would like to be able to filter by that solver to ignore the occasional simulation error of other solvers to more quickly and confidently know which token the solver has problems with.
AFAIK determining which solver created a settlement would currently involve clicking "surrounding documents" on each failed settlement to see the previous log which contains the solver name. This is quite cumbersome.
> Log solver name for failed simulation

- crates/orderbook/src/order_validation.rs
This PR uses order quotes to determine when orders are outside of the current market price and flag them as liquidity orders.
The rationale behind this change is that these orders are not intended to be traded immediately (i.e. they are long standing orders) and so should be treated differently. Concretely, we treat them as liquidity orders so that they don't trade against AMMs but other users once the market price moves in their favour. Longer term, we will start charging fees from order limit prices and will no longer need this distinction.
Note that this should not affect CowSwap UI traders at all since they will always create orders based on an API quote and will be "in the market price".
Added test cases verifying pricing logic.
This PR flags additional orders as liquidity orders. We …
> Flag out of market price orders as liquidity

- crates/e2e/tests/e2e/services.rs
- crates/model/src/order.rs
- crates/model/src/signature.rs
- crates/orderbook/src/arguments.rs
- crates/orderbook/src/main.rs
- crates/orderbook/src/order_validation.rs
- crates/orderbook/src/orderbook.rs
- crates/orderbook/src/signature_validator.rs
- crates/orderbook/src/solvable_orders.rs
- database/sql/V023__add_eip1271_signature.sql
This PR adds initial proof-of-concept support for EIP-1271 orders with help from the initial work done by @elpiel.
This PR does a few things:
1. Changes the `SignatureValidating` component to support batched validation. This is important for computing solvable orders as we don't want increase the delay too significantly by doing one node round-trip per order.
2. Add a check when the order is added on whether or not the EIP-1271 signature is valid in the `OrderValidator`.
3. When building batches in the `SolvableOrdersCache`, check on each auction whether or not the EIP-1271 signature is **still** valid (and filter out the order if it is not). This is because EIP-1271 is implementation dependent and may have mechanisms to cancel a signature on-chain for example.
There are still a few …
> Proof of concept EIP-1271 orders

- crates/shared/src/price_estimation/zeroex.rs
- crates/shared/src/zeroex_api.rs
- crates/solver/src/solver/zeroex_solver.rs
Starting on 2022-06-30 0x will by default compute trade routes which aim to protect against high slippage and MEV attacks.
Those routes can have worse prices than unprotected routes so because we already protect against those things we don't need to use the worse prices unnecessarily.
[Slack thread](https://cowservices.slack.com/archives/C0360881AHZ/p1655502415558449) of the 0x team reaching out to use and suggesting this change.
Ran ignored test making a swap request to the 0x API which still produces results suggesting that the API either already supports the flag or doesn't throw an error when it encounters an unsupported flag.
<details>
<summary>Output of ignored test</summary>
```
test zeroex_api::tests::test_api_e2e ... ok
Price Response: {
"bestRoute": [
{
"percent": 100,
"swaps": …
```
> Disable 0x slippage protection

- crates/e2e/tests/e2e/services.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
- crates/model/src/order.rs
Preliminary support for EIP-1271 orders was introduced in #311. This PR adds a new E2E test to verify trading with Smart Contract EIP-1271 orders works.
Specifically, the `smart_contract_orders` E2E test was modified to include both an EIP-1271 (which is incidentally signed off-chain) and PreSign order from Gnosis Safe.
This is the test plan 🥄.
> Add EIP-1271 E2E Test

- crates/solver/src/solver/naive_solver.rs
- crates/solver/src/solver/naive_solver/multi_order_solver.rs
Fixes observed naive solver panics.
We have special encoding semantics for:
- Liquidity orders
- Ether buy orders (i.e. buy orders that use the special `0xe...` marker address.
Specifically, for liquidity orders, we add additional clearing price entries for their `buy_token` to ensure that they always get exactly their limit price when trading.
For Ether buy orders, we change their `buy_token` to the wrapped native token (WETH on mainnet for example) before sending `LiquidityOrder` instances to individual solvers. When these orders get added to the settlement, we add an extra clearing price for `0xe...` that matches exactly the price of the wrapped native token (e.g. WETH). In the code we call this a "token equivalency".
However, when adding liquidity Ether buy orders, **we do not add a …
> Fix panic for liquidity orders buying Eth

- Cargo.lock
- crates/number_conversions/Cargo.toml
- crates/number_conversions/src/lib.rs
- crates/orderbook/Cargo.toml
- crates/orderbook/src/conversions.rs
- crates/orderbook/src/database/orders.rs
- crates/shared/Cargo.toml
- crates/shared/src/conversions.rs
- crates/shared/src/sources/balancer_v2/swap/fixed_point.rs
- crates/solver/Cargo.toml
- crates/solver/src/in_flight_orders.rs
- crates/solver/src/settlement/settlement_encoder.rs
- crates/solver/src/solver/naive_solver/multi_order_solver.rs
In order to disentangle some dependencies I'm moving this to it's own crate. The plan is to move the BigDecimal <-> U256 conversion into the database crate without making it depend on shared.
Some of the conversion implementations have been slightly changed.
CI, existing tests
> Move some U256 conversions into own crate

- Cargo.lock
- crates/database/Cargo.toml
- crates/database/src/byte_array.rs
- crates/database/src/lib.rs
- crates/orderbook/src/conversions.rs
- crates/orderbook/src/database/orders.rs
- crates/orderbook/src/database/quotes.rs
- crates/orderbook/src/database/trades.rs
without going through Vec<u8>
This is more efficient, more type safe, easier to use.
new and old unit tests
> Support fixed size byte arrays in database natively

- Cargo.lock
- crates/driver/Cargo.toml
- crates/driver/src/api.rs
- crates/driver/src/api/execute.rs
- crates/driver/src/api/solve.rs
- crates/driver/src/commit_reveal.rs
- crates/driver/src/driver.rs
- crates/driver/src/lib.rs
This PR implements step 1 of #337 and creates a very rough sketch of the internal architecture of the new `Driver`.
It introduces the new `CommitRevealSolving` trait and makes use of it.
Nothing to test yet
> Basic mock up of new driver logic

- crates/driver/src/arguments.rs
- crates/driver/src/driver.rs
- crates/driver/src/main.rs
Implements step 4 of #337
This PR just instantiates the `SolutionSubmitter` and stores it in each `Driver` instance. The instantiation logic and CLI argument code has been lifted from the `solver` binary.
I used the same initialization approach explained in #340 to make it clearer what subcomponents actually belong to the submission logic.
> Initialize SolutionSubmitter in new driver

- crates/solver/src/driver.rs
- crates/solver/src/lib.rs
- crates/solver/src/settlement_rater.rs
Moving the settlement rating logic into its separate component makes it easy to share it with the new driver.
The new driver will need that for the compatibility wrapper which adapts legacy solvers to support the new commit-reveal approach.
With the new component the wrapper can easily find the best solution and report its total surplus and required gas reimbursement.
only moved code around => CI
> Move Settlement rating into separate component

- crates/orderbook/src/arguments.rs
- crates/orderbook/src/main.rs
- crates/shared/src/price_estimation.rs
- crates/shared/src/price_estimation/balancer_sor.rs
Fixes https://github.com/cowprotocol/services/issues/342
After merging should change configuration to enable this as price estimator and native price estimator.
new ignored test and manually ran orderbook and estimated price between the two problematic tokens from https://app.balancer.fi/#/pool/0x3dd0843a028c86e0b760b1a76929d1c5ef93a2dd000200000000000000000249 .
> Add BalancerSor price estimator

- .github/workflows/deploy.yaml
Now that Görli staging services are available, they should also be restarted on deployment.
Test that the new Kubernetes deployments exist with `kubectl get deployment | grep dfusion-v2-.*-goerli'`.
> Restart Görli pods on deployment

- crates/model/src/solver_competition.rs
- crates/solver/src/driver.rs
This PR extends the settlement competition JSON to additionally include `auction` field that contains information about the orders that were considered in the auction and, more critically, the external price vector that was used for ranking the settlements.
The main motivations for adding additional information are:
- External prices are required for verifying the computed objective value amounts
- We intend on using the external price vector from the auction to compute total solver surplus that will be used in the solver payout computation.
- Orders allow us to compute disregarded utility for an auction (and verify things like envy-freeness - not necessarily something we want to enforce at the moment, but a general target that we have AFAIU).
Note that this still does not store the …
> Add auction to settlement competition information

- crates/e2e/tests/e2e/services.rs
- crates/model/src/solver_competition.rs
- crates/orderbook/src/api.rs
- crates/orderbook/src/api/get_solver_competition.rs
- crates/orderbook/src/api/post_solver_competition.rs
- crates/orderbook/src/lib.rs
- crates/orderbook/src/main.rs
- crates/orderbook/src/solver_competition.rs
- crates/shared/src/api.rs
- crates/solver/src/driver.rs
- crates/solver/src/orderbook.rs
This PR refactors solver competition storage into a `SolverCompetitionStoring` component. The existing in-memory storage was changed to conform to this new interface.
There are, however, some notable changes to how solver competition storage works. Storage competition will eventually need to be stored in the database. This means that the "ID" for storing it needs to come from there. This is a bit unfortunate because the auction ID is computed in the `solver`, but storage is happening in the `orderbook`. Previously, we had just allowed drivers to arbitrarily replace `SolverCompetition` values for arbitrary IDs. Moving forward with this change, drivers will just be able to `POST` a new solver competition (and will be returned the ID of the newly pushed storage competition). This has some …
> Refactor solver competition storing

- crates/e2e/tests/e2e/services.rs
- crates/model/src/auction.rs
- crates/orderbook/src/main.rs
- crates/orderbook/src/orderbook.rs
- crates/orderbook/src/solvable_orders.rs
- crates/orderbook/src/solver_competition.rs
- crates/shared/src/http_solver/model.rs
- crates/shared/src/price_estimation/http.rs
- crates/solver/src/driver.rs
- crates/solver/src/settlement.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/http_solver.rs
This PR is a follow up to #352
Specifically, this PR changes the `Auction` model to also include the next solver competition ID that will be used. This gives the driver information as to which solver competition it is "fighting" for.
Additionally, the previous `auction_id` used in the driver was renamed to `run_id` and identifies the driver run and **not** the settlement competition. Note that these two things increment separately since a run can end up with no settlements, and the next run will be different (hence, have a different `run_id`) but still be "fighting" for the same solver competition (hence, have the same `auction_id`).
This information is used in a few places:
- Each driver run now includes both the auction ID and run ID in the span
- The HTTP solvers send the auction ID, …
> Include next solver competition ID in auction and logs

- crates/database/src/lib.rs
- crates/e2e/tests/e2e/services.rs
- crates/model/src/solver_competition.rs
- crates/orderbook/src/api/get_solver_competition.rs
- crates/orderbook/src/database.rs
- crates/orderbook/src/database/solver_competition.rs
- crates/orderbook/src/main.rs
- crates/orderbook/src/solver_competition.rs
- crates/shared/src/http_solver.rs
- crates/shared/src/http_solver/model.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/http_solver.rs
- database/sql/V024__store_settlement_competition_blobs.sql
This PR stores solver competitions as JSON data-blobs in the database.
This is a temporary measure to start permanently storing competition information in the database. In the long run the `autopilot` will be responsible for storing solver competition information (including things such as the solver proposals and execution attestations for each `driver`+solver combo). For now, because the format for storing solver competition information is very unclear, just store it as a JSON blob.
CI uses database for end to end tests to exercise new code.
Also, running end to end tests locally:
```
% cargo test -p e2e -- --ignored
...
2022-07-08T17:37:27.616Z DEBUG auction{id=1 run=0}: solver::driver: starting single run
...
2022-07-08T17:37:29.140Z DEBUG auction{id=2 run=1}: solver::driver: starting …
```
> Store settlement competition as JSON blobs in database

- crates/shared/src/price_estimation.rs
The old implementation of `PriceEstimationError::clone()` would recurse endlessly when it contained the `RateLimited` error type.
This problem was only triggered in the Baseline estimator. That's the only estimator which is able to estimate multiple prices queries with a single request. That's why it's the only one which needed to clone the single original error into the result of multiple price estimation requests.
This [code example](https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=97080f772cdcd3305ef391fb39b07004) shows the problem nicely.
The issue results in different errors for debug and release builds. In debug builds you will get a stack overflow and on release builds the code gets optimized to a busy loop. This busy loop caused the baseline estimator to …
> Fix endless recursion when cloning PriceEstimationError

- crates/e2e/tests/e2e/eth_integration.rs
- crates/e2e/tests/e2e/onchain_settlement.rs
- crates/e2e/tests/e2e/services.rs
- crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
- crates/e2e/tests/e2e/vault_balances.rs
- crates/orderbook/src/solvable_orders.rs
When e2e tests manually update the solvable orders cache it is possible
that the result is overwritten by the automatic update which in turn
could have been initiated at an earlier point in time leading to a
recently created order being missing.
Fixes https://github.com/cowprotocol/services/issues/362
> Fix e2e test solvable orders logic

- .github/workflows/pull-request.yaml
No need to compile the dependencies from scratch every time.
ci still works
> Enable cargo cache for CI coverage job

- crates/database/src/lib.rs
- crates/database/src/quotes.rs
- crates/database/src/solver_competition.rs
- crates/orderbook/src/database/solver_competition.rs
> Move solver competition storing into database crate

- crates/database/src/solver_competition.rs
- crates/orderbook/src/database/solver_competition.rs
- database/sql/V025__settlement_competition_tx_hash.sql
Allows us to query solver competition info by tx hash.
Next step is to change the api route to also allow a hash.
New unit test and temporary unit test that shows the migration works.
The temporary test should be removed before merging.
> Store solver_competition tx_hash in column

- crates/orderbook/openapi.yml
- crates/orderbook/src/api/get_solver_competition.rs
- crates/orderbook/src/database/solver_competition.rs
- crates/orderbook/src/solver_competition.rs
- Removed InMemoryStorage because it wasn't needed anymore.
- Simplified NotFound error because there is no reason to return the id back.
I added a new route `by_tx_hash` instead of overloading a single route because I felt it was more clear and harder to accidentally misuse.
CI, adapted test
> Make solver_competition route work with tx hash

- crates/shared/src/sources/balancer_v2/graph_api.rs
This PR configures our Subgraph initialization to know about the Görli subgraph.
This is the last piece required for Balancer V2 to work on Görli.
Make sure we can query Balancer V2 liquidity on Görli:
```
% cargo run -p solver -- \
--baseline-sources BalancerV2 \
--solver-account 0xA70B6e99FCF41bF78d626a95B8C095b87D4A4285 \ 
--transaction-strategy DryRun \
--orderbook-url https://barn.api.cow.fi/goerli/                            
...
2022-07-27T13:53:32.736Z  INFO shared::gas_price_estimation: estimator Web3, networkid 5
2022-07-27T13:53:32.856Z  INFO solver: using baseline sources baseline_sources=[BalancerV2]
2022-07-27T13:53:34.019Z DEBUG shared::sources::balancer_v2::pool_init: initialized registered pools block=7299817 pools=100
...
2022-07-27T13:53:37.348Z DEBUG solver::driver: …
```
> Configure Balancer V2 subgraph for Goerli

- crates/e2e/tests/e2e/services.rs
- crates/orderbook/src/api.rs
- crates/orderbook/src/api/post_solver_competition.rs
- crates/orderbook/src/lib.rs
- crates/orderbook/src/main.rs
- crates/orderbook/src/solvable_orders.rs
Without this change it is possible for one driver run loop to store the
solver competition info for the current id and then start the next run
loop before the api updates the solvable orders cache which results in
the id being reused by the driver.
CI. There isn't a great way to observe this in a unit or e2e test. Afterwards can check that we don't get the log message "stored solver competition with unexpected ID".
> Update the auction's next solver competition id immediately

- crates/shared/src/oneinch_api.rs
In order to match or slightly beat the prices 1inch offers in their frontend we tolerated more complex solution than they did. Complex solutions have a higher risk of reverting and of negative slippage costing us a lot of money.
To stay competitive but hopefully reduce the overall costs slightly we instead now use the default complexity arguments again (which are identical to what 1Inch uses for their frontend).
manual test running the order book locally
```
2022-08-01T09:55:08.006Z DEBUG request{id=1}: shared::oneinch_api: Query 1inch API for url https://api.1inch.exchange/v4.1/1/quote?fromTokenAddress=0xdef1ca1fb7fbcdc777520aa7f396b4e015f497ab&toTokenAddress=0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48&amount=1000000000000000000000000&protocols=UNISWAP_V1%2CUNISWAP_V2%2CSUSHI%2CMOONISWAP%2 …
```
> Use default arguments for 1inch solution complexity

- crates/autopilot/src/database.rs
- crates/autopilot/src/database/quotes.rs
- crates/autopilot/src/lib.rs
- crates/e2e/tests/e2e/services.rs
- crates/orderbook/src/database/quotes.rs
- crates/orderbook/src/main.rs
Cleaning old quotes makes more sense in the autopilot because it doesn't make sense to scale this process up with the api pods. It only needs to happen in one place.
CI
> Move database quote maintenance into autopilot

- crates/e2e/tests/e2e/services.rs
- crates/orderbook/src/lib.rs
- crates/orderbook/src/main.rs
- crates/orderbook/src/order_validation.rs
- crates/orderbook/src/orderbook.rs
- crates/orderbook/src/solvable_orders.rs
- crates/shared/src/lib.rs
- crates/shared/src/signature_validator.rs
This module is needed in orderbook and autopilot. Later I might do a fine grained refactor move some things out of shared again.
CI
> Move signature validator module into shared

- crates/orderbook/src/main.rs
- crates/shared/src/price_estimation/http.rs
- crates/shared/src/sources/uniswap_v3/pool_fetching.rs
- crates/solver/src/main.rs
This PR activates periodic background maintenance task to update the pools liquidity on UniswapV3 pools (I forgot to add this in https://github.com/cowprotocol/services/pull/388).
Initially, this was intended to be done with:
`uniswap_v3_pool_fetcher.spawn_maintenance_task(...)`
but it makes more sense to me to add this function to the `ServiceMaintenance` which is triggered on each new block. Although currently UniswapV3 is using subgraph under the hood, this change makes even more sense since we are moving towards an event based pool liquidity update.
> Activate UniswapV3 pool fetching periodic maintenance

- crates/shared/src/arguments.rs
- crates/shared/src/sources.rs
I noticed when configuring our `autopilot` pod that when using the default `--baseline-sources`, it would crash-loop.
The default baseline sources include Uniswap V3, however it fails to initialize for Görli because of a missing subgraph.
Additionally, Balancer V2 is supported on Görli but was missing from the default configuration.
Run the autopilot with `UniswapV2,SushiSwap,BalancerV2` connected to Görli and see it not crash:
```
...
2022-08-09T17:40:47.437Z  INFO autopilot: using baseline sources baseline_sources=[UniswapV2, SushiSwap, BalancerV2]
...
```
> Fix default baseline sources for Goerli

- crates/driver/src/api/solve.rs
- crates/driver/src/arguments.rs
- crates/driver/src/auction_converter.rs
- crates/driver/src/commit_reveal.rs
- crates/driver/src/driver.rs
- crates/driver/src/main.rs
- crates/shared/src/api.rs
- crates/solver/src/driver.rs
- crates/solver/src/liquidity_collector.rs
This should mostly conclude step 6 in #337 
This PR adds liquidity collection to the `AuctionConverter` in the new driver enabling the solvers to actually compute solutions.
Following steps were needed:
* create `LiquidityCollecting` trait (for testing purposes)
* add CLI arguments to new driver
* increase the allowed payload size for `/solve` (auctions are quite big)
I was so far not able to get a solution which actually simulates. I will delay debugging that (if that was even caused by a bug in the new driver) to a follow up PR where I focus on logging errors with tenderly links like the current driver does it.
Added unit test for liquidity collection in `AuctionConverter`.
<details>
<summary>manual test piping a real auction to quasimodo through the new driver</summary>
During this …
> Collect liquidity in new driver

- crates/model/src/order.rs
- crates/solver/src/driver.rs
- crates/solver/src/in_flight_orders.rs
This PR removes the `Hash` implementation from the `Order` type because it is ambiguous.
For example, consider the following order:
```rust
let order0 = Order {
metadata: OrderMetadata {
uid: x,
executed_amount: 0,
// ...
},
data: OrderData {
partially_fillable: true,
// ...
},
// ...
}
```
And
```rust
let order1 = {
let mut order = order0.clone();
order.metadata.executed_amount += 1; // so it got a little executed
order
};
```
Then, you might expect:
```rust
let mut set = HashSet::new();
set.insert(order0);
set.insert(order1);
assert!(set.len(), 1);
```
HOWEVER, this is not the case, as it would be actually (and for good reason):
```rust
assert!(set.len(), 2);
```
This change required a small refactor to the in-flight order code (although should not change the behaviour).
Note that we …
> Don't implement `Hash` for `Order`.

- crates/solver/src/driver.rs
- crates/solver/src/in_flight_orders.rs
I really hope this PR doesn't again break something 🤞 , it's just adding some more logging (I promise to not do any logic changes).
When debugging why a specific order took long to get matched, I noticed that it wasn't included in all auctions even though it had never been part of an in-flight settlement. Currently we log the number of orders that get filtered in this step but not their order IDs. This PR add logging for the filtered IDs
Run driver against mainnet prod in DryRun mode and see the following log statement:
> 2022-08-10T14:17:11.786Z DEBUG auction{id=15977 run=0}: solver::driver: reduced 12 orders to 11 because in flight at last seen block 15314828, difference: [0xdcb5921ee9cb5e3124e84c1c7ce0f24ec097ca86179704cfbebbc2c6eff00aa8fc78f8e1af80a3bf5a1783bb59ed2d1b10f78ca962f50b60]
> [Logging] Log filtered orders that are assumed to be inflight

- crates/shared/src/maintenance.rs
Fixes #444.
This PR replaces maintenance error alerts (i.e. `tracing::error!` log messages that cause alert notifications) with metrics tracking the last seen block, as well as the last successfully updated block.
This allows us to have more complex alerts (such as >3 successive maintenance failures, or no new block in past minute) and reduce noise.
Check the metrics are there:
```
% cargo run -p orderbook &
% cargo run -p solver &
% cargo run -p autopilot &
% curl -s http://localhost:9586/metrics | rg maintenance
gp_v2_api_maintenance_last_seen_block 15322558
gp_v2_api_maintenance_last_updated_block 15322558
% curl -s http://localhost:9587/metrics | rg maintenance
gp_v2_solver_maintenance_last_seen_block 15322560
gp_v2_solver_maintenance_last_updated_block 15322560
% curl -s …
```
> Track maintenance blocks

- crates/database/src/orders.rs
- database/sql/V028__index_settlements_tx_hash.sql
Fixes https://github.com/cowprotocol/services/issues/89 .
- This is somewhat different from sketch in the comment because that approach wasn't valid sql and not entirely correct.
- The previous test wrongly inserted the settlement event before the trade event.
- We forgot to add an index on the settlements table by tx hash which I have fixed too. This doesn't influence the correctness of the code change.
CI, adapted test
> Fix handling of multiple settlements in same block

- crates/solver/src/driver.rs
- crates/solver/src/in_flight_orders.rs
I'm not sure if this logic change is the correct fix, but the problem I'm seeing is that we currently filter out [this order](https://explorer.cow.fi/orders/0xdcb5921ee9cb5e3124e84c1c7ce0f24ec097ca86179704cfbebbc2c6eff00aa8fc78f8e1af80a3bf5a1783bb59ed2d1b10f78ca962f50b60) as being "in-flight" even though it is not. 
The reason is that in the current logic an order is filtered if either its buy or sell Amount are reached. This means a partially fillable order (e.g. sell 100 DAI for at least 50USDC) would be filtered if it was filled at a 50% at a price of 1:1 (50 DAI sold for 50 USDC). In this case we would have reached the sell amount and therefore no longer retain this order.
In this fix I changed the filled condition to be based on the order kind. A sell order is filled if its sell …
> Don't filter our partially fillable sell orders that have reached minBuyAmount

- Cargo.lock
- crates/autopilot/Cargo.toml
- crates/autopilot/src/arguments.rs
- crates/autopilot/src/database.rs
- crates/autopilot/src/lib.rs
- crates/autopilot/src/solvable_orders.rs
- crates/e2e/tests/e2e/eth_integration.rs
- crates/e2e/tests/e2e/onchain_settlement.rs
- crates/e2e/tests/e2e/services.rs
- crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
- crates/e2e/tests/e2e/vault_balances.rs
- crates/model/src/lib.rs
- crates/orderbook/src/api.rs
- crates/orderbook/src/api/get_auction.rs
- crates/orderbook/src/api/get_solvable_orders.rs
- crates/orderbook/src/api/get_solvable_orders_v2.rs
- crates/orderbook/src/api/post_solver_competition.rs
- crates/orderbook/src/arguments.rs
- crates/orderbook/src/database/orders.rs
- crates/orderbook/src/database/solver_competition.rs
- crates/orderbook/src/lib.rs
- crates/orderbook/src/main.rs
- crates/orderbook/src/orderbook.rs
- crates/orderbook/src/solver_competition.rs
Moves the solvable_orders module into autopilot, instantiates it, and makes it store the auctions in the database.
In the orderbook we read the auction from the database.
CI
> Move auction creation into autopilot

- crates/database/src/quotes.rs
- crates/database/src/trades.rs
- crates/model/src/auction.rs
- crates/model/src/quote.rs
- crates/model/src/solver_competition.rs
- crates/orderbook/src/database/trades.rs
- crates/orderbook/src/order_quoting.rs
- crates/orderbook/src/order_validation.rs
- crates/shared/src/arguments.rs
- crates/shared/src/balancer_sor_api.rs
- crates/shared/src/http_solver/model.rs
- crates/shared/src/oneinch_api.rs
- crates/shared/src/paraswap_api.rs
- crates/shared/src/price_estimation.rs
- crates/shared/src/signature_validator.rs
- crates/shared/src/sources/balancer_v2/graph_api.rs
- crates/shared/src/sources/balancer_v2/pools.rs
- crates/shared/src/sources/uniswap_v3/graph_api.rs
- crates/shared/src/sources/uniswap_v3/pool_fetching.rs
- crates/shared/src/subgraph.rs
- crates/shared/src/token_list.rs
- crates/shared/src/zeroex_api.rs
- crates/solver/src/interactions/allowances.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/settlement_submission.rs
CI has updated to use Rust 1.63. This introduced some new clippy lints which caused our CI to fail (mostly "you should implement `Eq` as well" lints).
This PR just fixes the lints so we can move on with our lives.
> Fix Rust 1.63 Cargo Clippy Warnings

- crates/shared/src/http_solver/model.rs
The `Debug` implementation of `InteractionData` was not doing what it was supposed to. It was clearly intended to print the `call_data` as `0x123....` although [Kibana](https://logs.cow.fi/app/discover#/doc/63bc0b10-5f93-11e9-bf17-fbe383fc7c9c/logstash-2022.08.18?id=4fpcsIIBO2Iz_eQrKT_b) shows it currently being logged as `[1, 2, 3, ...]` instead.
To enable the `#[derivative(...)]` override macros on the members of the struct the struct also has to use the `#[derivative(TRAIT_TO_OVERRIDE)]` macro as a whole.
CI
verified the fixed `Debug` output with a temporary local test:
```
InteractionData { target: 0xffffffffffffffffffffffffffffffffffffffff, value: 0, call_data: 0x01020304, inputs: [TokenAmount { amount: 9999, token: 0x0101010101010101010101010101010101010101 }], outputs: [TokenAmount …
```
> Fix Debug implementation of InteractionData

- crates/autopilot/src/lib.rs
- crates/orderbook/src/main.rs
- crates/shared/src/arguments.rs
- crates/shared/src/oneinch_api.rs
- crates/shared/src/price_estimation/oneinch.rs
- crates/solver/src/main.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/oneinch_solver.rs
The 1Inch solver is costing a lot of money to run because it keeps positive slippage. One way to reduce the cost a bit is to participate in 1Inch's referral program.
This program rewards referrers some amount of `1INCH` tokens for every trade referred to 1Inch. The rewards can be claimed "approximately once per week" [[0](https://help.1inch.io/en/articles/4585140-what-is-the-referral-program-and-how-does-it-work)]. The 1Inch DAO can vote how much of the fees get rewarded for the referral [[1](https://app.1inch.io/#/1/dao/vote/referralShare)].
new CLI argument:
```
--one-inch-referrer-address <ONE_INCH_REFERRER_ADDRESS>
Which address should receive the rewards for referring trades to 1Inch
[env: ONE_INCH_REFERRER_ADDRESS=]
```
logs for CLI argument:
```
...
one_inch_url: …
```
> Make referrer address configurable for 1Inch

- crates/solver/src/driver.rs
- crates/solver/src/driver_logger.rs
- crates/solver/src/lib.rs
- crates/solver/src/settlement_ranker.rs
Useful refactoring for step 8 of #337 
Settlement submission has a lot of subtleties and currently involves a huge amount of logging and metrics. Ideally the new driver would do that exactly as the current one and to not introduce bugs by poorly copying bits and pieces I refactored the current logging logic into the `DriverLogger`. I also made `submit_settlement()` a free function which only needs a `SolutionSubmitter` and a `DriverLogger` to handle the submission, logging and metrics.
That allows me to simply re-use that component in the new driver resulting in the identical behavior.
The refactor moves a bunch of code so to help with the review I made small commits which all compiled without any clippy warnings. So I would suggest reviewing those commits individually and in order.
To be …
> Move much of the logging out of the driver

- crates/autopilot/src/lib.rs
Fixed #462 
This PR adds the UniswapV2-like liquidity `PoolCache` instance to the list of components that require block maintenance.
We noticed that prices included in the auctions were inaccurate for specific tokens. We identified that one potential issue was that the configuration between the `autopilot` and `orderbook` were different. However, it did not explain why the configuration with **less** liquidity had **better** prices.
It turns out that we weren't running block maintenance on our `PoolCache` instance. The check that verifies that the cached pool data is sufficiently up to date compares the fetched block with the last updated block:
https://github.com/cowprotocol/services/blob/6d56663e7b6296597599a5accce746278243606c/crates/shared/src/recent_block_cache.rs#L286-L293
Which …
> Make sure to maintain UniV2 pool fetcher

- crates/shared/src/http_solver/model.rs
Partly fixes #453
AFAIK the new interaction format changed 2 things in backwards compatible ways:
1. add `inputs` and `outputs` for interactions and assume empty lists if they were not in the serialized response
2. allow serializing call data as an array of numbers (old way) and as a hex string
I see that solvers already adopted the `input` and `outputs` but not the new serialization scheme so this PR will only make `inputs` and `outputs` required but still allows the old `call_data` format.
Manual test verifying that solutions don't cause deserialization errors.
Updated existing unit test for backwards compatibility (it now only verifies desierialization of the old `call_data` format).
> Require inputs and outputs for interactions in settlement

- crates/shared/src/http_solver/model.rs
Fixes #453
Drops deprecated way to serialize `call_data` (as integer array instead of hex string). This was done in a separate PR to make reverting it easier if this causes issues (because some solvers might still use it) as discussed [here](https://github.com/cowprotocol/services/pull/455#issuecomment-1224146798).
CI
> Drop deprecated call_data format

- crates/shared/src/sources/balancer_v2/pool_fetching.rs
While debugging, I noticed that we have a lot of noise in our info messages. 
I would like to reduce it, in order to get an easy overview of the state of our infrastructure by only viewing the info logs.
> [easy] using debug instead of info in some places

- crates/driver/src/main.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/http_solver.rs
Patches #454.
One of the external solvers integrating with our protocol noticed that orders that they were explicitly trying to solve for were being filtered out and not sent as part of the instance they were solving for.
Specifically, the external solver integration aimed at handling orders trading specific tokens by entering and exiting on-chain positions instead of the standard swapping with on-chain liquidity. This meant that orders for these tokens were not being passed to the solvers and were being filtered out (since there was no baseline liquidity between those tokens and the fee token) despite the order being allowed (because of existing price estimate). This meant that these orders could never be solved! They can't be handled by our single order solvers and were getting filtered …
> No liquidity or filtering of non-fee-connected-tokens for external solvers

- crates/solver/src/settlement_submission/submitter/custom_nodes_api.rs
We got some new error messages from Erigon node for already existing txs. See [here](https://logs.cow.fi/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d%2Fd,to:now))&_a=(columns:!(log),filters:!(),index:'63bc0b10-5f93-11e9-bf17-fbe383fc7c9c',interval:auto,query:(language:kuery,query:'%20log:%20%22custom_nodes_1%22%20and%20log:%20%22error%22'),sort:!(!('@timestamp',desc))))
> Adding new error messages for existing tx from erigon node

- crates/driver/src/main.rs
- crates/solver/src/liquidity/zeroex.rs
- crates/solver/src/main.rs
There were quite a few [simulation failures](https://cowservices.slack.com/archives/C0361CDD1FZ/p1661543463263019) for settlements including `ZeroExInteraction`s. This was caused by the `ZeroExInteraction` not automatically appending the appropriate `Approval` interaction when the `ZeroExInteraction` was used and encoded in a settlement.
To fix that I followed how the balancer liquidity and interaction handles this and implemented it accordingly for ZeroEx.
added unit test verifying the encoded `Approval` and `ZeroExInteraction`
> Use AllowanceManager in ZeroExInteraction

- crates/driver/src/arguments.rs
- crates/driver/src/commit_reveal.rs
- crates/driver/src/driver.rs
- crates/driver/src/main.rs
- crates/solver/src/driver.rs
- crates/solver/src/driver_logger.rs
- crates/solver/src/settlement_rater.rs
Implements step 8 and partly step 7 of #337
Recently I refactored some of the current driver logic into separate components in order to reuse them in the new driver. This PR makes use of the free function responsible for submitting settlements as well as logging and metrics related to that.
In order to make the refactored code compatible with the new driver I had to do a few additional changes:
1. Don't submit a `RatedSettlement` but instead  require a `Settlement` and a few additional pieces of information.
2. Split `SettlementRater::rate_settlements()` into simulating (+estimating gas costs) and rating the settlement.
3. Add an wrapper around `dyn CommitRevealSolving` which implements `dyn Solver`. This is definitely not optimal but much of the existing logic passes around `Arc<dyn …
> Reuse submission logic from current driver in the new driver

- README.md
- crates/autopilot/src/arguments.rs
- crates/orderbook/src/arguments.rs
- crates/shared/src/arguments.rs
As a follow up to #473, this PR makes all our "flag" command line arguments consistent. That is, you now enable flags with `--my-flag` instead of `--my-flag true`.
Previously, we had used `parse(try_from_str), default_value = "false"` to work around Kubernetes configuration templating limitations. However, those limitations are no longer present (well, they never were... we just figured out how to include conditionals in the template). This PR changes all flags to be more "Unix-y" (and IMO natural), where `--some-flag` is used to enable it instead of `--some-flag true`.
Additionally, I removed the `default_value = "true"` attribute from the `--enable-blockscout` flag. This is for two reasons:
- Since this is a flag that doesn't parse an argument value, this effectively means that it …
> Make flag command line arguments consistent

- crates/autopilot/src/solvable_orders.rs
This just rewords the message that gets logged when EIP-1271 signatures for orders become invalid.
The main motivation here is to make all "order filtering" messages follow a similar pattern for better grep-ability in the logs.
CI
> Reword log for filtered invalid EIP-1271 orders

- crates/solver/src/driver_logger.rs
It happened to me a few times that I wanted to analyze the occurrence of a simulation error in relation to certain properties of the failed settlement. The most recent example is [here](https://cowservices.slack.com/archives/C0361CDD1FZ/p1661587836883249?thread_ts=1661543463.263019&cid=C0361CDD1FZ).
If you only look at a few specific simulation error it's possible to get the human readable settlement. But if you want to do gather some large scale data this approach is too cumbersome and manual.
A simple way to address this issue is to also log the simulation error with the readable and queryable settlement. Theoretically one could also only have 1 log statement for readable settlement, simulation link and simulation error but the code has a comment saying this option would lead to too …
> Log simulation error with readable settlement

- crates/solver/src/settlement_submission/submitter/eden_api.rs
The eden submitter tries 2 ways of submitting a transaction. In case we currently hold a prioritized slot in the block due to staking eden we start with `eth_sendSlotTx` and if that fails because we currently don't hold the slot we try the normal `eth_sendRawTransaction`.
The problem is that `eth_sendSlotTx` has apparently been removed which leads to [these](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/doc/6eecf430-220f-11ed-bbdc-2f476b18353d/logstash-prod-2022.08.30?id=eZhQ7YIBNGla5u5d5v43) errors. However, the error suggests that the method `eth_sendSlotTxs` exists so let's just use that one instead.
CI + deploy and check errors
> Use eth_sendSlotTxs in eden submission

- crates/autopilot/src/arguments.rs
- crates/driver/src/arguments.rs
- crates/orderbook/src/arguments.rs
- crates/shared/src/arguments.rs
- crates/solver/src/arguments.rs
- crates/solver/src/solver.rs
This PR refactors `arguments::display_*` to do a little more than just display the arguments. When implementing additional arguments flags for other PRs, I found the pattern required to use those helper methods quite tedious and error-prone (I would forget the `writeln` at the end, use `writeln` instead of `write` for the name, place another field between the `display_*` and `writeln!(f)` to name a few):
```rust
write!(f, "some_flag: ")?;
display_X(&f.some_flag, f)?;
writeln!(f)?;
```
Since the `arguments::display_*` methods are only ever used for fields, I thought it made sense to specialize them so its a bit more ergonomic to use:
```rust
display_X(f, "some_flag", &f.some_flag)?;
```
Run the crates and see the formatted arguments still work (not included here as it would make the PR …
> refactor arguments display

- crates/autopilot/src/arguments.rs
- crates/autopilot/src/lib.rs
- crates/orderbook/src/arguments.rs
- crates/orderbook/src/main.rs
- crates/shared/src/bad_token/token_owner_finder.rs
- crates/shared/src/bad_token/token_owner_finder/liquidity.rs
- crates/shared/src/bad_token/trace_call.rs
This PR refactors how token owner finder initialization works.
Specifically, it:
1. Changes the command line arguments to expect a list of `TokenHolderFinderStrategies`. The idea here is that we plan on falling back to additional token holder APIs, and having separate `enable_...` flags for each is untenable.
2. Moves the liquidity-based token holder finder implementations to a separate module. The main motivation here is that the logic for finding a token holder with a minimum amount needs to move to a shared place. This is because various bad token detection implementations (Tenderly, storage override, etc.) will need a token holder address.
3. Shared initialization code - this ensures that the `autopilot` and `orderbook` are in-sync WRT token holder initialization logic.
This PR is …
> Refactor token holder finding startup

- crates/driver/src/arguments.rs
- crates/driver/src/main.rs
- crates/e2e/tests/e2e/eth_integration.rs
- crates/e2e/tests/e2e/onchain_settlement.rs
- crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
- crates/e2e/tests/e2e/vault_balances.rs
- crates/shared/src/arguments.rs
- crates/solver/src/arguments.rs
- crates/solver/src/main.rs
- crates/solver/src/settlement_submission.rs
- crates/solver/src/settlement_submission/submitter.rs
Currently eden's submission error alert is one of our noisiest. Also it's not really actionable so let's try to fix it.
My current working hypothesis is that eden sometimes submits a transaction into the mempool but reports an error anyway. This would lead our submission logic to think the gas price which would require a replacement tx would be the price of `tx_1 * 1.25 (MIN_GAS_BUMP)`. But since the mempool already knows about `tx_2` which must have at least a gas price of `tx_1 * 1.25` the actual replacement tx would have to have a gas price of at least `tx_2 * (1.25^2)`.
This hypothesis came from logs like [this](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-29T13:54:25.446Z',to:'2022-08-29 …
> Hopefully fix noisy submission error alert on eden

- crates/solver/src/settlement.rs
Need to debug log them to see the full address.
CI still compiles
> Print full token address in prioce violation log

- crates/shared/src/bad_token/token_owner_finder.rs
- crates/shared/src/bad_token/token_owner_finder/ethplorer.rs
- crates/shared/src/paraswap_api.rs
- crates/shared/src/rate_limiter.rs
Fixes #206.
This PR adds an additional external token holder API as a `TokenHolderFinding` implementation. This API seems much snappier than Blockscout, but it does aggressive rate-limiting in the free tier (which is why I already included a `RateLimiter` instance with it).
Not too long ago Blockscout API went down for maintenance. With this change, we have another "backup" external token holder API to fall-back to in those cases.
Some additional integration tests that can be run:
```
% cargo test -p shared -- ethplorer --ignored                
Finished test [unoptimized + debuginfo] target(s) in 0.30s
Running unittests src/lib.rs (target/debug/deps/shared-7e49af595ac95baf)
running 2 tests
test bad_token::token_owner_finder::ethplorer::tests::test_blockscout_token_finding_no_owners ... …
```
> Added new Ethplorer based token holder API

- crates/shared/src/transport.rs
- crates/shared/src/transport/extensions.rs
This PR introduces a new `EthExt` Web3 API implementation (similar to the existing `web3::api::Eth`).
It adds a `eth_call` with state overrides as specified in the [Go Ethereum `eth_call` documentation](https://geth.ethereum.org/docs/rpc/ns-eth#eth_call).
This "extension" is intended on being used for doing simulations with state overrides of trades and for bad token detection. 
CI - also added a manual test. You can execute it with Infura for example:
```
% export NODE_URL=https://mainnet.infura.io/v3/$INFURA_PROJECT_ID
% cargo test -p shared -- can_call_with_state_override --ignored
Finished test [unoptimized + debuginfo] target(s) in 0.16s
Running unittests src/lib.rs (target/debug/deps/shared-2a45c524d94b8144)
running 1 test
test …
```
> Web3 API implementation for eth_call with state overrides

- README.md
- crates/autopilot/src/arguments.rs
- crates/autopilot/src/lib.rs
- crates/driver/src/main.rs
- crates/orderbook/src/arguments.rs
- crates/orderbook/src/main.rs
- crates/shared/src/lib.rs
- crates/solver/src/main.rs
This PR adds a separate `--tracing-node-url` parameter for allowing a separate node URL to for the `trace_callMany` calls.
It is possible that tracing nodes are harder to run and/or more expensive with external node providers. With this change, we have more flexibility with how we split our RPC calls (for example, we can have separate plans for our regular Ethereum RPC calls, and a special plan - with much less traffic - for our `trace_callMany` calls).
Additionally, we deprecate the no-longer-needed `--skip-trace-api` parameter, using the presence of the `--tracing-node-url` as an indicator of whether or not tracing API is supported.
CI. Check that we are instantiating separate nodes:
```
% cargo run -p orderbook -- --node-url $NODE_URL --tracing-node-url $NODE_URL …
```
> Allow configuration of separate tracing nodes.

- crates/solver/src/settlement_submission.rs
- crates/solver/src/settlement_submission/submitter.rs
Right now it's quite tricky to follow what each submission strategy is doing (eden, flashbots, custom nodes) because they are all running concurrently. Many log statements have the submission name in them but not all and it's easy to forget to add the name when adding a new log.
To address both issues I added a tracing info span to the call site of `Submitter::submit()` method.
The tracing span obviously has to contain the submission API name, but since some submission APIs can be instantiated multiples times (custom nodes, flashbots) I also added the index of the submission strategy to the tracing span.
Because the borrow checker was not happy with me trying to copy the index into the async block I ended up moving the logic into a helper function which made it easier to specify which …
> Use tracing span for submission loop

- crates/autopilot/src/database/events.rs
- crates/autopilot/src/lib.rs
- crates/shared/src/current_block.rs
- crates/shared/src/event_handling.rs
- crates/shared/src/sources/balancer_v2/graph_api.rs
- crates/shared/src/sources/balancer_v2/pool_fetching.rs
- crates/shared/src/sources/balancer_v2/pool_fetching/pool_storage.rs
- crates/shared/src/sources/balancer_v2/pool_init.rs
- crates/shared/src/sources/balancer_v2/pools/common.rs
- crates/shared/src/sources/balancer_v2/pools/liquidity_bootstrapping.rs
- crates/shared/src/sources/balancer_v2/pools/stable.rs
- crates/shared/src/sources/balancer_v2/pools/weighted.rs
This PR starts implementing steps (2) and (3) from https://github.com/cowprotocol/services/issues/478 (but slightly different than explained in here)
Step (1) is implemented in https://github.com/cowprotocol/services/pull/485
Changes in this PR:
1. Implemented batch RPC call to get the block number and block hash from last N blocks.
2. `last_handled_block` in `EventHandler` is no longer a single value, but vector. It remembers last N blocks number and hash.
3. Function `EventHandler::event_block_range` is smarter. Now it detects the most common situation (where only one block is added compared to last function call), but also, if this is not the case, does a reorg search and returns the minimum block range needed to update the events (instead of always returning the full N length block …
> Implement steps (2) and (3) for EventHandler

- crates/shared/src/order_validation.rs
As title. Onchain orders later also need to access the function, but they will not have the same "order type"
testplan:
none
> [Easy] Making is_order_outside_market_price more flexible for future use-case

- Cargo.lock
- crates/autopilot/src/arguments.rs
- crates/autopilot/src/lib.rs
- crates/driver/src/arguments.rs
- crates/driver/src/main.rs
- crates/e2e/tests/e2e/eth_integration.rs
- crates/e2e/tests/e2e/onchain_settlement.rs
- crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
- crates/e2e/tests/e2e/vault_balances.rs
- crates/orderbook/src/arguments.rs
- crates/orderbook/src/main.rs
- crates/shared/Cargo.toml
- crates/shared/src/arguments.rs
- crates/shared/src/bad_token/token_owner_finder.rs
- crates/shared/src/bad_token/token_owner_finder/blockscout.rs
- crates/shared/src/gas_price_estimation.rs
- crates/shared/src/http_client.rs
- crates/shared/src/lib.rs
- crates/shared/src/zeroex_api.rs
- crates/solver/Cargo.toml
- crates/solver/src/arguments.rs
- crates/solver/src/main.rs
- crates/solver/src/settlement_access_list.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/settlement_submission/submitter.rs
- crates/solver/src/solver.rs
This PR refactors how we create and pass around HTTP clients.
Previously, we used to use one shared `reqwest::Client` instance globally in our application. This was good because it ensured that our HTTP configuration was common everywhere. However this has some limitations:
- We share connection pools across APIs, which doesn't make sense since they connect to different hosts.
- We cannot configure API HTTP clients differently, this was an issue with Blockscout, but also things like the `ZeroExApi` and `TenderlyApi` where we needed to specify headers per request instead of specifying default headers per client.
- We need cookies for sticky connections with our load balancer. This meant we would have a globally shared cookie jar, instead of a cookie jar just for our Ethereum node …
> Refactor HTTP client initialization

- crates/shared/src/http_solver.rs
Passing "--ucp_policy EnforceForOrders" as a query parameter when calling quasimodo is no longer necessary.
> Removed unused parameter when calling quasimodo.

- crates/orderbook/src/arguments.rs
- crates/orderbook/src/main.rs
- crates/shared/src/order_validation.rs
- crates/solver/Cargo.toml
This PR adds a new `--eip1271-skip-creation-validation` flag to the `orderbook` API. This flag controls whether or not ERC-1271 orders need to have `isValidSignature` on creation. Note that order signatures are still verified by the `autopilot` when preparing auctions (i.e. it still filters invalid signatures from batches). This means that this change will not change the orders that make it to the solver, but just allow invalid orders to be placed.
The main motivation for this change is to enable "smart" orders that start off invalid and become valid at some later point in time.
Examples of this are:
- "Good after time" (GAT) orders
- Stop-loss orders
There are some potential concerns about order spamming (i.e. creating orders with invalid signatures that won't ever become valid). …
> Add flag for skipping EIP-1271 order signature validation on creation

- crates/shared/src/price_estimation.rs
- crates/shared/src/price_estimation/trade_finder.rs
- crates/shared/src/price_estimation/zeroex.rs
This PR refactors the 0x price estimator to use the new `TradeFinding` abstraction from #519.
It introduces a new generic `TradeEstimator` price estimating implementation. Other DEXag-based prices estimators (such as ParaSwap and 1Inch) can also be refactored for this new scheme in follow-up PRs.
CI - existing tests continue to pass.
> Refactor 0x Price Estimator

- crates/driver/src/arguments.rs
- crates/driver/src/main.rs
- crates/e2e/tests/e2e/eth_integration.rs
- crates/e2e/tests/e2e/onchain_settlement.rs
- crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
- crates/e2e/tests/e2e/vault_balances.rs
- crates/shared/src/lib.rs
- crates/shared/src/tenderly_api.rs
- crates/solver/src/arguments.rs
- crates/solver/src/driver.rs
- crates/solver/src/driver_logger.rs
- crates/solver/src/main.rs
- crates/solver/src/settlement_access_list.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/settlement_submission/submitter.rs
This PR refactors the `TenderlyApi` type to more closely follow our other API implementations. Namely:
- Define a `TenderlyApi` trait
- Define a `TenderlyHttpApi` implementation for it
We need to split out the `TenderlyApi` into something that can also be re-used for trade simulation and bad token detection. Specifically, not all nodes support `eth_call` with state overrides, but Tenderly does - so it can be used as an alternative for `eth_call` with state override and `trace_callMany` bad token detection.
CI. Existing tests continue to pass.
Additionally, existing integration test continues to pass.
The `--tenderly-url` flag was replaced by `--tenderly-user` and `--tenderly-project`.
> Refactor `TenderlyApi` for reuse in bad token detection

- crates/model/src/bytes_hex.rs
- crates/shared/src/bad_token/roundtrip.rs
- crates/shared/src/code_simulation.rs
- crates/shared/src/lib.rs
- crates/shared/src/macros.rs
- crates/shared/src/tenderly_api.rs
- crates/shared/src/transport/extensions.rs
This PR implements a new `CodeSimulating` abstraction for simulating a contract call with state overrides.
This is **different** than the `eth_call` with state overrides introduced in #507, in that it abstracts away how the simulation is done. Specifically, not all nodes implement `eth_call` with state overrides (Nethermind for example), but Tenderly works for all of our supported networks. This means we can use Tenderly for these simulations even on networks where we connect to Nethermind nodes (Gnosis Chain for instance).
Added some integration tests:
```
% cargo test -p shared -- --ignored code_simulation
Finished test [unoptimized + debuginfo] target(s) in 0.24s
Running unittests src/lib.rs (target/debug/deps/shared-e14dee386a6fa988)
running 2 tests
test …
```
> Implement Component for Simulating EVM Bytecode

- crates/shared/src/order_quoting.rs
- crates/shared/src/price_estimation.rs
- crates/shared/src/price_estimation/balancer_sor.rs
- crates/shared/src/price_estimation/baseline.rs
- crates/shared/src/price_estimation/competition.rs
- crates/shared/src/price_estimation/http.rs
- crates/shared/src/price_estimation/instrumented.rs
- crates/shared/src/price_estimation/native.rs
- crates/shared/src/price_estimation/oneinch.rs
- crates/shared/src/price_estimation/paraswap.rs
- crates/shared/src/price_estimation/sanitized.rs
- crates/shared/src/price_estimation/trade_finder.rs
- crates/shared/src/price_estimation/zeroex.rs
- crates/shared/src/trade_finding/zeroex.rs
This PR adds a new `from` optional field for price estimation queries. This can be used by the quote endpoint for specifying the user it is quoting for. This allows components like the `TradeVerifier` to use this user address as the actual trader when verifying the trading logic so that:
- We can check that the token can be traded by the actual user doing the trade
- We can use the user's real token balance: this makes the simulation more accurate (so actual token `tranfer` logic gets used, and the gas estimation more accurately reflects what will be used by the trade execution).
Adjusted unit tests to ensure field is properly set.
> Add from field to price estimation queries

- crates/solver/src/orderbook.rs
The api can return a 404 if there is no current auction. In this case the body is empty so we get a generic "failed to decode json" error message. With this change we check the status code and return a better message.
CI, didn't manually test how the error message looks exactly
> Return better error message if auction is 404

- crates/solver/src/settlement_submission/submitter.rs
- crates/solver/src/settlement_submission/submitter/public_mempool_api.rs
Some suggestions/concerns were brought up shortly after merging a few tweaks in our submission logic.
This PR addresses them:
* always log unexpected errors in the `PublicMempoolApi` otherwise it's hard to debug when an alert reports problems for a specific node url ([comment](https://github.com/cowprotocol/services/pull/558#discussion_r975432329))
* don't overpay for cancellations ([comment](https://github.com/cowprotocol/services/pull/522#discussion_r974222108))
> Address comments for submission logic

- crates/shared/src/current_block.rs
Sometimes we have the problem that our load balancer starts sending requests to nodes which are stuck in the past. When that happens we receive vastly outdated blocks which can cause problems in our system.
Dshackle is supposed to handle old nodes but it looks like it forwards one outdated response before avoiding that node for a while.
Since this issue is quite problematic for the data consistency of the system but happens rarely I decided to log it as an error so we get automatic alerts when it happens.
I added histogram metrics so we can configure alerts for suspicious update deltas without having to change the code later on.
<details>
<summary>metrics</summary>
```
gp_v2_api_block_stream_update_delta_bucket{sign="positive",le="0"} 0 …
```
> Prevent very old blocks from entering the current_block_stream

- crates/autopilot/src/database/onchain_order_events/ethflow_events.rs
Switches the order of reading quote_id and valid_to from data of event.
The e2e tests were successful and this was the only issue found. 
=> Your reviews were great and caught almost everything! Thanks again!
Note that [Federico changed this only recently](https://github.com/cowprotocol/ethflowcontract/pull/10), it was only missed to change here.
> Easy Fix: ethflow parsing

- crates/shared/src/oneinch_api.rs
- crates/shared/src/price_estimation/oneinch.rs
- crates/shared/src/solver_utils.rs
- crates/shared/src/trade_finding.rs
- crates/shared/src/trade_finding/oneinch.rs
- crates/solver/src/solver/oneinch_solver.rs
This PR introduces a 1Inch `TradeFinding` implementations.
In #519 and #520, we introduced a `TradeFinding` price estimator that can additionally simulate trade calldata to make sure trades are valid.
This PR adds a `TradeFinding` implementation for 1Inch so that it can be used with this price estimation abstraction in the future. Note that we don't quite make use of it yet, for reasons 👇.
One of the functionality changes in the PR is that now, for price estimation, we don't just compute a 1Inch `quote` but `quote` and `swap`. This is because:
- `quote` has `gas_estimate` values - while they aren't needed if we simulate, they are needed by the `TradeFinding` interface and will be used if:
- A `TradeFinding`-based price estimator is configured without a `TradeVerifier` for trade simulation …
> Introduce 1Inch Trade Finder

- crates/shared/src/price_estimation/trade_finder.rs
- crates/shared/src/trade_finding.rs
- crates/shared/src/trade_finding/oneinch.rs
- crates/shared/src/trade_finding/zeroex.rs
When porting 1Inch and ParaSwap price estimators to the new `TradeFinding` abstraction (so that we can simulate trades).
For both 1Inch and ParaSwap, we only need the calldata **IF** we are simulating trades (i.e. `trade_verifier.is_some()`). The "vision" is to have only trade verification for `price_quality: Optimal`, so for our `Fast` estimates, we don't want the additional parallel API requests (for 1Inch) or additional roundtrip API requests (for ParaSwap).
With this change, expand the `TradeFinding` abstraction to also provide logic for getting quotes without calldata, and use that when no verification is needed. This has the effect that our 1Inch and ParaSwap `Fast` price estimates will work exactly as they do today, and the `Optional` one will simluate trades.
Added unit test to …
> Expand TradeFinding Interface for Quoting

- crates/shared/src/paraswap_api.rs
- crates/shared/src/price_estimation/paraswap.rs
- crates/shared/src/token_info.rs
- crates/shared/src/trade_finding.rs
- crates/shared/src/trade_finding/paraswap.rs
- crates/solver/src/solver/paraswap_solver.rs
This PR is a follow up to https://github.com/cowprotocol/services/pull/519 and https://github.com/cowprotocol/services/pull/520, where we introduced a `TradeFinding` interface and price estimator (with trade simulations).
Specifically, this PR implements a ParaSwap price finder that conforms to the new interface. This way, we will be able to make ParaSwap price estimates as before, but with one important caveat: We used to pre-fetch all token information for the "streamed" estimates. This was a nice optimization that allowed us to use a single round-trip to fetch all token infos for all traded tokens when batching price estimation queries.
For now, I just removed this feature because:
- It doesn't really improve price estimate performance since that is for a single trading pair anyway (so …
> Introduce ParaSwap Trade Finder

- crates/shared/src/oneinch_api.rs
- crates/shared/src/price_estimation/oneinch.rs
- crates/shared/src/trade_finding/oneinch.rs
Follow up from #552 (and very similar to #520) - this PR refactors the 1Inch price estimator to be implemented in function of the `OneInchTradeFinder` (i.e. its trade finding interface). This allows the price estimator to use the shared `TradeFinderPriceEstimator` implementation with rate limiting, request sharing and trade simulation.
Existing unit tests continue to pass, as does manual test:
```
% cargo test -p shared -- --ignored --nocapture price_estimation::oneinch
Finished test [unoptimized + debuginfo] target(s) in 13.46s
Running unittests src/lib.rs (target/debug/deps/shared-dc5df787a41d4411)
running 1 test
[crates/shared/src/price_estimation/oneinch.rs:211] &result = Ok(
Estimate {
out_amount: 10512215403913030143,
gas: 703807,
},
)
1 WETH buys 10.51221540391303 GNO, costing …
```
> Refactor 1Inch Price Estimator

- crates/shared/src/price_estimation/paraswap.rs
This PR is similar to #561. It refactors the ParaSwap price estimator to be implemented in function of the `ParaswapTradeFinder` (i.e. its trade finding interface). This allows the price estimator to use the shared `TradeFinderPriceEstimator` implementation with rate limiting, request sharing and trade simulation.
Manual ParaSwap test passes:
```
% cargo test -p shared -- --ignored --nocapture price_estimation::paraswap
Blocking waiting for file lock on build directory
Compiling shared v0.1.0 (/Users/nlordell/Developer/cowprotocol/services/crates/shared)
Finished test [unoptimized + debuginfo] target(s) in 19.33s
Running unittests src/lib.rs (target/debug/deps/shared-dc5df787a41d4411)
running 1 test
[crates/shared/src/price_estimation/paraswap.rs:78] &result = Ok(
Estimate {
out_amount: …
```
> Refactor ParaSwap Price Estimator

- crates/shared/src/price_estimation/zeroex.rs
- crates/shared/src/request_sharing.rs
- crates/shared/src/trade_finding.rs
- crates/shared/src/trade_finding/zeroex.rs
- crates/shared/src/zeroex_api.rs
- crates/solver/src/solver/zeroex_solver.rs
This PR adds request sharing internally to the 0x `TradeFinding` implementation.
While enabling trade simulation and verification, I noticed it would be beneficial for the "fast" and "optimal" and native price estimators to share requests during quoting. For this to happen, we now have two layers of request sharing:
- First, we share requests internally to the `TradeFinding` implementations. This allows requests to be shared regardless of whether or not we will simulate the trade. For example, when the FE starts, it issues parallel "fast" and "optimal" requests. For `TradeFinding` implementations, they can share all (0x - `get_swap`) or some (1Inch - `get_quote` - and ParaSwap - `get_price`) of the API requests they are making for computing the quote and/or trades.
- Second, we share …
> Add Request Sharing to 0x Trade Finder

- crates/shared/src/paraswap_api.rs
- crates/shared/src/trade_finding/paraswap.rs
- crates/shared/src/trade_finding/zeroex.rs
- crates/solver/src/solver/paraswap_solver.rs
This PR implements inner request sharing for the ParaSwap trade finder.
Specifically, computing a trade with the ParaSwap API is a two step process:
- First query the `price` API endpoint to get a priceroute
- Commit to the price route by building transaction data with the `transaction` API endpoint
For price estimation, a "fast" estimate would just optimistically use the quoted result from the `price` API call, while the "optimal" one would additionally build a transaction and simulate it to make sure its valid.
Since the FE typically makes simultaneous "fast" and "optimal" requests for a given price quote, it makes to share the `price` API request between the two estimators. For this, we add a `RequestSharing` to the ParaSwap `TradeFinding` implementation so that it can share its inner …
> Implement Inner Request Sharing for ParaSwap Trade Finder

- crates/driver/openapi.yml
Documents the other methods outlined in https://github.com/cowprotocol/services/issues/230 .
Compared to Nic's examples I have removed some duplicate parameters. For example in /execute the response does not echo the auction id back. It also doesn't echo the objective value back. I think this isn't needed. Or is this supposed to indicate the objective value has changed?
The signatures are left as TODO for now. We will first integrate this with our own driver and we only need the signatures once third parties fully run their solvers.
CI
> Document solver api

- crates/autopilot/src/database/onchain_order_events.rs
- crates/database/src/orders.rs
For the old order placement process via API, we wanna populate the error "DuplicatedOrder" to the API and throw it as an error.
But for the orders that are indexed via the onchain_order parsing, we don't wanna receive an error, as it's expected that with each reorg, we would try to insert the orders again.
> Don't error on insert_orders conflicts for the onchain_placed_orders

- crates/autopilot/src/database/auction.rs
- crates/database/src/ethflow_orders.rs
- crates/database/src/orders.rs
- crates/model/src/order.rs
- crates/orderbook/src/database/orders.rs
Adds a new flag `is_ethflow_order`. This flag is required, as we need to do some special operations for ethflow orders, e.g. add a special pre_interaction to wrap eth.
Please review together with the follow-up: [PR](https://github.com/cowprotocol/services/pull/581)
Note: There is an alternative way to implement it:
- storing the ethflow_address in the settlement_encoder and then identifying ethflow orders as orders that use this ethflow_address as owner. However, I found this more cumbersome for 1 main reason: This would mean we need to propagate the eth_flow address to all places where we need to check whether an order is an ethflow order. Just alone for the settlement encoder, this requires storing the ethflow_address in the SettlementEncoder + Settlement structs. Since they are …
> Add the flag is_ethflow_order

- crates/driver/src/main.rs
- crates/solver/src/driver_logger.rs
- crates/solver/src/main.rs
- crates/solver/src/metrics.rs
- crates/solver/src/settlement_ranker.rs
Our solver metrics usually have labels for the solver name and the outcome of the thing being measured (like simulation failure/success). By default these metrics do not exist until they receive their first value because the prometheus library cannot know the label values in advance.
This is problematic for our alerting setup where we want to write rules that mention these labels. These alerts would enter the "no data" state until the metric really exists. Semantically "no data" is equivalent to a 0 value in these cases but we don't want to assume this in the alert itself because then we might later accidentally rename a metric or label causing the alert to stop working even though the alert would report itself as "ok". By doing the 0 initialization we will get warned on rename.
There are …
> Initialize solver metrics

- crates/shared/src/current_block.rs
- crates/shared/src/event_handling.rs
Updates `MAX_REORG_BLOCK_COUNT` to `64` since in POS blocks are finalized after 2 epochs of 32 blocks.
While at it, removed function `async fn current_block_number(&self) -> Result<u64>;` since it's no longer used anywhere.
> Update MAX_REORG_BLOCK_COUNT to 64

- Cargo.lock
- Cargo.toml
- crates/alerter/Cargo.toml
- crates/autopilot/Cargo.toml
- crates/contracts/Cargo.toml
- crates/contracts/src/bin/vendor.rs
- crates/database/Cargo.toml
- crates/driver/Cargo.toml
- crates/e2e/Cargo.toml
- crates/global-metrics/Cargo.toml
- crates/model/Cargo.toml
- crates/model/src/lib.rs
- crates/model/src/order.rs
- crates/number-conversions/Cargo.toml
- crates/orderbook/Cargo.toml
- crates/shared/Cargo.toml
- crates/shared/src/gas_price_estimation.rs
- crates/shared/src/zeroex_api.rs
- crates/solver/Cargo.toml
- crates/testlib/Cargo.toml
This PR refactors our crates to use [workspace dependencies](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table) which was introduced in Rust 1.64. Specifically, this is a new feature that allows you to specify dependencies at a workspace level, and have crates [inherit them](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table). This allows dependency versions and common features to be specified at the workspace level and avoid duplication.
There are some non-trivial changes regarding specified crates and features. More details 👇.
CI - no real changes, just Cargo dependency refactoring.
> Update to Cargo Workspace Dependencies

- crates/autopilot/src/database/auction.rs
- crates/database/src/ethflow_orders.rs
- crates/database/src/orders.rs
- crates/model/src/order.rs
- crates/orderbook/src/database/orders.rs
Reverts cowprotocol/services#580
We will try to remove the is_ethflow_flag and instead store a pre_interaction for ethflow orders that identifies them uniquely.
See discussions:  https://github.com/cowprotocol/services/pull/581#issuecomment-1261852674
> Revert "Add the flag is_ethflow_order"

- crates/shared/src/oneinch_api.rs
- crates/solver/src/liquidity/slippage.rs
- crates/solver/src/solver/oneinch_solver.rs
This change is motivated by #578, where we want absolute caps for other internal solvers.
Specifically, this PR introduces a `SlippageCalculator` component that is responsible for computing slippage amounts for input tokens. It contains shared logic for computing an approximate slippage percentage that capped by a native token value.
Additionally, this PR re-writes existing slippage computations in function of this new component, making sure that the previous slippage related tests continue to function as before.
Note that we also start rounding the percentages for the 1Inch API. This is because the API only accepts up to a certain precision. Experimentally, it appears that it accepts up to 4 digits after the `.`. However, in this PR truncate it to the nearest basis point (so it continues …
> Refactor Slippage Computation

- Cargo.lock
- crates/solver/Cargo.toml
- crates/solver/src/liquidity.rs
- crates/solver/src/liquidity/balancer_v2.rs
- crates/solver/src/liquidity/slippage.rs
- crates/solver/src/liquidity/uniswap_v2.rs
- crates/solver/src/liquidity/uniswap_v3.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/solver/balancer_sor_solver.rs
- crates/solver/src/solver/baseline_solver.rs
- crates/solver/src/solver/http_solver.rs
- crates/solver/src/solver/http_solver/settlement.rs
- crates/solver/src/solver/naive_solver.rs
- crates/solver/src/solver/naive_solver/multi_order_solver.rs
In preparation for #578, this PR changes all of our `liquidity`-based solvers (Baseline, Naive, Quasimodo) to use the new slippage calculation component for computing slippage.
This change:
- Makes applying slippage no longer part of the `Interaction` implementation. This allows different solvers to be configured with different slippage parameters.
- Introduces `SlippageContext` - a per-auction context for computing slippage amounts (since they are dependent on token prices, i.e. the auctions `ExternalPrices` value.
In a follow up PR I will:
- Add the slippage calculator to the remaining DEX aggregator solvers
- Add configuration command line options to control the maximum relative and absolute slippage for the solvers.
Adjusted unit tests to account for the fact that the …
> Use Slippage Calculator for Internal Solvers

- crates/solver/src/liquidity/slippage.rs
- crates/solver/src/solver/balancer_sor_solver.rs
- crates/solver/src/solver/baseline_solver.rs
- crates/solver/src/solver/http_solver.rs
- crates/solver/src/solver/naive_solver.rs
- crates/solver/src/solver/naive_solver/multi_order_solver.rs
- crates/solver/src/solver/oneinch_solver.rs
- crates/solver/src/solver/paraswap_solver.rs
- crates/solver/src/solver/zeroex_solver.rs
This PR adds the `SlippageCalculator` component to each DEX aggregator solver. This is in preparation for #578 to allow configuring absolute slippage limits for all solvers.
Additionally, I refactored `SlippageContext` (i.e. the per-`Auction` context for computing slippage with absolute slippage limits) creation to make its use a bit more ergonomic.
Existing tests continue to pass.
> Use Slippage Calculator for DEX Ag Solvers

- crates/driver/src/arguments.rs
- crates/driver/src/main.rs
- crates/shared/src/arguments.rs
- crates/shared/src/bad_token/token_owner_finder.rs
- crates/shared/src/http_client.rs
- crates/solver/src/arguments.rs
- crates/solver/src/liquidity/slippage.rs
- crates/solver/src/main.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/balancer_sor_solver.rs
- crates/solver/src/solver/baseline_solver.rs
- crates/solver/src/solver/http_solver.rs
- crates/solver/src/solver/naive_solver.rs
- crates/solver/src/solver/oneinch_solver.rs
- crates/solver/src/solver/paraswap_solver.rs
- crates/solver/src/solver/zeroex_solver.rs
Fixes #578 
This PR adds command line configuration options for configuring relative and absolute slippage for all solvers. With this change, we can have an absolute cap on the negative slippage for all internal solvers can incur in a settlement, limiting potential solver losses.
Note that, in order to make slippage configuration more succinct, I modified how slippage configuration works. There are now only two flags `--relative-slippage-bps` and `--absolute-slippage-in-native-token`. These flags can specify values as:
```
${global_value}(,${solver_kind}=${solver_value})*
```
This allows us to specify a global value that applies to all solvers (with `~` to represent "default" - so 10 BPS and no absolute cap) as well as specific solver override values. This means that our current slippage …
> Configure Relative and Absolute Slippage for all Solvers

- crates/shared/src/oneinch_api.rs
- crates/shared/src/zeroex_api.rs
- crates/solver/src/solver/zeroex_solver.rs
In investigating the new absolute slippage logic, I found that there are cases (for *very* large orders) where we were submitting settlements with 0 slippage tolerance.
This is because, in a couple of places, we use a **truncating** conversion from slippage to basis points. This means that if the relative adjusted slippage (capped by the absolute slippage value) is less than a basis point, we were 
This PR does two things:
- Changes the 1Inch `Slippage` to encode more precision (I determined experimentally that 4 decimal digits of precision is the maximum that accepted by 1Inch - see #589 for original discussion of how the 1Inch API does not accept arbitrary precision in its slippage tolerance configuration)
- Changes the 0x solver to use the full precision slippage factor, instead of …
> Increase Slippage Precision

- Cargo.lock
- crates/shared/src/arguments.rs
- crates/shared/src/bad_token/token_owner_finder.rs
- crates/shared/src/http_client.rs
- crates/solver/src/liquidity/slippage.rs
When upgrading to `clap` version 4, the new auto-`ArgGroup` feature caused some issues with how we do command line arguments.
Specifically, `clap`'s `derive(Parser)` was creating `ArgGroups` automatically for every `Arguments` type. The name of the group was the struct name, meaning that when we flattened multiple `Arguments` together, the group names would collide. The work-around we used was to rename the structs (I also added a type alias to keep the work-around local to the individual argument types).
Now, `clap` added a `group(skip)` that we can use for our "flattened" `Arguments` making the work-around no longer needed.
Make sure the executables run:
```
% cargo run -p alerter -- --help
...
% cargo run -p autopilot -- --help
...
% cargo run -p driver -- --help
...
% cargo run -p …
```
> Remove Clap ArgGroup Workaround

- crates/shared/src/order_validation.rs
We have been made aware of a fake UI that sets a malicious address as recipient and therefore steals users proceeds when swapping.
This PR allows for such an address to be banned.
Added unit tests
> Don't allow banned users to be set as receiver

- crates/shared/src/event_handling.rs
This PR changes logic around the final status of the update.
Now, in case of partial update `Err` is returned instead of `Ok` as an indicator that the `EventHandler` storage is not updated to the newest block state, which would enable implementing retry mechanism outside of `EventHandler` scope as mentioned in https://github.com/cowprotocol/services/pull/590#issuecomment-1262283356
Node propagation issue (causing the update to be skipped in some occasions) is very complex to solve in the function `event_block_range` therefore leaving it as is.
The consequence of this change is a lot more maintenance errors to be reported to metric system (I don't see any other major impact)
> Change EventHandler logic around partial and skipped updates

- crates/database/src/solver_competition.rs
- crates/e2e/tests/e2e/services.rs
- crates/solver/src/driver.rs
- crates/solver/src/main.rs
- crates/solver/src/orderbook.rs
The advantage of this is that we still have the competition info in cases where we don't observe a transaction hash (for example because driver is restarted or node doesn't see tx in time).
We originally did it this way but stopped when we had the auto incrementing competition id. Now that we have a proper auction id there is no reason to not go back to it.
CI
> Store solver competition info in more cases

- crates/autopilot/src/arguments.rs
- crates/autopilot/src/lib.rs
- crates/orderbook/src/arguments.rs
- crates/orderbook/src/main.rs
- crates/shared/src/arguments.rs
- crates/shared/src/http_client.rs
- crates/shared/src/price_estimation.rs
- crates/shared/src/price_estimation/factory.rs
- crates/shared/src/price_estimation/http.rs
- crates/shared/src/price_estimation/native.rs
This PR moves the price estimator creation logic into a new `factory` module, and moves shared price estimation arguments into `price_estimation::Arguments` structure.
This is mostly a refactor, the logic should have remained the same (modulo moving from closures to a struct, and passing `PriceEstimatorType` around instead of strings).
Rust compiler. Also run the autopilot and orderbook with all the supported price estimators and see that the startup works.
> Refactor Price Estimation Initialization

- crates/autopilot/src/solvable_orders.rs
- crates/driver/src/auction_converter.rs
- crates/model/src/auction.rs
- crates/model/src/order.rs
- crates/shared/src/http_solver/model.rs
- crates/shared/src/price_estimation/http.rs
- crates/solver/src/driver.rs
- crates/solver/src/liquidity.rs
- crates/solver/src/liquidity/order_converter.rs
- crates/solver/src/liquidity/zeroex.rs
- crates/solver/src/solver/http_solver.rs
part of https://github.com/cowprotocol/services/issues/606
This would have been nicer with https://github.com/cowprotocol/services/pull/529 but I decided to do it this way first so we get this out quicker. I plan on doing 529 later at which point the rewards in the auction can be passed directly in the order vector instead of being an separate map.
CI
> Set solver rewards in auction and http solver model

- crates/autopilot/src/database/auction.rs
- crates/database/src/orders.rs
- crates/model/src/interaction.rs
- crates/model/src/lib.rs
- crates/model/src/order.rs
- crates/orderbook/src/database/orders.rs
- crates/orderbook/src/orderbook.rs
- crates/shared/src/db_order_conversions.rs
- crates/solver/src/solver/http_solver/settlement.rs
This PR provides the dp operations for the pre-interactions: inserting and reading of the interactions + reading the interactions for all orders.
Please note that reading the array of pre_interactions in xsql in a type-save way is not easy. I tried to find a better method for quite some time, but I was not successful. If you know a better method, let me know.
> Pre_interactions: db operations  

- Cargo.lock
- Cargo.toml
Bump ethcontract version to v0.22.0 to include the latest fix https://github.com/gnosis/ethcontract-rs/pull/842
> Bump ethcontract-rs version to v0.22.0

- crates/solver/src/driver.rs
Currently the values we report in the solution competition endpoint doesn't end up. E.g.: 0xf51ff72d36a8207a73c7f0b44885ad28e54e2f202c784bdeed0a909a7428ee46
```
"objective": {
"total": 7150641875698944,
"surplus": 8271014084027250,
"fees": 12404678571674150,
"cost": 15526027201486478,
"gas": 828962
}
```
`surplus + fees - cost != total`
This is because we record `unscaled_subsidized_fee` but use `scaled_unsubsidized_fee` when evaluating the objective ([code](https://github.com/cowprotocol/services/blob/2cbeac93ea82cf5b4bdba0459e8a37b0c099f1cf/crates/solver/src/driver/solver_settlements.rs#L44)).
I'm not sure if this was originally intended, but if not I'm changing it to make the values match (it has caused confusion for solvers checking the values).
> Align fee with objective value computation in solution competition reporting

- crates/shared/src/sources/uniswap_v3/graph_api.rs
Values received from UniswapV3 subgraph need to be treated as decimals.
Pushing this as a separate PR since it needs Marco ASAP to compare the driver liquidity with lpbook liquidity.
> Treat UniV3 subgraph values as decimals instead of hex

- crates/solver/src/settlement_submission/submitter.rs
This PR removes noisy temporary logs that are no longer needed, especially after @MartinquaXD implemented the submitter prefix for each log printed in `settlement_submission`.
> Remove old temporary logs

- crates/database/src/onchain_broadcasted_orders.rs
- crates/database/src/orders.rs
- database/sql/V032__create_index_order_owner.sql
- database/sql/V034__create_index_order_owner.sql
Since my previous [PR](https://github.com/cowprotocol/services/pull/583/files), the query get_user_order is no longer performant. Since the index `user_order_creation_timestamp` is a combination of user and creation_timestamp, my left outer join + additional where condition lowered the performance of the query significantly.
I see two ways to fix it:
- serve ethflow-orders and normal orders via different API requests and combine them in the front-end
- have non-optimized queries in the backend, hoping that they are still fast enough
(kudos to @vkgnosis who foresaw the challenge already 3 months ago during a design discussion. Unfortunately, I forgot about it)
This PR implements the second alternative:
I think if we have an index on the 'owner' instead the index on the combination of owner …
> Ethflow orders in get_user_order()

- crates/shared/src/sources/uniswap_v3/graph_api.rs
- crates/shared/src/subgraph.rs
By testing the driver provided liquidity for UniswapV3, @marcovc noticed that for some pools our ticks data was populated only partially. The reason was because the old `POOLS_WITH_TICKS_BY_IDS_QUERY` query was not paginated for ticks which can be really long.
This required me to completely redesign the queries to support the pagination for both pools and ticks and also have different queries for each of them.
Tested with unit tests.
> Redesign the ticks fetch

- crates/model/src/order.rs
This fixes the shadow solver not working because prod endpoint doesn't have the field yet.
CI
> Don't require `interactions` field

- .github/workflows/deploy.yaml
Might fix master deployment action error because rinkeby pods no longer exist.
CI after merging
> Remove rinkeby autodeploy

- crates/solver/src/driver.rs
Previously we did not store 0 and assumed that orders without a row had 0 reward. Now we make the 0 explicit to distinguish it from some other reason that no reward was stored.
CI, simple enough to not warrant specific test
> Store risk adjusted reward in DB even if it is 0

- crates/solver/src/driver.rs
in case something goes wrong with storing them in the database.
Note that the line below this `self.store_solver_competition` can fail. In that case we wouldn't store the rewards in the database. We could completely abort the settlement process but then we lose a perfectly good settlement. With these logs we have an alternative way of retrieving them. The downside is that we have to notice this either through the error log that is emitted when the storing fails or when the reward script runs and can't find the competition info for this settlement.
CI
> Log rewards of winning solution

- crates/autopilot/src/lib.rs
- crates/autopilot/src/solvable_orders.rs
- crates/e2e/tests/e2e/services.rs
The ethflow contract always enforces that every ethflow order has sufficient balance. Hence, we don't need to check it with the autopilot. 
Note that it's necessary to bypass the check, as otherwise, it might happen that the WETH balance is not sufficient. This is due to the fact, that sometimes first the eth needs to be wrapped as WETH.
Alternative implementation:
We could have also checked that there is sufficient balance, after executing the pre_interactions of an order. This would have been nice since it is more generic. But this would cost us even more time during auction cutting and would put more load on our nodes. Hence, I decided against this implementation.
> Ethflow: No balance check for ethflow orders

- crates/autopilot/src/lib.rs
- crates/driver/src/arguments.rs
- crates/driver/src/main.rs
- crates/orderbook/src/main.rs
- crates/shared/src/arguments.rs
- crates/shared/src/price_estimation/http.rs
- crates/shared/src/sources/uniswap_v3/pool_fetching.rs
- crates/solver/src/main.rs
This PR makes UniswapV3 pool fetcher reads `MAX_POOLS_TO_INITIALIZE` from configuration.
We might need this to lower the number if performance is bad.
> Add argument for MAX_POOLS_TO_INITIALIZE

- crates/shared/src/sources/uniswap_v3/pool_fetching.rs
This PR sets more realistic value for average gas used for UniswapV3 swap. Initially it was set to 300k since we had no idea what to put there.
We considered calculating this programmatically but concluded that value received is not worth the implementation effort.
> Set more realistic value for mean gas used for UniswapV3 swap

- crates/solver/src/settlement_submission/submitter.rs
- crates/solver/src/settlement_submission/submitter/public_mempool_api.rs
Now includes address, nonce and final tx hash in more cases.
This is useful when debugging a  settlement transaction hash that we didn't record in the db.
CI, observe log later
> Improve solution submission log

- docker-compose.yaml
- docker/hardhat/Dockerfile
- docker/hardhat/hardhat.config.js
Added a `docker-compose.yaml` file for easily setting up a local environment to run manual or e2e tests. This should simplify the setup for new and existing users. I'd like to see the team use this to learn if it works for everyone and if others find it convenient as well. This allows you to run the following:
```sh
docker-compose up
docker-compose up -d
```
This creates a postgres database listening on `localhost:5432`, runs the migrations on the database, starts a local [adminer](https://www.adminer.org/) instance at `localhost:7402` which allows you to browse the database (password: 123), and starts a local hardhat node at `localhost:8545`.
If everyone agrees, we can update our `README.md` file to instruct users to simply run `docker-compose` instead of doing laborious manual …
> Added docker-compose file

- crates/driver/src/auction_converter.rs
- crates/shared/src/baseline_solver.rs
- crates/shared/src/http_solver/model.rs
- crates/shared/src/price_estimation/baseline.rs
- crates/shared/src/price_estimation/http.rs
- crates/shared/src/sources/swapr/reader.rs
- crates/shared/src/sources/uniswap_v2/pool_fetching.rs
- crates/shared/src/sources/uniswap_v3/pool_fetching.rs
- crates/solver/src/liquidity.rs
- crates/solver/src/liquidity/balancer_v2.rs
- crates/solver/src/liquidity/uniswap_v2.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/solver/baseline_solver.rs
- crates/solver/src/solver/http_solver.rs
- crates/solver/src/solver/http_solver/settlement.rs
- crates/solver/src/solver/naive_solver.rs
- crates/solver/src/solver/naive_solver/multi_order_solver.rs
Fixes #494  partially.
Added pool address to each amm sent to solver.
Liquidity fetch block number, although it exists, is not guaranteed to be correct at the moment, and is a bit trickier to fix, so will leave it as a separate PR and work on that later.
Note that most of the code changes are fixes of dependent unit tests.
Unit tests passing.
> Add contract pool address to AMMs

- crates/driver/src/driver.rs
- crates/solver/src/driver_logger.rs
- crates/solver/src/settlement_ranker.rs
- crates/solver/src/settlement_rater.rs
- crates/solver/src/solver.rs
Follow up PR for https://github.com/cowprotocol/services/pull/661
Defines struct `TransactionWithMessage` with data to be sent to solvers in case of simulation failure. 
Transaction input data + block number represents the bare minimum needed for simulation reconstruction.
~All other data is more or less static or irrelevant (`from`, `to`, `gas`, `gas_price`) therefore being skipped.~
Edit: added `from` and `to`.
> Add params for solver callback

- crates/database/src/ethflow_orders.rs
Related to: https://github.com/cowprotocol/services/issues/626
EThflow orders should only be refunded if they were placed reasonably. This PR allows querying for the reasonably placed ethflow orders by querying for all ethflow orders with a certain min_validity_duration, and min_slippage.
unit tests only.
I provided a performance test, as the query has several joins and calculations in the query. But the performance is reasonable. 
Thanks @e00E for suggesting this direct approach. I had doubts about the query performance, but I think it's good enough and hence this is the right way to go.
> [Refunder] DB operations for refundable orders considering min validity duration, min slippage

- crates/database/src/ethflow_orders.rs
One of the PRs planned in here: https://github.com/cowprotocol/services/issues/626
The refunder service needs to overwrite the "is_refunded" status and this PR allows him to do so.
unit test
> [Refunder] Allow to mark orders as refunded

- crates/database/src/lib.rs
During the last weeks, we forgot to update this constant. It's being used for tests and metrics.
> [Easy] Inserting missing tables into ALL_TABLES constants

- crates/autopilot/src/database/onchain_order_events.rs
- crates/database/src/orders.rs
During normal order creations, we are copying the quote of the order from the quotes table to the order_quotes table. 
This Pr implements the same functionality for onchain-placed orders.
Unit test
> Storing the order_quotes for onchain_orders

- crates/e2e/tests/e2e/services.rs
- crates/orderbook/src/api.rs
- crates/orderbook/src/api/post_order.rs
- crates/orderbook/src/api/post_quote.rs
- crates/orderbook/src/arguments.rs
- crates/orderbook/src/main.rs
- crates/shared/src/order_quoting.rs
- crates/shared/src/order_validation.rs
- crates/solver/src/driver.rs
Progress on #643.
Added the ability to create limit orders for the API so that the frontend can start implementing their UI against it. I considered a few different alternatives, such as checking the price estimate before actually generating the quote, but ultimately the best way is to simply check that the fees are zero. Added some tests for that.
Also, there is now a new CLI argument for optionally enabling limit orders to be created. I propose to keep this flag disabled in prod but enable it on staging.
Automated tests.
Limit orders can be placed now. These are the same as liquidity orders (zero fees), but the owner doesn't have to be whitelisted.
> Allow limit order placement

- Cargo.lock
- crates/refunder/Cargo.toml
- crates/refunder/LICENSE-APACHE
- crates/refunder/LICENSE-MIT
- crates/refunder/src/arguments.rs
- crates/refunder/src/lib.rs
- crates/refunder/src/main.rs
- crates/refunder/src/refund_service.rs
Part of: https://github.com/cowprotocol/services/issues/626
After longer thoughts, we decided to go for a separate crate, see discussion in issue. This was also Nick's suggestion.
This PR provides an empty crate with a start of a basic refunder activity:
- Getting the refundable orderUids. 
In the following PRs, I will try to create the tx that refunds these orderUids.
None
> [Refunder] creating basic crate

- crates/shared/src/bad_token/token_owner_finder.rs
Since we configure everything using env vars in practice, we also need to allow for the Ethplorer API Key to be parsed via env var.
export ETHPLORER_API_KEY=
And then observe that the key is set when launching both the orderbook as well as the autopilot.
> [Trivial] Allow Ethplorer API Key to be passed via env variable

- crates/solver/src/liquidity/slippage.rs
- crates/solver/src/solver/baseline_solver.rs
- crates/solver/src/solver/http_solver/settlement.rs
- crates/solver/src/solver/naive_solver/multi_order_solver.rs
In #589 et. al., we introduced a new mechanism for computing slippage values. Specifically, we now have a hybrid relative/absolute slippage approach, where we apply a relative slippage capped at a maximum absolute value denominated in the network's native token.
This works well for DEX aggregators since the slippage calculation relies on external prices, and DEX aggregators **always** apply slippage to a token amount for a traded token (which are guaranteed to have external prices).
However, this does not work well for solvers that use the "liquidity" abstraction. Specifically, we fetch liquidity for all traded tokens **AND** a set of base tokens. While the traded tokens all have external prices, base tokens are not guaranteed to have external prices. This means that it is possible to try …
> Improve Handling of Slippage for AMMs

- crates/autopilot/src/lib.rs
- crates/driver/src/arguments.rs
- crates/driver/src/main.rs
- crates/orderbook/src/main.rs
- crates/shared/src/arguments.rs
- crates/shared/src/price_estimation.rs
- crates/shared/src/price_estimation/factory.rs
- crates/shared/src/tenderly_api.rs
- crates/shared/src/trade_finding.rs
- crates/solver/src/arguments.rs
- crates/solver/src/main.rs
Follow up to #657 
This PR adds the new command line options required for creating a `TradeVerifier` instance. The trade verifier gets used with the supported price estimators (introduced in #657).
With this change, it is now possible to configure DEX aggregator price estimators to simulate the estimates that they receive from their respective APIs, in order to have:
- A more accurate gas estimate for the trade
- An exact input and output amount for the trade (thus, helping catch issues where the advertised exchange rate does not match what actually gets executed on-chain - either because of a DEX aggregator bug, or weird on-chain interactions with the tokens and AMMs being used for the particular trade).
Additionally, while testing, I found some small improvements to the simulation setup …
> Trade Simulation Configuration

- crates/model/src/order.rs
Reverts cowprotocol/services#680
This was done temporarily to deal with the fact that the shadow solver was expecting this field but that it wasn't included by the production `orderbook` service.
Now that we are releasing, we can remove this (as a missing `class` field can be considered an error).
> Revert "Make new `class` field backwards compatible with shadow solver"

- crates/shared/src/bad_token/token_owner_finder.rs
This PR just makes the newly introduced `--whitelisted-owners` default to the empty list so that it isn't required for running the `orderbook` binaries.
The following starts:
```
cargo run -p orderbook
```
> Specify default whitelisted owners

- crates/autopilot/src/database/auction.rs
- crates/autopilot/src/database/onchain_order_events.rs
- crates/autopilot/src/lib.rs
- crates/autopilot/src/solvable_orders.rs
- crates/e2e/tests/e2e/services.rs
- crates/model/src/order.rs
- crates/orderbook/src/api/get_auction.rs
- crates/orderbook/src/database/orders.rs
- crates/orderbook/src/database/quotes.rs
- crates/orderbook/src/main.rs
- crates/shared/src/order_quoting.rs
- crates/shared/src/order_validation.rs
Progress on #643.
Quotes limit orders whenever an auction is cut. The next PR will start caching the calculated fees to reduce the frequency of quoting, since quoting isn't cheap.
Note that the fee does not get stored anywhere in out database yet.
Refactored some interfaces to make things more explicit and to try to illustrate business logic a tiny bit more clearly.
Currently the change is not covered by tests. I will add an E2E test once it makes sense.
Adds a new field to the `Order` type. This is a backwards-compatible change.
> Limit order fees

- crates/shared/src/trade_finding/paraswap.rs
This PR just fixes the ParaSwap slippage configuration for trade simulations. It was mistakenly set to 100% 🤦.
CI
> Fix ParaSwap Trade Simulation Slippage

- crates/shared/src/order_quoting.rs
This PR makes a small change in the computed `price_estimation::Query` for a given `api/v1/quote` request.
In experimenting with trade simulations, I noticed that there are clients that are making price `quote` requests with `from: 0`. This is not a problem in and of itself, but does cause a lot of issues WRT trade simulation. Specifically, many tokens actually disallow transferring to and/or from the 0 address (as its treated as a special address), and it is conceivable that the 0-address has special semantics in existing exchanges (as it does for our exchange's `order.receiver`).
With that in mind, it makes sense for us to have special handling of the 0-address for price quoting. There were 3 different ways I thought of approaching this issue:
1. Have an additional condition in the …
> Improved Handling of Quotes From 0-Address

- crates/shared/src/code_simulation.rs
- crates/shared/src/tenderly_api.rs
It turns out that the Tenderly simulation API uses a slightly different format for specifying state overrides.
This PR adds the necessary conversion between the "standard" Ethereum RPC state override format and the Tenderly one.
New manual test to verify that the code simulation component works with state overrides on Tenderly:
```
% cargo test -p shared -- --ignored --nocapture tenderly_state_override_conversion
Finished test [unoptimized + debuginfo] target(s) in 9.57s
Running unittests src/lib.rs (target/debug/deps/shared-4d8b654460977cb8)
running 1 test
test code_simulation::tests::tenderly_state_override_conversion ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 382 filtered out; finished in 0.97s
```
> Fix Tenderly State Object Serialization

- crates/driver/src/settlement_proposal.rs
- crates/model/src/order.rs
- crates/solver/src/driver/solver_settlements.rs
- crates/solver/src/in_flight_orders.rs
- crates/solver/src/liquidity/order_converter.rs
- crates/solver/src/settlement.rs
- crates/solver/src/settlement/settlement_encoder.rs
- crates/solver/src/solver/http_solver/settlement.rs
Supporting limit orders ([#705](https://github.com/cowprotocol/services/issues/705)) requires a way to add trades to the `SettlementEncoder` in way that bypasses the uniform clearing price requirements. This is needed to account for the `surplus_fee`.
A similar thing was already needed for liquidity trades which had to be traded at exactly the limit price to not get any surplus. Instead of adding yet another field to the `SettlementEncoder` for limit orders I would like to rename `liquiditiy_order_trades` to `custom_price_trades` and reuse it for limit order trades because the underlying requirement is the same (bypass UCP in favor of a custom price).
Additionally I also refactored how you add orders to the `SettlementEncoder`. Instead of exposing multiple different functions …
> Refactor how to add liquidity trades to SettlementEncoder

- crates/autopilot/src/auction_transaction.rs
- crates/autopilot/src/database.rs
- crates/autopilot/src/database/auction_transaction.rs
- crates/autopilot/src/lib.rs
This PR gets this component ready to be used:
- Refactor db calls to go through implementations on Postgres as we usually do to get timing stats
- Add a span to the updater task
- Extend the manual test
- Spawn the updater task in autopilot.
- Slightly refactor how we handle tasks that should never return ending
ran manual test
> Run auction transaction update task

- crates/shared/src/fee_subsidy/cow_token.rs
- crates/shared/src/lib.rs
- crates/solver/src/settlement_post_processing/mod.rs
- crates/solver/src/settlement_rater.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/settlement_submission/submitter.rs
Partially implement #688.
This PR changes the default `web3::Transport` implementation that is used in the services to be the `transport::Buffered` type. This transport implementation receives JSON RPC requests over a channel and automatically batches them based on runtime configuration parameters. The main motivation for using this are two-fold:
- First, this makes coding of "batched" requests easier (you basically just need to `futures::join` concurrent RPC requests)
- Second, it allows for runtime configuration of maximum batch size (where previously it used a hard-coded `const` value of `100`) as well as number of concurrent batches (which we didn't have previously).
Additionally, I removed manual uses of the `transport::Buffered` in the code since the underlying transport is already …
> Use Buffered transport everywhere

- crates/autopilot/src/lib.rs
- crates/driver/src/arguments.rs
- crates/driver/src/main.rs
- crates/orderbook/src/main.rs
- crates/refunder/src/arguments.rs
- crates/refunder/src/lib.rs
- crates/shared/src/arguments.rs
- crates/shared/src/ethrpc.rs
- crates/solver/src/main.rs
Fixes #688.
This PR adds CLI configuration options for controlling request buffering. Specifically, you can now control:
- The maximum batch size. This is used to 
- The maximum concurrency for Ethereum RPC requests.
For example:
- `--ethrpc-max-batch-size 10`: Sets the maximum batch size to 10 RPC requests. Uses the default `--ethrpc-max-concurrent-requests` value of `1`, meaning only ever 1 batch RPC request is sent to the node at any given time
- `--ethrpc-max-batch-size 10 --ethrpc-max-concurrent-requests 0`: Like above but disable concurrent request limiting (that is, if you make 93 simultaneous requests, the buffered transport will send 10 simultaneous batches to the node)
- `--ethrpc-max-batch-size 0 --ethrpc-max-concurrent-requests 5`: Disable batching, but only send up to 5 …
> Configure Ethereum RPC Request Buffering

- crates/autopilot/src/arguments.rs
- crates/driver/src/arguments.rs
- crates/orderbook/src/arguments.rs
- crates/shared/src/arguments.rs
- crates/shared/src/bad_token/token_owner_finder.rs
- crates/shared/src/ethrpc.rs
- crates/shared/src/http_client.rs
- crates/solver/src/arguments.rs
This PR just adds missing `env` attributes on CLI flags.
Just the compiler - no new logic, just new attributes on CLI flags.
> Read All CLI Flags From Environment

- crates/autopilot/src/lib.rs
- crates/autopilot/src/risk_adjusted_rewards.rs
- crates/orderbook/src/main.rs
- crates/shared/src/oneinch_api.rs
- crates/shared/src/price_estimation/factory.rs
- crates/shared/src/price_estimation/oneinch.rs
- crates/shared/src/price_estimation/paraswap.rs
- crates/shared/src/price_estimation/trade_finder.rs
- crates/shared/src/price_estimation/zeroex.rs
- crates/testlib/src/lib.rs
- crates/testlib/src/protocol.rs
In debugging failed trade simulations, I came [across an example](https://dashboard.tenderly.co/gp-v2/staging/simulator/d23e02b3-bd0e-44cd-9d53-e7ff43d20e3b/debugger?trace=0.9.10.0.0) of a failed simulation caused by having the proceeds of a trade interaction go to the trader instead of the settlement contract (which is what is expected for the usual settlement flow).
This is because some trade calldata encodes the receiver of the proceeds directly instead of assuming `msg.sender` (i.e. the address of the caller of the transaction).
This PR changes the `TradeFinder` price estimator to always query `TradeFinding` interfaces with the `from` address set to the settlement contract. Conceptually, this makes sense as we want to estimate the price of a trade as if it were being executed as part …
> Price Estimates From Settlement Contract

- crates/solver/src/liquidity/uniswap_v3.rs
- crates/solver/src/settlement/settlement_encoder.rs
- crates/solver/src/settlement_ranker.rs
- crates/solver/src/solver/http_solver.rs
- crates/solver/src/solver/http_solver/settlement.rs
Add temporary logs to better inspect encoding flow for Quasimodo solutions.
More context [here](https://cowservices.slack.com/archives/C0375NV72SC/p1667386363586569)
This PR should not be part of the next week release, meaning revert PR is expected to be merged until the end of week.
> Add temporary logs for Quasimodo encoding issue

- crates/solver/src/driver.rs
I just noticed that with the introduction of limit orders we should be storing their rewards too.
I'm intentionally doing a full match on the enum so the compiler will complain when we add a new variant.
this change isn't unit tested but it is simple enough
> Store limit order rewards

- crates/autopilot/src/auction_transaction.rs
- crates/autopilot/src/database/auction_transaction.rs
This prevents a race condition where we could update the row in settlements first and then exit because the pod shuts down without updating auction_transaction.
This PR only moves code around so that it happens in a transaction, without changing that code.
Almost no logic change (just moving code into a transaction). Testing the exact race condition is hard because you'd need Postgres to error or shutdown the future at the perfect time.
> Use transaction to  update settlement tx info

- crates/e2e/tests/e2e/services.rs
- crates/model/src/time.rs
- crates/orderbook/src/api/post_order.rs
- crates/orderbook/src/arguments.rs
- crates/orderbook/src/main.rs
- crates/shared/src/order_quoting.rs
- crates/shared/src/order_validation.rs
Fixes #728 
This PR adds a new configuration option for specifying the maximum order validity for limit orders. This allows separate values to be set for market and limit orders.
Additionally, it was done in a way that opens the door to add other validity limits (for example, we should probably add one for `pre-sign` orders as well).
Existing order validation tests continue to pass. Also extended the existing unit test to cover the new code paths.
We can now specify `MAX_LIMIT_ORDER_VALIDITY_PERIOD`. The default of 1 year is what was suggested on Slack.
> Configurable Maximum Limit Order Validity

- crates/model/src/order.rs
- crates/orderbook/openapi.yml
- crates/orderbook/src/database/orders.rs
- crates/orderbook/src/orderbook.rs
This PR adds multiple order cancellation to the orderbook.
The context for this change is that the CoW Swap limit order front end wants to add support for cancelling multiple orders at once.
With the current API (`DELETE /api/v1/orders/${orderUid}`), this has to be done where, for each order, a wallet signature is requested. This means that if you were to cancel 10 orders, you would need to sign 10 MetaMask popups at once. In order to work around this, we introduce a new `OrderCancellations` message that can be signed to indicate intent to cancel multiple orders at once. In the same example as above, the user would only need to sign a single MetaMask popup (including the order UIDs of all 10 orders).
The actual API documentation and end point will be added in a follow up PR, this just …
> Allow Cancelling Multiple Orders At Once

- crates/shared/src/trade_finding/oneinch.rs
Fixes #555
For the 1Inch trade finding implementation we regularly query `/spender` to get the current smart contract address. This seems wasteful because this is not going to change very often. Therefor a bit of caching was introduced.
I decided to hardcode the cache validity to a pretty low 60 seconds because I think it doesn't make sense to manually tweak this parameter very much and 60 seconds is already a big improvement over the status quo.
This change will probably not speed up the quoting process, though because we already run multiple API requests in parallel and I expect `/spender` to be by far the fastest. For that reason I could also understand some opposition to this PR because people might not feel it's worth the added complexity. I have no strong opinion on that and …
> Cache the 1inch spender

- crates/autopilot/src/database/onchain_order_events.rs
- crates/shared/src/order_validation.rs
This PR adjusts the order classification logic.
Specifically, when limit orders were disabled, it was possible to create market orders with a 0-fee (as the 0-fee would cause it to skip the `get_quote_and_check_fee` fee check but disabled limit orders make the order be considered a market order).
@fedgiac and I already applied a hotfix in production, this PR adds the fix to `main` as 
well. This is not urgent (as limit orders are enabled in staging, so it is not possible to create 0-fee market orders ATM).
Additionally, this PR also:
- restores the behaviour of out-of-market orders being flagged as liquidity orders
- only stores quotes at order creation if an existing quote wasn't found. This is to avoid orders that are created with a specific quote ID getting a different one.
Changed the …
> Adjust Market Order Logic When Limit Orders Are Disabled

- crates/database/src/orders.rs
- database/sql/V041__create_index_on_orders_with_owner_and_timestamp.sql
When we deployed this PR: https://github.com/cowprotocol/services/pull/701 to production, it caused severe performance decreases. This PR reverts the PR + improves the performance with another trick.
It re-creates the old index that was deleted [here](https://github.com/cowprotocol/services/pull/610/files#diff-2794b4d292d74cb53a35285b59b1c05669ee45a9298edfe40098c720eb8f8433R2) and thereby optimizes the first search query of the union all. This helps especially, by limiting the requested rows in the first query by (OFFSET * OVER_ALL_LIMIT). Especially for small offsets, the query gets its old performance back.
But let's also discuss in this PR other methods to make the query faster, or whether we should delete old orders. I think with limit orders approaching, the db performance will …
> Get_user_order performance next trial

- crates/solver/src/analytics.rs
- crates/solver/src/driver.rs
- crates/solver/src/driver/solver_settlements.rs
- crates/solver/src/driver_logger.rs
- crates/solver/src/in_flight_orders.rs
- crates/solver/src/settlement.rs
- crates/solver/src/settlement/settlement_encoder.rs
- crates/solver/src/settlement_ranker.rs
- crates/solver/src/solver/http_solver/settlement.rs
- crates/solver/src/solver/naive_solver/multi_order_solver.rs
Throughout the code, we assume `order_trades == user_trades` (in order words, all custom price trades are non-user orders). This is because previously, we only had market and liquidity orders, so the distinction was true.
This PR adds removes `order_trades` and `custom_price_trades` methods in favour of new `trades` (for all trades) and `user_trades` (for user trades) methods, which IMO helps clarify intent as to which trades we care about at the various call-sites.
With this, we fix the issue where limit orders aren't considered as user orders in some places.
One thing I noticed and am not very fond of is the current `Settlement` vs `SettlementEncoder` abstraction. Specifically, I think the way that the current separation is designed contributed to this being an issue in the first place. …
> Consider Limit Orders as User Orders

- crates/driver/src/arguments.rs
- crates/driver/src/auction_converter.rs
- crates/driver/src/main.rs
- crates/e2e/tests/e2e/services.rs
- crates/shared/src/http_solver/model.rs
- crates/shared/src/price_estimation/http.rs
- crates/solver/src/auction_preprocessing.rs
- crates/solver/src/driver.rs
- crates/solver/src/liquidity.rs
- crates/solver/src/liquidity/order_converter.rs
- crates/solver/src/liquidity/zeroex.rs
- crates/solver/src/main.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/solver/http_solver.rs
This PR defines each order maturity at the beginning of each `Auction`. Then forwards this information to all solvers.
This will allow solvers to be smarter about our order maturity logic and avoid creating settlement that will fail the maturity check in the driver.
Makes sense to add this since I expect all solvers to use this to optimize their algorithms.
Updated unit tests.
Changed data format for `solve` endpoint. Solvers should be notified about new `is_mature` field.
> Forward Order Maturity to Solvers

- crates/solver/src/arguments.rs
- crates/solver/src/main.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/single_order_solver.rs
Fixes #753
With the release of the limit order feature we expect that we have to handle a lot more orders. The `SingleOrderSolver` (aptly named) can only solve a single order at a time and every order takes some amount of time. Because the `SingleOrderSolver`s can be quite slow solving an entire `Auction` is already time boxed.
To improve the chances to work on orders that can actually be settled and make the most of our the time we have we want to prioritize orders which are generously priced; meaning that they want to sell a lot and buy a little (denominated in ETH).
Since the auction already gives us prices for all the traded tokens in the order we can simply use those to compute each order's native `sell_amount` and `buy_amount` and prioritize the orders based on their ratio.
Note …
> Prioritize orders in `SingleOrderSolvers`

- crates/model/src/order.rs
- crates/solver/src/liquidity/order_converter.rs
- crates/solver/src/settlement/settlement_encoder.rs
This PR fixes an issue with encoding limit orders with the special `BUY_ETH_ADDRESS`.
Specifically, we don't add a token equivalency for these kinds of orders (because their buy price) which causes a "missing buy token error" when adding the limit order to the settlement encoder.
I changed the PR to unconditionally add token equivalency for all orders. I did this so that the order converter doesn't need to know implementation details about the `SettlementEncoder`, and even if we add an additional price here that isn't needed, it gets cleaned up in the `drop_unnecessary_tokens_and_prices` call so we don't have to pay more gas for it.
Added case in unit test.
> Add Support for Limit Order Buying Eth

- crates/autopilot/src/database.rs
- crates/autopilot/src/database/onchain_order_events.rs
- crates/autopilot/src/database/orders.rs
- crates/autopilot/src/limit_order_quoter.rs
- crates/database/src/orders.rs
- crates/model/src/quote.rs
- crates/shared/src/order_quoting.rs
- crates/shared/src/order_validation.rs
Fixes #770 
This PR makes sure limit orders also set their `full_fee_amount`. Specifically, CoW Protocol orders have 2 different fee fields:
- `fee_amount`: This is the actual fee amount that we charge the user. In order to make trading more attractive on CoW Swap, we have a few "knobs" for configuring subsidies on orders used to compute this amount. For limit orders, this is the analogous to `surplus_fee` which is the actual fee we change the user (but instead of it being a pro-rated fee, it is taken from the order's surplus).
- `full_fee_amount`: This is the actual expected "cost" of executing the order. We store this for a couple of reasons:
1. Primary reason is that we want to use this value in the objective function and **not** the actual fee amount. The reason for this is we want …
> Include Full Fee Amount For Limit Orders

- crates/solver/src/settlement.rs
- crates/solver/src/settlement/settlement_encoder.rs
This PR changes the logic of `drop_unnecessary_tokens_and_prices` to not filter out uniform clearing prices for any user orders.
This is because, as part of our design, we wanted to include the uniform clearing price in the settlement clearing price vector (even if it doesn't get used) to on-chain uniform clearing price "documentation".
Added unit test that verifies this.
> Include Limit Order Buy Token Uniform Clearing Price

- .github/workflows/deploy.yaml
- docker/Dockerfile.binary
Refunder builds need to also be copied into the docker image. 
Also, we want to have automatic re-deployments of the refunder
> Configuring refunder builds and auto-redeployments

- crates/shared/src/exit_process_on_panic.rs
While debugging something I added this test to make sure it still works in tokio tasks. Useful to have in the repo.
ran the new test
> Add panic-hook test for tokio

- crates/e2e/tests/e2e/eth_flow.rs
- crates/e2e/tests/e2e/local_node.rs
- crates/e2e/tests/e2e/main.rs
- crates/e2e/tests/e2e/refunder.rs
- crates/e2e/tests/e2e/services.rs
- crates/refunder/src/refund_service.rs
Refactors a few shared components in preparation fort the eth flow e2e test.
Some minor logic changes are consequence of the refactor but I consider them inconsequential:
- Instead of using `buy_amount = 1`, the order is modified to include a slippage tolerance of 99.99%. This should make it clear that extra slippage must be included for the refunder to work (I stumbled on this for longer than I should have).
- The receiver becomes an arbitrary address.
- The signature is now empty, as it's ignored by the contract anyway.
CI: e2e test still works.
> Refactor shared components in refunder e2e test

- crates/shared/src/order_validation.rs
- crates/shared/src/signature_validator.rs
I observed alerts:
```
request{id="..."}: shared::api: internal server error error=order_validation
Caused by:
contract call reverted with message: Some("!match")
```
This was caused because the `validate_signature_and_get_additional_gas` check would call `is_valid_signature` which would revert. We weren't classifying these contract reverts and they were bubbling up as "other" errors and turning into 500 errors (when really they should be 400 bad request errors).
Just the compiler. Logic didn't really change, we should add an E2E test that trades an ERC-1271 order.
> Handle ERC-1271 Signature Verification Reverts

- crates/shared/src/http_solver/model.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/solver/http_solver.rs
- crates/solver/src/solver/http_solver/settlement.rs
Preparation PR for https://github.com/cowprotocol/services/pull/791
The purpose of this PR is to make the https://github.com/cowprotocol/services/pull/791 breaking change less _breaking_, meaning we would give solvers time to change their format for `ExecutionPlan`, and once we make sure all solvers are using the new format, we can merge https://github.com/cowprotocol/services/pull/791.
Updated unit tests.
> Add Possibility To Receive Both Coordinates and Internalization Flag

- crates/e2e/tests/e2e/eth_integration.rs
- crates/e2e/tests/e2e/limit_orders.rs
- crates/e2e/tests/e2e/main.rs
- crates/e2e/tests/e2e/onchain_components.rs
- crates/e2e/tests/e2e/onchain_settlement.rs
- crates/e2e/tests/e2e/order_cancellation.rs
- crates/e2e/tests/e2e/refunder.rs
- crates/e2e/tests/e2e/services.rs
- crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
- crates/e2e/tests/e2e/vault_balances.rs
Implements Nick's suggestion from [here](https://github.com/cowprotocol/services/pull/808#discussion_r1026141436).
With these changes `e2e::services` only contains functions related to setting up the services, all other functions are related to some form of onchain execution and are moved to `e2e::onchain_components` . No logic changes are included.
E2e tests still work. Number of new lines is larger than number of deleted lines (no functions missing, import statements are bigger now).
> Separate e2e helper function: services and onchain components

- crates/autopilot/src/lib.rs
- crates/driver/src/main.rs
- crates/e2e/tests/e2e/services.rs
- crates/orderbook/src/main.rs
- crates/shared/src/maintenance.rs
- crates/solver/src/main.rs
This PR changes the service maintenance component to retry updating to the latest block after some delay instead of waiting until a new block is observed.
This is done for two reasons:
1. In order to reduce alert noise because of maintenance update delays (I made sure to keep track of success and failure so we can setup dashboards and alerts for it).
2. Because we want maintenance to run so we are at the "latest" block always. Without retrying, we stay 12 seconds knowing that there is a new block and we have stale data before trying to update again. So, conceptually, retrying here is not so much of a sin.
Furthermore, in terms of the first point, changing the parameters of the alerts is not really possible. The issue is that the current alert measures how stale our data is (i.e. how far …
> Retry service maintenance

- crates/solver/src/arguments.rs
Related to #820
We recently changed the batch auction model preparation to fetch balances for all market makable tokens. This isn't an issue for our deployments because the list is quite small, however, the list that the driver uses by default has 4900(!) tokens.
This PR is just a really easy change to help the situation by:
- using a much smaller list with 50 tokens
- using the actual list that is being used for market makable tokens
Run locally and see that the new default list is accepted by the driver.
> Change Default Market Makable Token List

- crates/database/src/lib.rs
- crates/database/src/order_execution.rs
- crates/database/src/order_rewards.rs
- crates/database/src/orders.rs
- crates/model/src/order.rs
- crates/model/src/solver_competition.rs
- crates/orderbook/openapi.yml
- crates/orderbook/src/database/orders.rs
- crates/orderbook/src/database/solver_competition.rs
- crates/shared/src/db_order_conversions.rs
- crates/solver/src/driver.rs
- crates/solver/src/settlement.rs
- database/sql/V044__limit_order_execution.sql
Fixes https://github.com/cowprotocol/services/issues/771 .
We store the surplus fee amount as it was used in the auction in the database in the same way we store the order cow reward. We rename the table to indicate that it stores generic per-auction-per-order information.
TODO before merging: Make sure solver rewards script can handle the new table name.
CI, new unit test
> Persist limit order surplus fee

- crates/autopilot/src/solvable_orders.rs
We started getting a few alerts related to:
```
2022-11-17T15:02:08.583Z ERROR auction{id=4083531 run=3196}: solver::driver: error normalizing limit order err=surplus_fee adjustment would underflow sell_amount
```
This PR fixes that alert by removing invalid limit orders from the auction where their computed surplus fee is greater than what they are actually selling (so no amount of surplus can pay the order fee).
Additionally, I changed the `filter_mispriced_limit_orders` computation (I originally was surprised it didn't catch this) to use the discounted sell amount for the market price check. Specifically, we should use the discounted sell amount (as that represents what is actually being traded for the buy token) and added some overflow checking.
Added unit test!
> Filter Order With Insufficient Sell Amount

- crates/shared/src/http_solver/model.rs
- crates/solver/src/solver/http_solver.rs
This test randomly fails because HashSet order is not guaranteed.
CI
> Make test deterministic

- crates/orderbook/src/api/post_order.rs
- crates/orderbook/src/orderbook.rs
This PR makes some small improvements to logging of order creation. Specifically, today, I was trying to debug a failed order creation for @avsavsavs, but wasn't able to find the exact cause (or even match a quote to the equivalent order creation request).
We add two things here:
- We add the actual quote ID that the order gets created with (and not just the optional quote ID that the order was made with - this allows us to find what quote ID actually gets chosen for an order in line with the UID - right now we have a multi-step process to try and find the "found quote" log in the same request)
- We log the order creation parameters on failure, making it easier to see exactly what the order was created with and better understand the error.
The compiler - no real logic changes just piping …
> Improve Order Creation Logging

- crates/shared/src/http_solver/model.rs
While investigating a few cases where we notified solvers about failed simulations I noticed that we [log](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/doc/6eecf430-220f-11ed-bbdc-2f476b18353d/logstash-prod-2022.11.23?id=jQpjo4QBiG37jPBs3VQS) the `call_data` as an array of numbers instead of a hex string. This less condensed and overall less useful so we should log the hex string instead.
Used a temporary `dbg!()` statement to see that the formatting works as intended
> Encode simulation failure call data has hex string

- crates/shared/src/http_solver.rs
- crates/solver/src/driver_logger.rs
If a solution fails to simulate on the latest block but not on the block the auction started at we don't report an error in the usual [place](https://github.com/cowprotocol/services/blob/main/crates/solver/src/driver_logger.rs#L178-L193) because most of the time this was caused by the racy nature of the blockchain. This makes debugging errors that happen only on the latest block much harder.
However, since Dusan introduced the `/notify` endpoint there exists a [log](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/doc/6eecf430-220f-11ed-bbdc-2f476b18353d/logstash-prod-2022.11.22?id=TkccoYQBdK0bxeq9cejm) which reports the simulation failure on the latest block. It's just very hard to find because the log gets printed in a new task which doesn't have the tracing span …
> Improve tracability of logs for simulation failures on the latest block

- crates/autopilot/src/database/onchain_order_events/ethflow_events.rs
- crates/e2e/tests/e2e/eth_flow.rs
- crates/e2e/tests/e2e/eth_integration.rs
- crates/e2e/tests/e2e/main.rs
- crates/e2e/tests/e2e/services.rs
- crates/shared/src/signature_validator.rs
Adds an e2e test for eth-flow orders and corresponding API expectations.
I also extracted what was needed to initialize the driver from another test into its own function. I don't think it contains any specific logic for that test, but it's worth double checking this when reviewing.
New code is a test.
> Add e2e test for eth flow orders

- crates/shared/src/bad_token/token_owner_finder.rs
- crates/shared/src/bad_token/token_owner_finder/solvers/solver_finder.rs
- crates/shared/src/bad_token/trace_call.rs
Sometimes the new token owner finder implementation is quite noisy because it always logs an error when something fails. However, those errors tend to be temporary, not critical and not really actionable (because we are relying on external servers).
To not let the alert channels become too noisy we can simply add a few metrics and alert based on those.
In order to have meaningful metrics we need to have some identifier associated with them (in case we have to query more urls in the future). To not introduce unnecessary complexity I decided to simply use the urls as the identifier.
Manual test running the order book locally and grepping for the new metrics:
```
gp_v2_api_updates{identifier="https://seasolver.dev/token_holders",result="failure"} 0 …
```
> Add metrics for `AutoUpdatingSolverTokenOwnerFinder`

- crates/shared/src/bad_token/token_owner_finder/solvers/solver_finder.rs
While creating a grafana panel for the new metrics I noticed that the metric name is horribly vague so I made it more specific.
simple rename; no test
> Give metrics for token owner updates more specific name

- crates/autopilot/src/arguments.rs
- crates/autopilot/src/lib.rs
- crates/autopilot/src/solvable_orders.rs
- crates/e2e/tests/e2e/services.rs
- crates/refunder/src/arguments.rs
The eth-flow contract is deployed independently for each supported network and should not have a default value. The current default is the testing contract on Görli.
The changes here are as follows:
1. `ethflow_contract` and `enable_ethflow_orders` arguments are merged together. If no contract is specified, the eth flow is disabled. Otherwise it's enabled.
2. `ethflow_contract` is now a required argument to the refunder.
It also fixes a small bug where even if the eth flow is disabled the eth-flow orders were given preferential treatment in `solvable_orders`.
Note that [this MR](https://gitlab.gnosisdev.com/devops/aws/aws-infra-staging/k8s-team-namespaces/gnosis-staging-k8s-gp/-/merge_requests/584) should be applied before merging this one (please also review that if you approve this). …
> Remove default eth-flow contract

- crates/orderbook/src/api/version.rs
In a recent refactoring the `/version` endpoint lost its `/v1` prefix. It's currently `/api/version` instead of `/api/v1/version` like the openapi specification says.
With this PR the openapi specification and the actual routes are back in order again.
Credit to @ennmichael and @poolpitako for noticing.
```
curl --request GET --url http://localhost:8080/api/v1/version
{"branch":"fix-api-version-endpoint","commit":"6db54a76144ccba2e52a32f3510f930b66bba8d0","version":"v2.82.0-19-g6db54a7"}
```
> Route version endpoint at `/v1/version` again

- crates/orderbook/openapi.yml
Just remove Rinkeby from the OpenAPI spec - it isn't a thing anymore.
CI - we validate the OpenAPI spec 🎉.
> Remove Rinkeby From OpenAPI Spec

- README.md
We no longer run the infrastructure for `rinkeby` so we should no longer mention it in our `README.md` to avoid confusion.
> Drop Rinkeby from README.md

- crates/shared/src/gelato_api.rs
- crates/shared/src/lib.rs
Follow up to #599 
I previously experimented with a Gelato relay service submitter in #599. The idea is to allow a separate relay service to execute settlement transactions on behalf of solvers so that they don't have to worry about execution details.
This PR is the first in a stack of 3 for enabling Gelato submission support. I am basically just breaking down the existing #599 into smaller pieces to make them easier to review and "self-contained".
In the following PRs I will:
1. Introduce the Solver trampoline contract and settlement signing.
2. Implement a Gelato submitter using the API introduced in this PR executed over the solver trampoline.
Added a manual test for executing a transaction over the Gelato relay. Requires a 1Balance account with an API key.
```
% cargo test -p shared …
```
> Add Gelato API Module

- crates/driver/src/arguments.rs
- crates/driver/src/main.rs
- crates/shared/src/gelato_api.rs
- crates/solver/src/arguments.rs
- crates/solver/src/main.rs
- crates/solver/src/settlement_submission.rs
- crates/solver/src/settlement_submission/gelato.rs
Succeeds #599 
This PR adds the Gelato settlement submission strategy and is based on #839 and #840. 
With this new strategy, transaction are submitted over the Gelato relay network, so no transaction execution/submission needs to be handled by the driver 🎉.
Note that there is a bit of a code-smell in the `SettlementSubmitter` component. I didn't want to address that in this PR, but I left a clarifying comment to try and explain the issue. Perhaps this is something we can refactor in the near future.
Added a new manual test for submitting a [settlement](https://goerli.etherscan.io/tx/0x9b3d0a61d2862f98651cf7b8e8d7edccc3f7aaa3621dd9a8e26576c9a6cc4e5e):
```
% cargo test -p solver -- gelato::tests::execute_relayed_settlement --ignored --nocapture
Compiling solver v0.1.0 …
```
> Implement Gelato Settlement Submission Strategy

- crates/driver/src/main.rs
- crates/solver/src/main.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/http_solver.rs
- crates/solver/src/solver/http_solver/settlement.rs
These orders do not need a correct uid because it doesn't matter for encoding the settlement for the contract which is why we are currently storing a default 0 uid.
It is still nice to have the correct uid for logging and in the competition info.
Harris talked about this on [slack](https://cowservices.slack.com/archives/C0375NV72SC/p1669893929989719).
adapted test
> Set the correct order uid for foreign liquidity orders

- crates/driver/src/auction_converter.rs
- crates/driver/src/main.rs
- crates/e2e/tests/e2e/limit_orders.rs
- crates/e2e/tests/e2e/onchain_settlement.rs
- crates/e2e/tests/e2e/services.rs
- crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
- crates/e2e/tests/e2e/vault_balances.rs
- crates/solver/src/driver.rs
- crates/solver/src/liquidity/balancer_v2.rs
- crates/solver/src/liquidity/uniswap_v2.rs
- crates/solver/src/liquidity/uniswap_v3.rs
- crates/solver/src/liquidity/zeroex.rs
- crates/solver/src/liquidity_collector.rs
- crates/solver/src/main.rs
Fixes #869 
In order to reuse the `LiquidityCollector` for solving an auction as well as estimating a quote `Query` it should not rely on the `LimitOrder` type to collect liquidity for. Instead it internally only uses `TokenPair` so this is what I refactored it to use in the high level API.
Also I made the existing liquidity sources implement the `LiquidityCollecting` trait and the `LiquidityCollector` know takes a list of those to collect liquidity on them in parallel.
As a side note I also changed how the liquidity sources get initialized in the driver and solver main because it looked quite messy.
Only a refactor so existing tests should detect an error
Updated 1 unit test to work with the new interface
> Refactor liquidity collection

- Cargo.lock
- crates/autopilot/Cargo.toml
- crates/autopilot/src/solvable_orders.rs
- crates/model/src/order.rs
Instead of just knowing how many orders are in the current auction or got filtered out it would be nice to know how many orders of each class there are.
This could help us see how popular the new limit order feature is and if we are filtering out lots and lots of limit orders because they are out of the market price range.
[related slack thread](https://cowservices.slack.com/archives/C049P351GKF/p1669924566478809?thread_ts=1669912430.193089&cid=C049P351GKF)
> Track solvable orders metrics grouped by order class

- crates/solver/src/interactions/allowances.rs
- crates/solver/src/liquidity/balancer_v2.rs
- crates/solver/src/liquidity/uniswap_v2.rs
- crates/solver/src/liquidity/uniswap_v3.rs
- crates/solver/src/liquidity/zeroex.rs
- crates/solver/src/solver/balancer_sor_solver.rs
- crates/solver/src/solver/http_solver/settlement.rs
- crates/solver/src/solver/oneinch_solver.rs
- crates/solver/src/solver/paraswap_solver.rs
- crates/solver/src/solver/zeroex_solver.rs
While working with other code I found it wrong that "no allowance needed" is a separate enum case that also implements Interaction but is encoded as nothing so it disappears later. This feels weird because we still drag it around until the settlement is encoded.
Ci with existing tests
> Remove Approval::AllowanceSufficient in AllowanceManager refactor

- crates/autopilot/src/main.rs
- crates/driver/src/arguments.rs
- crates/driver/src/main.rs
- crates/orderbook/src/main.rs
- crates/refunder/src/arguments.rs
- crates/refunder/src/main.rs
- crates/shared/src/arguments.rs
- crates/solver/src/main.rs
Parameter to customize the refunder at a logger level.
They were taken from the other services and isolated to a macro.
```
$ cargo run --bin refunder -- --ethflow-contract 0x0000000000000000000000000000000000000000 --refunder-pk 0x0  2>/dev/null
2022-12-06T14:08:49.918Z  INFO refunder: running refunder with validated arguments:
[...]
$ cargo run --bin refunder -- --ethflow-contract 0x0000000000000000000000000000000000000000 --refunder-pk 0x0 --log-stderr-threshold 'trace' 2>/dev/null
[no output]
```
> Add logging options to refunder

- crates/shared/src/interaction.rs
- crates/solver/src/solver/balancer_sor_solver.rs
- crates/solver/src/solver/oneinch_solver.rs
- crates/solver/src/solver/paraswap_solver.rs
- crates/solver/src/solver/single_order_solver.rs
- crates/solver/src/solver/zeroex_solver.rs
In single_order_solver.rs we add a custom `struct SingleOrderSettlement` which single order solvers return instead of the normal `struct Settlement`. This struct is much simpler than the full Settlement. By using it we can share more code between single order solvers.
The motivation for this is that I want to fix two bugs in the settlement merging logic. This is currently implemented in terms of full settlement which makes it more complicated than it needs to be. Merging single order solver settlements is easier than merging full settlements and this is the only place we want to merge settlements.
no logic change, some unit tests adjusted
> Use simpler Settlement type in SingleOrderSolver

- crates/autopilot/src/solvable_orders.rs
Supersedes #921, and based on a suggestion by @vkgnosis in that same PR.
This PR introduces a `OrderFilterCounter` type that keeps a tally of the current orders throughout the auction building process. Additionally, we record candidate order counts by class, meaning we can get:
- `auction_candidate_orders - auction_solvable_orders` for the number of filtered orders by class. This replaces the filtered orders by class metric introduced in #903
- `auction_filtered_orders` to get the number of filtered orders by reason. I did not additionally classify here by `OrderClass` because it added a lot of noise and wasn't useful information for most of the filtering cases.
Additionally, we log the order UID and reason for every filtered order - so it should be easier and more deterministic to debug …
> Collect total filtered orders by class, and filtering by reason

- crates/solver/src/settlement/settlement_encoder.rs
The optimization pipeline which should improve the objective value of a settlement by applying a few gas optimizations can cause solutions that are not viable to pass the simulation by internalizing AMM interactions that are overly optimistic.
Check out this [trade](https://explorer.cow.fi/orders/0x79d6e25eb8dfe279df8e6248c01fd9b337b14a2842af1719deb556e09483ca031a0af84ef9f0a5e60967c319b03dca9a9221bde563920171) selling `USDC` for `AMPL`. `Paraswap` currently gives too optimistic prices for `AMPL`. That means the settlement provided by `paraswap` would likely have reverted. Because the order was selling `USDC` (a trusted token) the optimization pipeline was allowed to internalize the erroneous AMM interaction which resulted in a working settlement with an unbeatable price (because we pay …
> Mark interaction as internalizable instead of dropping it

- crates/autopilot/src/arguments.rs
- crates/autopilot/src/lib.rs
This PR adds a new `--surplus-fee-update-interval` flag.
Currently the surplus fee update interval is determined by the surplus fee expiry configuration, but it makes sense to have this be configured by a separate knob. Specifically, we may want to update more often in order to have limit orders get included in the auction sooner, without needing to make the limit order surplus fee expiry shorter.
The default value is set to 60s, so 30s shorter than the current default configuration.
Run the autopilot and see that the the configuration option is set:
```
% cargo run -p autopilot
...
surplus_fee_update_interval: 60s
...
```
> Separate Configuration For Limit Order Update Interval

- crates/driver/src/settlement_proposal.rs
- crates/shared/src/http_solver/model.rs
- crates/solver/src/in_flight_orders.rs
- crates/solver/src/settlement.rs
- crates/solver/src/settlement_submission.rs
- crates/solver/src/solver/http_solver/settlement.rs
Fixes https://github.com/cowprotocol/services/issues/812
The simplest possible solution.
Additionally, we can improve this by:
1. Sending protocol strategies to http searchers and matching them with strategies received back from searchers .
2. Give option to searchers to define Vec<Strategy> instead of single strategy.
The case where searchers send solution and want to submit with flashbots or nothing would be best solved with (1) IMO.
> Searchers can provide preferred submission strategy

- crates/autopilot/src/database/onchain_order_events.rs
- crates/autopilot/src/database/onchain_order_events/event_retriever.rs
- crates/autopilot/src/event_updater.rs
- crates/autopilot/src/lib.rs
- crates/e2e/tests/e2e/eth_flow.rs
- crates/e2e/tests/e2e/local_node.rs
- crates/e2e/tests/e2e/refunder.rs
- crates/e2e/tests/e2e/services.rs
(A rehashing of #934, if you are familiar with it just read the section **This PR** and keep in mind that the e2e test is copied from there.)
We pick up orders from the eth-flow contract by interpreting it as an instance of a generic wrapper contract `CoWSwapOnchainOrders`. This generic contracts defines events that should be interpreted as the creation of valid orders, directly from the blockchain.
However, the eth-flow contract can also emit other events that are not part of the `CoWSwapOnchainOrders` interface (namely order refunds). In the current implementation, our `CoWSwapOnchainOrders` contract instance (representing the contract at the eth-flow address) tries to interpret these events as an event that belongs to `CoWSwapOnchainOrders` itself and, when failing, returns an error …
> Do not block onchain order parsing on unknown events

- crates/autopilot/src/arguments.rs
- crates/autopilot/src/database/onchain_order_events/ethflow_events.rs
- crates/autopilot/src/event_updater.rs
- crates/autopilot/src/lib.rs
- crates/shared/src/event_handling.rs
PR #906 introduces an issue when starting the services: regardless of the currently available events, the autopilot now reindexes all eth-flow events at every restart.
This PR introduces a new way to create an `EventHandler` that only prevents indexing old events but does not trigger a reindexing if newer events are available.
I also sneaked in a flag for specifying the start block of the eth-flow, if you prefer I can do it in another PR.
New unit test. (However it's ignored by default because it requires a node and relies on events being generated in the settlement contracts at the time of running.)
> Add indexing starting block unless other events are available

- crates/autopilot/src/arguments.rs
In #937 I forgot to add the new argument to the display implementation of the arguments.
(I also added a hyphen to `ethflow_contract` for consistency with the rest.)
Run the autopilot with the new argument and see the output.
> Print missing argument variable ethflow_indexing_start

- crates/refunder/src/refund_service.rs
The refunder checks the owner of a Uid in the earthflow contract. Normally, this owner is a non-zero value, as the 0 address can not place orders, and invalided orders have a non-zero uid.
But since we migrated the contracts, and the refunder tried to refund non-existing orders, this owner field has become zero for some orders. Hence, I decided to filter these cases out and throw a warning. 
(But this still is no perfect solution for contract migrations)
> [Refunder] Ignore uids with zero owner for refunding

- crates/driver/src/auction_converter.rs
- crates/driver/src/main.rs
- crates/e2e/tests/e2e/limit_orders.rs
- crates/e2e/tests/e2e/onchain_settlement.rs
- crates/e2e/tests/e2e/services.rs
- crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
- crates/e2e/tests/e2e/vault_balances.rs
- crates/solver/src/driver.rs
- crates/solver/src/liquidity/balancer_v2.rs
- crates/solver/src/liquidity/uniswap_v2.rs
- crates/solver/src/liquidity/uniswap_v3.rs
- crates/solver/src/liquidity/zeroex.rs
- crates/solver/src/liquidity_collector.rs
- crates/solver/src/main.rs
Fixes #900 
This is just a small refactor to remove a bit of duplicated logic.
Instead of collecting relevant token pairs based on the `BaseTokens` in each `LiquidityCollecting` implementation we can simply do it once in the `LiquidityCollector`.
Existing unit tests still pass
> Handle base tokens in `LiquidityCollector`

- .github/workflows/pull-request.yaml
- README.md
- crates/e2e/tests/e2e/eth_flow.rs
- crates/e2e/tests/e2e/local_node.rs
- crates/e2e/tests/e2e/refunder.rs
- crates/refunder/src/refund_service.rs
- crates/shared/src/current_block.rs
The refunder showed some tricky patterns:
It was using the CPU time to check which orders are refundable. Then it simulated the refund tx on the last block, but in the last block, the orders were not yet refundable, and hence, the simulation resulted in a very low gas limit estimation. 
If then the tx would hit on chain, the tx would use a lot more gas - as it would actually do the refunding. See [here](https://goerli.etherscan.io/address/0x2c53223ec0d536defd79a422b6dedf324b398bbd) for the failed tx.
This PR fixes this, as the refunder will only use the block-time and not the CPU time for the calculation of the refundable orders.
One nice side effect of this change is that we no longer need to do the complicated "node starting point from the past" introduce here: …
> [refunder] refundable order calculation should depend on blocktime

- crates/autopilot/src/database/onchain_order_events/ethflow_events.rs
- crates/database/src/ethflow_orders.rs
- crates/database/src/orders.rs
We have seen the following errors: 
```
2022-12-14T11:36:16.502Z  WARN maintenance{block=16182672}: shared::maintenance: Service Maintenance Error: append_custom_onchain_orders failedCaused by:
0: append_ethflow_orders failed during appending pre_interactions
1: error returned from database: duplicate key value violates unique constraint "interactions_pkey"
2: duplicate key value violates unique constraint "interactions_pkey"
```
I forgot the implement the conflict handling for pre-interactions. During reorgs, the orders need to be reindexed. Hence, we need to re-insert the pre_interactions again. Since the same order_uid could potentially reflect another order - same order, but different order owner or ethflow_valid_to -, we will update the pre_signatures and not just disregard the …
> Update pre-interactions during re-org handling

- crates/e2e/tests/e2e/refunder.rs
The refunder test is flanky. E.g. [here](https://github.com/cowprotocol/services/actions/runs/3695869171/jobs/6258798439) it failed on main branch.
The reason is probably that the time of the blockchain proceeds too much between these commands: 
```
let valid_to = timestamp_of_current_block_in_seconds(&web3).await.unwrap() + validity_duration;
// Accounting for slippage is necesary for the order to be picked up by the refunder
let ethflow_order =
ExtendedEthFlowOrder::from_quote(&quote_response, valid_to).include_slippage_bps(9999);
ethflow_order
.mine_order_creation(&user, &contracts.ethflow)
.await;
```
such that the validity_duration - 10 - this is the time between mining and valid_to -  was too strict:
```
RefundService::new(..., validity_duration -10, ...)
```
I fixed it by being …
> Improve flanky refunder test

- .github/workflows/deploy.yaml
The refunder is running in all networks in staging and needs to be restarted on deploy.
Compare to same string in master.
Diffing the outputs of ` yq '.jobs.deploy.steps[6].with.pods' <.github/workflows/deploy.yaml` yields:
> Restart refunder on deploy

- crates/database/src/orders.rs
Currently, we see on staging the following error:
```
WARN maintenance{block=16189813}: shared::maintenance: Service Maintenance Error: insert_orders failedCaused by:
0: error returned from database: current transaction is aborted, commands ignored until end of transaction block
1: current transaction is aborted, commands ignored until end of transaction block
```
I think this is due to the fact that a first insert_order returns an error - duplication of uid - which we ignore. Then we try to proceed with another query. But since it's a db-transaction, and not a single query, it keeps on telling that the last command produced already an error. 
This PR makes sure that the first insertion does not even fail.
(see here for more context: …
> Fixing conflict in reorg handling by autopilot for ethflow

- crates/autopilot/src/database/orders.rs
- crates/autopilot/src/limit_orders/quoter.rs
- crates/database/src/orders.rs
This is a theoretical issue I noticed while thinking about limit orders as part of oncall.
Currently, the limit order fee updater retrieves orders with outdated fees in an arbitrary ordering because the sql query does not include an ORDER BY clause. This is problematic because it is possible that the fee estimate for an order keeps failing forever, for example because the quote is out of price. If this happened for all of the 100 orders that the query returns, then the updater would never make progress.
This PR fixes this issue by slightly changing the semantics of the surplus_fee and surplus_fee_timestamp columns. When updating the fee fails, surplus_fee is set to null and surplus_fee_timestamp is updated to the current time. With this change we can return the limit orders with outdated …
> Prevent limit order fee updater from getting stuck

- crates/autopilot/src/solvable_orders.rs
- crates/model/src/order.rs
- crates/orderbook/src/database/orders.rs
- crates/shared/src/db_order_conversions.rs
- crates/shared/src/order_validation.rs
- crates/solver/src/driver.rs
- crates/solver/src/driver/solver_settlements.rs
- crates/solver/src/liquidity/order_converter.rs
- crates/solver/src/settlement.rs
- crates/solver/src/settlement/settlement_encoder.rs
This fixes the panic that we saw in the last hour on staging.
The root cause is a mismatch on the expectations on the surplus_fee field for limit orders. In #775 we want back and forth on whether it should be nullable. In the end we decided against nullable becausae we would quote limit orders on order creation. That however was decided against in #784 . This left some parts of the code expecting the field to be non nullable and other parts expecting it to be nullable. 
In this PR make sure we can handle the fields being null.
Note that this issue wasn't introduced by #965 . That just made it more visible. We already had orders without surplus_fee in the database which would trigger a panic if anyone tried to fetch them from the /orders endpoint.
CI, adjusted unit tests, manual test
> Fix handling of limit orders without surplus_fee

- crates/autopilot/src/arguments.rs
- crates/autopilot/src/database/orders.rs
- crates/autopilot/src/lib.rs
- crates/autopilot/src/limit_orders/metrics.rs
- crates/autopilot/src/limit_orders/quoter.rs
- crates/database/src/orders.rs
- crates/e2e/tests/e2e/services.rs
The current update mechanism works in the following way:
1.  Get all outdated fee limit orders.
2. Update the fee for every order. Do this for N orders in parallel.
3. Sleep 60 seconds.
4. Repeat.
The new update mechanism works in the following way:
1. Get the N most outdated fee limit orders.
2. Update the fee these N orders in parallel.
3. If there were no outdated orders sleep 10 seconds. If there were outdated do not sleep.
4. Repeat
The new update mechanism has the following advantages:
- When there are too many limit orders to keep up with, it has more throughput because there is no sleep between updates.
- When we can keep up with all limit orders, the average time an order is outdated for is lower.
- A single update is shorter which prevents wasting work on orders that become …
> Smooth out limit order fee updates

- crates/database/src/orders.rs
The queries dealing with limit orders are not taking into account all the conditions that can cause an order to be unsolvable. Most importantly the "already settled" condition was missing.
In this PR I factor out the solvable orders query so that it can be reused by the solvable_orders function and the limit order related queries. This ensures that both work on the same conditions. Reusing this query is becoming hairy. If these queries diverge more I would stop reusing and copy paste instead.
After merging we should look at the speed of the changed queries to see if there is problematic performance.
CI, existing and adjusted unit tests
> Fix not filtering out already solved orders for limit order quoting

- crates/contracts/build.rs
- crates/shared/src/sources.rs
- crates/shared/src/sources/swapr.rs
This PR adds Swapr liquidity on Mainnet.
Swapr is UniV2 clone from the DXdao which we already supported on Gnosis Chain, so adding support on Mainnet was super easy.
Added a unit test to check that the pool address matches an existing pool on Mainnet.
Also ran the solver locally with just Swapr liquidity and [generated a settlement simulation](https://dashboard.tenderly.co/gp-v2/staging/simulator/3338c8c5-a982-49c2-a02e-6f42466a43da). Note that the transferred amounts are exact to the atom, so it looks like the pool computation is working as expected (Swapr has different fees per pool).
> Add Swapr Mainnet Liquidity

- crates/model/src/solver_competition.rs
- crates/orderbook/src/database/solver_competition.rs
- crates/solver/src/driver.rs
- crates/solver/src/settlement.rs
- crates/solver/src/settlement/settlement_encoder.rs
Fixes https://github.com/cowprotocol/services/issues/604
This PR adds a new `uniniternalized_call_data` field to the settlement competition debug JSON blob that gets uploaded to the database.
The motivation behind this change is that, currently, the only way for external solvers to inspect internalized data from their competition is to ask us to look it up in the logs. This is not ideal.
For this change, I made the `uniniternalized_call_data` **only get added if it different from `call_data`**. The reason for this is database size considerations.
Rust compiler. Serialization test.
> Include Uninternalized Settlement In Solver Competition Data

- crates/shared/src/http_solver/model.rs
- crates/solver/src/solver/http_solver.rs
- crates/solver/src/solver/http_solver/settlement.rs
This PR re-applies https://github.com/cowprotocol/services/pull/928.
We needed to **temporarily** disable it because it would break price estimation. This should be merged once the HTTP solver price estimation is changed to include execution plans.
> Make `execution_plan` Mandatory for Custom Interactions Again

- crates/e2e/tests/e2e/eth_flow.rs
- crates/model/src/order.rs
- crates/orderbook/openapi.yml
- crates/orderbook/src/database/orders.rs
- crates/shared/src/db_order_conversions.rs
There was a tiny inconsitency between the openapi spec and the sent data. We wanted to send the user field sender instead of user.
> [Easy] rename part of the ethflow data api

- crates/alerter/src/main.rs
This PR includes the fix to the limit order price check in the alerter from #923.
Essentially, the alerter price checks were happening with limit order prices **before** fees. It should take the `surplus_fee` into account when determining if it is settleable or not.
Make [an order that is within market price **before** fees](https://barn.explorer.cow.fi/orders/0xe8c6c4c4e572516afb60814aa8cbd9fb2629738b32a56470a051271d56758f6cdbc682d0ec19bd276fd6c2af4e0189b584bb31e163b7fe9b).
Run the alerter and see that it does not mark the order as settleable.
```
% cargo run -p alerter -- --orderbook-api https://barn.api.cow.fi/mainnet/ --update-interval 1 --time-without-trade 1
```
Just to double-check I applied this diff:
```diff
diff --git a/crates/alerter/src/main.rs b/crates/alerter/src/main.rs …
```
> Fix limit order price check in `alerter`

- crates/shared/src/sources/uniswap_v3/pool_fetching.rs
Fixes https://github.com/cowprotocol/services/issues/1020
UniswapV3PoolFetcher does two things in a single maintenance run:
1. Update events for already cached pools.
2. Fetch pools state checkpoint for non-cached pools (this is where the problematic subgraph call is used).
This PR lowers severity of error for task (2). In case of error during missing pools update, we just log the error.
> Missing pools update is not maintenance error

- .github/workflows/pull-request.yaml
- docker/hardhat/hardhat.config.js
While working on a patch I wanted to run e2e tests locally but they failed. After some investigation I saw that the hardhat config file we initialize the docker testing container with differs slightly from the hardhat config we use for our CI tests.
The difference was that only the CI config sets the `initialDate` to enable time travel shenanigans required for eth flow e2e tests.
Edit: Instead of keeping the github workflow file and the `hardhat.config.js` file in sync I made the github workflow file import the other file. That means all the hardhat changes required for our e2e test should be added to [hardhat.config.js](https://github.com/cowprotocol/services/blob/main/docker/hardhat/hardhat.config.js) from now on.
Ran e2e test locally using the updated docker container.
e2e tests in CI …
> Update hardhat config for docker testing container

- Cargo.lock
- crates/refunder/Cargo.toml
- crates/refunder/src/arguments.rs
- crates/refunder/src/lib.rs
- crates/refunder/src/main.rs
Closes #977.
Adds metrics and liveness checks to the refunder.
Refund loop errors have been demoted from `error!`s to `warn!`s.
I ran the refunder locally with `cargo run --bin refunder -- --ethflow-contract 0xD02De8Da0B71E1B59489794F423FaBBa2AdC4d93 --refunder-pk 0x1111111111111111111111111111111111111111111111111111111111111111`.
For checking that everything worked I used:
```
curl --write-out '%{http_code}' localhost:9590/liveness
curl localhost:9590/metrics | grep refunder_main
```
I triggered refunder failures by disconnecting my computer from the internet.
<details><summary>Example output</summary>
```
refunder_main_refunding_loops{result="error"} 20
refunder_main_refunding_loops{result="success"} 9
```
</details>
> Add metrics for refunder

- Cargo.lock
- crates/solver/Cargo.toml
- crates/solver/src/arguments.rs
- crates/solver/src/lib.rs
- crates/solver/src/main.rs
- crates/solver/src/s3_instance_upload.rs
- crates/solver/src/s3_instance_upload_arguments.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/http_solver.rs
We want Quasimodo instances to be stored on AWS S3 for later debugging. See https://github.com/cowprotocol/services/issues/334 .
This currently happens through the obsolete MIP solver which in our cluster is configured to do nothing except upload the instance. However, this instance uploading is hard to maintain and brittle. Recently it started failing and filling up the disk space of the container. It is also unnecessary overhead to run the whole MIP image just to upload instances.
There were two main ideas for re-implementing the uploading in Rust:
1. Continue using a full solver pod to upload instances.
2. Integrate the uploading into the driver.
I went with 2. because the extra pod has too much organizational overhead. I do not want to maintain a whole binary, pod, staging …
> Enable s3 instance uploading

- crates/solver/src/arguments.rs
After refactoring into a second argument struct I forgot to add the print here.
not needed
> Print s3 arguments

- crates/autopilot/src/lib.rs
- crates/autopilot/src/limit_orders/metrics.rs
While looking into ways to optimize `surplus_fee` quoting I found 1 metric somewhat confusing.
Limit order quoting was implemented in a way that updates the `surplus_fee` before the `autopilot` would consider it too old to be used in an auction.
However, the current metrics look a bit misleading:
The upper graph shows spikes of unquoted orders whereas the other graphs combined suggest a constant number of orders with usable `surplus_fee`. After some investigation I realized the lower graph shows the number of orders the `LimitOrderQuoter` intends to quote; not the number of orders where the `surplus_fee` is too old to be considered.
To monitor the overall health/efficiency of the system I think it's more insightful to track the unusable limit orders instead.
In case you consider the …
> Track number of limit orders with valid `surplus_fee`

- crates/shared/src/http_solver/model.rs
- crates/solver/src/driver.rs
anyhow errors must be converted to string using the debug representation in order to get the full stack of error information.
I also removed the From implementation because it was used in one place and I felt inlining it was easier to understand.
look at logs afterwards
> Fix not using full error description for solver run errors

- crates/autopilot/src/solvable_orders.rs
- crates/e2e/tests/e2e/services.rs
- crates/shared/src/price_estimation/factory.rs
- crates/shared/src/price_estimation/native_price_cache.rs
This PR tries to optimize how we fetch native prices for the solvable orders.
Currently the approach is to:
1. collect all traded tokens in the solvable orders
2. query their native prices
3. filter out all solvable orders for which we don't have the native prices of the tokens
Step `2` already uses the `CachingNativePriceEstimator` so all the cached prices get returned immediately and we only issue price estimation requests for the uncached prices. In order to not delay the auction creation for too long in case we have too many uncached prices step `2` gets aborted after some time (3.5 seconds). Since estimating a single price can already take 2 seconds and we currently don't do parallel price estimates we can usually only get 2 new prices in the 3.5 seconds. This means by delaying the …
> Fetch missing native prices in background task

- crates/solver/src/solver/http_solver.rs
- crates/solver/src/solver/http_solver/instance_cache.rs
- crates/solver/src/solver/http_solver/instance_creation.rs
Currently (since https://github.com/cowprotocol/services/pull/461) we do some duplicate work in `prepare_model` because the function either returns a filtered or an unfiltered version. Both versions use the same data from the node so it is wasteful to fetch it twice. With this PR we fetch the data only once.
adjusted test still works
Optionally add notes, suggestions and warnings for the releaser. They will be included in the release changelog.
> Create http solver filtered and unfiltered instance together

- crates/solver/src/solver.rs
- crates/solver/src/solver/http_solver.rs
- crates/solver/src/solver/http_solver/instance_cache.rs
- crates/solver/src/solver/http_solver/instance_creation.rs
The http solver model is shared by all http solvers and only read. This allows us to store it in Arc instead of the current behavior which clones it.
The context still needs to be cloned. I will see if I can get rid of this requirement in another PR.
existing tests
> Reduce http solver memory usage with Arc

- crates/autopilot/src/database/orders.rs
- crates/autopilot/src/limit_orders/quoter.rs
- crates/database/src/orders.rs
- database/sql/V047__index_orders_by_quote_parameters.sql
Fixes #1029
After computing a quote for the `surplus_fee` of an order we'll use the same quote for all identical orders (`sell_token`, `buy_token`, `sell_amount`).
This will make sure that users with identical orders will get treated fairly (same `surplus_fee`) and that we issue ~40% fewer price estimation requests for limit order quoting.
Updated existing unit tests
[Manual test](https://github.com/cowprotocol/services/pull/1037#issuecomment-1376037932) to verify that orders get picked up as quoted and that the performance is alright.
> Bulk update surplus fees

- crates/database/src/byte_array.rs
When I started updating identical `surplus_fee`s in bulk I introduced an unreadable tracing span into our log messages. This PR implements `Debug` for the DB `ByteArray` such that it prints a hex encoded string instead of an array of numbers.
compare logs
old: `2023-01-11T11:03:59.059Z DEBUG surplus_fee{order_spec=OrderFeeSpecifier { sell_token: ByteArray([218, 193, 127, 149, 141, 46, 229, 35, 162, 32, 98, 6, 153, 69, 151, 193, 61, 131, 30, 199]), buy_token: ByteArray([67, 171, 118, 94, 224, 80, 117, 215, 138, 216, 170, 121, 220, 177, 151, 140, 163, 7, 146, 88]), sell_amount: BigDecimal("1000000000") }}: shared::rate_limiter: reset rate limit ...`
new: `2023-01-11T11:13:11.459Z DEBUG surplus_fee{order_spec=OrderFeeSpecifier { sell_token: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2, …
> Log DB byte arrays as hex string

- crates/autopilot/src/solvable_orders.rs
- crates/e2e/tests/e2e/services.rs
- crates/shared/src/price_estimation.rs
- crates/shared/src/price_estimation/factory.rs
- crates/shared/src/price_estimation/native.rs
- crates/shared/src/price_estimation/native_price_cache.rs
If we want to be able to keep all limit orders quoted at the same time we have to keep the native price cache up-to-date at all times. Unfortunately the number of unique tokens across all limit orders is too big (~200) for the native price cache background worker to keep up-to-date when we are updating prices purely sequentially.
This PR introduces a CLI argument (`--native-price-cache-concurrent-requests`) which allows the background worker to update prices concurrently.
This PR in conjunction with #1053 should allow us to perfectly tweak the parameters required to keep the native price cache entirely up-to-date on average.
Updated existing unit tests
Added new unit test
Manual test to verify argument printing:
```
2023-01-12T10:22:46.540Z  INFO autopilot: running autopilot with …
```
> Native price cache concurrent requests

- crates/driver/openapi.yml
- crates/solvers/openapi.yml
Motivated by recent Quasimodo changes.
Note that for the driver API I only added the status code to /quote and not the other routes. The other routes should always be available.
n/a
> Let http solvers indicate they cannot keep up

- crates/shared/src/http_solver.rs
- crates/shared/src/price_estimation/http.rs
- crates/shared/src/rate_limiter.rs
Quasimodo has recently gotten the ability to signal when it can't keep up through the TOO_MANY_REQUESTS status code. Our code is not aware of this and treats it as a generic error. Generic errors sometimes end up logged as internal errors so that we can investigate them. This doesn't make sense for the rate limit.
This PR makes us aware of the rate limit and turns it into the already existing price estimation error of the same type.
Note that this PR does not make the Rust RateLimiter aware of this status code. We might want to integrate that this so that it counts towards our local rate limit too. This can be done in another PR.
Didn't see a good way to unit test this. After merging the error logs about this status code should go away.
> Do not treat http solver rate limit as generic error

- crates/solvers/src/domain/mod.rs
- crates/solvers/src/domain/order.rs
This PR adds the `Order` domain model. Additionally, it introduces a `NonLiquidity` marker type that wraps an order to indicate that it is a user and non-liquidity order. This allows the Baseline solver to operate on `NonLiquidity` orders only so it never accidentally solver for a liquidity order.
Rust compiler. An E2E test will be added for testing baseline solving.
> Introduce Order and order::NonLiquidity Domain Objects

- crates/solver/src/s3_instance_upload.rs
I've been thinking about allowing external access to the s3 instances and came to the conclusion that it doesn't make sense to group them by date. The Gnosis s3 script does something like this, probably so that they can display the bucket like a folder structure without having too many files in the same folder. However, to S3 there are no folders. These are just files that happen to have slashes in their name. By introducing some arbitrary partitioning scheme like the date, we make it harder to know the path of an instance. By using only the id the path is perfectly predictable.
manual test
> Do not group s3 uploads by date

- crates/shared/src/oneinch_api.rs
- crates/shared/src/paraswap_api.rs
- crates/shared/src/rate_limiter.rs
- crates/shared/src/zeroex_api.rs
The `0x`, `Paraswap` and `1Inch` api implementation can issue a lot of logs which essentially all get duplicated in the `CompetitionPriceEstimator`.
Also `1Inch` and `0x` can issue logs which are crazy long (`1Inch` liquidity sources and `0x` limit orders as liquidity).
All of this seems to be just noise when you are debugging something locally. I think one could even argue how useful those logs are in the actual deployment but I left them just to be safe.
> Demote 0x, Paraswap and 1Inch api logs to `trace!`

- crates/autopilot/src/lib.rs
- crates/autopilot/src/limit_orders/metrics.rs
- crates/autopilot/src/limit_orders/quoter.rs
- crates/autopilot/src/solvable_orders.rs
- crates/shared/src/bad_token/token_owner_finder/solvers/solver_finder.rs
- crates/shared/src/current_block.rs
- crates/shared/src/http_solver.rs
- crates/shared/src/maintenance.rs
- crates/shared/src/price_estimation/native_price_cache.rs
- crates/shared/src/token_list.rs
- crates/solver/src/solver/http_solver/instance_cache.rs
Ideally we would like to know what caused each log to appear. This means for any sort of request that we are using info spans containing the `request_id`.
But we have a bunch of background tasks which can produce a lot of logs which fly under the radar.
This PR adds an info span for every task we spawn (minus tests, request batching and the main tasks like the `orderbook`).
Note that logs originating from the initialization sequence didn't get any new tracing spans but I think this is fine.
Ran autopilot locally to check logs (I just picked a bunch of updated logs in no particular order):
```
2023-01-16T12:02:36.063Z DEBUG ServiceMaintenance:maintenance{block=16419218}: shared::event_handling: latest blocks: Some((16419091, 0xbbbf69cb04d06485409046a10bdd55da81582849a7cbae8798ca34159ed06375 …
```
> Better tracability with more info spans

- Cargo.lock
- crates/solvers/Cargo.toml
- crates/solvers/src/api/dto/mod.rs
- crates/solvers/src/api/mod.rs
- crates/solvers/src/cli/baseline.rs
- crates/solvers/src/cli/mod.rs
- crates/solvers/src/domain/eth/mod.rs
- crates/solvers/src/main.rs
Supersedes #1039 
As the title suggests, this PR hooks up the Baseline solver to the API endpoint in the `solvers` crate. Note that it is done in a very straight forward way - i.e. with the current implementation, multiple solver types are not implemented ATM. Once I add the second solver type, I will refactor the `api` module to make this possible.
Additionally, in order to configure the Baseline solver, I added some simple command line argument parsing. Note that the network-specific configuration options are included as command line arguments! Concretely, this means we will need a Baseline solver engine instance for each network. I _think_ this is a good thing as:
- It keeps per-network configuration to separate pods
- A spike in Görli and Gnosis Chain traffic will not affect Mainnet …
> Hook up Baseline Solver to API

- crates/solvers/src/api/dto/auction.rs
- crates/solvers/src/boundary/baseline.rs
- crates/solvers/src/domain/liquidity/concentrated.rs
- crates/solvers/src/domain/liquidity/limit_order.rs
- crates/solvers/src/domain/liquidity/mod.rs
- crates/solvers/src/domain/liquidity/stable.rs
In order to integrate the remaining Gnosis solvers, we need to map the remaining liquidity from the Auction DTO into domain objects.
This PR introduces new liquidity types as well as mapping boilerplate between the DTOs and the domain objects.
Rust compiler, just simple data-mapping.
> Introduce Remaining Liquidity Domain Objects

- crates/solver/src/s3_instance_upload.rs
- crates/solver/src/solver/http_solver/instance_cache.rs
Implemented suggestion from https://github.com/cowprotocol/services/pull/1086#pullrequestreview-1253174388 (I wasn't able to explain my suggestion very well, so thought it was easier to just write it out).
This PR changes the S3 upload logic to explicitly specify that:
- the file is a JSON document
- the file is Gzip encoded
This does a couple of nice things for us:
- It is stored compressed on S3, so saves space 🎉 (same as before)
- AWS automatically sets the correct `Content-*` headers when retrieving the file, this means that HTTP clients will do the Gzip decoding for us, removing the manual step of `gunzip` and making using these uploaded files slightly more ergonomic (motivation for this change)
Manually run the ignored test.
Notice how it is stored in compressed format on S3 (4.6 …
> Upload Auction Instance JSON with Gzip Content Encoding

- crates/solver/src/solver/single_order_solver.rs
- crates/solver/src/solver/zeroex_solver.rs
Fixes https://github.com/cowprotocol/services/issues/1021
Closes https://github.com/cowprotocol/services/pull/1025 
See #1021 for motivation for this change.
I have intentionally not implemented Nic's [suggestion](https://github.com/cowprotocol/services/pull/1025#discussion_r1060501210) of only checking for negative objective value *after* merging all single solutions. This is because it makes more sense to filter out bad solutions individually. If we have some good orders and some bad orders (like stable to stable trade) then filtering out after merging could make the whole settlement become bad. By filtering before merging this doesn't happen and we can still merge all the good orders. There is some space for a more optimal algorithm but I felt the complexity wasn't worth it. I expect …
> Do not emit negative objective value settlements in zeroex solver

- crates/autopilot/src/arguments.rs
- crates/autopilot/src/lib.rs
- crates/autopilot/src/solvable_orders.rs
Currently we wait a fixed interval of 2 seconds after every auction update loop. This commit change the behavior to wait as long is needed to reach the configured target effective update interval.
If creating the auction is slow then we sleep less or not at all. If creating the auction is fast then we sleep the for longer.
This an improvement because we get more auctions on slow environments and less on fast environments. For example, at the moment creating the auction on staging Goerli is very fast which means there is a new auction every 2 seconds. This creates unnecessary churn for the solvers and for the data that we keep track of per auction like instance uploading.
This PR makes the target interval configurable and sets the default to 10 seconds from the previous 2 seconds. This …
> Make auction update interval smarter

- crates/solver/src/arguments.rs
- crates/solver/src/driver.rs
Same change as https://github.com/cowprotocol/services/pull/1101 but for the driver. I forgot we'd need it there too.
As before, the reasoning for changing the default is that this won't have any effect on busy networks where solving already takes 10 seconds. Also need to adjust the value we set this too in the cluster, which I have a Gitlab branch for.
observe after merging
> Make driver run loop update interval smarter

- crates/driver/src/domain/liquidity/balancer/mod.rs
- crates/driver/src/domain/liquidity/balancer/stable.rs
- crates/driver/src/domain/liquidity/balancer/weighted.rs
- crates/driver/src/domain/liquidity/fetcher.rs
- crates/driver/src/domain/liquidity/mod.rs
- crates/driver/src/domain/liquidity/swapr.rs
- crates/driver/src/domain/liquidity/uniswap/mod.rs
- crates/driver/src/domain/liquidity/uniswap/v2.rs
- crates/driver/src/domain/liquidity/uniswap/v3.rs
- crates/driver/src/domain/liquidity/zeroex.rs
This PR introduces "skeleton" types for the `driver` liquidity.
The idea is to wrap the existing `LiquidityCollector` in a boundary module, and "baseline source" by "baseline source" introduce wrapping logic into the `driver`. As such, each of the liquidity data types are intentionally left empty and will be populated once the wrapping/conversion logic gets introduced.
For now, I wanted to have this PR to:
- Come to consensus on the type names and module layout for liquidity and liquidity fetching
- Introduce documentation for each of the supported pool types
In following PRs, I will slowly build these abstractions and fill in code and types as needed.
I also proposed a module organization following the suggestion [here](https://github.com/cowprotocol/services/pull/1066#pullrequestreview-1 …
> Introduce Driver Liquidity Domain Objects

- crates/driver/src/boundary/liquidity/mod.rs
- crates/driver/src/boundary/liquidity/uniswap/v2.rs
- crates/driver/src/domain/liquidity/mod.rs
- crates/driver/src/domain/liquidity/uniswap/v2.rs
- crates/solver/src/liquidity.rs
- crates/solver/src/liquidity/balancer_v2.rs
- crates/solver/src/liquidity/order_converter.rs
- crates/solver/src/liquidity/uniswap_v2.rs
- crates/solver/src/liquidity/uniswap_v3.rs
- crates/solver/src/liquidity/zeroex.rs
This PR introduces boundary logic for fetching Uniswap V2 liquidity, and mapping it to domain liquidity models.
This is mostly just mapping `solver` types to `driver` types.
One notable change is the introduction of a `SettlementHandling::as_any` method, in order to downcast `dyn SettlementHandling` trait objects into concrete types. This is needed to extract pool information that is relevant to the domain liquidity object. I think that this is a bit of a hack, but mostly harmless and should be removed (i.e. purged with 🔥) once we complete the boundary liquidity mappings and finally move code from `solver` to `driver` crate. The plan for removing the use of `Any` is to change `settlement_handler` to use concrete types for each pool type. This is quite hard to do ATM because …
> Fetch Uniswap V2 Liquidity

- crates/driver/src/boundary/liquidity/mod.rs
- crates/driver/src/boundary/liquidity/uniswap/mod.rs
- crates/driver/src/boundary/liquidity/uniswap/v2.rs
- crates/driver/src/boundary/mempool.rs
- crates/driver/src/boundary/mod.rs
- crates/driver/src/domain/liquidity/mod.rs
- crates/driver/src/domain/liquidity/uniswap/v2.rs
- crates/driver/src/infra/blockchain/mod.rs
- crates/solver/src/interactions/allowances.rs
- crates/solver/src/interactions/uniswap_v2.rs
- crates/solver/src/liquidity.rs
- crates/solver/src/liquidity/uniswap_v2.rs
This PR introduces Uniswap v2 swap encoding in the `driver`. It is implemented by wrapping existing `solver` crate logic.
One interesting detail is that the `UniswapInteraction` types expects `msg.sender == receiver` which is not always true. The new `driver` code no longer has this assumption, but it is worth pointing out.
Additionally, we introduce a `NoAllowanceManaging` type, which is just a dummy `AllowanceManaging` implementation that pretends like no allowances are set. The reason for this is that the current driver already has allowance setting logic in `eth::allowance` module that I intend to reuse. This saves the back-and-forth request to fetch approvals for all liquidity (instead of just fetching approvals for the tokens that are encoded in a settlement).
Rust compiler, logic …
> Encode Uniswap V2 Interactions

- crates/driver/src/boundary/liquidity/uniswap/v2.rs
- crates/driver/src/boundary/settlement.rs
- crates/driver/src/domain/competition/solution/interaction.rs
- crates/driver/src/domain/competition/solution/mod.rs
- crates/driver/src/domain/eth/mod.rs
- crates/driver/src/domain/liquidity/mod.rs
- crates/driver/src/domain/liquidity/uniswap/v2.rs
This PR changes the `boundary::settlement` module to create a settlement in function of the `solver::settlement::Settlement` and `solver::settlement::SettlementEncoder` interfaces.
This simplifies the work we need to do for encoding `LiquidityInteraction`s within a settlement (no need to setup a "liquidity map" like we would have to with the `SettledBatchAuctionModel` interface).
Existing driver settlement E2E test continues to work!
```
% cargo test -p driver -- --nocapture --ignored --test-threads 1
...
test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.76s
```
Note that we aren't testing Uniswap V2 interactions quite yet (the existing E2E tests use `Interaction::Custom` interactions ATM), but that is the next PR.
> Include Solution Liquidity in Settlement

- docker/Dockerfile.binary
This PR adds the `driver` and `solvers` binaries to the "binaries" Docker image we build. This will enable us to run them in our infrastructure.
1. Build the docker image
```sh
docker build . -f docker/Dockerfile.binary -t cowprotocol/services
```
2. Check that the binaries are there
```sh
docker run -it --rm cowprotocol/services bash -c 'which driver; which solvers'
```
```
/usr/local/bin/driver
/usr/local/bin/solvers
```
> Add `driver` and `solvers` to Docker Image

- crates/database/src/ethflow_orders.rs
Some integrators might send us orders with 0 slippage (e.g. [DefiLlama](https://cowservices.slack.com/archives/C0361CDD1FZ/p1674246929312629)). These orders can currently not be automatically refunded because the DB query currently requires the order's slippage to be strictly greater than the configured `--min-slippage-bps`. And we can also not configure negative `--min-slippage-bps`.
Note that we wouldn't really want to refund such orders but in case those orders make it into our system because the integrator was not aware it would be nice if we could just configure the `refunder` accordingly instead of having to manually refund those orders.
This PR patches the DB query such that the `order_slippage >= min_slippage_bps` is enough.
Unit tests are still passing.
> Add support for 0 slippage ETH flow refunds

- docker/Dockerfile.dev-geth
This PR refactors the `dev-geth` Dockerfile to accomplish a few things:
1. Make it compatible with Apple Silicon (because, that is what I use!)
2. Wrap the execution in `tini` to handle things like `Ctrl-C` and not timeout on `docker compose down`
3. Reduce the image size
Build and run the new image:
```
docker build -t dev-geth -f docker/Dockerfile.dev-geth .
docker run -it --rm dev-geth
```
Image size decreased 💪:
```
% docker images
REPOSITORY            TAG       IMAGE ID       CREATED              SIZE
dev-geth              latest    f7240baa55b6   About a minute ago   188MB
dev-geth-old          latest    7e2c9067809d   About an hour ago    3.17GB
```
I also double-checked that this would work on x86_64 Linux systems with:
```
docker build -t dev-geth-amd64 -f …
```
> Refactor `dev-geth` Dockerfile

- crates/driver/openapi.yml
When the spec was written we hadn't decided yet that we were using an arbitrary tag of a couple of bytes to identify transactions yet.
> Document transaction identifier in openapi

- crates/driver/src/domain/competition/auction.rs
- crates/driver/src/domain/competition/mod.rs
- crates/driver/src/domain/quote.rs
- crates/driver/src/infra/api/error.rs
- crates/driver/src/infra/api/mod.rs
- crates/driver/src/infra/api/routes/solve/dto/auction.rs
- crates/driver/src/infra/api/routes/solve/mod.rs
- crates/driver/src/infra/solver/dto/auction.rs
- crates/driver/src/infra/solver/dto/solution.rs
- crates/driver/src/infra/solver/mod.rs
This PR refactors the `liquidity` field out of the `Auction` domain type.
The rationale behind this change is that `Auction`s can exist with or without liquidity, and that `liquidity` is just an "augmentation" provided by the driver, but orthogonal to the actual auction.
Furthermore, having liquidity part of the `Auction` already made its creation (in `dto::Auction::from_domain`) a bit awkward:
1. We need to first have the orders and then get the liquidity, so we need a partial auction to create the full one
2. Makes it awkward to look at other auction parameters (like `tokens` or `deadline` for example)
3. Makes it `async`.
Additionally, `liquidity` is a shared concept between `Auction` and `quote::Order`, so having as sidecar data seemed more natural.
Driver tests still pass.
```
test …
```
> Refactor `liquidity` Field out of `Auction` Domain Object

- crates/driver/src/boundary/liquidity/mod.rs
- crates/driver/src/domain/competition/mod.rs
- crates/driver/src/domain/liquidity/mod.rs
- crates/driver/src/domain/quote.rs
- crates/driver/src/infra/api/error.rs
- crates/driver/src/infra/api/mod.rs
- crates/driver/src/infra/api/routes/mod.rs
- crates/driver/src/infra/api/routes/quote/dto/mod.rs
- crates/driver/src/infra/api/routes/quote/dto/order.rs
- crates/driver/src/infra/api/routes/quote/mod.rs
- crates/driver/src/infra/liquidity/fetcher.rs
- crates/driver/src/infra/liquidity/mod.rs
This PR changes `/quote` endpoint to first fetch and pass in liquidity to the solver engine.
Additionally, it introduces a new `quote::Tokens` struct to maintain the invariant that `sellToken != buyToken` for quotes (which doesn't make sense).
Driver tests continue to pass.
Also, manually request a quote with a driver + baseline solver pair and see the baseline solver find a price!
```
2023-01-20T12:48:10.736Z TRACE driver::infra::solver: got response from solver self.config.endpoint=http://localhost:7872/ res=Ok("{\"prices\":{\"0x6b175474e89094c44da98b954eedeac495271d0f\":\"1000000000000000000\",\"0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2\":\"1547346991108415943371\"},\"trades\":[{\"kind\":\"fulfillment\",\"order\":\"0x000000000000000000000000000000000000000000000000000000000000000000000 …
```
> Fetch Liquidity when `/quote`-ing

- crates/driver/src/domain/competition/mod.rs
- crates/driver/src/domain/quote.rs
- crates/driver/src/infra/api/error.rs
- crates/driver/src/infra/liquidity/fetcher.rs
Fixes https://github.com/cowprotocol/services/issues/1130.
Log an error when liquidity fetching fails instead of returning an HTTP error.
> Gracefully handle liquidity errors in `driver`

- Cargo.lock
- crates/autopilot/Cargo.toml
- crates/autopilot/src/database.rs
- crates/autopilot/src/database/recent_settlements.rs
- crates/autopilot/src/driver_model.rs
- crates/autopilot/src/run_loop.rs
- crates/database/src/lib.rs
- crates/database/src/settlements.rs
I decided on the approach of using the existing event infrastructure to find recent settlement transactions. Otherwise it would be a lot more work to implement reorg robustness and event fetching.
For this PR I set the tag to the auction id. This can be considered a placeholder, although it works well in practice too as long as different environments on the same network do not use the same id at the same time. I'm going to make an issue for this because it isn't part of this PR.
sql has a test, rest needs to wait for a proper end to end test
> Implement autopilot transaction finding

- crates/autopilot/src/database/onchain_order_events.rs
- crates/orderbook/src/api/cancel_order.rs
- crates/orderbook/src/api/get_order_by_uid.rs
- crates/orderbook/src/api/get_orders_by_tx.rs
- crates/orderbook/src/api/get_trades.rs
- crates/refunder/src/submitter.rs
- crates/solver/src/solver/http_solver.rs
Martin noticed in https://github.com/cowprotocol/services/pull/1144 that we sometimes include `:` in format strings even though this doesn't have any effect.
I also inlined some more cases that clippy doesn't catch because they appear in macros that aren't std's `format!`.
CI
> Fix unused `:` in format strings

- crates/autopilot/src/arguments.rs
- crates/autopilot/src/lib.rs
- crates/shared/src/network.rs
In the colocated autopilot we need to know the time between blocks on the network. Instead of making several individual block timeouts configurable I feel it makes more sense to derive them automatically from the block interval.
CI, double check that staging pods still start
> Configure network's time between block

- crates/autopilot/src/solvable_orders.rs
- crates/e2e/tests/e2e/services.rs
- crates/shared/src/price_estimation.rs
- crates/shared/src/price_estimation/factory.rs
- crates/shared/src/price_estimation/native_price_cache.rs
Ideally the `autopilot`'s native price cache has the prices warm in the cache at all times. For that to work the `CachingNativePriceEstimator` supports updating prices in the background before they actually expire.
The component already supported customizing that prefetch time but so far we didn't have a CLI argument for that.
This PR adds that argument: `--native-price-cache-prefetch-time-secs`. Configuring this should help us reduce the number of orders that don't make it into the current auction due to missing native prices.
Ran `autopilot` locally:
Prints CLI arguments:
```
...
native_price_cache_max_age_secs: 60s
native_price_prefetch_time_secs: 2s
native_price_cache_max_update_size: 100
...
```
Prints a help text:
```
--native-price-prefetch-time-secs …
```
> Make native price cache prefetch time configurable

- crates/solver/src/main.rs
- crates/solver/src/solver.rs
This PR adds plumbing to pass the already existing ParaSwap rate limiter configuration to the ParaSwap solver. This should help us alleviate rate limiting issues that we are seeing in our solver.
Compiler, no new logic, just plumbing.
> Pass ParaSwap Rate Limiter to Solver

- crates/solver/src/solver/http_solver/instance_cache.rs
This PR changes the instance cache to record metrics instead of issuing error alerts when uploading to S3 fails. This is because uploading can intermittently fail, and these instance are used for debugging anyway, so temporary failures to upload is not a big issue. With metrics, we can setup an alert if it starts failing for, say, 10 minutes straight which means that there is probably something more seriously wrong that requires some attention.
CI
> Record Metrics for S3 Uploads

- crates/autopilot/src/solvable_orders.rs
This PR adds a new gauge for the number of **market** orders that are filtered out because of missing prices. This is because filtering out market orders for this reason is more serious than limit orders. This new metric will allow us to monitor this separately and potentially create alerts to deal with missing market order native token prices.
I also changed the `checkpoint` to log the order's class to make debugging filtered orders in the log easier.
Rust compiler
> Improve Metrics fo Auction Building

- crates/autopilot/src/solvable_orders.rs
- crates/contracts/src/bin/vendor.rs
- crates/shared/src/price_estimation/native_price_cache.rs
The native price cache cannot keep up with the amount of tokens it has to process in production. This can lead to market orders not settling because the orders are not considered solvable because of missing native prices.
This PR prioritizes the updates of market order tokens over other tokens. This functionality is only used by the autopilot's solvable order module.
new unit test for the harder to understand part of the change
> Prioritize updates of market order native token prices

- crates/autopilot/src/solvable_orders.rs
- crates/shared/src/maintenance.rs
@MartinquaXD rightfully pointed out that the `#[metrics()]` attributes were unnecessary for metrics that don't have labels (or other configuration options).
This PR fixes that (and fixes it in other places as well).
One of the changed metrics are still there:
```
% curl -s 'http://localhost:9587/metrics' | rg last_updated_block
gp_v2_solver_maintenance_last_updated_block 8409425
```
> Remove Unnecessary `#[metrics()]` Attibutes

- crates/e2e/tests/e2e/eth_integration.rs
- crates/e2e/tests/e2e/limit_orders.rs
- crates/e2e/tests/e2e/onchain_components.rs
- crates/e2e/tests/e2e/onchain_settlement.rs
- crates/e2e/tests/e2e/order_cancellation.rs
- crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
- crates/e2e/tests/e2e/vault_balances.rs
- docker/hardhat/hardhat.config.js
Our older hardhat e2e tests assume they can send transactions with 0 gas price. This doesn't work with the new geth e2e tests. To bring the systems in line I change the existing tests to no longer use 0 gas price. In some tests this requires changes to fund trader accounts that need to send an approval transaction.
CI e2e tests
> Use non zero gas price in e2e tests

- crates/driver/example.toml
- crates/driver/src/infra/config/file/load.rs
- crates/driver/src/infra/config/file/mod.rs
- crates/driver/src/infra/solver/mod.rs
The address can be calculated from the private key so there is no reason to pass it separately. That only leaves space for mismatching the parameters.
still compiles
> Do not pass solver address in driver config

- crates/driver/openapi.yml
- crates/driver/src/infra/api/routes/solve/dto/auction.rs
While writing the autopilot-driver e2e test I noticed some mistakes in the api. This PR changes the driver's rust API types and populates the openapi spec with the details of the Order struct.
This leaves some fields that were previously populated unset. Autopilot should not provide this information. Driver should fetch it itself, which I have not implemented.
CI
> Update colocated driver API details

- crates/shared/src/rate_limiter.rs
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f36f362ce1571bcb34ed0debab7afc6c
The `u64::MAX` limit is not the right value to use here, and can cause panics. This showed up in staging.
Tests still pass. After applying to staging we'll see if it goes away.
> Fix duration overflow bug

- crates/driver/src/boundary/liquidity/uniswap/v2.rs
- crates/driver/src/boundary/settlement.rs
- crates/shared/src/http_solver/model.rs
- crates/solver/src/interactions/allowances.rs
- crates/solver/src/interactions/balancer_v2.rs
- crates/solver/src/interactions/uniswap_v3.rs
- crates/solver/src/liquidity.rs
- crates/solver/src/liquidity/balancer_v2.rs
- crates/solver/src/liquidity/slippage.rs
- crates/solver/src/liquidity/uniswap_v2.rs
- crates/solver/src/liquidity/uniswap_v3.rs
- crates/solver/src/liquidity/zeroex.rs
- crates/solver/src/solver/baseline_solver.rs
- crates/solver/src/solver/http_solver/settlement.rs
- crates/solver/src/solver/naive_solver.rs
- crates/solver/src/solver/naive_solver/multi_order_solver.rs
Replaced the `(H160, U256)` tuple in `AmmOrderExecution` with `TokenAmount` struct. Also replaced separate `token`, `amount` fields or params with `TokenAmount` in related code.
Fixes #692
GitHub workflows
> Use `TokenAmount` in `AmmOrderExecution`

- crates/shared/src/paraswap_api.rs
We are getting a lot of errors from paraswap that contain the error message: `Err(Other("EOF while parsing a value at line 1))`.https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/kXG8f
In order to understand this error better, I want to see the raw response and introduce the same tracing log as we have it for the price API request.
> New tracing logs for debugging Paraswap

- crates/driver/src/infra/config/file/mod.rs
- crates/driver/src/tests/setup/driver.rs
- crates/solvers/src/config/baseline/file.rs
This helps detect accidentally specifying configuration that has no effect. I was unable to find something similar for clap argument parsing.
ran the driver and solvers test
> Deny unknown config file fields

- crates/autopilot/src/driver_model.rs
- crates/driver/src/infra/api/routes/quote/dto/order.rs
- crates/driver/src/infra/api/routes/solve/dto/auction.rs
- crates/driver/src/infra/solver/dto/solution.rs
- crates/solvers/src/api/dto/auction.rs
- crates/solvers/src/api/dto/solution.rs
This helps catch cases where the types used in serialization don't line up.
Also added some `camelCase` annotations where they were missing and removed one of of the deserialize/serialize derives when the type is only used in one direction.
CI, ran existing colocation tests
> Deny unknown fields in colocation APIs

- Cargo.lock
- crates/autopilot/src/lib.rs
- crates/orderbook/src/main.rs
- crates/shared/Cargo.toml
- crates/shared/src/arguments.rs
- crates/shared/src/bad_token/trace_call.rs
- crates/shared/src/price_estimation/http.rs
- crates/shared/src/sources.rs
- crates/shared/src/sources/swapr/reader.rs
- crates/shared/src/sources/uniswap_v2.rs
- crates/solver/src/main.rs
Allows us to configure custom univ2 instances. This is useful in e2e tests. A custom univ2 instance is the address of a router contract along with the init_hash for calculating pool addresses.
As a follow up it could allow us to get rid of all of the univ2 fork hardcodes that we currently have in the code. We would remove them as baseline sources and move them into the new argument in our cluster configuration.
manually test and observe after merging
> Allow specifying custom univ2 like liquidity in command line arguments

- crates/solvers/example.baseline.toml
- crates/solvers/src/infra/config/baseline/file.rs
- crates/solvers/src/infra/config/baseline/mod.rs
- crates/solvers/src/infra/contracts.rs
- crates/solvers/src/run.rs
@vkgnosis pointed out in #1202 that the chain ID parameter being mandatory is not practical for local deployments or when testing out on new chains.
In fact, the baseline solver only needs to know the WETH address, so this PR changes the configuration semantics to require either:
- specifying a `chain-id` to use the canonical WETH contract for that chain.
- specify a custom `weth` address to use that instead, at which point the `ChainId` is no longer needed
Adjusted test loading the example TOML configuration.
> Optional Chain ID in Baseline Solver Configuration

- crates/model/src/solver_competition.rs
This PR makes the solver competition endpoint backwards compatible, otherwise we are unable to request historic data.
The One Compiler To Rule Them All (i.e. `rustc`).
> Make Solver Competition Deserialization Backwards Compatible

- crates/driver/src/infra/api/routes/solve/dto/auction.rs
- crates/driver/src/tests/cases/quote.rs
- crates/driver/src/tests/cases/settle.rs
- crates/driver/src/tests/cases/solve.rs
Some of my recent changes broke the e2e test:
- Didn't update some field names detected by `deny_unknown_fields` .
- Solution score changes because driver no longer sets gas price. See https://github.com/cowprotocol/services/issues/1196 . Getting the current gas price has to be implemented in the driver.
manually ran driver e2e tests
> Fix driver e2e test

- Cargo.lock
- crates/driver/Cargo.toml
- crates/driver/src/infra/api/error.rs
- crates/driver/src/infra/api/routes/solve/dto/auction.rs
- crates/driver/src/infra/api/routes/solve/mod.rs
- crates/driver/src/infra/blockchain/mod.rs
- crates/driver/src/tests/cases/solve.rs
Fixes #1196 .
The driver was not fetching gas prices but they are required for the solvers.
- Add some logging to the `route` function. This is useful because it doesn't make sense to report on all errors in detail through the autopilot-driver API but we do want to log them for debugging.
- Change the score comparison in the test to be approximate. Required because the computed score is not deterministic (unrelated to my change). The test fails if the score deviates by more than 1% from the expected value.
run the changed test
> Get gas price in driver

- crates/solver/src/lib.rs
- crates/solver/src/run.rs
- crates/solver/src/settlement_submission/submitter.rs
Like with other crates this allows use to use the solver main function in e2e tests.
still compiles, no logic change if argument isn't specified
> Use configured contract addresses

- crates/autopilot/src/lib.rs
- crates/orderbook/src/run.rs
- crates/refunder/src/arguments.rs
- crates/refunder/src/lib.rs
- crates/shared/src/arguments.rs
- crates/solver/src/driver.rs
- crates/solver/src/run.rs
A couple of times, we have accidentally connected services meant for Goerli to Mainnet. This leads to a bunch of events getting indexed in the wrong database and is very painful to cleanup.
This PR adds a chain ID sanity check on start up to prevent this from happening.
```
% cargo run -p autopilot -- --node-url https://goerli.infura.io/v3/$INFURA_PROJECT_ID --chain-id 6
...
2023-02-15T15:40:45.363Z ERROR shared::tracing: thread 'main' panicked at 'assertion failed: `(left == right)`
left: `5`,
right: `6`: connected to node with incorrect chain ID'
```
We should configure the `CHAIN_ID` environment variable on all our pods.
> Check Chain ID on Startup

- Cargo.lock
- Cargo.toml
This PR improves the revert detection from Nethermind nodes and should help us detect the following errors (instead of causing alerts):
```
ERROR (pod: dfusion-v2-api-xdai-86774456bb-9lhdt):
2023-02-16T07:11:37.743Z ERROR request{id="b4b48a376396a0c741bc6bb499199ecd"}: orderbook::api::post_order: ValidationErrorWrapper err=web3 error: RPC error: Error { code: ServerError(-32015), message: "Reverted 0x656e636f646564206f7264657220213d207472616461626c65206f72646572", data: None }
```
Tests were added in `ethcontract`
> Bump Ethcontract To Improve Nethermind Revert Detection

- crates/shared/src/http_solver.rs
- crates/shared/src/price_estimation.rs
- crates/shared/src/price_estimation/factory.rs
- crates/shared/src/price_estimation/http.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/http_solver.rs
I did something bad...
This **incredibly hacky** PR changes the Yearn solver price estimator to use a custom path for the solve request. This is because the HTTP solver expects requests to `/quote` instead of `/solve` for price estimation.
Why is it done in such a hacky way? Well the new `driver` binary already supports arbitrary paths for solvers (so in this case we would be able to configure the URL to be `https://the.yearn.solver.eth/path/to/quote`). This means that this technical debt will be removed for free in the very near future without any additional work.
The alternative would be to stop appending `/solve` in the `http_solver.rs` implementation and to add `/solve` to the URL for each external solver in our deployment configuration. I chose against this for a couple of reasons: …
> Custom 'solve' URL Path for HTTP Solvers

- .github/workflows/pull-request.yaml
Some networking changes in GitHub CI is causing Hardhat to bind to **only** `::1`, and is no longer binding to `127.0.0.1`. This causes local node tests to fail, as they are unable to connect to the Hardhat instance.
This PR just forces Hardhat to bind to `127.0.0.1` instead of `localhost`, thus avoiding the issue.
Tests should start running again.
> Force Hardhat to Bind to 127.0.0.1

- crates/solver/src/metrics.rs
I accidentally changed the name of one metric.
n/a
> Fix name of trade counter metric

- crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
- crates/shared/src/token_list.rs
- crates/solver/src/arguments.rs
- crates/solver/src/run.rs
- crates/solver/src/settlement_post_processing/optimize_buffer_usage.rs
- crates/solver/src/solver/http_solver.rs
- crates/solver/src/solver/http_solver/instance_creation.rs
Factored out of https://github.com/cowprotocol/services/pull/1229 .
For an e2e test we need a token whose buffers are allowed to be traded. The existing test accomplishes this by manually creating the token list component. With the change to using only the main/run functions of the crates this is no longer possible.
In this PR we change the driver arguments to allow passing in a hardcoded token list and not using a remote URL. We also simplify the token list component by removing extra token information like the symbol, decimals etc that are not relevant for the rust code.
CI
> Refactor token list module

- Cargo.lock
- crates/e2e/tests/e2e/colocation_univ2.rs
- crates/solver/src/liquidity.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/naive_solver.rs
- crates/solvers/Cargo.toml
- crates/solvers/src/boundary/mod.rs
- crates/solvers/src/boundary/naive.rs
- crates/solvers/src/domain/liquidity/constant_product.rs
- crates/solvers/src/domain/mod.rs
- crates/solvers/src/domain/naive.rs
- crates/solvers/src/domain/order.rs
- crates/solvers/src/infra/cli.rs
- crates/solvers/src/run.rs
- crates/solvers/src/tests/baseline/direct_swap.rs
- crates/solvers/src/tests/legacy/attaching_approvals.rs
- crates/solvers/src/tests/legacy/jit_order.rs
- crates/solvers/src/tests/legacy/market_order.rs
- crates/solvers/src/tests/mod.rs
This PR adds the naive solver to the `solvers` crate. It turned out to be harder than anticipated because the naive solver implementation is tightly coupled with the `Settlement` type.
Since the code is fairly simple, I hope to move the logic into the `domain` as soon as possible (hence the test coverage from #1233), especially considering since most of the bugs stem from the fact that we are mixing `LimitOrder` "synthetic" orders with `Order` "signed" orders (and all the weird cases related to custom prices, and synthetic order amounts).
Tests are included in #1233.
> Boundary Naive Solver Implementation

- crates/solvers/src/tests/balancer/market_order.rs
- crates/solvers/src/tests/balancer/mod.rs
- crates/solvers/src/tests/balancer/not_found.rs
- crates/solvers/src/tests/balancer/out_of_price.rs
- crates/solvers/src/tests/baseline/direct_swap.rs
- crates/solvers/src/tests/dex.rs
- crates/solvers/src/tests/legacy/attaching_approvals.rs
- crates/solvers/src/tests/legacy/jit_order.rs
- crates/solvers/src/tests/legacy/market_order.rs
- crates/solvers/src/tests/legacy/mod.rs
- crates/solvers/src/tests/mod.rs
- crates/solvers/src/tests/naive/extract_deepest_pool.rs
- crates/solvers/src/tests/naive/filters_out_of_price_orders.rs
- crates/solvers/src/tests/naive/limit_order_price.rs
- crates/solvers/src/tests/naive/matches_orders.rs
- crates/solvers/src/tests/naive/reserves_too_small.rs
- crates/solvers/src/tests/naive/rounds_prices_in_favour_of_traders.rs
- crates/solvers/src/tests/naive/swap_less_than_reserves.rs
- crates/solvers/src/tests/naive/without_pool.rs
This PR adds E2E tests to the ported Balancer SOR solver.
Nothing too crazy happening here. I also moved the `tempfile` logic out of `create_temp_config_file` into the `tests::SolverEngine` creation in order to make it easier to reuse for future solvers.
Added a `dex::setup` API mock for mocking external DEX HTTP APIs. I made it accept bothe `GET` and `POST` methods right off the bat as they will be needed for other DEX aggregator API solvers.
🥄
> Add Balancer SOR Solver E2E Tests

- crates/autopilot/src/lib.rs
- crates/autopilot/src/limit_orders/quoter.rs
- crates/autopilot/src/solvable_orders.rs
- crates/e2e/tests/e2e/colocation_univ2.rs
- crates/e2e/tests/e2e/eth_flow.rs
- crates/e2e/tests/e2e/eth_integration.rs
- crates/e2e/tests/e2e/limit_orders.rs
- crates/e2e/tests/e2e/local_node.rs
- crates/e2e/tests/e2e/onchain_components.rs
- crates/e2e/tests/e2e/onchain_settlement.rs
- crates/e2e/tests/e2e/order_cancellation.rs
- crates/e2e/tests/e2e/refunder.rs
- crates/e2e/tests/e2e/services.rs
- crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
- crates/e2e/tests/e2e/vault_balances.rs
- crates/orderbook/src/run.rs
- crates/shared/src/arguments.rs
- crates/shared/src/current_block.rs
- crates/solver/src/arguments.rs
- crates/solver/src/run.rs
- crates/solver/src/settlement_access_list.rs
- crates/solver/src/settlement_ranker.rs
- crates/solver/src/settlement_submission/submitter.rs
This PR makes all e2e tests use the library run functions instead of manually creating components. This separates the test from the code more which will help future refactoring and makes the tests more extensive because the components are run just like they are as standalone binaries.
As a side effect many tests become simpler. There is potential for a lot more e2e improvements after this but I didn't want to put more than necessary in this PR.
E2e tests become slower because we can no longer drive individual components at the exact moment it is needed. Instead some checks have to be converted to polling with the `wait_for_condition` function. Running all tests on CI goes from 90s to 120s. This is not a big deal. There are low hanging fruits to speed tests up and eventually the plan is to …
> Refactor e2e tests to use crate run functions

- crates/e2e/tests/e2e/services.rs
- crates/solver/src/arguments.rs
My e2e refactor added a default to the argument. This is problematic because in shadow mode we don't want any such node and it is hard to set the argument to no value with clap.
see that CI succeeds
> Fix transaction-submission-nodes driver argument

- crates/solvers/src/domain/dex/mod.rs
- crates/solvers/src/domain/dex/slippage.rs
- crates/solvers/src/infra/dex/mod.rs
- crates/solvers/src/infra/dex/zeroex/dto.rs
- crates/solvers/src/infra/dex/zeroex/mod.rs
Similar to #1234, this PR ports the 0x API to the `solvers` crate.
Nothing too special, although we make use of the `reqwest::RequestBuilder::query(q: impl serde::Serialize)` to avoid manual serialization code 🎉.
Additionally, I added some (hopefully) more complete documentation to the DTOs with links to the online documentation. I also removed fields that we don't need/use to keep the DTOs as slim as possible.
No E2E test quite yet. However, a manual test can be run:
<details><summary><code>manual-test.patch</code></summary>
```diff
diff --git a/crates/solvers/src/infra/dex/zeroex/mod.rs b/crates/solvers/src/infra/dex/zeroex/mod.rs
index 287385da..d2ff7ce3 100644
--- a/crates/solvers/src/infra/dex/zeroex/mod.rs
+++ b/crates/solvers/src/infra/dex/zeroex/mod.rs
@@ -190,3 +190,55 @@ impl …
```
> Port 0x Api

- crates/refunder/src/refund_service.rs
Makes error message more readable, as suggested by Martin when [we saw it in the alerts](https://cowservices.slack.com/archives/C037PB929ME/p1677142527169469).
I just confirmed that debug printing H256 looks good:
```
let order_hash = [
223, 233, 185, 202, 128, 197, 77, 101, 90, 198, 129, 33, 192, 78, 11, 250, 201, 191, 1,
211, 166, 49, 250, 113, 169, 224, 81, 185, 214, 166, 7, 25,
];
tracing::error!("{:?}", H256(order_hash));
```
prints
```
2023-02-23T10:58:25.131Z ERROR refunder: 0xdfe9b9ca80c54d655ac68121c04e0bfac9bf01d3a631fa71a9e051b9d6a60719
```
> More readable order hash in error message

- crates/driver/example.toml
Use obviously fake PKs in example configuration to avoid confusion.
> Use Obviously Wrong Private Keys in Example Config

- crates/driver/src/infra/cli.rs
We don't need debug logs for all crates like arbitrary dependencies.
n/a
> Change driver default log filter

- crates/shared/src/balancer_sor_api.rs
Balancer sometime sends empty responses leading to these logs:
```
2023-02-27T07:44:20.562Z  WARN auction{id=5699489 run=7891}: solver::solver::single_order_solver: Solver BalancerSOR error: EOF while parsing a value at line 1 column 0
```
In the past this usually meant that we got a 429 (rate limiting) error. This PR starts logging the status code and preemptively adds a nicer error message for that case.
CI
> Balancer response status code

- crates/driver/src/infra/config/file/load.rs
- crates/solvers/src/infra/config/balancer/file.rs
- crates/solvers/src/infra/config/baseline/file.rs
- crates/solvers/src/infra/config/legacy.rs
- crates/solvers/src/infra/config/zeroex/file.rs
Fixes #1266 
Printing the exact TOML parsing error is helpful to quickly fix your syntax but unfortunately it can also reveal secrets like a private key or api keys.
Unfortunately there is also a way to expose secrets with the `Display` formatted version of the error. It's more difficult to expose secrets with that but we should probably not take the risk and drop the TOML parsing error altogether.
Before (text includes private key):
```
thread 'main' panicked at 'TOML syntax error while reading "../driver.toml": Error { inner: Error { inner: TomlError { message: "expected `.`, `=`", original: Some("disable-access-list-simulation = true\nmiep\n\n[[solver]]\nname = \"cowdexag\"\nendpoint = \"http://0.0.0.0:7872\"\nabsolute-slippage = \"1000000000000000000\" # Denominated in wei, …
```
> Omit toml parsing error details for secrecy

- crates/autopilot/src/run_loop.rs
- crates/driver/openapi.yml
Closes https://github.com/cowprotocol/services/pull/1268 . Nick suggested that an empty solution can be indicated by using a 0 score. This makes sense to me. This means Driver doesn't need to change. Although I'm not sure if Driver assigns nonzero score to solutions that only settle liquidity orders, in which case a change should still be done.
colocation e2e test still works
> Colocation: Do not execute empty solutions

- crates/autopilot/src/database/auction_prices.rs
- crates/autopilot/src/database/on_settlement_event_updater.rs
- crates/autopilot/src/decoded_settlement.rs
- crates/autopilot/src/on_settlement_event_updater.rs
- crates/autopilot/src/solvable_orders.rs
- crates/database/src/auction_prices.rs
- crates/model/src/solver_competition.rs
- crates/orderbook/src/database/solver_competition.rs
- crates/shared/src/http_solver/model.rs
- crates/solver/src/driver.rs
- crates/solver/src/settlement_rater.rs
Fixes https://github.com/cowprotocol/services/pull/1279#discussion_r1118812860
Decision was made to simplify the insertion of the auction external prices. Now we do it from the driver instead of autopilot. 
Additionally, changes score multiplication factor to be an absolute value - score discount.
> SolverRewards 6: Populate external prices from driver

- crates/autopilot/src/decoded_settlement.rs
- crates/autopilot/src/on_settlement_event_updater.rs
Fixes https://github.com/cowprotocol/services/pull/1279#discussion_r1118787688
Core change: 
```
let executed_amount = match order.data.kind {
OrderKind::Buy => order.metadata.executed_buy_amount,
OrderKind::Sell => order.metadata.executed_sell_amount_before_fees,
},
```
> SolverRewards 8: Fix executed amount for fee calculation

- crates/e2e/tests/e2e/colocation_univ2.rs
- crates/e2e/tests/e2e/eth_flow.rs
- crates/e2e/tests/e2e/eth_integration.rs
- crates/e2e/tests/e2e/limit_orders.rs
- crates/e2e/tests/e2e/onchain_settlement.rs
- crates/e2e/tests/e2e/order_cancellation.rs
- crates/e2e/tests/e2e/refunder.rs
- crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
- crates/e2e/tests/e2e/setup/mod.rs
- crates/e2e/tests/e2e/setup/services.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
- crates/e2e/tests/e2e/vault_balances.rs
Fixes https://github.com/cowprotocol/services/issues/1223 .
The last two failures were cases where simulating the transactions in solver::driver took surprisingly long. Without more detail I'm guessing this is hardhat being slow on Github CI and not a bug in our code. To fix it I change the timeout of all wait_for_condition from 10 s to 30 s.
CI e2e tests
> Increase e2e test wait_for_condition timeouts

- crates/shared/src/oneinch_api.rs
Right now 1Inch responses only get logged if tracing is enabled. Since this is currently not enabled we don't get to see what caused these [parsing errors](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-28T21:31:14.884Z',to:'2023-03-01T09:00:00.000Z'))&_a=(columns:!(log),filters:!(),grid:(columns:('@timestamp':(width:164))),index:'6eecf430-220f-11ed-bbdc-2f476b18353d',interval:auto,query:(language:kuery,query:'log:%20%22solver::solver::single_order_solver:%20Solver%201Inch%22%20or%20log:%20%22response%20from%201inch%20api%22'),sort:!(!('@timestamp',desc)))).
We could simply enable trace logs again but that would be quite noisy and AFAIK we currently have to avoid putting to much pressure on …
> Always log 1Inch parsing errors

- crates/autopilot/src/database/on_settlement_event_updater.rs
- crates/autopilot/src/on_settlement_event_updater.rs
All settlement events are indexed by both staging and production databases.
However, auctions only exist in one of the environments.
This PR inserts settlement observations only if the auction exist.
Thanks @MartinquaXD for figuring out the issue. I did have the same issue when ran CIP20 changes locally, but thought it is because of running the local db. :/
> SolverRewards 9: Update settlement details if exist

- crates/solver/src/driver.rs
If we have 2 best solutions with identical scores, I don't want to mess them up sorting with `unstable`.
Also adding solver competition log (temporarily since we have issues with the database in staging right now).
> SolverRewards 10: Fix score sorting

- crates/autopilot/src/arguments.rs
- crates/autopilot/src/lib.rs
- crates/e2e/tests/e2e/setup/services.rs
- crates/orderbook/src/arguments.rs
- crates/orderbook/src/run.rs
Fixes https://github.com/cowprotocol/services/issues/1288 
This PR adds/changes flags for controlling limit orders. We can independently control fill or kill and partially fillable. fill or kill is enabled by default.
CI
> Add command line arguments to control limit orders

- crates/autopilot/src/arguments.rs
- crates/e2e/tests/e2e/colocation_univ2.rs
- crates/e2e/tests/e2e/setup/services.rs
- crates/orderbook/src/arguments.rs
- crates/shared/src/arguments.rs
By default a clap bool argument is disabled and enabled when the flag is specified like `--foo`. This makes it impossible to define a flag that is default enabled while also being able to be manually turned off with something like `--foo=false`. In this  PR I change all bool arguments to require passing in a value. This is  more consistent with how other arguments are parsed and more flexibly because it allows default enabled. This changes that that a plain `--foo` without value is not longer accepted, which is fine.
CI
I have checked that the cluster is fine because it uses environment variables, which always needed a manual `=true`.
> Improve bool argument handling

- crates/autopilot/src/decoded_settlement.rs
- crates/autopilot/src/on_settlement_event_updater.rs
Adding temporary logs for fee calculation.
For tx hash 0xa0adf944224c3cda52dfb98e072dd98cb70f3eecb1fc2c8447644c2d70055ecf we get different fees when we compare:
1. what Solver competition endpoint returns
2. what OnSettlementEventUpdater calculated
3. what manual calculation returns using bare db values
I noticed that `full_fee_amount` is different for order when used `https://barn.api.cow.fi/docs/#/default/get_api_v1_orders__UID_` vs manually querying the staging db (super weird).
> SolverRewards: Add temporary logs

- crates/shared/src/bad_token/trace_call.rs
Fixes a small formatting issue that I noticed when investigating a bad token.
None.
> Fix bad token format errors

- crates/shared/src/bad_token/trace_call.rs
Fixed one more log where `format!()` wasn't used.
Altered one log slightly to make it more easily grepable.
CI
> More fixes for token quality logs

- crates/orderbook/src/arguments.rs
- crates/orderbook/src/run.rs
- crates/shared/src/order_validation.rs
Part of https://github.com/cowprotocol/services/issues/1289 .
- Use config option for allowing partially fillable limit orders.
- Slightly refactor code.
- Logic change: Previously, when limit orders were disabled and an order with 0 fee was placed, it was automatically converted into a market order and validated as such. This is changed to continue to treat the order as a limit order which fails validation because limit orders are disabled. I'm not sure what the motivation for the previous way of doing things is.
modified tests
> Handle partially fillable limit orders in order validation

- crates/autopilot/src/solvable_orders.rs
- crates/model/src/order.rs
- crates/orderbook/openapi.yml
This field serves no purpose. We are soon going to need a new similar field to communicate the available balance for partially fillable orders. I want to give the new field a different name to avoid confusion.
Potential problems:
Is the frontend using this field? After grepping their repos for this field, I don't think so.
CI
> Deprecate order meta data available balance

- crates/driver/src/domain/competition/solution/mod.rs
- crates/driver/src/domain/competition/solution/trade.rs
- crates/driver/src/tests/cases/limit_order/buy.rs
- crates/driver/src/tests/cases/limit_order/mod.rs
- crates/driver/src/tests/cases/limit_order/sell.rs
- crates/driver/src/tests/cases/verify_asset_flow/limit.rs
- crates/driver/src/tests/cases/verify_asset_flow/liquidity.rs
- crates/driver/src/tests/cases/verify_asset_flow/market.rs
- crates/driver/src/tests/cases/verify_asset_flow/mod.rs
Add some tests for the `driver` limit orders. Covers a new test for buy limit orders and some tests for asset flow verification.
Tests.
> `driver`: limit order tests

- crates/solver/src/arguments.rs
- crates/solver/src/driver.rs
- crates/solver/src/run.rs
- crates/solver/src/settlement_ranker.rs
Parameter `auction_rewards_activation_timestamp` defines the time when we switch to ranking the solutions by score.
Current plan is the following:
1. This PR becomes part of the next week release which is applied on Monday 13th of March.
2. 14th of March at 00.00am ranking by score is activated.
3. 14th of March at ~ 09.00am solver rewards script is executed for the past week ending with 14th of March 00.00am (ranking by objective_value)
4. 21st of March at ~ 09.00am solver rewards script is executed for the dates 14-21 March (ranking by score).
With this change, there is no need to do configuration changes (apply release) on 14th of March at 00.00am.
~One concern I have is the timezone considered by solver rewards script. @bh2smith do you know which one is used? Here I assumed Utc.~
> Activate auction rewards based on timestamp

- crates/autopilot/src/decoded_settlement.rs
- crates/autopilot/src/on_settlement_event_updater.rs
In case we index a transaction initiated by solver that ends up emitting `Settlement` event but is not a standard transaction calling `settle`, we want to add entry to `settlement_observations` table with all zeros. Currently this fails and `on_settlement_event_updater` is crash looping. 
More context how this happened: https://cowservices.slack.com/archives/C0361CDD1FZ/p1678983343723179
> Fix decoding settlement

- crates/solver/src/solver/http_solver/settlement.rs
Forwards score provided by solvers to settlement creation.
Unfortunately, using `Option` and `mut settlement` while building the settlement prevented rust compiler to help me catch this.
> CIP20: Forward score to settlement creation

- crates/shared/src/http_solver/model.rs
- crates/solver/src/arguments.rs
- crates/solver/src/driver.rs
- crates/solver/src/metrics.rs
- crates/solver/src/run.rs
- crates/solver/src/settlement_ranker.rs
Do not consider non-positive zero score settlements for solver competition.
Settlement has non-positive score in two cases
- solver provided zero score
- solver did not provide score -> fallback to objective_value which is negative or zero (with or without discount doesn't matter)
Put under parameter so we can easily disable this if there are a lot of auctions with no positive winner score.
> CIP20: Filter out non-positive score settlements

- crates/shared/src/code_simulation.rs
- crates/shared/src/price_estimation.rs
- crates/shared/src/price_estimation/factory.rs
Fixes #1341 
This PR introduces a web3 trade simulator that falls back to Tenderly on failures. One pain-point of using the `Web3` simulator is that it makes debugging failed simulations very hard. This PR introduces a fallback mechanism such that only failed simulations go to Tenderly. This way, we save Tenderly credits but keep debugging easy!
Manual test, was able to create a [simulation on Tenderly](https://dashboard.tenderly.co/public/safe/safe-apps/simulator/7dec4cdd-ab30-4b9d-93c4-2d5883364803) for debugging.
> Introduce Web3 Code Simulator with Tenderly Fallback

- crates/solver/src/settlement_access_list.rs
- crates/solver/src/settlement_ranker.rs
- crates/solver/src/settlement_rater.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/settlement_submission/dry_run.rs
Fixes https://github.com/cowprotocol/services/pull/924 which is not working properly. 
Let's observe the example:
```
max_fee: 200
max_tip: 5
base_fee: 100
```
When the node executes the `eth_estimateGas` with the given gas price, it uses `effective_gas_price` to check if account balance is enough to execute the transaction. In this case, effective gas price is 105.
The code `let gas_price = gas_price.bump(SOLVER_BALANCE_MULTIPLIER)` only bumps the `max_tip`, so the effective gas price is now 115 (which is not want we want).
This PR fixes this so the effective gas price after bumping is 525.
Related to the [issue](https://cowservices.slack.com/archives/C036PMLUPQF/p1678625544766379?thread_ts=1678615853.015859&cid=C036PMLUPQF) we had with Raven solver when it ran out of funds during a …
> Fix bumping the gas price for simulation

- crates/driver/src/boundary/settlement.rs
- crates/driver/src/domain/competition/auction.rs
- crates/driver/src/domain/eth/gas.rs
- crates/driver/src/domain/eth/mod.rs
- crates/driver/src/domain/quote.rs
- crates/driver/src/infra/blockchain/mod.rs
- crates/driver/src/infra/solver/dto/auction.rs
- crates/driver/src/tests/cases/limit_order/buy.rs
- crates/driver/src/tests/cases/limit_order/sell.rs
- crates/driver/src/tests/cases/quote.rs
- crates/driver/src/tests/cases/settle.rs
- crates/driver/src/tests/cases/solve.rs
- crates/driver/src/tests/cases/verify_asset_flow/limit.rs
- crates/driver/src/tests/cases/verify_asset_flow/liquidity.rs
- crates/driver/src/tests/cases/verify_asset_flow/market.rs
- crates/driver/src/tests/cases/verify_internalization.rs
- crates/driver/src/tests/setup/blockchain/mod.rs
Related to #1360
This PR makes the driver EIP-1559 aware internally. Previously, it would just make use of `effective_gas_price` everywhere. However, there are EIP-1559 specific requirements that require a more complete gas estimate picture.
This PR is a required step for implementing #1360 and fixing account balance checks before committing to a settlement.
Unit tests continue to pass after adjusting for new gas price estimates. Note that `eth_gasPrice` RPC call is different than an EIP-1559 price estimate, which we do using the `gas_estimation::NativeGasEstimator` crate.
I also change E2E tests that assert a specific score to also assert a specific effective gas price, since the two are correlated.
> Make Driver EIP-1559 Aware

- Cargo.lock
- crates/autopilot/src/database/onchain_order_events.rs
- crates/autopilot/src/solvable_orders.rs
- crates/database/src/ethflow_orders.rs
- crates/database/src/orders.rs
- crates/database/src/quotes.rs
- crates/driver/Cargo.toml
- crates/e2e/tests/e2e/eth_flow.rs
- crates/e2e/tests/e2e/refunder.rs
- crates/model/src/order.rs
- crates/orderbook/src/api/post_quote.rs
- crates/shared/src/order_quoting.rs
- crates/shared/src/zeroex_api.rs
- crates/solver/src/arguments.rs
- crates/solvers/Cargo.toml
Out of curiosity I ran `cargo audit` to see if there are any known vulnerabilities. This showed a few that could be easily fixed by running `cargo update`.
One exception was `chrono` which used by default an old version of the `time` crate. To fix that I needed to add `default-features = false` where we didn't import `chrono` from the workspace. This resulted in a few deprecation warnings that I fixed.
The deprecated functions that could panic got replaced with functions that returned `None` instead.
Since using the default resulted in such surprising behavior of `chrono` I guess it would make sense if we always used `default-features = false` and always explicitly list all the features we intend to use.
compiler, CI
> Audit and update dependencies

- crates/solver/src/settlement_rater.rs
- crates/solver/src/settlement_submission.rs
- crates/solver/src/settlement_submission/submitter.rs
- crates/solver/src/solver.rs
Together with #1363 this supersedes #1361.
#1363 introduced a change where we compute the absolute maximum `max_fee_per_gas` we are willing to pay per solver run. With that change, we can now, deterministically, decide upfront if a solver account has sufficient Ether to submit a settlement accounting for gas spikes.
Historically, we relied on `eth_estimateGas` RPC call failing when a solver had insufficient funds, however, this behavior is node-dependent and cannot be relied on (See https://github.com/cowprotocol/services/pull/1361#issuecomment-1477951819 for more details).
In this PR we change the settlement raking to additional query solver balances and ensure that the settlement can be executed even if the `max_fee_per_gas` is charged.
The equivalent fix in the co-located driver was …
> Verify Solver Account Balances

- crates/solvers/src/infra/config/balancer/mod.rs
- crates/solvers/src/infra/config/dex/balancer/file.rs
- crates/solvers/src/infra/config/dex/balancer/mod.rs
- crates/solvers/src/infra/config/dex/file.rs
- crates/solvers/src/infra/config/dex/mod.rs
- crates/solvers/src/infra/config/dex/zeroex/file.rs
- crates/solvers/src/infra/config/dex/zeroex/mod.rs
- crates/solvers/src/infra/config/mod.rs
- crates/solvers/src/infra/config/zeroex/mod.rs
- crates/solvers/src/run.rs
- crates/solvers/src/tests/balancer/mod.rs
- crates/solvers/src/tests/zeroex/mod.rs
- crates/solvers/src/tests/zeroex/options.rs
Reorganized the directory structure responsible for loading configs for dex solvers to be more in line with the file structure of their logic.
This makes it so that config loading and the solver implementation are composed of 2 parts.
1. logic that is shared across all dex solvers
2. logic that only relates to each solver's dex API
Also adds a new argument which controls how we handle partially fillable orders required for [this](https://github.com/cowprotocol/services/pull/1358#issuecomment-1479201711).
CI
> Reorganize dex solver config loading

- crates/solver/src/liquidity/order_converter.rs
This PR changes the order converter to not require surplus fees for partially fillable limit orders.
Alerts will go away in barn.
> Don't Error on Partially Fillable Limit Order Missing Surplus Fee

- crates/autopilot/src/lib.rs
- crates/orderbook/src/run.rs
- crates/solver/src/run.rs
Fixes #1336.
@sunce86 discovered that, when Uniswap V3 fails to initialize, we will have an alert but just continue running the services with Uniswap V3 liquidity (despite it being configured).
This PR changes the initialization logic to crash on such event. This makes it:
1. A much louder error, less likely to go unnoticed. If pods start crash-looping, then UniV3 liquidity can always be disabled, making resolving this issue also more explicit (i.e. the on-call will know if we are running without UniV3).
2. More in line with the configuration, so if you configure Uniswap V3 liquidity, you will have Uniswap V3 liquidity
CI
> Crash on Failed UniV3 Initialization

- crates/driver/src/infra/solver/dto/solution.rs
- crates/shared/src/http_solver/model.rs
- crates/shared/src/price_estimation/http.rs
- crates/solver/src/solver/http_solver/settlement.rs
- crates/solvers/openapi.yml
Trivial PR that splits out from #1366 the new fields in the solution DTOs required for including fee amounts from external solvers. This will be needed by the Gnosis solvers for communicating the solver fees.
Rust compiler.
> Add Solver Fee Fields to DTOs

- crates/solvers/src/api/dto/solution.rs
- crates/solvers/src/boundary/legacy.rs
- crates/solvers/src/boundary/naive.rs
- crates/solvers/src/domain/auction.rs
- crates/solvers/src/domain/dex/mod.rs
- crates/solvers/src/domain/dex/slippage.rs
- crates/solvers/src/domain/order.rs
- crates/solvers/src/domain/solution.rs
- crates/solvers/src/domain/solver/baseline.rs
- crates/solvers/src/domain/solver/dex/solver.rs
- crates/solvers/src/tests/dex/mod.rs
- crates/solvers/src/tests/dex/partial_fill.rs
- crates/solvers/src/tests/dex/wrong_execution.rs
- crates/solvers/src/util/math.rs
- crates/solvers/src/util/mod.rs
Fixes #1292.
This PR adds surplus fee computation to the DEX solvers for partially fillable limit orders. In particular, it also adjusts the limit prices so that the UCP reflects the "actual traded amounts" without the fees.
Added E2E tests for partially fillable limit order fee logic.
> Solver Computed Surplus Fees

- crates/e2e/tests/e2e/colocation_univ2.rs
- crates/solvers/config/example.baseline.toml
- crates/solvers/src/boundary/baseline.rs
- crates/solvers/src/domain/dex/mod.rs
- crates/solvers/src/domain/solution.rs
- crates/solvers/src/domain/solver/baseline.rs
- crates/solvers/src/domain/solver/dex/solver.rs
- crates/solvers/src/infra/config/baseline/file.rs
- crates/solvers/src/infra/config/baseline/mod.rs
- crates/solvers/src/run.rs
- crates/solvers/src/tests/baseline/mod.rs
- crates/solvers/src/tests/baseline/partial_fill.rs
In the context of co-location, the Baseline solver is treated differently than DEX aggregator solves (mostly because it is synchronous and fast and doesn't have to deal with many things like rate limiting, etc.).
Because of this, we can have a specialized implementation for partially fillable orders where we attempt multiple swaps at different prices in a single `solve` loop instead of doing it over multiple auctions.
Added an E2E test that successfully solves a partially fillable limit order with the baseline solver 🎉.
> Support Partially Fillable Orders in Baseline

- crates/solver/src/solver/balancer_sor_solver.rs
- crates/solver/src/solver/oneinch_solver.rs
- crates/solver/src/solver/paraswap_solver.rs
- crates/solver/src/solver/single_order_solver.rs
- crates/solver/src/solver/zeroex_solver.rs
This PR extends the `SingleOrderSolver` interface to provide a gas estimate along with its single order solution.
Compiler
> Extend SingleOrderSolver Interface With Gas Estimate

- Cargo.lock
- crates/shared/Cargo.toml
- crates/shared/src/arguments.rs
- crates/shared/src/external_prices.rs
- crates/solver/src/arguments.rs
- crates/solver/src/run.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/single_order_solver.rs
- crates/solver/src/solver/single_order_solver/fills.rs
- crates/solver/src/solver/zeroex_solver.rs
This PR ports some of the logic from the co-located solver into the legacy solver. Namely:
- Managing fills between solver runs
- Computing settlements given a single order settlement and gas price estimates.
Since the math for the latter is quite tricky, I added a unit test to verify things are working as expected.
Added a unit test. Full partially fillable E2E test coming up.
> Port Partial Fills to Legacy Solver

- crates/solver/src/liquidity/slippage.rs
- crates/solver/src/solver/baseline_solver.rs
- crates/solver/src/solver/single_order_solver.rs
- crates/solvers/src/domain/solver/baseline.rs
This PR ports the changes from #1390 to the legacy baseline solver.
Existing baseline solver tests (unit and E2E) continue to pass, so nothing appears to be broken. E2E in a follow up PR.
> Port Partial Fills to Legacy Baseline

- crates/autopilot/src/arguments.rs
- crates/e2e/tests/e2e/colocation_partial_fill.rs
- crates/e2e/tests/e2e/partially_fillable.rs
- crates/solver/src/arguments.rs
- crates/solver/src/driver.rs
- crates/solver/src/run.rs
We had an issue where the driver crashed on a partially fillable order. It makes more sense to control this feature in the driver than in the autopilot.
compiles, e2e tests still work
> Add flag to driver controlling partially fillable orders

- crates/shared/src/http_solver/model.rs
- crates/solver/src/settlement_ranker.rs
Solver team decided to filter out the scores that are too high (breaking the social consensus).
Whole explanation can be read here https://cowservices.slack.com/archives/C035N0YEB6J/p1680111646093119
> CIP20: Filter out too high scores

- crates/solver/src/solver/single_order_solver.rs
- crates/solver/src/solver/single_order_solver/fills.rs
- crates/solvers/src/domain/solver/dex/fills.rs
- crates/solvers/src/domain/solver/dex/solver.rs
- crates/solvers/src/tests/dex/partial_fill.rs
It's possible that a partially fillable order can only be solved for a small portion with the given liquidity. We'll try lower and lower amounts until we eventually find that fill amount. If then some big trade happens on-chain which lowers the price on a key liquidity pool it could be that a way bigger partial fill is then possible.
In order to find out we need to increase the tried fill amount after a successful attempt. This was originally suggested by @fedgiac [here](https://github.com/cowprotocol/services/pull/1358#pullrequestreview-1354254330).
One unfortunate thing is that this also causes us to flip-flop between finding some solution and finding no solution in case no new liquidity appeared and we just happened to find the biggest possible fill amount. I hope this is not a huge …
> Increase partial fill attempt after success

- crates/solver/src/solver/naive_solver.rs
Filters out partially fillable limit orders in the `NaiveSolver` until we properly support computing a reasonable `solver_fee` for them. Discussed in [here](https://cowservices.slack.com/archives/C0361CDD1FZ/p1680600757352139?thread_ts=1680598458.372809&cid=C0361CDD1FZ) and tracked in #1414.
compiler
> Filter out partially fillable limit orders in NaiveSolver

- crates/database/src/orders.rs
We noticed a partially fillable [order](https://barn.api.cow.fi/mainnet/api/v1/orders/0x514a80473dc24034a1983ec831603f2f100ad7defd1578b077c637f73f3b92ecffab14b181409170378471b13ff2bff5be012c646434b605) had a surplus fee set, which confused a solver. The reason is that the code that updates FOK limit order surplus fees together didn't filter out partially fillable orders.
did not adjust test
> Do not update surplus fee of partially fillable orders

- crates/orderbook/openapi.yml
I've noticed that the solver competition path is outdated and I tried to fill in the blanks.
Double check that my changes match the code.
You can plop `crates/orderbook/openapi.yml` into [this website](https://editor.swagger.io/) to see the new changes.
<details><summary>Resulting schema</summary>
</details>
> Update OpenAPI solver competition path

- crates/solver/src/liquidity/order_converter.rs
- crates/solver/src/solver/single_order_solver.rs
This PR fixes a panic that was happening because of a "divide by 0" in the single order solver prioritization logic. It does so in two ways:
- First, it adjusts the code to no longer panic on 0 amounts. In theory, the `native_buy_amount` should never really be 0, but dealing with the case is very simple, so I decided to handle it defensively.
- Second, we now discard partially fillable orders where one of the amounts scale to 0. This can happen in cases where the target amount (i.e. buy amount for sell orders, sell amount for buy orders) has a smaller value than the side amount, and the order is mostly filled. Most of our code assumes orders without 0 amounts, so we should not produce limit orders with these amounts anywhere.
Added unit tests to verify logic changes.
> Fix Divide By Zero Panic

- Cargo.lock
- crates/autopilot/src/decoded_settlement.rs
- crates/database/Cargo.toml
- crates/database/src/events.rs
- crates/database/src/orders.rs
Fixes #1437 
@fhenneke highlighted some discrepancies in the computed observed fees and the actual solver fees for any given settlement.
This is the result of two issues:
- the `executedAmount` encoded in a trade in a settlement transaction **gets ignored** for fill or kill orders. As such, it is not correct to compare these amounts when matching orders. This shouldn't be an issue with the fee `fold` logic, the `solver_fee` amount is the same for each FoK order execution (for which there should be exactly 1).
- The computed total `executedAmount` for an order was using the `executedSellAmountWithFees` and not the simple `executedSellAmount`, as such it was computing an incorrect total executed amount for sell orders.
This PR addresses those two issues.
Added a unit tests to verify that …
> Fix Order Execution to Trade Matching

- crates/shared/src/order_validation.rs
This PR relaxes the pre-sign balance check exception to also include `TransferFailed`. From looking at the [initial PR that added this exception](https://github.com/gnosis/gp-v2-services/pull/1587) there is no indication of why this would be an issue.
This will enable special orders with "virtual" balances (such as Agave flash loan orders) to work with the API.
CI
> Relax PreSign Balance Exception

- crates/solver/src/driver_logger.rs
- crates/solver/src/settlement_submission.rs
We currently are estimating transactions with and without access lists for cancelled transactions which is negatively impacting our access list metrics.
However, it does not make sense to do this - cancelled transactions don't pay for access lists, so it should not impact the total performance of including vs not including access lists.
CI
> No Simulation for Cancelled Settlement Transactions

- crates/autopilot/src/database/orders.rs
- crates/autopilot/src/on_settlement_event_updater.rs
- crates/database/src/orders.rs
Fixes #1443.
FoK limit orders can solver fee amount changes per auction. In the case where a limit order is included in solutions from different auctions where the first ones fail to mine, we are left with multiple entries in the `order_execution` table for the same FoK limit order, with potentially different `solver_fee` values.
The current query does not take this into account and would potentially select the `solver_fee` from the wrong auction when computing the observed settlement score.
This PR fixes this by passing in an `auction_id` to the query so only the correct order execution entries are used. Note that **we pass the `auction_id` in** instead of joining tables (like we do in 79f69a7ccc9408bd2e3f91f805c4b5542f52dbb5) because the `auction_transaction` and `settlements` are not …
> Match Order Executions To Auction ID

- crates/shared/src/paraswap_api.rs
- crates/solver/src/solver/balancer_sor_solver.rs
- crates/solver/src/solver/oneinch_solver.rs
- crates/solver/src/solver/paraswap_solver.rs
- crates/solver/src/solver/single_order_solver.rs
- crates/solver/src/solver/zeroex_solver.rs
Follow up to #1310
This PR introduces rate limit handling for the single order solvers. This is introduced as single order solvers occasionally enter "rate limiting spiral of death". Specifically, our orderbook is very large, and in the event we start getting rate limited, we tend to spam every single order to the DEX API as we run through the entire orderbook to try to solve (this is because round-tripping when getting rate limited is very quick).
To combat this, we now have back-off strategies in our single order solvers.
CI and existing unit tests.
Configured rate limiting strategy in staging.
> Add Rate Limiting Support to Single Order Solvers

- crates/shared/src/http_solver/model.rs
- crates/solver/src/settlement_rater.rs
Increases the reported block number by 1 to avoid misunderstanding (with external solvers) of the block height on which the simulation was done. 
At the same time, `tx_index` is explicitly provided.
Discussion: https://cowservices.slack.com/archives/C036JAGRQ04/p1682065321347269
> Adjust the simulation block number

- crates/refunder/src/refund_service.rs
- crates/shared/src/api.rs
- crates/shared/src/balancer_sor_api.rs
- crates/shared/src/http_solver/model.rs
- crates/shared/src/subgraph.rs
- crates/solver/src/solver/optimizing_solver.rs
As usual the new rust version comes with new clippy lints.
Running `cargo clippy --fix` took care of all warnings.
CI
> Fix new clippy warnings

- crates/solver/src/solver/score_computation.rs
Fixes https://github.com/cowprotocol/services/issues/1453
I thought about putting the change under the configuration parameter, but it seems like it's not needed since we are going to use MEVBlocker permanently. Also, new parameter would need to be coupled somehow with the transactions submission strategy parameters (every time we need to update the submission configuration we would potentially need to also remember to update the configuration for score calculator).
@harisang can you double check that the unit test change is correct? Now the score is slightly increased.
> Adjust score calculator for reverts

- crates/solver/src/arguments.rs
- crates/solver/src/run.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/http_solver.rs
- crates/solver/src/solver/http_solver/settlement.rs
- crates/solver/src/solver/naive_solver.rs
@fleupold requested a hotfix to support an OTC trade on GC. This currently fails because solvers that could facilitate that trade (Naive, Quasimodo) are not participating in the solver competition because their solutions get discarded due to missing fees for partially fillable limit orders.
This PR adds a new CLI argument that either triggers a partially fillable trade without a fee to be discarded or sets the fee to 0.
compiler
> Allow missing fees on cheap chains

- crates/shared/src/price_estimation/factory.rs
In order to get even more data with https://github.com/cowprotocol/services/pull/1456 we can also collect the price prediction metrics for the native price estimator as it's not able to introduce any bias like the fast price estimator would.
This was really an oversight in the linked PR as I thought the native price estimator would already use the optimal price estimator under the hood. Should have verified that.
CI
> Enable quote predictions for native price estimator

- crates/solver/src/solver/single_order_solver.rs
In #1442 we introduced rate limiting logic to single order solvers. This was done to allow single order solvers to recover in the face of too many orders (single order solvers were entering a "death spiral", where at some point within an auction, it would get rate limited and continue single order solving for the remaining orders in the book, making the problem even worse).
The fix helped in that we are no longer sending requests to external APIs for some time when rate limited, however, it caused issues with the single order solver success metrics. Specifically, when a solver gets rate limited, it will fail all orders until the rate limit backoff timeout is done. This causes solvers that are being rate limited at some point in an auction to have inflated error numbers (since the single …
> Stop Rate Limited Single Order Solver

- crates/solver/src/driver.rs
- crates/solver/src/driver_logger.rs
- crates/solver/src/settlement_ranker.rs
- crates/solver/src/settlement_rater.rs
- crates/solver/src/solver.rs
We recently noticed that the `1Inch` solver does not compute a fee for partially fillable limit orders.
To fix that I want to be able to simulate a settlement in the context of the `SingleOrderSolver`. This will allow us to get the exact gas used for a given settlement and will enable a bunch of other nice things like knowing before settlement merging which solutions work and which are the best. This would allow us to trivially merge the best solutions across all dex solvers to have a single more competitive gnosis solver (which also respects the rules that every solver should only submit a single solution)
Because the `SingleOrderSolver` does not store a `dyn Solver` we can't pass that to the `SettlementRater`.
I saw 2 options:
1. Adjust the `SettlementRater` to not take a `dyn Solver` …
> Don't require a `dyn Solver` to simulate and rate a Settlement

- crates/shared/src/tracing.rs
Context https://github.com/cowprotocol/oncall/issues/13 .
`Backtrace::capture` doesn't capture a backtrace if the environment variable RUST_LIB_BACKTRACE is set to 0 because capturing a backtrace is slow.  This PR switches to `force_captures` which does what the name implies. This is fine because this code isn't performance sensitive because it only runs just before killing the process after a panic anyway.
> Always capture backtrace on panic

- crates/autopilot/src/solvable_orders.rs
In debugging timing/race conditions issues with auction building and event indexing (specifically, orders appearing in auctions after trades have already happened) - I added a few new logs to help with this.
Specifically, we now log when we update the `autopilot` solvable orders cache, as well as when we store the new auction in the database to be served by the orderbook API. This should help in debugging the aforementioned race conditions.
CI.
> Additional Autopilot Logs

- crates/autopilot/src/solvable_orders.rs
- crates/driver/src/boundary/settlement.rs
- crates/shared/src/remaining_amounts.rs
- crates/solver/src/driver.rs
- crates/solver/src/liquidity/order_converter.rs
- crates/solver/src/order_balance_filter.rs
#1439 introduced alert noise when encountering partially fillable orders that scale to 0 amounts.
This PR modifies the auction building process to filter out these orders before hand (there is no point in including them in the auction if they can't be executed anyway).
Note that this is achieved by modifying the existing `remaining_amount::Remaining` logic to scale by both remaining execution and available balance. One implementation note is that we **do not** put these in the same ratio, but instead scale in two steps. This is to prevent filtering out large orders with large partial balance, and would affect [existing orders](https://explorer.cow.fi/orders/0xbf386c0e1913c11edfdf6d267ea716b72fc3a3bd6002eef116d1c42b86b17b3a10ccd4136471c7c266a9fc4569622989fb4cab9964b6c2f4?tab=overview)). …
> Silence alert for dust orders

- crates/autopilot/src/on_settlement_event_updater.rs
- crates/solver/src/settlement_post_processing/mod.rs
- crates/solver/src/settlement_post_processing/optimize_score.rs
I want to remove the temporary `log_filter` configuration we introduced for CIP20 observations: https://github.com/cowprotocol/infrastructure/blob/73a3e20ad270a9af279bd9a09dde08d9ea825831/services/Pulumi.yaml#L19
But before that, let's promote the `OnSettlementEventUpdater ` logs from `trace` to `debug` since I always want to have this log for debugging purposes.
Edit: also improving the logs for score calculator (related to issue with Baseline solver fallback to objective value).
> Promote log to debug

- crates/orderbook/src/arguments.rs
- crates/orderbook/src/run.rs
- crates/shared/src/order_validation.rs
Fixes: #1487 
Adds a CLI argument that controls whether we allow quoting and creating orders with custom interactions and already makes it available in the `OrderValidator`.
This flag currently doesn't do anything but I thought it would be nice if it already existed in the needed places for when we start working on the actual feature.
Argument logged at startup:
```
...
max_limit_orders_per_user: 10
enable_custom_interactions: false
```
`--help` text
```
--enable-custom-interactions <ENABLE_CUSTOM_INTERACTIONS>
Enable support for orders with custom pre- and post-interactions
[env: ENABLE_CUSTOM_INTERACTIONS=]
[default: false]
[possible values: true, false]
```
> Add CLI arg for allowing orders with custom interactions

- crates/solver/src/settlement/settlement_encoder.rs
Fixes #1484 
In order to actually execute post-interactions the `SettlementEncoder` needs to be aware of them. This is mostly a copy-and-paste job since it already knows about pre-interactions for EthFlow orders.
Added unit test to verify that merging treats post interactions correctly
Added unit test that verifies that `add_trade()` correctly adds pre- and post-interactions to the settlement.
> Encode post interactions

- crates/solver/src/solver/single_order_solver.rs
- crates/solver/src/solver/single_order_solver/fills.rs
Noticed while on call debugging. This is cleaner and doesn't rely on trace logs being enabled because we already log when an order is excluded here. Noticed while on call debugging.
I'm not implementing the full error trait through ThisError because it isn't needed here and is more work.
none
> Be explicit about fillable amount error

- .github/workflows/pull-request.yaml
- docker/hardhat/Dockerfile
Fixes https://github.com/cowprotocol/services/issues/1105.
Add driver tests to CI. Start using `docker-compose` in CI instead of translating the compose setup into a GitHub workflow. This has a few benefits: it ensures that the local environment setup is on-par with the CI environment setup, it removes the burden of maintaining two different environment setup flows, and it tests the docker-compose setup in CI so it's impossible to commit code with a broken docker-compose.
There is one issue: because dev-geth is part of this repo, it needs to be built from scratch every time the dev-geth compose service is started. This adds up to 10 minutes to the CI pipeline. The solution to this problem is to extract dev-geth into its own repository, with its own release schedule and push the docker …
> CI improvements

- crates/solver/src/auction_preprocessing.rs
- crates/solver/src/driver.rs
- crates/solver/src/liquidity/order_converter.rs
- crates/solver/src/liquidity/slippage.rs
- crates/solver/src/metrics.rs
- crates/solver/src/order_balance_filter.rs
- crates/solver/src/run.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/balancer_sor_solver.rs
- crates/solver/src/solver/baseline_solver.rs
- crates/solver/src/solver/http_solver.rs
- crates/solver/src/solver/http_solver/instance_cache.rs
- crates/solver/src/solver/http_solver/instance_creation.rs
- crates/solver/src/solver/http_solver/settlement.rs
- crates/solver/src/solver/naive_solver.rs
- crates/solver/src/solver/oneinch_solver.rs
- crates/solver/src/solver/paraswap_solver.rs
- crates/solver/src/solver/single_order_solver.rs
- crates/solver/src/solver/zeroex_solver.rs
Part of https://github.com/cowprotocol/services/issues/1378 .
Currently we do order pre processing in the driver run loop. There we decide what orders are assigned what balance and normalize them (convert from `model::Order` to  `solver::LimitOrder`). This is in tension with letting solvers do the balance assignment. Previously all solvers expected pre-filtered `LimitOrder`s, now some solvers (external http solvers) expect raw orders with the extra information needed for balance assignment.
This PR moves the pre processing from the driver run loop into the individual solvers. The order type in `solver::Auction` is changed to `model::Order` from `solver::LimitOrder`. The logic is still the same as before (same balance filtering). It has only moved and is now run by every `solver::Solver`. …
> Move order pre processing into solvers

- .github/workflows/pull-request.yaml
#1503 was merged before this [comment](https://github.com/cowprotocol/services/pull/1503#issuecomment-1546019929) was addressed.
This PR makes it so that we only install the nightly version of `cargo fmt` for the `lint` job which is the only one that actually needs it.
The change only shaves of ~12s from a few jobs but the real improvement is just having a minimal yaml file for the workflow.
CI
> Drop nightly components from testing jobs

- crates/shared/src/sources/balancer_v2/pool_fetching.rs
Small QOL PR to make panic debugging quicker.
```
$ export NODE_URL='an xdai node'
$ export BALANCER_FACTORIES='Weighted'
$ export BASELINE_SOURCES='BalancerV2'
$ cargo  run --bin orderbook -- 
[...]
2023-05-18T10:58:28.526Z ERROR shared::tracing: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Cannot retrieve Balancer factory BalancerV2WeightedPoolFactory
Caused by:
could not find deployed contract for network 100', /home/fedgiac/code/gnosis/services/crates/orderbook/src/run.rs:266:72
```
> Better error messages when failing to retrieve Balancer factory

- crates/driver/openapi.yml
- crates/driver/src/domain/quote.rs
- crates/driver/src/infra/api/error.rs
- crates/driver/src/infra/api/routes/quote/dto/order.rs
- crates/driver/src/tests/cases/quote.rs
- crates/shared/src/arguments.rs
- crates/shared/src/trade_finding.rs
- crates/shared/src/trade_finding/external.rs
- crates/solvers/src/domain/dex/mod.rs
- crates/solvers/src/domain/solution.rs
- crates/solvers/src/domain/solver/baseline.rs
- crates/solvers/src/domain/solver/dex/mod.rs
A while ago we added support for getting price estimates in both the `autopilot` and `orderbook`. Because of code drift, this was no longer working. This PR fixes inconsistencies so that price estimation works from a co-located driver.
Manual local test. Will introduce an E2E test in a follow up.
1. Run a `driver` + `solvers baseline`
2. Run `orderbook --baseline-sources None --price-estimation-drivers 'colocated|http://localhost:11088/solver/'`
3. Make a quote:
```
% curl -s http://localhost:8080/api/v1/quote -X POST -H 'content-type: application/json' --data '@-' <<JSON | jq
{
"from": "0x0000000000000000000000000000000000000000",
"sellToken": "0x6b175474e89094c44da98b954eedeac495271d0f",
"buyToken": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
"kind": "sell",
"sellAmountBeforeFee": …
```
> Fix Driver Quotes from Protocol

- crates/solver/src/driver.rs
- crates/solver/src/solver/single_order_solver.rs
Context: https://cowservices.slack.com/archives/C0361CDD1FZ/p1684230417712809
Trivial PR, that mainly
1. Sets a parent span as a first line in the single order solver so that subsequent logs that are related to a solver but not an order can still be associated with a particular solver instance
2. Logs the simulated transaction in case we are unable to rate a single order settlement, which should make it easy to reproduce what was the error.
I think it would be good to merge this in the next release so we can debug some of the unsatisfying auctions we saw this week more reliably.
> [Logging] Improve single order solver logs

- crates/shared/src/price_estimation.rs
- crates/shared/src/price_estimation/external.rs
- crates/shared/src/price_estimation/factory.rs
- crates/shared/src/price_estimation/trade_finder.rs
- crates/shared/src/trade_finding/external.rs
Follow up to #1520 
This PR changes the co-located driver estimator to use the same trade verification machinery as our other price estimators.
Manual test, same as #1520 but with `--trade-simulator Web3 --simulation-node-url "$NODE_URL"`
> Use Trade Verification With Driver Quotes

- crates/solver/src/solver/score_computation.rs
This PR readjusts the score computation for Gnosis solvers, since we now have zero cost whenever a transaction fails. This is due to MEV Blocker and the soft cancellations we can now do.
See also relevant discussion on [Slack](https://cowservices.slack.com/archives/C0375NV72SC/p1684508285452079).
> Fix Gnosis solvers score computation since revert cost is now zero

- crates/autopilot/src/database/onchain_order_events.rs
- crates/autopilot/src/lib.rs
- crates/orderbook/src/run.rs
- crates/shared/src/arguments.rs
- crates/shared/src/fee_subsidy.rs
- crates/shared/src/fee_subsidy/config.rs
- crates/shared/src/order_quoting.rs
- crates/shared/src/order_validation.rs
Related to https://github.com/cowprotocol/services/issues/1465 . With the meaning of app data changing, it doesn't make sense to award a subsidy to an arbitrary app data hash value because the value is a hash of something else and not freely chooseable.
If we wanted to keep app id (which is not app data hash) based subsidies then we would need to do that through the full app data. But this feature in general makes little sense because anyone could pick an app id that has a subsidy even when they're not actually coming from that app. So it makes more sense to remove. I don't think we're actively using this anyway. In the infra configuration I see one value which has last been mentioned on Slack more than a year ago.
Follow ups:
- Remove this configuration from the infra repo.
CI
> Remove app data hash based fee subsidy

- Cargo.lock
- crates/app-data-hash/Cargo.toml
- crates/app-data-hash/src/lib.rs
Part of https://github.com/cowprotocol/services/issues/1465 .
Note that this crate doesn't concern itself with the full app data format. It treats it as raw bytes. I've done it this way to make it easy to reuse. We will have more specific validation logic in the order creation code.
I am using the tiny-keccak crate because we already depend on it through web3.
CI
> Create app-data-hash crate

- crates/orderbook/src/api/post_order.rs
#1524 changed the error messages for signature errors. This PR adjusts one of them to use the full address instead of a partial one. The address type's `Display` implementation only shows the first and last two bytes of the address, so this changes the message to use the `Debug` implementation for string formatting so the full address is included in the error.
CI.
> Fix Wrong Owner Message to Include Full Address

- crates/shared/src/price_estimation/factory.rs
#1521 introduced a regression where we were incorrectly formatting price estimator labels for metrics. This PR fixes that issue.
Run the orderbook locally and check the metrics:
```
% curl -s 'http://localhost:9586/metrics' | rg -i oneinch 
gp_v2_api_competition_price_estimator_queries_won{estimator_type="OneInch",order_kind="sell"} 1
gp_v2_api_price_estimates{estimator_type="OneInch",result="failure"} 0
gp_v2_api_price_estimates{estimator_type="OneInch",result="success"} 0
gp_v2_api_price_estimates{estimator_type="OneInch_verified",result="failure"} 0
gp_v2_api_price_estimates{estimator_type="OneInch_verified",result="success"} 1
gp_v2_api_rate_limiter_rate_limited_requests{endpoint="OneInch_estimator"} 0
gp_v2_api_rate_limiter_requests_dropped{endpoint="OneInch_estimator"} 0 …
```
> Fix Format String for Price Estimator Instrumentation

- crates/solver/src/solver.rs
Closes: #1506
We decided that it's not worth to alert on this error. The reason is that after putting an order in the auction in the `autopilot` the circumstances might change enough that it will result in the order being dropped on the `driver` side due to no error.
This could happen because a partial fill for that order is already in-flight which would reduce the fillable amount in the `driver` too much. Also it could be that the user's balance changes when we see a new block which results in the same thing.
The only way to catch that would be to basically do the same conversion and check the `OrderConverter` does before hand to filter those orders out. But if we are fine with discarding those orders without an alert in this pre-test there is no good reason we shouldn't just demote the …
> Demote order conversion alert

- crates/driver/src/boundary/mempool.rs
- crates/driver/src/infra/config/file/load.rs
- crates/driver/src/infra/config/file/mod.rs
- crates/solver/src/arguments.rs
- crates/solver/src/run.rs
- crates/solver/src/settlement_submission.rs
- crates/solver/src/settlement_submission/submitter.rs
[Context](https://cowservices.slack.com/archives/C0361CDD1FZ/p1684746958813839) on slack.
Simply enabling soft cancellations in our MevBlocker proxy is not sufficient to avoid subtle bugs in our submission logic with that feature. We also have to add actual support for it.
The basic problem seems to be this:
1. solver wins auction
2. we start to submit the tx
3. tx start to revert so we cancel the tx
4. cancellation does not get mined (I assume due to the inner workings of MevBlocker + soft cancellations)
5. same solver wins again
6. we want to submit the next solution but we remember that the previous cancellation has not been mined yet and the gas price didn't increase enough that "normal" nodes would replace the tx so we just don't submit anything for 2 minutes (or however long it …
> Implement hacky support for soft cancellations

- crates/solver/src/arguments.rs
Adds logging of the `use_soft_cancellations` CLI flag that I forgot in #1544.
CI
> Log soft cancellations flag on startup

- crates/shared/src/price_estimation.rs
- crates/shared/src/price_estimation/factory.rs
- crates/shared/src/price_estimation/trade_finder.rs
- crates/shared/src/price_estimation/zeroex.rs
- crates/shared/src/trade_finding/zeroex.rs
This PR adjusts the 0x price estimator to only respond to buy orders when a "buy only" flag is set. This allows us to reduce load on the 0x API for the requests that it is more important for serving.
Added a unit test, also did a manual test running the orderbook locally with 0x sell orders disabled and saw that quotes were failing on "unsupported order type".
> Add Flag For Specifying only Buy Orders for 0x Estimator

- crates/e2e/tests/e2e/app_data.rs
- crates/shared/src/order_validation.rs
While manually testing creating an order with the new app data format, I noticed that I introduced a bug that wouldn't actually store it in the database. Adjusted the e2e to check for this.
CI
> Fix not storing full app data in DB

- crates/autopilot/src/decoded_settlement.rs
- crates/autopilot/src/on_settlement_event_updater.rs
[Context](https://cowservices.slack.com/archives/C0375NV72SC/p1686134241231889).
#1425 unintentionally changed the unit of the `surplus_fee` column to be Ether. This PR fixes that.
CI, it looks like there are no tests for this code 😞. I would like to add some in a follow up because of the time-sensitive nature of this hotfix.
> Update database with solver fees in sell token

- crates/autopilot/src/database/onchain_order_events.rs
- crates/database/src/app_data.rs
- crates/database/src/lib.rs
- crates/database/src/orders.rs
- crates/orderbook/src/api/post_order.rs
- crates/orderbook/src/database/orders.rs
- crates/orderbook/src/orderbook.rs
- database/README.md
- database/sql/V052__add_app_data.sql
We want to store full app data in indexed by the contract app data that refers to it. This is needed to so that we can have an API route for retrieving full app data by contract app data. This encodes on the database level that a contract app data can only have one associated full app data. This was previously not encoded because we were storing the full app data inline in the orders table.
We do not need to worry about hash collisions because both schemes use cryptographic hashes. A hash collision would be problematic because it would prevent creating an order with valid app data because the contract app data would be the same as a different already existing full app data.
CI tests that order insertion with and without full app data still works
> Store full app data in separate table

- crates/e2e/tests/e2e/app_data.rs
In order to make the new app data format backward compatible we decided we are going to continue to accept orders with just contract app data (no full app data), if the backend already knows the full app data. This is tested by this PR.
CI
> Extend app data e2e test

- crates/orderbook/src/api.rs
- crates/shared/src/api.rs
Currently all routes return `ApiReply`. For a new full app data retrieval route, I want to return a raw `String`. This isn't possible to represent as `ApiReply`. This PR changes the code to accept `Box<Reply>` so filters can return any type.
CI
> Use Box<Reply> in warp code

- crates/e2e/tests/e2e/app_data.rs
- crates/e2e/tests/e2e/setup/services.rs
- crates/orderbook/openapi.yml
- crates/orderbook/src/api.rs
- crates/orderbook/src/api/get_app_data.rs
- crates/orderbook/src/api/get_trades.rs
- crates/orderbook/src/database.rs
- crates/orderbook/src/database/app_data.rs
- crates/orderbook/src/lib.rs
- crates/orderbook/src/run.rs
Part of the new app data design. Allows fetching full app data by contract app data hash. You could already get an order's full app data through its order uid but now you can also do so without knowing the order.
CI
> Add route for full app data fetching

- crates/autopilot/src/database/onchain_order_events.rs
- crates/driver/src/domain/quote.rs
- crates/driver/src/infra/api/routes/quote/dto/quote.rs
- crates/model/src/quote.rs
- crates/orderbook/src/run.rs
- crates/shared/src/order_quoting.rs
- crates/shared/src/order_validation.rs
- crates/shared/src/price_estimation.rs
- crates/shared/src/price_estimation/balancer_sor.rs
- crates/shared/src/price_estimation/baseline.rs
- crates/shared/src/price_estimation/competition.rs
- crates/shared/src/price_estimation/http.rs
- crates/shared/src/price_estimation/instrumented.rs
- crates/shared/src/price_estimation/native.rs
- crates/shared/src/price_estimation/oneinch.rs
- crates/shared/src/price_estimation/paraswap.rs
- crates/shared/src/price_estimation/sanitized.rs
- crates/shared/src/price_estimation/trade_finder.rs
- crates/shared/src/price_estimation/zeroex.rs
- crates/shared/src/trade_finding.rs
- crates/shared/src/trade_finding/external.rs
- crates/shared/src/trade_finding/oneinch.rs
- crates/shared/src/trade_finding/paraswap.rs
- crates/shared/src/trade_finding/zeroex.rs
Closes #1512 
I now have a rough game plan for verified quotes.
Instead of introducing a new price quality `verified` (#1512) we implicitly verify all quotes where `from` is set. All the other pieces of data (besides custom interactions) already exist in the request so we can easily bundle the data that is only needed for verification into a struct which is optional. Only if the struct is `Some` we do verifications.
Also with this new idea I would rather make every individual price estimator decide whether it supports trade verification (and return an error if it doesn't) than creating a new price estimator hierarchy that doesn't contain the ones that don't support quote verification.
Things left over which should be doable in separate PRs:
1. Make remaining estimators aware of new …
> Hook up new simulation logic

- crates/autopilot/src/arguments.rs
- crates/autopilot/src/lib.rs
- crates/orderbook/src/arguments.rs
- crates/orderbook/src/run.rs
- crates/shared/src/account_balances.rs
- crates/shared/src/account_balances/arguments.rs
- crates/shared/src/account_balances/simulation.rs
- crates/shared/src/account_balances/web3.rs
- crates/shared/src/arguments.rs
- crates/shared/src/price_estimation.rs
- crates/shared/src/price_estimation/factory.rs
- crates/solver/src/run.rs
Follow up to #1586
This PR adds the required configuration options to setup a simulation based balance fetcher in the services. Note that this still needs to be done for the `driver`.
Ran locally and verified the balance simulation logs when trying to create an order for a token for which I had no balance (but some allowance):
```
2023-06-14T15:03:05.197Z TRACE request{id=7}: shared::account_balances::simulation: simulated balances query=Query { owner: 0xdbc682d0ec19bd276fd6c2af4e0189b584bb31e1, token: 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48, source: Erc20 } amount=Some(1000000000) simulation=Simulation { token_balance: 0, allowance: 115792089237316195423570985008687907853269984665640564039457584007912951809973, effective_balance: 0, can_transfer: false }
```
> Configure Account Balance Fetching Implementation

- Cargo.lock
- crates/orderbook/Cargo.toml
- crates/orderbook/src/arguments.rs
- crates/orderbook/src/ipfs.rs
- crates/orderbook/src/lib.rs
- crates/orderbook/src/orderbook.rs
- crates/orderbook/src/run.rs
- crates/shared/src/order_validation.rs
We want to continue to support IPFS based app data even when on order creation only the contract app data hash is specified. This PR changes how orders with only a contract app data hash are handled.
Before:
Order is accepted and we may or may not already have corresponding full app data in the database.
Now:
First try to find existing app data in database. If it doesn't exist try to find it on IPFS with the old and new method of CID generation. If it still doesn't exist then continue as before without full app data. If it does exist, then don't try to verify the hash of the found full app data because this might be the old way of storing on IPFS, which we cannot validate. Or it might be hardcoded app data that doesn't correspond to any IPFS data. Do verify that the schema is as expected. …
> Fetch full app data from IPFS when not specified

- .github/workflows/deploy.yaml
Fixes failing auto deployments due to Goerli solver changes.
Running Github actions after merge should resolve failing jobs.
Update auto deploy to include new co-location pods
> Add Goerli colocation pods to auto deploy

- crates/autopilot/src/fok_limit_orders/quoter.rs
- crates/shared/src/account_balances.rs
- crates/shared/src/account_balances/cached.rs
- crates/shared/src/account_balances/simulation.rs
- crates/shared/src/account_balances/web3.rs
- crates/shared/src/order_validation.rs
This PR adds interactions to the balance fetching API in order to correctly compute effective user balance including potential pre-interactions (such as signed EIP-2612 permit transactions).
One notable code smell is that we skip balance checks for FoK limit orders with custom interactions. This should be OK, where we will at worst include some additional fee queries for orders that don't actually need them (because of missing balances). I also noticed, on an unrelated point, that we don't verify quotes for FoK limit order surplus fees.
CI, no real logic change, just piping data through.
> Extend Balance Fetching API To Allow Pre-Interactions

- crates/database/src/orders.rs
- crates/model/src/order.rs
- crates/orderbook/src/api/post_order.rs
- crates/orderbook/src/database/orders.rs
- crates/shared/src/app_data.rs
- crates/shared/src/order_validation.rs
- crates/shared/src/trade_finding.rs
This PR adds the remaining glue code to enable pre-interactions. Namely:
- Parse custom interactions from app data
- Store custom interactions in the database
Added some unit tests for the DB operations, and E2E test introduced in #1604.
**This should not be enabled on Mainnet/Gnosis Chain until we properly trampoline the user interactions!**.
> Hook Up Pre- and Post- Interactions

- crates/driver/src/domain/competition/auction.rs
- crates/driver/src/domain/competition/mod.rs
- crates/driver/src/domain/competition/solution/mod.rs
- crates/driver/src/domain/quote.rs
- crates/driver/src/infra/api/mod.rs
- crates/driver/src/infra/api/routes/quote/mod.rs
- crates/driver/src/infra/solver/dto/auction.rs
- crates/driver/src/infra/solver/mod.rs
- crates/driver/src/infra/time.rs
- crates/driver/src/run.rs
- crates/driver/src/tests/setup/blockchain.rs
- crates/driver/src/tests/setup/driver.rs
- crates/driver/src/tests/setup/mod.rs
- crates/driver/src/tests/setup/solver.rs
- crates/e2e/tests/e2e/setup/colocation.rs
Use `OnceLock` and `#[cfg]` attributes for tests instead. Makes the code a lot easier to read and alleviates the pain of having to pass the `Now` object all over the place.
> Remove `infra::time::Now` from `driver`

- crates/orderbook/src/api.rs
- crates/orderbook/src/api/get_total_surplus.rs
Implement API endpoint to calculate total surplus.
Tried to test manually but for some reason I get this error:
```
2023-06-26T14:56:32.229Z ERROR shared::tracing: thread 'main' panicked at 'error innitializing Uniswap V3 pool fetcher: error
sending request for url (https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3): operation timed out
```
It seems like this API is down at the moment?
> API endpoint for total surplus

- crates/orderbook/src/api.rs
- crates/orderbook/src/api/get_total_surplus.rs
- crates/orderbook/src/database.rs
- crates/orderbook/src/database/total_surplus.rs
Adds the actual query to compute the total surplus of a user (since march 2023) for the hackathon project.
Currently only tested manually by comparing the surplus % to what the explorer shows for a given order and doing a request with `curl`.
To unblock the remaining hackathon team I want to merge this PR quickly and deliver tests in a follow up PR.
```
time curl http://localhost:8080/api/v1/users/0x5fc79e21ceca2aa0f7a0aac71ef3ddde8f004e9e/total_surplus
{"totalSurplus":"4202924650702963200"}
curl   0.00s user 0.01s system 2% cpu 0.349 total
```
> Implement total surplus query

- crates/autopilot/src/solvable_orders.rs
- crates/shared/src/order_validation.rs
- crates/shared/src/signature_validator.rs
- crates/shared/src/signature_validator/web3.rs
This PR starts implementing #1599,
Specifically, it adds an `interactions` key to the checks done by the signature validator component, which will be needed for considering ERC-1271 signatures that become valid from a pre-interaction (for example, a JIT Composable CoW order creation transaction). 
I also removed the `SignatureValidating::validate_signature` method as it was not used anywhere.
Unit tests verify new logic.
> Pass Custom Interactions for EIP-1271 Signature Validation

- crates/shared/src/bad_token/token_owner_finder/blockscout.rs
Fixes the blockscout errors that we currently see in our stack.
The mainnet API is no longer at `https://blockscout.com/eth/mainnet/` and has permanently moved to `https://eth.blockscout.com/api`. The xdai endpoint is getting an extra `/` at the end due to a recent change (#1606) in the way we handle URL strings.
We see these errors in our logs
Did manual tests by calling both xdai and mainnet paths.
```
https://blockscout.com/xdai/mainnet/api?module=token&action=getTokenHolders&contractaddress=0xd152bb8f047fec087b0f961739d4391574228fe2
https://eth.blockscout.com/api?module=token&action=getTokenHolders&contractaddress=0x5b685863494c33f344081f75e5430c260c224a32
```
Update Blockscout URL's for mainnet and xdai
> Update Blockscout url

- crates/orderbook/src/database/total_surplus.rs
The new total surplus query currently results in an error when the target address didn't do any trades since march 2023 which means we don't have any data to compute a total surplus with.
This PR simply falls back to 0 surplus in that case.
manual test with address that caused errors in staging:
```
time curl http://localhost:8080/api/v1/users/0x5b0abe214ab7875562adee331deff0fe1912fe42/total_surplus
{"totalSurplus":"0"}
curl   0.00s user 0.01s system 3% cpu 0.353 total
```
> Coalesce surplus when we have no data

- crates/autopilot/src/solvable_orders.rs
- crates/e2e/tests/e2e/eth_flow.rs
- crates/shared/src/arguments.rs
- crates/shared/src/oneinch_api.rs
- crates/shared/src/price_estimation/competition.rs
- crates/shared/src/trade_finding/oneinch.rs
- crates/solver/src/solver/oneinch_solver.rs
- crates/solvers/src/infra/dex/oneinch/mod.rs
This PR refactors the 1Inch cache to support multiple properties. Previously, the `ProtocolCache` was only used for caching `v5.0/1/liquidity-sources` requests, but it is now also caches `v5.0/1/spender` as well.
One additional notable change in behaviour is that we use a `tokio::sync::Mutex` instead of a `std::sync::Mutex`. This allows us to hold onto the `Mutex` lock across the API call. This effectively changes the behaviour such that that multiple concurrent calls to `v5.0/1/liquidity-sources` and `v5.0/1/spender` will be shared (they will `await` for the lock to be released which only happens after the API call finishes when the cache is out of date).
I moved the spender caching code over instead of using `TimedCache` because:
- We don't need to allocate a hash map for caching a …
> Uniform Caching of 1Inch Spender

- crates/autopilot/src/driver_api.rs
- crates/autopilot/src/driver_model.rs
- crates/autopilot/src/run_loop.rs
- crates/driver/src/domain/competition/mod.rs
- crates/driver/src/domain/competition/solution/settlement.rs
- crates/driver/src/infra/api/routes/settle.rs
- crates/driver/src/infra/mempool/mod.rs
- crates/driver/src/infra/observe/mod.rs
- crates/driver/src/tests/setup/mod.rs
Fixes #1632.
Return the internalized and uninternalized calldata in the `/settle` response body.
Updated automated tests.
> `driver`: return calldata in response of `/settle`

- crates/driver/src/boundary/liquidity/mod.rs
- crates/driver/src/boundary/liquidity/uniswap/v2.rs
- crates/solvers/src/api/dto/auction.rs
- crates/solvers/src/api/mod.rs
- crates/solvers/src/domain/liquidity/constant_product.rs
This PR fixes an issue where the `driver` was sending invalid UniV2 pools to the solver engine. The engine expects ~~`uint96`~~ `uint112` reserves, but it is possible to set up a pools that has more reserves than that (effectively bricking it).
Ran locally on Goerli and swapped with WETH <> `0xdc31ee1784292379fbb2964b3b9c4124d8f89c60` pool.
> Filter Out Invalid Uniswap V2 Pools

- crates/autopilot/src/database.rs
- crates/autopilot/src/database/order_events.rs
- crates/autopilot/src/run_loop.rs
- crates/autopilot/src/solvable_orders.rs
- crates/database/src/lib.rs
- crates/database/src/order_events.rs
- crates/orderbook/src/database/orders.rs
- database/README.md
- database/sql/V054__store_order_events.sql
Fixes #1582 
This PR implements storing timestamped events throughout the life cycle of every order.
In the autopilot all events get uploaded in a background task to not block the protocol unnecessarily. This is probably overkill in some places but I wanted to have a simple API that gets the job done.
It seems we currently don't have the tools required to test DB state when running an e2e test so I modified an existing e2e test that simply settles an order and checked my local DB afterwards. Looked good enough to merge but should be followed up with a PR implementing and actual e2e test for that.
> Sli order events

- crates/autopilot/src/database/auction.rs
- crates/autopilot/src/database/onchain_order_events.rs
- crates/e2e/tests/e2e/setup/onchain_components.rs
- crates/model/src/order.rs
- crates/orderbook/src/database/quotes.rs
- crates/shared/src/event_storing_helpers.rs
- crates/shared/src/order_quoting.rs
- crates/shared/src/order_validation.rs
This PR includes the additional hook `gas_limit` added in #1644 into the quoted fee amount.
Existing tests continue to pass (including E2E test which uses hooks). Also, modified a unit test to consider additional gas costs from signature verification and hooks.
> Include Additional Hook Gas In Quoted Fee

- crates/e2e/tests/e2e/eth_flow.rs
- crates/e2e/tests/e2e/main.rs
- crates/e2e/tests/e2e/order_cancellation.rs
- crates/e2e/tests/e2e/quoting.rs
- crates/e2e/tests/e2e/setup/mod.rs
- crates/model/src/quote.rs
- crates/orderbook/src/api/post_order.rs
- crates/orderbook/src/api/post_quote.rs
- crates/shared/src/order_quoting.rs
- crates/shared/src/order_validation.rs
- crates/shared/src/trade_finding.rs
This PR changes the `api/v1/quote` request to accept full app-data instead of just app-data hashes. This allows quoting to account for order hooks (i.e. custom interactions) when computing fees.
Added new E2E test that verifies quoting logic with additional gas costs.
> Account For Hooks While Quoting

- crates/autopilot/src/driver_model.rs
- crates/autopilot/src/run_loop.rs
- crates/driver/openapi.yml
- crates/driver/src/domain/mempools.rs
- crates/driver/src/infra/observe/mod.rs
- crates/e2e/tests/e2e/colocation_hooks.rs
- crates/e2e/tests/e2e/hooks.rs
- crates/e2e/tests/e2e/main.rs
In debugging why custom order interactions were not working on Goerli for my demo, I realized that we weren't serializing order interactions in the auction that we send to co-located drivers 🤦.
This PR fixes this issue, we now correctly marshal the interactions to the co-located drivers for solving.
Duplicated the hooks E2E test (formerly named `pre_interaction`, and renamed to `hooks` here, since we now call these hooks, and the E2E test included both pre- and post- hooks, so it was badly named to begin with).
> Send Order Interactions To Colocated Driver

- crates/orderbook/src/arguments.rs
- crates/orderbook/src/run.rs
- crates/shared/src/app_data.rs
☝️ 
```
% cargo run -p orderbook
...
app_data_size_limit: 8192
...
```
> Make App Data Size Limit Configurable

- crates/orderbook/openapi.yml
This PR:
1. Contains editorial changes to the *descriptions* and *summary* only for the `OrderBook` OpenAPI specification. Notably all descriptions / summaries:
a. Adhere to UK English.
b. Single-word descriptions / summaries are not punctuated. Otherwise, they are punctuated.
c. Standardises hyphenation.
d. Makes use of Markdown within the description with respect to cautions and notes.
**Why this PR?**
As part of expanding `cow-sdk` for documentation and usability for `ComposableCoW`, `openapi.yml` was reviewed to for editorial oversights / typos / grammer / formatting. This is due to `openapi.yml` being imported into `cow-sdk` for generated bindings.
There is no change to code coverage, therefore testing is not required.
> chore: openapi editorial

- crates/autopilot/src/decoded_settlement.rs
I though we might not store `settlement_observations` when running with the colocated driver because decoding fails with the additional data but that does not seem to be the case.
However, during the investigation I adjusted the existing tests to always run because they didn't need a `NODE_URL` after all.
> Always run decoded settlement tests

- crates/solver/src/settlement_submission.rs
- crates/solver/src/settlement_submission/submitter/common.rs
Fixes the fact that we cannot settle private mempool transactions with KMS keys. I overlooked and didn't test this codepath during development. Thanks to @vkgnosis for pointing me to the relevant change.
My plan is to hotfix prod so we can continue the key rotation as planned.
Locally ran the driver against the staging orderbook with the Legacy solver KMS key (in flashbots only mode). Got this successfult settlement: [0x5537310468560e1954877d8c25a281264010429cdd58e8b90a1f29df6b26513f](https://etherscan.io/tx/0x5537310468560e1954877d8c25a281264010429cdd58e8b90a1f29df6b26513f)
> [HotFix] Fix KMS submission for private submission strategies

- crates/solver/src/driver.rs
We noticed it was confusing that settlement submission didn't work but no message was printed.
CI
> Log settlement submission error

- crates/autopilot/src/driver_model.rs
- crates/autopilot/src/lib.rs
- crates/autopilot/src/run_loop.rs
- crates/driver/src/domain/competition/auction.rs
- crates/driver/src/infra/api/routes/solve/dto/auction.rs
There were problems with the ParaSwap solver indicating that token decimals are missing. This was because the autopilot wasn't passing the token info to the driver correctly.
CI still passes, will test this again on staging at some point.
> Pass token info to `driver`

- crates/driver/src/domain/competition/mod.rs
- crates/driver/src/infra/api/routes/settle.rs
- crates/driver/src/infra/api/routes/solve/dto/solution.rs
- crates/driver/src/infra/observe/mod.rs
Rename `competition::Reveal` into `competition::Solved` and `competition::Calldata` into `competition::Settled`.
> `driver`: rename a few types

- crates/shared/src/http_solver/model.rs
- crates/solver/src/settlement_ranker.rs
I [found a bug](https://cowservices.slack.com/archives/C0361CDD1FZ/p1689175111103549) while on call.
Beads & prayer
> Send `/notification` when solver returns empty solution

- crates/orderbook/src/run.rs
IPFS requests always timeout if the data doesn't exist on the network. This makes for a bad experience in the create_orders endpoint. This PR halves the usual timeout of 10s for http requests to 5 for IPFS requests.
look at metrics afterwards
> Lower IPFS request timeout

- crates/shared/src/bad_token/token_owner_finder.rs
Noticed while on call that these weren't printed.
check logs later
> Display missing token owner finder arguments

- crates/shared/src/http_solver.rs
Added more logs to observe the http communication with external solvers.
This is needed to check if the requests are properly crafted for the Raven colocated driver.
> Add logs to http request/response

- crates/shared/src/http_solver/model.rs
- crates/solver/src/driver.rs
Request from external solvers:
Sends additional `notify` request to all winning solvers and informs about submission result.
> Notify solvers about submission result

- crates/orderbook/openapi.yml
Signing scheme is present on the response but not documented in swagger.
> [Easy] Update swagger OrderParameters schema

- crates/driver/src/boundary/liquidity/mod.rs
- crates/driver/src/infra/config/file/mod.rs
- crates/driver/src/infra/liquidity/config.rs
- crates/driver/src/run.rs
☝️ 
This PR just introduces Balancer V2 liquidity in the driver.
Run the driver with Balancer V2 liquidity and watch it crash (with the configuration!):
```
thread 'main' panicked at 'not yet implemented: Balancer V2 liquidity fetcher not implemented: [BalancerV2 { vault: ContractAddress(0xba12222222228d8ba445958a75a0704d566bf2c8), weighted: [ContractAddress(0x8e9aa87e45e92bad84d5f8dd1bff34fb92637de9), ContractAddress(0x5dd94da3644ddd055fcf6b3e1aa310bb7801eb8b), ContractAddress(0x897888115ada5773e02aa29f775430bfb5f34c51), ContractAddress(0xa5bf2ddf098bb0ef6d120c98217dd6b141c74ee0)], stable: [ContractAddress(0xc66ba2b6595d3613ccab350c886ace23866ede24), ContractAddress(0x8df6efec5547e31b0eb7d1291b511ff8a2bf987c)], liquidity_bootstrapping: …
```
> Balancer V2 Liquidity Configuration in the Driver

- crates/autopilot/src/arguments.rs
- crates/autopilot/src/lib.rs
- crates/orderbook/src/arguments.rs
- crates/orderbook/src/run.rs
- crates/shared/src/arguments.rs
- crates/shared/src/price_estimation.rs
Fixes #1696.
It looks like we had a regression which caused `cargo run (orderbook|autopilot)` with no arguments to crash on startup. This PR addresses the issue.
Note that, since we plan on co-locating all estimators in the very near future, I also added logic for parsing `--(native-)?price-estimators None` such that it yields no price estimator (similar to the `--baseline-sources None` argument).
```
% cargo run -p orderbook --
...
price_estimators: Baseline|0x0000000000000000000000000000000000000000
native_price_estimators: Baseline|0x0000000000000000000000000000000000000000
...
% cargo run -p orderbook -- --price-estimators None --native-price-estimators None
...
price_estimators: None
native_price_estimators: None
...
% cargo run -p orderbook -- --price-estimators …
```
> Add Default Price Estimator

- crates/orderbook/openapi.yml
Updates the `PriceQuality` enum.
Lately we introduced the variant `verified` which means that specific quote needs to be verified/simulated in order to be accepted as valid. 
Related to [slack](https://cowservices.slack.com/archives/C036G0J90BU/p1690299239980499) discussion.
> Update openapi docs for priceQuality

- .github/workflows/deploy.yaml
I noticed warnings:
```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
These seem to be related to the Docker actions that we use. I updated to a more recent version of the actions which should use a more recent `@actions/core` package and use the new `GITHUB_(STATE|OUTPUT)` mechanism for setting state and output for an action. …
> Update Docker GitHub Actions Version

- crates/orderbook/src/ipfs.rs
- crates/orderbook/src/ipfs_app_data.rs
- crates/orderbook/src/lib.rs
- crates/orderbook/src/orderbook.rs
- crates/orderbook/src/run.rs
I observed automated order creation through our API with an order that has no full app data. The order later fails validation. This puts pressure on our IPFS gateway because we have to check whether the app data exists every time. This PR relives some of this pressure by caching IPFS app data.
This PR contains several changes:
- Move IPFS app data fetching from the ipfs module to a dedicated ipfs_app_data module.
- Refactor IPFS code to not treat all reqwest errors as missing app data. Missing app data is only the result when the request and response fetching is successful with a status code that isn't 200.
- Add a cache to the ipfs_app_data module.
existing tests and observe Pinata request counts later
> Cache IPFS app data

- crates/autopilot/src/solvable_orders.rs
- crates/shared/Cargo.toml
- crates/shared/src/remaining_amounts.rs
- crates/solver/src/liquidity/order_converter.rs
- crates/solver/src/order_balance_filter.rs
- crates/solver/src/settlement/settlement_encoder.rs
Instead of passing in a full model::Order I create a new type holding exactly what parts of the full order are needed. This makes this module more reusable and makes it more clear which fields are relevant.
CI
> Refactor order remaining amount module

- crates/e2e/tests/e2e/app_data.rs
- crates/e2e/tests/e2e/colocation_hooks.rs
- crates/e2e/tests/e2e/hooks.rs
- crates/e2e/tests/e2e/quoting.rs
- crates/model/src/app_id.rs
- crates/model/src/order.rs
- crates/orderbook/openapi.yml
- crates/orderbook/src/orderbook.rs
- crates/shared/Cargo.toml
- crates/shared/src/app_data.rs
- crates/shared/src/app_data/compat.rs
- crates/shared/src/order_quoting.rs
- crates/shared/src/order_validation.rs
As discussed in [Slack](https://cowservices.slack.com/archives/C0375NV72SC/p1690365762570749) this PR changes the backend to use the `metadata` field for specifying hooks and deprecates the `backend`.
For simplicity's sake, we decided to ignore the `backend` field entirely if the `metadata` field is specified. While this is technically breaking behaviour, AFAICT, all uses of "hooks" have been without `metadata` being specified at all (following the [documentation](https://docs.cow.fi/overview/cow-hooks/cow-hooks-example)).
Added comprehensive unit tests. Adjusted E2E tests to use "metadata" field.
> Move hooks to metadata field

- crates/shared/src/price_estimation.rs
- crates/shared/src/price_estimation/factory.rs
This PR adds Raven as a legacy http price estimator, so that it can be enabled in production. This should be viewed as a temporary solution until we move to the colocated driver solution.
> Add Raven as legacy http price estimator

- crates/shared/src/http_solver.rs
Reduces noisy logs to `trace` so they can easily be turned off when they are no longer need (suggested [here](https://github.com/cowprotocol/services/pull/1686#issuecomment-1645794201)).
CI
> Decrease log level to trace

- crates/autopilot/src/database.rs
Follow-up to #1704 .
Describe context of what this change does, why it is needed and how it is accomplished
Run the `autopilot` and `orderbook` locally and:
```
% curl -s 'http://localhost:9589/metrics' | rg unused_app_data | rg -v '^#'
gp_v2_autopilot_unused_app_data 0
% curl -s 'http://localhost:8080/api/v1/app_data/0x586e9b1e1681ba3ebad5ff5e6f673d3e3aa129fcdb76f92083dbc386cdde4312' -X PUT --data-raw '{"hello":"world"}' > /dev/null
% sleep 60
% curl -s 'http://localhost:9589/metrics' | rg unused_app_data | rg -v '^#'
gp_v2_autopilot_unused_app_data 1
```
> Record Unused AppData Metrics 

- crates/orderbook/src/ipfs_app_data.rs
As usual with metrics where we know the label values beforehand, it is good behavior to initialize them.
manual test
> Initialize IPFS metrics

- crates/autopilot/src/lib.rs
- crates/orderbook/src/run.rs
- crates/shared/src/arguments.rs
- crates/shared/src/price_estimation/factory.rs
This PR adds support for adding arbitrary solvers as legacy HTTP solvers (a follow up to #1712 which allows more solvers to be added via configuration instead of requiring code changes).
This PR introduces a new `--price-estimation-legacy-solver` flag for configuring these solvers. These are meant to be used as an "intermediate" step while we get more solvers onboarded to CIP-27. It is different than setting up a co-located driver + legacy solver adapter in that:
- It respects the reported `feeEstimate` 
- Does not do simulation verification
This is meant for on-boarding solvers to be able to start participating without generating calldata for an interim period.
Note that this change slightly changes the `PriceEstimatorFactory` semantics. Specifically, price etimator entries are unique by …
> Add Support For Arbitrary Legacy Solver Estimators

- crates/autopilot/src/lib.rs
- crates/shared/src/sources/balancer_v2/graph_api.rs
- crates/shared/src/subgraph.rs
Related to https://github.com/cowprotocol/services/issues/1525
It happens quite often that we have to disable the graph based liquidity due to issues during its initialization phase.
IMO the "correct" solution would be to design a system that is able to check for new pools in the background (e.g. even if initialization works I think we currently wouldn't notice new pools being deployed while the system is running).
But since all the initialization errors are due to the graph timing out I think it would be a reasonable quick fix to simply query the graph in smaller batches.
Since we use pod roll over initialization speed is less important than reliability anyway.
> Query the graph in smaller chunks

- crates/autopilot/src/database/onchain_order_events.rs
- crates/autopilot/src/driver_model.rs
- crates/driver/src/boundary/settlement.rs
- crates/e2e/tests/e2e/app_data.rs
- crates/e2e/tests/e2e/order_cancellation.rs
- crates/e2e/tests/e2e/setup/services.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
- crates/model/src/app_data.rs
- crates/model/src/lib.rs
- crates/model/src/order.rs
- crates/model/src/quote.rs
- crates/orderbook/openapi.yml
- crates/orderbook/src/api/get_app_data.rs
- crates/orderbook/src/api/post_quote.rs
- crates/orderbook/src/api/put_app_data.rs
- crates/orderbook/src/app_data.rs
- crates/orderbook/src/database/app_data.rs
- crates/orderbook/src/database/orders.rs
- crates/orderbook/src/ipfs_app_data.rs
- crates/orderbook/src/orderbook.rs
- crates/shared/src/app_data.rs
- crates/shared/src/db_order_conversions.rs
- crates/shared/src/http_solver/model.rs
- crates/shared/src/order_validation.rs
As discussed [in Slack](https://cowservices.slack.com/archives/C0375NV72SC/p1690808347200279?thread_ts=1690297997.334099&cid=C0375NV72SC), it was suggested that the `GET`/`PUT` `api/v1/app_data/{hash}` APIs operate on:
```json
{
"fullAppData": "..."
}
```
My motivation for this change is to make the API less ambiguous. For example, conceptually an HTTP request/response with `Content-Type: application/json` implies that the content is, well, JSON and it becomes ambiguous whether things like spaces, trailing newlines, etc. matter or not. In fact many HTTP client utilities may make this assumption as well and end up doing things like adding new lines, re-serializing to be smaller by omitting whitespace, automatically parse the JSON content, etc. As such, we now return the aforementioned JSON …
> New AppData Get/Put Format

- crates/shared/src/price_estimation.rs
- crates/shared/src/price_estimation/factory.rs
This is a follow up to #1715 where we added a new `--price-estimation-legacy-solvers` flag to specify legacy HTTP solvers to use as price estimators. As such, the "builtin" estimators `Quasimodo`, `Yearn` and `Raven` are no longer needed.
This PR deprecates the aforementioned builtin estimators in favor of the new `--price-estimation-legacy-solvers` flag.
Rust CI - we are removing code, so nothing to test!
https://github.com/cowprotocol/infrastructure/pull/596 already does the required changes in order to no longer rely on the "builtin" versions of these legacy price estimators - those changes have already been applied.
> Remove Legacy Builtin Price Estimator

- crates/solver/src/driver.rs
For some reason the notification about a successfully mined solution contained a block hash which is fairly useless.
This PR notifies about the tx hash instead which can be easily found on etherscan.
compiler
> Notify about tx hash instead of block hash

- crates/solver/src/settlement_submission/submitter.rs
Follow up fix to https://github.com/cowprotocol/services/pull/1544 (please read that one for more context)
That PR only cleared `transactions` after a soft cancellations because I thought that `submitted_transactions` would always be overwritten with `transactions` afterwards.
However, this actually only happens when `transactions` is not empty which means the previous PR didn't have an effect.
Now we clear `transactions` to avoid waiting for any tx that will never be mined and we forcefully update `submitted_transactions` to actually ensure that we will not wait for the gas price to increase during the next submission of the same solver.
This PR also adds a log that states whenever we are waiting for the gas price to increase since this would have been useful debugging information a …
> Fix soft cancellations support

- crates/shared/src/current_block.rs
- crates/shared/src/current_block/arguments.rs
- crates/shared/src/current_block/eth_call.rs
- crates/shared/src/current_block/get_block_and_call.rs
This PR adds a new `GetBlockAndCall` "block fetching strategy".
This combines the `eth_call` strategy (which ensures that there is block state for the `latest` block) and the `eth_getBlock` strategy (to read the latest block hash - since the EVM defines `blockhash(block.number) == bytes32(0)`).
This is needed as the existing `eth_call` strategy relies on simulating on the `pending` block (so that `block.number - 1 == latest`, we do this so that `blockhash(block.number - 1) == blockhash(latest)` is available). However, this is [not supported on Nethermind](https://github.com/NethermindEth/nethermind/issues/5810). In addition, `eth_call` on `pending` is potentially going to be no longer supported on RPC nodes, meaning that the `eth_call` strategy will likely stop working some time in the …
> Add new GetBlockAndCall Strategy

- Cargo.lock
- Cargo.toml
Fixes issues with s & r being sometimes not minimally encoded in the KMS signatures.
Test was in the ethcontracts repo. Will check in staging that we don't see this error anymore
> [Trivial] Bump Ethcontract version

- crates/solvers/src/infra/cli.rs
Currently pods running the new `solvers` are logging lots of debug information of dependencies.
The new default log level will only log warnings and higher of dependencies and debug and higher of any code inside our repo.
Manually ran solver to see that logs are still being printed
> Proper default log level

- crates/solvers/src/infra/cli.rs
I noticed that the doc comment on clap commands is used as a help text. Therefore I added a very basic explanation what kind of strategy each command uses.
```
cargo run -p solvers -- --help
Compiling solvers v0.1.0 (/Users/martin/work/backend/main/crates/solvers)
Finished dev [unoptimized + debuginfo] target(s) in 3.09s
Running `target/debug/solvers --help`
Run a solver engine
Usage: solvers [OPTIONS] <COMMAND>
Commands:
baseline  solve individual orders exclusively via provided onchain liquidity
naive     optimistically batch similar orders and get difference from AMMs
legacy    forward auction to solver implementing the legacy HTTP interface
balancer  solve individual orders using Balancer API
zeroex    solve individual orders using 0x API
oneinch   solve individual orders using 1Inch …
```
> Nicer --help text for solver commands

- crates/autopilot/src/lib.rs
- crates/shared/src/sources/balancer_v2/graph_api.rs
- crates/shared/src/subgraph.rs
This reverts commit 95bb44c0d31f9afe6f23601fb5dbecc5f3cd8326 (#1719).
That commit did not have the promised effect. I already proposed a new change (#1736) but IMO that is too big to include without running it staging first so I opened this PR just to revert the bad changes.
> Revert "Query the graph in smaller chunks (#1719)"

- crates/shared/src/bad_token/token_owner_finder.rs
- crates/shared/src/bad_token/token_owner_finder/blockscout.rs
- crates/shared/src/bad_token/token_owner_finder/ethplorer.rs
This will allow us to reverse proxy and smoothen them to reduce rate limits.
run with `--token-owner-finders ethplorer,blockscout --ethplorer-api-url https://api.ethplorer.io --blockscout-api-url https://eth.blockscout.com`
Requires config value to be set to our reverse proxy in both staging and prod
> Make TokenOwnerFinding urls configurable

- crates/solver/src/liquidity/order_converter.rs
Fixes https://github.com/cowprotocol/services/issues/1757
For FOK limit orders solver_fee sent to solvers should be zero since it is expected to be provided by solvers.
> Send zero fee for FOK limit orders

- crates/driver/src/boundary/liquidity/balancer/v2/mod.rs
- crates/driver/src/boundary/liquidity/mod.rs
- crates/driver/src/boundary/liquidity/uniswap/v3.rs
- crates/driver/src/infra/liquidity/config.rs
- crates/solver/src/liquidity_collector.rs
Fixes #1525
When we restart the services we need to initialize `BalancerV2` and `UniswapV3` liquidity. That uses the graph and this is very unreliable. So far the process has been:
1. restart service and 🙏 that the graph works
2. see that it doesn't and disable `UniswapV3` and `BalancerV2`
3. periodically check if the graph works again to re-enable the liquidity
With this change we move liquidity initialization into a background task that retries until it succeeds.
Unit test to verify logic
Manual test to verify logs
> Init liquidity in background

- crates/solver/src/liquidity_collector.rs
Follow up to #1759
Although we are now automatically retrying to initialise the graph based liquidity it would be nice to some automated alerting system in case it's disabled for a long time.
This PR adds a very simply labled gauge which gets set to 0 when the initialisation wrapper gets created and set to 1 once the liquidity source has been initialised successfully.
Manually tested driver start up sequence to verify that values of gauges get set correctly after initialisation.
And extended the unit test to include metrics
Fetching `localhost:11088/metrics` returned:
```
driver_liquidity_enabled{source="balancer-v2"} 1
driver_liquidity_enabled{source="uniswap-v3"} 1
```
> Add metrics for the graph based liqudiity in driver

- crates/driver/example.toml
- crates/solvers/config/example.balancer.toml
- crates/solvers/config/example.oneinch.toml
- crates/solvers/config/example.paraswap.toml
- crates/solvers/config/example.zeroex.toml
- crates/solvers/src/infra/config/dex/file.rs
- crates/solvers/src/infra/config/dex/zeroex/file.rs
- crates/solvers/src/infra/dex/zeroex/mod.rs
- crates/solvers/src/tests/zeroex/mod.rs
For local test I usually like to take one of the existing example configuration files and patch it to my needs.
This showed that some of the examples are outdated or have values that could be improved in terms of ease of use.
Changes include:
* example solver in `driver` config is now compatible with defaults of the `solvers` binary
* documented `balancer-v2` and `uniswap-v3` liquidity in driver
* fixed incorrect format of `balancer` config
* configured `1Inch` to use `mainnet` instead of `goerli`
* added a file for `paraswap`
* made `0x` api key required (without you'll receive these response which fail to parse: `"No API key provided. Please visit https://0x.org/pricing to get a free API key or sign up to a paid plan`)
* made sure `solvers` and `driver` both expect `absolute-slippage` …
> fix examples

- crates/database/src/ethflow_orders.rs
- crates/solver/src/solver/http_solver/settlement.rs
Refunder is failing to fetch refundable orders due to an entry in the database table `order_quotes` with `buy_amount = 0`.
I am not sure if this quote is even valid, I guess it is.
This PR adds division by zero protection. Orders with `buy_amount = 0` will be skipped.
Deeper explanation what is probably happening is https://github.com/cowprotocol/services/pull/1767#issuecomment-1680825756
Requires hotfix to unblock refunder (if we don't want to manually fix prod database)
> Fix refunder

- crates/orderbook/openapi.yml
This PR updates the openapi definition for QuoteRequest to match the code https://github.com/cowprotocol/services/blob/main/crates/model/src/order.rs#L455-L473
It adds the optional `appDataHash` when `appData` is set to a stringified JSON with the full appData.
Unit tests
Locally generate the types on the SDK repo
> chore: update appData fields to QuoteRequest openapi definition
