cowprotocol/services

- crates/contracts/src/lib.rs
- crates/solver/src/pending_transactions.rs
> Fix rust 1.60 warnings

- crates/orderbook/src/main.rs
- crates/shared/src/http_solver.rs
- crates/shared/src/price_estimation/quasimodo.rs
- crates/solver/src/analytics.rs
- crates/solver/src/main.rs
- crates/solver/src/metrics.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/http_solver.rs
Fixes https://github.com/cowprotocol/services/issues/150
CI and manually tested that the argument works
> Allow passing external solvers as list

- README.md
> Update readme with Windows build fail info

- Cargo.lock
- crates/orderbook/Cargo.toml
- crates/orderbook/src/fee.rs
- crates/orderbook/src/gas_price.rs
- crates/orderbook/src/metrics.rs
- crates/shared/Cargo.toml
- crates/shared/src/gas_price_estimation.rs
- crates/shared/src/price_estimation/baseline.rs
- crates/solver/Cargo.toml
- crates/solver/src/driver.rs
- crates/solver/src/lib.rs
- crates/solver/src/settlement_post_processing/mod.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/settlement_submission/submitter.rs
- crates/solver/src/settlement_submission/submitter/custom_nodes_api.rs
- crates/solver/src/settlement_submission/submitter/eden_api.rs
- crates/solver/src/settlement_submission/submitter/flashbots_api.rs
Part of https://github.com/cowprotocol/services/issues/119 .
https://github.com/cowprotocol/gas-estimation/pull/3 has to be merged and tagged.
CI and unit tests
> Remove legacy fee

- crates/solver/src/driver.rs
CI, manual inspection of the api endpoint later
> Set block during simulation for solver competition

- crates/alerter/src/main.rs
The old end point is deprecated
Part of https://github.com/cowprotocol/services/issues/254
CI
> Use auction endpoint in alerter

- crates/orderbook/src/database/orders.rs
@nlordell this fixes the CI build for #250 in order to merge it
> fix clippy warning for Order type refactor

- crates/alerter/src/main.rs
Part of https://github.com/cowprotocol/services/issues/254
Was reviewing the code more and found this theoretical false positive.
CI
> Fix potential false positive in alerter

- crates/orderbook/src/api/post_solver_competition.rs
This gives better rejection messages.
CI
> Use path filter first before method

- crates/orderbook/src/main.rs
- crates/solver/src/main.rs
Re-adds the word "arguments" and starts then on a new line.
CI
> Make argument log prettier

- crates/shared/src/bad_token/token_owner_finder/blockscout.rs
After changing the error log to a warning in https://github.com/cowprotocol/services/pull/291 it would still be nice to get an alert about this component failing sometimes. With this PR we can do this based on metrics.
CI
> Add metrics to blockscout TokenOwnerFinding

- crates/orderbook/src/order_quoting.rs
This PR implements `find_quote` more correctly and deals with scaling `{sell,buy}_amount` values in the produced quote as well as detecting mis-matches when querying by ID.
This is the final step before implementing database access and then we should be able to use the quoter API in `POST api/v1/quote` as well for verifying fees when creating orders in `POST api/v1/orders`.
Added unit tests to check the search logic.
> Implement quote finding

- crates/orderbook/src/main.rs
Creating a `RateLimiter` will initialize the associated metrics which will lead to grafana showing a graph for it after #305 even if it is not used at all. To avoid confusion I delayed the creation of the `RateLimiter` until it's actually needed.
Now the presence of a graph in this [panel](https://dashboard-projects.gnosis.io/d/oPiE1Ennz/alerts-prod?editPanel=55&orgId=2&from=now-30m&to=now) means that the price estimator was actually enabled on that network in that time.
> Only create RateLimiter if it is needed

- Cargo.lock
- crates/database/Cargo.toml
- crates/database/src/lib.rs
- crates/e2e/Cargo.toml
- crates/e2e/tests/e2e/services.rs
- crates/orderbook/Cargo.toml
- crates/orderbook/src/database.rs
- crates/orderbook/src/database/events.rs
- crates/orderbook/src/database/orders.rs
- crates/orderbook/src/database/quotes.rs
- crates/orderbook/src/database/trades.rs
- crates/orderbook/src/lib.rs
This is needed by any crate running unit tests on the db.
CI
Optionally add notes, suggestions and warnings for the releaser. They will be included in the release changelog.
> Move common database operations into same crate

- crates/model/src/ratio_as_decimal.rs
- crates/model/src/u256_decimal.rs
> Fix Rust 1.62 warnings

- .github/workflows/deploy.yaml
- Cargo.lock
- README.md
- crates/contracts/build.rs
- crates/model/src/lib.rs
- crates/orderbook/Cargo.toml
- crates/orderbook/openapi.yml
- crates/orderbook/src/main.rs
- crates/shared/Cargo.toml
- crates/shared/src/arguments.rs
- crates/shared/src/gas_price_estimation.rs
- crates/shared/src/sources.rs
- crates/shared/src/sources/balancer_v2/pool_init.rs
- crates/shared/src/sources/sushiswap.rs
- crates/shared/src/sources/uniswap_v2.rs
- crates/solver/Cargo.toml
- crates/solver/src/settlement_submission/submitter.rs
Adds Görli support in the services.
Known to be working:
- Price estimations from Uniswap & Sushiswap
- Settling orders with [Uniswap](https://goerli.etherscan.io/tx/0x3c87600cb7606c45faafbbb185f52de8cd069cca251b8fcf437e41ae365c3a6a) & [Sushiswap](https://goerli.etherscan.io/tx/0x68cff45c86df9ae0a7e73cc6a4001e6c80ffe6b2d76d32563c4371926abeb94d)
- [Naive](https://goerli.etherscan.io/tx/0x5e815c264212d515f51ebbebe693c7172fb1d1707a92aabaf570867b522ba0c1) and [baseline](https://goerli.etherscan.io/tx/0xa0f8057abda5b554ed676c50d6f53f522d1d9d83799d675043ccd42d2f01dadf) solvers
- Web3, GnosisSafe, and Naive price estimator (see [already merged related PR](https://github.com/cowprotocol/gas-estimation/pull/5) for safe estimator)
Known not to work:
- Balancer (not all contracts needed are …
> Add Görli network

- crates/orderbook/src/order_quoting.rs
Currently we only need the native price of the `sell_token` during quote creation so we only query that [[0](https://github.com/cowprotocol/services/blob/main/crates/orderbook/src/order_quoting.rs#L425)]. Later when we try to build the auction we require the native price of the `sell_token` **AND** `buy_token` of each order [[1](https://github.com/cowprotocol/services/blob/main/crates/orderbook/src/solvable_orders.rs#L409-L414)].
That means we allow creating orders for which we can't compute the native price of the `buy_token` although we will never be able to settle them. That is a bad UX and happened [here](https://cowservices.slack.com/archives/C0361CDD1FZ/p1657565960978469?thread_ts=1657565724.533559&cid=C0361CDD1FZ) where the user wanted to buy [staked …
> Require native buy token price before creating quote

- crates/database/Cargo.toml
- crates/database/src/lib.rs
- crates/database/src/orders.rs
- crates/orderbook/src/database/orders.rs
- crates/orderbook/src/database/quotes.rs
> Move insert_order into database crate

- crates/database/src/byte_array.rs
- crates/database/src/orders.rs
- crates/orderbook/src/database/orders.rs
> Move insert_quote into database crate

- Cargo.lock
- crates/database/Cargo.toml
- crates/database/src/orders.rs
- crates/orderbook/Cargo.toml
- crates/orderbook/src/database/orders.rs
no logic change (except slight changes to tests because they're using a slightly different api)
existing and refactored unit tests
> Move remaining order functions into database crate

- Cargo.lock
- crates/database/Cargo.toml
- crates/database/src/lib.rs
- crates/database/src/quotes.rs
- crates/orderbook/src/database/quotes.rs
> Move quotes module into database

- Cargo.lock
- crates/shared/Cargo.toml
- crates/shared/src/http_solver.rs
- crates/shared/src/http_solver/model.rs
> Support gzip compressed http responses

- crates/solver/src/driver.rs
Diff easier to understand without whitespace changes.
CI
> Store tx hash for reverted transactions in solver_competition

- .github/workflows/deploy.yaml
Like the other pods it should restart in staging when we create a new image.
Observe afterwards
> Autodeploy autopilot

- Cargo.lock
- crates/autopilot/Cargo.toml
- crates/autopilot/src/arguments.rs
- crates/autopilot/src/lib.rs
Before moving more features from orderbook to autopilot.
Before merging need to double check we're setting the argument on staging.
CI, local run
> Initialize node connection in autopilot

- crates/e2e/tests/e2e/services.rs
- crates/orderbook/src/lib.rs
- crates/orderbook/src/main.rs
- crates/orderbook/src/order_validation.rs
- crates/orderbook/src/orderbook.rs
- crates/orderbook/src/solvable_orders.rs
- crates/shared/src/account_balances.rs
- crates/shared/src/lib.rs
This module is needed in orderbook and autopilot. Later I might do a fine grained refactor move some things out of shared again.
CI
> Move account balance module into shared

- crates/orderbook/src/main.rs
- crates/orderbook/src/metrics.rs
- crates/shared/src/price_estimation/instrumented.rs
> Refactor price estimator metrics to macro

- crates/orderbook/src/main.rs
- crates/orderbook/src/metrics.rs
- crates/shared/src/price_estimation/native_price_cache.rs
> Refactor native price estimator metrics with macro

- crates/shared/src/sources/uniswap_v3/pool_fetching.rs
- crates/solver/src/liquidity_collector.rs
Added logs for UniswapV3 pool fetching and caching. I want to make sure the caching is working as expected and check if any tweaks are needed.
Expected to remove the logs after the analysis.
> Add logs for UniswapV3 pool fetching

- crates/shared/src/bad_token/token_owner_finder/blockscout.rs
This PR improves Blockscout token finder error handling. The motivation here is that debugging that Blockscout was down issue was not as easy as it should have been.
Specifically, it now:
- We correctly propagate HTTP errors (previously, HTTP status codes were ignored)
- We report errors in the metrics for any kind of request error (previously, we only recorded errors if there was an HTTP transport-level error, things like HTTP error status codes and failure to parse the response body would be recorded as `"ok"`)
- Add additional error logging.
Run the orderbook and checkout the new logs:
```
...
2022-08-09T12:14:33.197Z DEBUG request{id=0}: shared::bad_token::token_owner_finder::blockscout: Response from Blockscout API status=503 Service Unavailable body=<html><script …
```
> Improve error logging and handling for Blockscout token owner finder

- crates/solver/src/driver.rs
We used to have an issue where the driver would sometimes see the same solver competition id as it used in the previous auction again, because the auction didn't get updated before the driver entered its next run loop. We fixed this by synchronously updating the auction when solver competition info is stored. This was removed with the PR that made autopilot create auctions as this this synchronization was no longer reasonably possible.
This PR adds a different fix to the driver. We wait up to 10 seconds to see the competition id increment. This will probably become obsolete soon too when we move to using auction ids generated by autopilot instead if solver competition ids (which were always a temporarily solution until we got real auction ids) but I'm not sure I'll be able to make this …
> Wait for auction competition id to change in driver

- README.md
This PR just updates the README to include some more up-to-date information on the project.
> updated readme to more prominently include info on autopilot

- Cargo.lock
- crates/autopilot/Cargo.toml
- crates/driver/Cargo.toml
- crates/orderbook/Cargo.toml
- crates/shared/Cargo.toml
- crates/solver/Cargo.toml
with fix for potential panic
CI, i will observe the warning log message added to gas-estimation
> Update gas estimation dependency

- crates/driver/src/auction_converter.rs
- crates/driver/src/commit_reveal.rs
- crates/driver/src/driver.rs
Because every driver will only be allowed to return a single `SettlementSummary` per auction it makes sense to build an abstraction which continuously solves the auction until the deadline is almost up and then submits the result from the most recent block.
This can be done in 2 ways:
`1`: Simply adapt `self.block_stream` to convert the auction and solve it on every new block in the usual way.
`2`: Adapt `self.block_stream` such that converting and solving the auction happens in a background task.
`1` is simpler but `2` yields more up-to-date results.
Let's assume the following:
* time to solution for the first block is 5 seconds
* 1 second after the starting the first computation a new block arrives
* time to solution for the second block is 3 seconds
Then 1) results in:
```
0s …
```
> Continuously solve auction with updated liquidity in new driver

- Cargo.lock
- crates/alerter/src/main.rs
- crates/autopilot/src/main.rs
- crates/driver/src/main.rs
- crates/e2e/tests/e2e/eth_integration.rs
- crates/e2e/tests/e2e/onchain_settlement.rs
- crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
- crates/e2e/tests/e2e/vault_balances.rs
- crates/orderbook/src/main.rs
- crates/shared/Cargo.toml
- crates/shared/src/exit_process_on_panic.rs
- crates/shared/src/lib.rs
- crates/shared/src/tracing.rs
- crates/solver/src/main.rs
Fixes https://github.com/cowprotocol/services/issues/514 . The issue and the comment in the PR explains more reasoning.
new manual test and CI shows that e2e tests don't panic
> Exit process if thread panics

- Cargo.lock
- crates/autopilot/Cargo.toml
- crates/contracts/Cargo.toml
- crates/driver/Cargo.toml
- crates/e2e/Cargo.toml
- crates/orderbook/Cargo.toml
- crates/shared/Cargo.toml
- crates/solver/Cargo.toml
- crates/testlib/Cargo.toml
Updating the ethcontract version
> Ethcontract-rs version 0.20.0

- crates/autopilot/src/solvable_orders.rs
- crates/orderbook/src/orderbook.rs
- crates/shared/src/current_block.rs
This would have been helpful when investigating why auction was out of date today.
CI
> Log current block number in more places

- crates/database/src/lib.rs
- crates/database/src/order_rewards.rs
- database/sql/V032__order_rewards.sql
Part of https://github.com/cowprotocol/services/issues/606 .
In another PR we are going to be storing the rewards in this table.
CI
> Add order_rewards table

- crates/shared/src/price_estimation/baseline.rs
- crates/shared/src/price_estimation/http.rs
- crates/shared/src/sources/uniswap_v2/pool_fetching.rs
As promised in #612 (separate PR so that it gets a proper review)
If accepted, I might also add code for the already added empty unit tests in this file
This.
> Unit test for HTTP gas price estimation

- crates/model/src/auction.rs
to fix shadow solver running on staging at prod endpoint.
CI
> Mark rewards as default

- Cargo.lock
- crates/autopilot/Cargo.toml
- crates/autopilot/src/arguments.rs
- crates/autopilot/src/lib.rs
- crates/autopilot/src/risk_adjusted_rewards.rs
- crates/autopilot/src/solvable_orders.rs
- crates/e2e/tests/e2e/services.rs
part of https://github.com/cowprotocol/services/issues/606
Implements the calculation as laid out in the CIP and sets up autopilot to use it.
CI, new unit tests
> Implement cip-14 risk adjusted reward calculation

- Cargo.lock
- crates/autopilot/Cargo.toml
- crates/autopilot/src/database/onchain_order_events/ethflow_events.rs
Inserting the wrapAll pre-interaction for ethflow orders.
I will add an e2e test once all PRs are merged
> Pre interactions: Insert pre-interactions for ethflow orders

- crates/solver/src/solver/http_solver.rs
Related to https://github.com/cowprotocol/services/issues/334 .
This log was useful at some point but I don't think it has been used much recently. It is very large which puts needless pressure on logging systems.
CI
> Make http solver instance log trace

- crates/solver/src/liquidity/order_converter.rs
After the introduction of the field `OrderMetadata::class` storing `OrderSettlementHandler::is_liquidity_order` became redundant.
This PR simply drops the unnecessary `is_liquidity_order` field and recovers the liquidity order state from the `class` field. Just a small clean up I saw while working on limit order support.
none
> Drop redundant liquidity order field

- crates/database/src/orders.rs
We improve the performance as some users experience a significant slow-down since th[e last PR.](https://github.com/cowprotocol/services/pull/610) 
See discussion [here](https://cowservices.slack.com/archives/C0361CDD1FZ/p1667035528153689):
I added another test -called postgres_user_orders_performance_user_with_many_orders  - that actually tests the case of one user having a lot of orders (like 100k orders). I tried different implementations and measured the performance:
Implementations
UNION: This is implementation as on main branch right now.
OR: This is the implementation of this PR
UNION with ordering twice: This adds additional orderings to each subtable in the UNION solution. The hope was that these orderings could be used by postgres to end queries early.
In the following I …
> Improving user orders performance

- crates/autopilot/src/auction_transaction.rs
- crates/autopilot/src/database.rs
- crates/autopilot/src/database/auction_transaction.rs
- crates/autopilot/src/lib.rs
- crates/database/src/auction_transaction.rs
- crates/database/src/lib.rs
- crates/orderbook/src/database/solver_competition.rs
- database/sql/V037__auction_transaction.sql
Part of https://github.com/cowprotocol/services/issues/634
I describe the design in detail in comments, not repeating here.
Still need to write a couple of sql tests but I thought this could be reviewed already.
The other todo comments that would enable the new functionality will be done in a follow up PR.
CI
> Implement more resilient auction id to tx hash association

- Cargo.lock
- crates/refunder/Cargo.toml
- crates/refunder/src/refund_service.rs
- crates/solver/src/liquidity/uniswap_v3.rs
Reuses now_in_epoch_seconds() in two places in the code.
> Reuse now_in_epoch_seconds()

- crates/driver/src/driver.rs
- crates/driver/src/main.rs
- crates/solver/src/driver.rs
- crates/solver/src/driver_logger.rs
- crates/solver/src/settlement_submission.rs
- crates/solver/src/settlement_submission/submitter.rs
CI e2e tests and will do manual test after merge
> Finish driver side of competition account-nonce storing

- crates/database/src/solver_competition.rs
- crates/driver/src/driver.rs
- crates/driver/src/main.rs
- crates/model/src/solver_competition.rs
- crates/orderbook/src/database/solver_competition.rs
- crates/solver/src/driver.rs
- crates/solver/src/driver_logger.rs
- crates/solver/src/settlement_submission.rs
- crates/solver/src/settlement_submission/submitter.rs
After this we need one more PR to populate the new field in driver.rs .
CI, new unit tests
> Finish autopilot side of competition account-nonce storing

- crates/solver/src/solver/http_solver.rs
I was looking into why Quasimodo was not being as successful as it should in the high volume times this evening, and noticed in local tests that the index of the liquidity AMM models didn't line up with the liquidity in the `SettlementContext` used for settlement encoding.
The reason is that the index that we use for matching AMM models to liquidity when encoding was being generated by enumerating all liquidity _with limit orders (like 0x) filtered out_ while the liquidity vector in the `SettlementContext` _still contained the limit orders_.
This PR addresses this by splitting the `orders` and `amms` early on in the `prepare_model` function to make sure we use them consistently throughout. This might also be the cause for Uniswap V3 liquidity not encoding correctly, but I did not confirm …
> Fix HTTP Solver Liquidity Indexing

- crates/shared/src/ethrpc/buffered.rs
I noticed when debugging that we only log `TRACE` logs for the buffered transport if they are single calls, and not if they are batched calls. This PR fixes that.
CI.
> Log Batched Buffered Requests

- crates/database/src/orders.rs
- crates/orderbook/src/database/orders.rs
Calculates the expired status based on the ethflow valid to.
Added unit tests
> Mark expired ethflow orders as such

- crates/model/src/order.rs
- crates/orderbook/openapi.yml
Tiny fix to go with our normal standard.
> Camel case for ethflow data in API

- crates/refunder/src/refund_service.rs
This is for @josojo in https://github.com/cowprotocol/services/pull/759/ . Couldn't attach it as a suggestion properly there. The PR goes into your branch. If you like it you can unmark it as draft and merge it.
> Refactor suggestion

- database/sql/V043__surplus_fee_null.sql
Fixes https://cowservices.slack.com/archives/C037PB929ME/p1668708218880869.
Tested manually.
> Migrate null surplus fees to 0 for limit orders

- .github/workflows/deploy.yaml
I believe this PR fixes the issue with the autodeployment, as we aren't running on mainnet but on Görli. I didn't really investigate however.
None!
> Fix autodeployment failure

- crates/shared/src/http_solver/model.rs
- crates/solver/src/settlement_rater.rs
Follow up PR for https://github.com/cowprotocol/services/pull/918
Forwards gas price to solvers in case of simulation failure since it might be relevant for reconstruction of failure.
Updated unit tests.
Notify solvers.
> Forward GasPrice to Solvers

- crates/autopilot/src/limit_orders/quoter.rs
This PR instruments the surplus fee update loop in order to make it easier to debug individual limit order surplus fee computation.
Run the autopilot and see the instrumented logs:
```
% cargo run -p autopilot
...
2022-12-12T09:12:33.176Z DEBUG surplus_fee{order=0xddcd865d5b03546eb46fe562d03eff4cf26d61e5d11b4d1ac5dd1e5222cf014adbc682d0ec19bd276fd6c2af4e0189b584bb31e16396f509}: shared::order_quoting: computed quote quote=Quote { id: None, data: QuoteData { sell_token: 0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6, buy_token: 0x91056d4a53e1faa1a84306d4deaec71085394bc8, quoted_sell_amount: 1000000000000000000, quoted_buy_amount: 7185168209849445686407, fee_parameters: FeeParameters { gas_amount: 220417.0, gas_price: 1043790217.0, sell_token_price: 1.0 }, kind: Sell, expiration: …
```
> Add Tracing Span to Surplus Fee Computation

- crates/autopilot/src/database/orders.rs
- crates/autopilot/src/limit_orders/quoter.rs
- crates/database/src/orders.rs
This reverts commit 84c60f8c3053ab6c5a3b0660e527bb3e991b0f2f.
After mering that PR we saw a panic on staging so it probably caused it. While I'm investigating, let's undo it.
CI, just a git rever
> Revert "Prevent limit order fee updater from getting stuck (#965)"

- crates/autopilot/src/database/orders.rs
- crates/autopilot/src/limit_orders/quoter.rs
- crates/database/src/orders.rs
- crates/e2e/tests/e2e/limit_orders.rs
We reverted this PR because of a panic. The panic has been independently fixed so now the PR can be applied again. There are no changes to the version that has already been reviewed.
CI
> Reapply #965

- crates/e2e/tests/e2e/limit_orders.rs
- crates/e2e/tests/e2e/services.rs
I observed this e2e test failing in a PR that didn't touch relevant code.
e2e test still works
> Fix flaky e2e test

- crates/autopilot/src/database/onchain_order_events.rs
- crates/orderbook/src/api/get_user_orders.rs
- crates/solver/src/solver/single_order_solver.rs
from the most recent rust release.
CI
> Fix clippy lints

- crates/shared/src/tracing.rs
When we created the current panic handler, it was not possible to manually print the stacktrace. We relied on logging an error message first and the panic being printed immediately after.
With one of the recent rust versions it became possible to emulate the output of the default panic handler. This has the advantage that we can form a single proper log message with the panic message.
I noticed that sometimes panics don't correctly show up in Kibana, which is fixed by this PR.
manual test of panic output
To test you can run `cargo test --package shared --lib -- exit_process_on_panic::tests::manual_thread --exact --nocapture --ignored` with and without the new panic hook. The output is the same except that the new hook prints some extra frames in the stack trace that the default hook …
> Improve panic logging

- crates/alerter/src/main.rs
This PR refactors the limit order inclusion check to be linear instead of quadratic in the `alerter`. Given the orderbook size of ~500 orders, I do think this may start to pay off at this point.
Run the alerter and see it do its thing.
> Linear Order Matching Algorithm in `alerter`

- crates/alerter/src/main.rs
This PR adds an additional log message to the alerter so that it reports the closed orders that it is investigating.
Run the alerter, and see it log closed orders:
```
% cargo run -p alerter -- --update-interval 1
...
2023-01-02T08:42:42.894Z DEBUG alerter: found 383 open orders
2023-01-02T08:42:42.894Z DEBUG alerter: found no fulfilled orders
2023-01-02T08:42:44.035Z DEBUG alerter: found 370 open orders
2023-01-02T08:42:44.035Z DEBUG alerter: found closed order order=0x3aabc97249e91af1c4022808634ec66ff86c3d98d4ea7bd19cd5f34798d59391b8f26c1cc45ab62fd750e08957fba5738094bbdb6426fb10
2023-01-02T08:42:44.095Z DEBUG alerter: found closed order order=0xf9457a2881f0557b5aea2215439ef44e8883e3770d65af2b14511efa63765f264be670ee941d277bdb16281ce5b0136e9a8743c564913214
2023-01-02T08:42:44.141Z DEBUG …
```
> Log Closed Orders in Alerter

- crates/driver/src/boundary/settlement.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/solver/http_solver.rs
- crates/solver/src/solver/http_solver/settlement.rs
Clone isn't needed and we reduce memory usage by not cloning.
existing tests
> Don't clone auction context

- crates/alerter/src/main.rs
Fixes https://github.com/cowprotocol/services/issues/1017
Changes:
- Try to find closed market orders first.
- Locally rate limit the outgoing /api/orders requersts
manually ran alerter
> Fix alerter getting rate limited by api

- crates/solvers/openapi.yml
- crates/solvers/src/api/dto.rs
- crates/solvers/src/api/dto/auction.rs
- crates/solvers/src/api/dto/mod.rs
- crates/solvers/src/api/dto/solution.rs
- crates/solvers/src/domain/auction.rs
- crates/solvers/src/domain/mod.rs
- crates/solvers/src/domain/solution.rs
- crates/solvers/src/util/conv.rs
- crates/solvers/src/util/mod.rs
This PR introduces the auction and solver domain models and adds conversion boiler plate between the their equivalent DTOs.
Rust Compiler, and a pinky promise for E2E test suite that covers the new logic.
> Introduce Auction and Solution Domain Models

- crates/driver/src/boundary/liquidity/mod.rs
- crates/driver/src/boundary/liquidity/uniswap/v2.rs
- crates/driver/src/boundary/settlement.rs
- crates/driver/src/domain/liquidity/uniswap/v2.rs
- crates/driver/src/infra/blockchain/contracts.rs
- crates/driver/src/infra/blockchain/mod.rs
- crates/driver/src/infra/liquidity/config.rs
- crates/driver/src/infra/simulator/tenderly/dto.rs
- crates/driver/src/infra/solver/dto/auction.rs
- crates/driver/src/infra/solver/dto/solution.rs
- crates/solvers/openapi.yml
- crates/solvers/src/api/dto/auction.rs
- crates/solvers/src/api/dto/solution.rs
- crates/solvers/src/tests/baseline/direct_swap.rs
This PR applies some fixes to the driver <> solver engine API boundary so that the two pieces are finally working together 🎉.
It contains some small fixes to get the `driver` working with `solvers baseline`:
- Add liquidity to the solver engine auction DTO
- Fix Tenderly access list serialization
- Serialize liquidity IDs as strings as per the OpenAPI spec (note that their internal representation remains `usize`).
- Change solver engine `gasEstimate` field to be a big integer
- Fix solver engine interaction tagged enum serialization
With these fixes, we are ready for 🚀!!!
We can run a driver+solver combo configured for Mainnet and actually `/solve`!
1. Run the baseline solver engine
```
cargo run -p solvers -- baseline --weth 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
```
2. Run the …
> Driver <> Solver Engine Boundary Fixes

- crates/orderbook/src/orderbook.rs
Our Grafana query for detecting no trades currently does not work when we restart the service and no new order gets created afterwards. To make the query work in those cases I initialized the counter values to 0 when creating the `Orderbook` instance.
[related alert](https://cowservices.slack.com/archives/C0371SB243E/p1674177084465269)
Ran orderbook locally and checked initialized metrics:
```
gp_v2_api_orderbook_orders{kind="limit",operation="cancelled"} 0
gp_v2_api_orderbook_orders{kind="limit",operation="created"} 0
gp_v2_api_orderbook_orders{kind="liquidity",operation="cancelled"} 0
gp_v2_api_orderbook_orders{kind="liquidity",operation="created"} 0
gp_v2_api_orderbook_orders{kind="user",operation="cancelled"} 0
gp_v2_api_orderbook_orders{kind="user",operation="created"} 0
```
> Init orderbook metrics

- crates/autopilot/src/database/onchain_order_events.rs
PR #1090 introduced error metrics for onchain orders. This PR adds a missing error condition where the provided quote is valid but the price is worse than what was quoted.
Unit tests.
> Add out-of-market-price error to onchain order metrics

- crates/driver/src/boundary/mempool.rs
- crates/driver/src/domain/competition/mod.rs
- crates/driver/src/domain/competition/solution/mod.rs
- crates/driver/src/domain/competition/solution/settlement.rs
- crates/driver/src/infra/solver/dto/solution.rs
- crates/driver/src/tests/cases/settle.rs
- crates/driver/src/tests/cases/solve.rs
- crates/solver/src/settlement_submission.rs
- crates/solver/src/settlement_submission/submitter.rs
Fixes https://github.com/cowprotocol/services/issues/1095.
Encodes solution ID as part of the onchain settlement.
Added an automated test.
> Encode solution ID in the settlement

- Cargo.lock
- crates/autopilot/Cargo.toml
- crates/autopilot/src/driver_api.rs
- crates/autopilot/src/driver_model.rs
- crates/autopilot/src/lib.rs
- crates/autopilot/src/run_loop.rs
- crates/autopilot/src/solvable_orders.rs
- crates/driver/openapi.yml
- crates/e2e/tests/e2e/services.rs
Part of https://github.com/cowprotocol/services/issues/862 .
Implements the first part of the run loop in autopilot.
Does not run yet. Will be tested by e2e tests eventually.
> Sketch out autopilot run loop

- crates/shared/src/bad_token/trace_call.rs
Add comment where to read about common cause of the failure. 
When investigated the issue, I came to this line and could not make any further progress.
Context: https://cowservices.slack.com/archives/C0375NV72SC/p1674661229317249
> Add documentation for balance_of failure

- Cargo.lock
- crates/autopilot/Cargo.toml
- crates/autopilot/src/driver_model.rs
- crates/autopilot/src/run_loop.rs
I'm making some PRs focused on getting something actually runnable without perfect correctness. This PR implements the main competition logic in autopilot. Next one will like contain the finding of the transaction.
not yet
> Continue autopilot competition implementation

- crates/driver/src/domain/competition/mod.rs
- crates/driver/src/domain/liquidity/mod.rs
- crates/driver/src/infra/config/file/mod.rs
- crates/driver/src/infra/solver/dto/auction.rs
- crates/driver/src/main.rs
> Remove global `#[allow(dead_code)]` in `driver`

- crates/solver/src/metrics.rs
Since mostly Quasimodo and MIP were responsible for solver run alerts, it is very likely that we have "No Data" issues with this alert because of missing `failure` label metrics. This PR initializes solver run metrics so this doesn't happen.
CI.
> Reset Solver Run Outcome Metrics

- crates/autopilot/src/run_loop.rs
Derives some parameters for waiting for the transaction based on the network block interval. It might seem like we should  keep the deadline in real time but we're going to eventually communicate the deadline to the Solver and for that keeping it in blocks makes more sense. At that point we would remove MAX_WAIT_TIME in favor of something configurable.
Fixes https://github.com/cowprotocol/services/issues/1137 
not yet
> Use network block interval in autopilot run loop

- crates/shared/src/price_estimation/native_price_cache.rs
Allows us to measure the size of the cache and the update throughput.
CI, see metrics after merging
> Add more metrics to native price cache

- crates/solver/src/solver/single_order_solver.rs
The match rate for market orders currently doesn't look great. This PR makes it so that our single order solvers always try to settle market orders first and only then work on limit orders.
CI
> Single order solvers always try settling market orders first

- crates/shared/src/http_solver/model.rs
- crates/solver/src/settlement.rs
Issue tracker: https://github.com/cowprotocol/services/issues/1108
Starts with implementing https://github.com/cowprotocol/services/issues/1114
> SolverRewards: Add score to Settlement

- crates/shared/src/price_estimation/native_price_cache.rs
While working with this module I noticed a couple of details that I'd like to change:
- Create a new struct for the update task to group its data.
- Move all other fields into `Inner`.
- Don't explicitly store `Metrics`.
existing tests
> Small native price cache refactor

- crates/autopilot/src/lib.rs
- crates/orderbook/src/run.rs
- crates/shared/src/arguments.rs
Needed for e2e tests.
CI, new functionality is not yet used or tested
> Allow configurable settlement contract and native token address

- crates/solvers/Cargo.toml
- crates/solvers/src/lib.rs
- crates/solvers/src/main.rs
- crates/solvers/src/run.rs
- crates/solvers/src/tests/mod.rs
This allows it to be easily used in e2e tests.
no logic change
> Make solvers crate usable as library

- crates/autopilot/src/limit_orders/metrics.rs
- crates/solver/src/metrics.rs
Factored out of https://github.com/cowprotocol/services/pull/1229 .
Without the `MetricStorage` derive, initializing the metrics fails when this is done in tests that run after eachother in the same `cargo test` run. This happens on CI when running e2e tests. With the derive this works fine.
CI, after merge check staging Grafana dashboard in case of broken metrics due to accidental rename
> Fix metrics not being allowed to initialize twice

- crates/shared/src/arguments.rs
- crates/shared/src/sources/uniswap_v2.rs
Better argument help message and better printing of the argument if set.
CI, manual test
> Improve custom univ2 liquidity argument formatting

- crates/autopilot/src/driver_api.rs
> Provide more error context for autopilot driver request

- crates/database/src/auction_participants.rs
- crates/database/src/auction_prices.rs
- crates/database/src/auction_transaction.rs
- crates/database/src/events.rs
- crates/database/src/lib.rs
- crates/database/src/settlement_observations.rs
- crates/database/src/settlement_scores.rs
- crates/database/src/settlements.rs
- database/sql/V048__create_settlement_rewards.sql
Autopilot and orderbook callsite functions will be introduced in a follow up PR.
> SolverRewards 3: Updated db schema and read/write functions

- crates/autopilot/src/arguments.rs
- crates/autopilot/src/lib.rs
- crates/database/src/auction_participants.rs
- crates/database/src/settlement_scores.rs
- crates/database/src/settlements.rs
- crates/e2e/tests/e2e/limit_orders.rs
- crates/e2e/tests/e2e/onchain_settlement.rs
- crates/e2e/tests/e2e/services.rs
- crates/e2e/tests/e2e/settlement_without_onchain_liquidity.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
- crates/e2e/tests/e2e/vault_balances.rs
- crates/model/src/solver_competition.rs
- crates/orderbook/src/database/solver_competition.rs
- crates/shared/src/arguments.rs
- crates/solver/src/arguments.rs
- crates/solver/src/driver.rs
- crates/solver/src/main.rs
- database/sql/V048__create_settlement_rewards.sql
Populates database tables `settlement_scores` and `auction_participants`.
> SolverRewards 4: Populate scores and participants

- crates/driver/src/domain/competition/mod.rs
- crates/driver/src/domain/competition/solution/mod.rs
Context from https://github.com/cowprotocol/services/pull/1268 . 
still compiles, no test for simulations actually not happening
> Do not simulate empty solution

- database/sql/V048__create_settlement_rewards.sql
https://github.com/cowprotocol/services/pull/1279#discussion_r1118823720
Fixes code review comments for database sql file.
> SolverRewards 7: Fix sql comments and formating

- crates/solver/src/driver.rs
After further debugging I found another edge case that doesn't work well with current score ordering.
Lets say we have already ordered solutions `(hash, score)`:
```
[
(0x1, 0), // rank 3
(0x2, 0), // rank 2
(0x3, 0), // rank 1
]
```
Previous code would sort them by score, but since scores are the same, `std::cmp::Reverse` would also do nothing and we would publish `(0x1, 0)` as winner which is not aligned with the ranking.
I changed the code to order by ranking which is straight forward. Note that reverse is no longer needed since for ranking we need ascending order, starting from `1`.
> SolverRewards 11: Sort settlements by ranking

- crates/autopilot/src/limit_orders/quoter.rs
- crates/database/src/orders.rs
This was brought up in https://github.com/cowprotocol/services/pull/1295#discussion_r1121685830 .
The limit order quoter should not quote partially fillable limit orders. This doesn't matter at the moment because we don't allow partially fillable limit orders to be created but it is going to matter soon.
CI, adapted tes
> Do not quote partially fillable limit orders

- crates/autopilot/src/solvable_orders.rs
- crates/e2e/tests/e2e/main.rs
- crates/e2e/tests/e2e/partially_fillable.rs
part of https://github.com/cowprotocol/services/issues/1290
new e2e test
> Test that auction includes partially fillable limit order

- crates/shared/src/price_estimation/sanitized.rs
Filter out estimates with 0 amounts with the `SanitizedPriceEstimator`. This avoids forwarding these bad queries and causing actual API requests.
Added a unit test case for this.
> Filter Out Zero Amount Estimates

- crates/shared/src/oneinch_api.rs
Reports 1Inch error that can not be parsed as a RestError with the status code of the unparsable response. This can inform callers how to handle that error (e.g. rate limiting).
> Handle malformed 1Inch responses

- crates/shared/src/price_estimation/factory.rs
- crates/shared/src/price_estimation/http.rs
Yearn doesn't use the liquidity so there is no reason to send a huge request (liquidity makes up for most of the size) to them.
compiles, no test that liquidity really isn't sent because code is simple enough
> Do not send liquidity to Yearn

- crates/driver/src/domain/quote.rs
> Fix rust 1.68 warnings

- crates/solver/src/arguments.rs
Moves CIP20 activation to next week.
> CIP20 move activation date

- crates/solver/src/settlement_submission/submitter.rs
In debugging settlement submission, I added a few more unit tests that verify the submitter's gas estimation logic.
Just adding them to the code-base more permanently.
These are the tests.
> Add Unit Tests for Submitter Estimator

- crates/driver/src/boundary/settlement.rs
- crates/driver/src/domain/competition/order/mod.rs
- crates/driver/src/domain/competition/solution/mod.rs
- crates/driver/src/domain/competition/solution/settlement.rs
- crates/driver/src/infra/api/error.rs
- crates/driver/src/tests/cases/verify_internalization.rs
Fixes https://github.com/cowprotocol/services/issues/1009.
The last missing piece for solution verification: simulating the settlement without internalizing any interactions.
Added an automated test.
> `driver`: simulate non-internallized interactions as part of solution verification

- crates/solvers/config/example.legacy.toml
This PR just adds a sample Legacy solver configuration for documentation purposes.
```
cargo run -p solvers -- legacy --config crates/solvers/config/example.legacy.toml
```
> Add Example Legacy Solver Adapter Configuration

- crates/shared/src/trade_finding/zeroex.rs
- crates/shared/src/zeroex_api.rs
- crates/solver/src/arguments.rs
- crates/solver/src/run.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/zeroex_solver.rs
- crates/solvers/src/infra/config/dex/zeroex/file.rs
- crates/solvers/src/infra/dex/zeroex/dto.rs
- crates/solvers/src/infra/dex/zeroex/mod.rs
- crates/solvers/src/tests/mock/http.rs
- crates/solvers/src/tests/zeroex/market_order.rs
- crates/solvers/src/tests/zeroex/options.rs
This PR adds support for RFQ-T liquidity to the 0x solver.
Specifically, it sets `takerAddress` and `intentOnFilling=true` for 0x quotes. We had originally set `intentOnFilling=false` as it made sense given the documentation, however the 0x team let us know that we can use this value to be `true` (and we just might have PMMs penalize us, which just means they won't give us RFQ quotes anymore - and not that they will give us invalid RFQ quotes). `takerAddress` is needed for RFQ-T support.
`enableSlippageProtection` flag was also added at the 0x team's suggestion (and it made sense to add along with the existing changes).
Note that I added this behind a feature flag so we can easily turn it off-and-on depending on whether or not we run into any issues.
For additional context: …
> Add Support for RFQ-T to 0x Solver

- crates/solver/src/settlement.rs
While reviewing https://github.com/cowprotocol/services/pull/1338 I noticed that part of this function wasn't getting formatted. The reason is a very long line with a macro which rustfmt can't handle. In this commit move from `matches!` to `if let` which fixes the issue. This leads to the comment getting line wrapped which breaks the ascii art formatting of it. To fix this I reformat the comment.
CI, no logic change
> Fix code formatting

- crates/solver/src/solver/single_order_solver/fills.rs
- crates/solvers/src/domain/solver/dex/fills.rs
Currently the dex solvers don't perform very well in terms of partially fillable orders. This is caused by the fact that we currently pick the amount we want to fill as the `sell_amount` and the order's original buy amount (for sell orders).
That means instead of finding some trade with the original prices but lower volume we actually required the API to return a trade for half the sell amount but the entire buy amount (effectively requiring a price twice as good as actually necessary).
Now we actually pick the partial fill amount and scale the other amount based on the partial fill and the order's original limit price.
No e2e test as we are short on time :(
> Scale partial fill amounts correctly

- crates/solver/src/solver/single_order_solver.rs
Felix noticed and reported on Slack that this function had a comment saying it wasn't right for partially fillable orders. This is correct. We forgot to adjust it when implementing partial fill support for single order solvers.
adapted test
> Take partial fill into account for execution_respects_order

- crates/solver/src/solver/baseline_solver.rs
Print order uid for easier debugging.
n/a
> Better error log for baseline_solver error

- Cargo.lock
- crates/driver/Cargo.toml
- crates/driver/example.toml
- crates/driver/src/domain/competition/order/mod.rs
- crates/driver/src/domain/eth/gas.rs
- crates/driver/src/infra/api/mod.rs
- crates/driver/src/infra/config/file/load.rs
- crates/driver/src/infra/config/file/mod.rs
- crates/driver/src/lib.rs
- crates/driver/src/main.rs
- crates/driver/src/tests/cases/example_config.rs
- crates/driver/src/tests/cases/settle.rs
- crates/driver/src/tests/cases/solve.rs
- crates/driver/src/tests/cases/verify_internalization.rs
- crates/driver/src/tests/mod.rs
- crates/driver/src/tests/setup/blockchain/uniswap_weth.rs
- crates/driver/src/tests/setup/driver.rs
- crates/driver/src/tests/setup/mod.rs
- crates/driver/src/tests/setup/new/blockchain.rs
- crates/driver/src/tests/setup/new/driver.rs
- crates/driver/src/tests/setup/new/mod.rs
- crates/driver/src/tests/setup/new/solver.rs
- crates/driver/src/util/time.rs
- crates/e2e/tests/e2e/setup/colocation.rs
Progress on https://github.com/cowprotocol/services/issues/1306.
Refactor the test framework to make tests easy to write. Refactor some of the tests to use the new test framework, which is in `setup::new`. I'm aware of all TODOs and I'm leaving them for follow-up PRs. Eventually I plan to migrate the `setup::new` module to be simply `setup`.
> `driver`: better test framework

- crates/solver/src/solver.rs
- crates/solver/src/solver/http_solver.rs
Liquidity information takes up a lot of space in the instance. Only some solvers (only Quasimodo?) uses it so it is wasteful to send it to all of them.
This PR adds a configuration argument to disable sending liquidity to an http solver. The argument defaults to true which is the behavior before this PR.
After merging we should configure the argument on staging and see reduced network load.
adjusted argument parsing test, real test of this change has to be done in staging
> Configure use of liquidity in http solvers

- crates/solver/src/solver.rs
Part of https://github.com/cowprotocol/services/issues/1378
This PR adds a per external solver argument to configure whether the solver can internally handle assigning user balances to orders.
I'm aware I could derive the string conversion but this isn't a traditional clap enum arg so I wanted to make it more explicit.
adjusted test
> Add argument for external solver user balance support

- crates/shared/src/zeroex_api.rs
This PR adds fined-grained metrics to 0x API requests.
More context on the reason for this change can be found [here](https://cowservices.slack.com/archives/C0375NV72SC/p1682497082350169?thread_ts=1682493288.057339&cid=C0375NV72SC).
Compiler, no logic changes, just recording new metrics.
> Add 0x API Metrics

- crates/driver/src/domain/competition/solution/mod.rs
Small refactoring. Fixing up some comments. Don't return misleading types. (`simulate` shouldn't return `settlement::Verified` since the settlement has not been verified yet.)
Automated tests.
> Tiny refactoring

- crates/solver/src/solver/baseline_solver.rs
This message is spammy and not helpful.
none
> Remove useless log message

- crates/solvers/src/domain/order.rs
- crates/solvers/src/domain/solution.rs
- crates/solvers/src/infra/cli.rs
- crates/solvers/src/infra/config/dex/mod.rs
- crates/solvers/src/infra/config/dex/paraswap/file.rs
- crates/solvers/src/infra/config/dex/paraswap/mod.rs
- crates/solvers/src/infra/dex/oneinch/mod.rs
- crates/solvers/src/infra/dex/paraswap/mod.rs
- crates/solvers/src/lib.rs
- crates/solvers/src/run.rs
- crates/solvers/src/tests/mod.rs
- crates/solvers/src/tests/paraswap/market_order.rs
- crates/solvers/src/tests/paraswap/mod.rs
- crates/solvers/src/tests/paraswap/not_found.rs
- crates/solvers/src/tests/paraswap/out_of_price.rs
- crates/solvers/src/tests/zeroex/not_found.rs
Follow-up to https://github.com/cowprotocol/services/pull/1513.
Fixes https://github.com/cowprotocol/services/issues/882.
Adds CLI and tests for the ParaSwap integration in `solvers`.
Automated tests.
> `solvers`: ParaSwap CLI

- database/README.md
Was editing the file for a different reason and wanted to do this in separate PR.
n/a
> Fix whitespace mistakes in database readme

- crates/shared/src/order_validation.rs
Replace the macro in this test with a function. Ran into this while working on something else. Also turns `async` into `now_or_never` because it wasn't needed by the test.
The diff is small without whitespace changes.
test still passes
> Refactor test

- crates/shared/src/price_estimation/gas.rs
- crates/solver/src/test.rs
> Fix rust 1.70 warnings

- Cargo.lock
- crates/autopilot/src/database/onchain_order_events.rs
- crates/database/src/orders.rs
- crates/driver/src/boundary/settlement.rs
- crates/e2e/Cargo.toml
- crates/e2e/tests/e2e/app_data.rs
- crates/e2e/tests/e2e/main.rs
- crates/model/src/order.rs
- crates/orderbook/src/database/orders.rs
- crates/shared/src/db_order_conversions.rs
- database/README.md
- database/sql/V051__add_full_app_data.sql
Part of https://github.com/cowprotocol/services/issues/1465 .
new e2e test
> Store full app data in database

- crates/orderbook/openapi.yml
Forgot to document that we return this out through OrderMetadata now.
CI
> Document full app data field in API

- crates/shared/src/tracing.rs
Noticed while reviewing the other PR. Std has functionality to do the same thing.
CI
> Replace manual once initialization with std::sync::Once

- crates/orderbook/openapi.yml
- crates/orderbook/src/api/get_total_surplus.rs
As @vkgnosis said ultimately I decided to add this to openapi, just document that it's unstable.
Dropped the openapi file into https://editor.swagger.io/.
> Total surplus endpoint openapi spec

- crates/shared/src/signature_validator/web3.rs
This PR adds a gas cap to the `isValidSignature` simulation. It uses the same cap as we have for settlement simulation in the `solver`.
This makes it so simulations are accurate when internal calls rely on `TRAP` behaviour. For more context: https://www.notion.so/cownation/AAVE-Milkman-Order-Investigation-6edb9c6150094831bd3b204e693d4bba?pvs=4#05a7cdf59e8746b084c110236d692084
CI
> Add Gas Limit To ERC-1271 Check

- crates/shared/src/bad_token/token_owner_finder/blockscout.rs
> Update blockscout.rs to add support for goerli

- crates/e2e/tests/e2e/quoting.rs
> Fix Copy-Pasta Error From #1649

- crates/orderbook/openapi.yml
[Slack discussion](https://cowservices.slack.com/archives/C056TDLDE0Y/p1689072332416029)
Also fixed some trailing whitespaces because my editor does it automatically.
CI
> Mention non backend app data schema

- crates/driver/README.md
A `README` file explaining what the driver is and why it exists.
> Add a README file for the driver

- Cargo.lock
- crates/driver/Cargo.toml
- crates/driver/src/boundary/liquidity/balancer/v2/mod.rs
- crates/driver/src/boundary/liquidity/balancer/v2/weighted.rs
- crates/driver/src/boundary/settlement.rs
- crates/driver/src/domain/competition/solution/interaction.rs
- crates/driver/src/domain/liquidity/balancer/v2/mod.rs
- crates/driver/src/domain/liquidity/balancer/v2/weighted.rs
- crates/driver/src/infra/config/file/mod.rs
- crates/driver/src/infra/solver/dto/auction.rs
- crates/driver/src/infra/solver/mod.rs
- crates/shared/src/sources/balancer_v2/pool_fetching.rs
- crates/solver/src/interactions/balancer_v2.rs
- crates/solver/src/liquidity/balancer_v2.rs
Follow up to #1700
This PR adds the boilerplate code to create domain `balancer::v2::weighed::Pool` domain models and encode interactions for these.
Run the driver locally with just Balancer V2 liquidity enabled with the baseline solver and see do its thing:
```
% curl -s http://localhost:11088/mybologna/quote -H 'Content-Type: application/json' --data '@-' <<JSON | jq
{
"sellToken": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
"buyToken": "0x6810e776880c02933d47db1b9fc05908e5386b96",
"amount": "1000000000000000000",
"kind": "sell",
"deadline": "2024-03-25T00:00:00.000Z"
}
JSON
{
"amount": "16149644265706225285",
"interactions": [
{
"target": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
"value": "0",
"callData": "0x095ea7b3000000000000000000000000ba12222222228d8ba445958a75a0704d566bf2c80 …
```
> Add Driver Support for Balancer V2 Weighted Pools

- crates/driver/src/boundary/liquidity/balancer/v2/mod.rs
- crates/driver/src/boundary/liquidity/balancer/v2/stable.rs
- crates/driver/src/boundary/liquidity/balancer/v2/weighted.rs
- crates/driver/src/boundary/settlement.rs
- crates/driver/src/domain/competition/solution/interaction.rs
- crates/driver/src/domain/liquidity/balancer/v2/stable.rs
- crates/driver/src/infra/solver/dto/auction.rs
- crates/shared/src/sources/balancer_v2/pools/stable.rs
- crates/solver/src/liquidity.rs
- crates/solver/src/liquidity/balancer_v2.rs
- crates/solver/src/settlement_simulation.rs
- crates/solver/src/solver.rs
- crates/solver/src/solver/http_solver/instance_creation.rs
- crates/solver/src/solver/http_solver/settlement.rs
Follow up to #1700 
This adds stable pool support to the driver.
Run the solver with Balancer V2 and use Quasimodo to quote for a stable-stable trade:
```
% curl -s http://localhost:11088/mybologna/quote -H 'Content-Type: application/json' --data '@-' <<JSON | jq
{
"sellToken": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
"buyToken": "0x6b175474e89094c44da98b954eedeac495271d0f",
"amount": "10000000", 
"kind": "sell",
"deadline": "2024-03-25T00:00:00.000Z"
}
JSON
{
"amount": "9999886669034360163",
"interactions": [
{
"target": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
"value": "0",
"callData": "0x095ea7b3000000000000000000000000ba12222222228d8ba445958a75a0704d566bf2c80000000000000000000000000000000000000000000000000000000000000000"
},
{
"target": …
```
> Add Driver Support for Balancer V2 Stable Pools

- Cargo.lock
- Cargo.toml
We have a custom fork of Warp with one extra commit for a feature we need. This fork was owned by my Github account. I've moved it into the Cowprotocol organisation because that is the proper owner.
CI
> Update warp fork dependency

- crates/orderbook/src/ipfs_app_data.rs
> Add metrics for IPFS app data metrics

- crates/orderbook/src/app_data.rs
Addresses https://github.com/cowprotocol/services/pull/1705#discussion_r1279162402
This PR changes the error strings to be consistent with the `openapi.yaml` spec.
> Update App Data Error Strings

- crates/solver/src/driver.rs
While debugging slow order execution times I noticed that there is no way to tell when an order is in the current auction. We log orders that get filtered out from the auction but not when an order shows up. In the colocated code this is solved through order observation events but we don't have these for non colocated code. This PR fixes that by logging how the auction that the driver handles changes. This is smarter than logging the full auction because it only logs the difference.
I made this a debug log because we usually want to know about this in hindsight and it isn't too spammy compared to other driver logs.
Check logs after deploying
> Log orders in auction

- crates/orderbook/openapi.yml
Part of the fix to address https://github.com/cowprotocol/cow-sdk/issues/134
This is the second approach as suggested here https://github.com/ferdikoomen/openapi-typescript-codegen/issues/1424
The first approach was implemented on https://github.com/cowprotocol/cow-sdk/pull/137 It's a breaking change on the SDK side and creates a lot of noise.
This change will allows us to fix the issue with minimal changes
Describe context of what this change does, why it is needed and how it is accomplished
There are no effective changes on the code per se, and the resulting schema doc should be equivalent.
I did test it on the target repo (SDK) and the generated the types with the changes here. See [this PR](https://github.com/cowprotocol/cow-sdk/pull/138/files)
> Create sub types for OrderQuoteSide kind enums

- crates/solver/src/settlement_submission/submitter.rs
Follow up fix for #1723 and #1544
Both of these fixes focussed on not tracking the cancellation transaction **when the deadline was reached**. However, we also cancel transactions when the simulation starts reverting, cf:
https://github.com/cowprotocol/services/blob/96b039be1b5eb8bf2a3cea39591553faa3d6ee2c/crates/solver/src/settlement_submission/submitter.rs#L460-L475
In this case we don't remove the pending cancellation transaction (which will never get mined) and indeed persist it for future tracking (which will prevent further runloops of that solver if the base fee decreases).
I believe the proper fix is to **never persist** any pending transaction when soft cancellations are turned on. We will always either have a mined transaction or submit a cancellation tx which means in the case …
> Don't track cancellation tx when submission stops on simulation revert

- crates/shared/src/price_estimation/competition.rs
Currently we sort price estimate by some condition and pick the estimator that provided the first entry as the winner.
However, it can happen that the first entry is an error. That happens if all estimators returned an error. In that case it doesn't make sense to say some solver provided a "winning error".
This PR makes it so that metrics related to winning are only incremented if the best solution is not an error.
I decided to leave the arguably somewhat misleading log of "winning price estimate" unchanged because it's only used for debugging and introducing a new log specifically when all solvers produce errors seems to do more harm than good.
CI
> Only count winner if we actually got a quote

- crates/autopilot/src/solvable_orders.rs
Adds metric to keep track of the failures of the solvable orders cache update.
Inspired by the occasional one off failures of `trace_callMany` that raises alert in #alerts-prod channel [message](https://cowservices.slack.com/archives/C0371SB243E/p1692111482978209)
Plan is to add a grafana alert to check if there are several consecutive failures or if the rate of failures is high.
> Track success of solvable orders cache update

- crates/driver/src/boundary/mod.rs
- crates/driver/src/infra/blockchain/mod.rs
Uses the same buffered `Web3` implementation we are currently using in the remaining code base.
This is useful as it should drastically reduce the number of individual requests we send to our nodes.
Technically the buffered `Web3` client offers a bunch of configuration parameters but for now I decided to hard code the ones we have been using for a long time in our infra without any issues.
Not much changed so e2e tests should be sufficient
> Use buffered Web3 in driver

- crates/shared/src/price_estimation.rs
Stumbled upon this when looking through the different price estimation errors
CI
> [Trivial] Remove unused code

- Cargo.lock
- Cargo.toml
- crates/solver/src/driver.rs
- crates/solver/src/settlement_submission/submitter.rs
Pretty format gas price.
Right now it is very hard to visually compare gas prices in logs. It's hard to notice a difference between 30000000000 (30gwei) and 300000000000 (300 gwei)
Dependent on https://github.com/cowprotocol/gas-estimation/pull/11.
> Pretty format gas price

- crates/orderbook/src/ipfs_app_data.rs
This PR adds timing metrics for fetching AppData from IPFS. I noticed that we are getting the occasional alert around order creation taking longer than expected, this metric should help us see if it lines up with IPFS app data queries taking too long (instead of manually looking at log timestamps).
I also considered adding a label on "outcome", but didn't think it would be super valuable here.
No logic changes, so Rust CI.
Note that the existing IPFS metric names got renamed (to remove the duplicate `api_api` from the name). Will update Grafana once PR merges.
> Add Timing Metrics for IPFS

- crates/solvers/src/api/dto/auction.rs
- crates/solvers/src/boundary/legacy.rs
- crates/solvers/src/domain/auction.rs
- crates/solvers/src/domain/solver/baseline.rs
- crates/solvers/src/domain/solver/dex/mod.rs
This PR changes the baseline solver to respect the auction deadline.
CI - very minor logic change I didn't think it was worth introducing a test for.
> Respect Deadline in Baseline Solver

- crates/autopilot/src/run_loop.rs
Implements this comment https://github.com/cowprotocol/services/pull/1909/files/406e3c5a3a7716e2e98e1f9d13882b5d788a156a#r1342328884
> [Trivial] Replace filter_map().flatten() with flat_map()

- crates/shared/src/price_estimation.rs
Remove raven/yearn not used anymore arguments.
> Remove not used arguments

- crates/e2e/src/setup/onchain_components.rs
- crates/e2e/tests/e2e/colocation_hooks.rs
- crates/e2e/tests/e2e/smart_contract_orders.rs
A small PR that isolates some boilerplate needed for generating Safes in e2e tests for future use.
These changes are exclusively a refactor, no logic changes or new code involved.
E2e tests still work.
> Isolate Safe creation to dedicated function

- crates/driver/src/run.rs
Adds a simple log to easily find when the driver restarted and with config.
> [TRIVIAL] Add driver restart log

- database/README.md
Updates the `/database/README.md`.
Document `solver` column in `quotes` and `order_qutoes` tables
> Mention solver address in quotes tables

- crates/autopilot/src/run_loop.rs
- crates/driver/src/infra/observe/mod.rs
- Only log solutions in info if they are non empty
- Log the full auction in auction kickoff log
> More minor logging improvements

- crates/driver/src/infra/solver/mod.rs
The `naive` solver currently has phases where it produces lots of parsing errors like [these](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-20T13:31:01.846Z',to:'2023-10-20T15:25:44.372Z'))&_a=(columns:!(log),filters:!(),grid:(columns:('@timestamp':(width:164))),index:ea511870-d9b3-11ed-a9d0-a17451f01cc1,interval:auto,query:(language:kuery,query:'log:%20%22EOF%20while%20parsing%20a%20value%22'),sort:!(!('@timestamp',desc)))).
`Deserialize(Error("EOF while parsing a value", line: 1, column: 0))`
This looks like it refers to an empty string (EOF on the first character) but for anything else it would be nice to actually have an error log stating which string could not be deserialized.
Adds …
> Log response that could not be parsed

- crates/autopilot/src/run_loop.rs
Currently we first `.join_all()` the driver `/solve` requests and only afterwards issue logs.
The metrics correctly measure the time each requests takes but the logs make it look like all drivers respond at the same time which is confusing.
Move logging / metrics into future created for `.join_all()` to issue the logs exactly when each individual `driver` returns their response.
compiler
> Log driver response when it comes in

- crates/driver/src/boundary/score.rs
- crates/driver/src/boundary/settlement.rs
- crates/driver/src/domain/competition/auction.rs
- crates/driver/src/domain/competition/mod.rs
- crates/driver/src/domain/competition/score.rs
- crates/driver/src/domain/competition/solution/settlement.rs
- crates/driver/src/domain/eth/gas.rs
- crates/driver/src/domain/eth/mod.rs
- crates/driver/src/infra/api/routes/solve/dto/auction.rs
- crates/driver/src/infra/notify/mod.rs
- crates/driver/src/infra/notify/notification.rs
- crates/driver/src/infra/solver/dto/notification.rs
- crates/solver/src/settlement_ranker.rs
- crates/solver/src/settlement_rater.rs
- crates/solvers/src/api/routes/notify/dto/notification.rs
- crates/solvers/src/boundary/legacy.rs
- crates/solvers/src/domain/notification.rs
- crates/solvers/src/domain/solution.rs
Implements #4 from https://github.com/cowprotocol/services/issues/1891
> Colocation notify - bad score

- crates/driver/src/domain/competition/solution/settlement.rs
- crates/driver/src/domain/eth/mod.rs
- crates/driver/src/infra/observe/mod.rs
Print block number for each failure or success of the simulation.
> Add block number to log

- crates/solvers/src/infra/config/dex/file.rs
Adjusts DEX rate limiter config default values
Using logs
> [Trivial] DEX rate limiter default config values

- crates/autopilot/src/driver_model.rs
- crates/driver/openapi.yml
- crates/driver/src/infra/api/routes/solve/dto/auction.rs
- crates/driver/src/tests/setup/driver.rs
The driver API is not up to date.
Pasted the text in to see it render correctly
Part of #2182
> Update Driver API

- crates/autopilot/src/arguments.rs
- crates/autopilot/src/run.rs
- crates/autopilot/src/solvable_orders.rs
- crates/e2e/tests/e2e/colocation_buffers.rs
- crates/e2e/tests/e2e/colocation_eth_safe.rs
- crates/e2e/tests/e2e/colocation_ethflow.rs
- crates/e2e/tests/e2e/colocation_hooks.rs
- crates/e2e/tests/e2e/colocation_partial_fill.rs
- crates/e2e/tests/e2e/colocation_quoting.rs
- crates/e2e/tests/e2e/colocation_solver_competition.rs
- crates/e2e/tests/e2e/colocation_univ2.rs
- crates/e2e/tests/e2e/tracking_insufficient_funds.rs
Initiative to simplify autopilot parameters so we can move them to `toml` format.
Removes colocation flag as we no longer see we will revert to non-colocated driver.
> Remove colocation flag

- crates/driver/src/infra/api/mod.rs
- crates/solvers/src/api/mod.rs
Was merged too quickly (cc @mfw78 )
> 2223 follow up comment

- crates/driver/src/domain/competition/mod.rs
- crates/driver/src/infra/notify/mod.rs
- crates/driver/src/infra/solver/mod.rs
- crates/solvers/src/api/routes/notify/mod.rs
- crates/solvers/src/domain/solver/baseline.rs
I accidentally committed and merged some dirty debug logs in #2222 
This PR reverts those
> [Trivial] Fix dirty logs

- crates/solvers/openapi.yml
Fixes #2229 (cf. discussion there on why this is correct)
> [Trivial] fix solver docs

- README.md
- crates/orderbook/openapi.yml
Now that we have running services on Sepolia, we can add information on where to find them.
```
for base_url in {barn.,}api.cow.fi/sepolia; do echo "Checking $base_url:"; curl -X 'GET' "https://$base_url/api/v1/auction" -H 'accept: application/json'; echo; done
```
> Announce Sepolia availability

- crates/autopilot/src/database/onchain_order_events.rs
- crates/e2e/tests/e2e/ethflow.rs
For ethflow orders we so far did not discriminate market or limit order checks because they only ever existed as market orders. However, with the 0 fee initiative which converts all market orders to limit orders with 0 fee (making the solver responsible for taking an appropriate fee) we have to make that distinction.
If an order was created with a non-zero `fee_amount` value we continue to require a quote that confirms that the signed `fee_amount` is reasonable.
But if `fee_amount == 0` we simply skip verifying the fee value against the found quote because we no longer run the risk of losing money due to different semantics and handling of limit orders.
Added an `e2e` test that fails with `low_fee` during order creation same as described in the issue.
Fixes #2248
> Zero fee ethflow orders

- crates/autopilot/src/database/quotes.rs
- crates/database/src/orders.rs
Fixes https://github.com/cowprotocol/services/issues/2257
Added db test.
> Single sql query for reading quotes

- crates/autopilot/src/run_loop.rs
While the logic introduced in #2123 is sound the concern brought up by Dusan [here](https://github.com/cowprotocol/services/pull/2123#discussion_r1416005409) caused issues down the line.
Specifically looking up the `0x000` tx_hash will always fail and would get logged as an error in the node proxy  which surfaced [here](https://github.com/cowprotocol/infrastructure/pull/1062#issuecomment-1921802494)
Over all it's probably best to avoid issuing requests we know will fail even it the system is able to handle an error on those.
Make `InFlightOrders` optional and don't fetch the tx_receipt when it has not been initialized yet.
I decided to use `tokio::sync::Mutex` instead of `std::sync::Mutex` because calling a future while holding the lock made the code cleaner and since there is no …
> Avoid looking up 0x000 tx_hash

- crates/e2e/tests/e2e/limit_orders.rs
I think we actually broke the test when we merged some of the verified quotes logic (that's the problem with flaky test, people tend to just ignore them when they fail)
Even locally, I'm getting a driver/solver timed out trying to place the order. This is because the first run of the driver requires fetching all AMMs and liquidity sources from scratch which can be a time consuming endeavour. After that the cache is warm and we can respond fast.
Alternatively, I thought about making the time limit configurable and changing it in the e2e tests but we might actually want to get a failing test if we are unable to process quote requests in < 5s.
By running the flaky e2e test, and seeing it now passes reliably.
> Fix forked mainnet test

- crates/solvers/openapi.yml
Yearn team noticed that this was not updated after we stopped continuously updating fees for fok limit orders.
> Small fix for solvers openapi spec

- crates/driver/src/domain/competition/solution/fee.rs
- crates/driver/src/infra/api/routes/solve/dto/auction.rs
Addresses latest comments from the original PR: [1](https://github.com/cowprotocol/services/pull/2375#discussion_r1484285247), [2](https://github.com/cowprotocol/services/pull/2375#discussion_r1485937886)
> PriceImprovement driver leftovers

- crates/driver/src/domain/competition/solution/mod.rs
Inlines `with_protocol_fees` to prevent unintentionally calling the function multiple times and changing the state of the struct. Protocol fees are meant to be applied only once and be done with it, so doing it in constructor feels natural.
> Inline function `with_protocol_fees`

- crates/autopilot/src/arguments.rs
- crates/autopilot/src/run.rs
- crates/autopilot/src/solvable_orders.rs
- crates/driver/src/domain/competition/mod.rs
- crates/driver/src/domain/competition/order/mod.rs
- crates/driver/src/infra/blockchain/contracts.rs
- crates/driver/src/infra/config/file/load.rs
- crates/driver/src/infra/config/file/mod.rs
- crates/driver/src/run.rs
- crates/driver/src/tests/setup/solver.rs
Now that the vulnerability was fixed on a smart contract level we no longer need the mitigation in the backend.
Reverts https://github.com/cowprotocol/services/pull/2402
> Revert cow amm mitigation

- crates/autopilot/src/database/fee_policies.rs
- crates/driver/src/tests/cases/settle.rs
- crates/driver/src/tests/setup/mod.rs
Alternative to https://github.com/cowprotocol/services/pull/2508
Skips saving policies if empty.
Maybe better solution since it was asked to move dto conversion https://github.com/cowprotocol/services/pull/2470#discussion_r1512970100
Ran locally few e2e tests.
> Fix policy saving

- crates/driver/src/infra/solver/dto/auction.rs
- crates/driver/src/tests/setup/solver.rs
- crates/solvers-dto/src/auction.rs
- crates/solvers/openapi.yml
Do not break API contract with the solver with the fee policies
Since right now we only calculate the fee policies in the driver, do not send it in the API contract to the solver.
1. Regression test
> Do not alter the solver API with the fee policies

- crates/driver/src/domain/competition/solution/mod.rs
- crates/driver/src/tests/cases/protocol_fees.rs
We need to count the protocol fees for the scoring in all the cases. Good catch from @fleupold .
See @fleupold 's comment: https://github.com/cowprotocol/services/pull/2544#discussion_r1541118981
- Count the protocol fees for the scoring in all the cases
> [EASY] Bug: Count the protocol fees for the scoring in all the cases

- database/README.md
- database/sql/V064__update_on_chain_order_placement_error_enum.sql
https://cowservices.slack.com/archives/C0361CDD1FZ/p1711653554068709
Should be covered by tests
> `non-zero-fee` DB enum variant

- Cargo.lock
- crates/database/Cargo.toml
- crates/database/src/onchain_broadcasted_orders.rs
Inspired by error https://github.com/cowprotocol/services/pull/2574, now the unit test will fail if we forget to add the new variant to database.
Existing tests
> [EASY] Iterator for OnchainOrderPlacementError

- crates/driver/src/domain/liquidity/uniswap/v3.rs
Liquidity can be huge and is not really meaningful (even for debugging)
> Don't debug log Uni v3 pool state

- crates/driver/src/domain/competition/mod.rs
The comment wasn't correct (cf. line 350)
> [Trivial] fix solution merging comment

- crates/driver/src/domain/competition/solution/fee.rs
- crates/driver/src/domain/competition/solution/mod.rs
- crates/driver/src/domain/competition/solution/scoring.rs
- crates/driver/src/domain/competition/solution/trade.rs
- crates/driver/src/infra/notify/mod.rs
- crates/driver/src/infra/notify/notification.rs
- crates/driver/src/infra/solver/dto/notification.rs
- crates/shared/src/http_solver/model.rs
- crates/solvers-dto/src/notification.rs
- crates/solvers/openapi.yml
- crates/solvers/src/api/routes/notify/dto/mod.rs
- crates/solvers/src/boundary/legacy.rs
- crates/solvers/src/domain/notification.rs
Add more notify call for scoring
Add notify calls for the following score errors:
- `InvalidExecutedAmount`
- `MissingPrice(TokenAddress)`
- `CustomPrice(String)`
1. e2e
2. unit test
Fixes #2597
> Add more notify call for scoring

- .github/workflows/pull-request.yaml
- crates/driver/src/domain/competition/solution/mod.rs
Adds a CI step to run doctests
CI
> Enable doctests

- crates/driver/src/boundary/settlement.rs
- crates/driver/src/domain/competition/auction.rs
- crates/driver/src/domain/competition/mod.rs
- crates/driver/src/domain/competition/order/mod.rs
- crates/driver/src/domain/competition/solution/encoding.rs
- crates/driver/src/domain/competition/solution/mod.rs
- crates/driver/src/domain/competition/solution/settlement.rs
- crates/driver/src/infra/config/file/load.rs
- crates/driver/src/infra/config/file/mod.rs
- crates/driver/src/infra/solver/dto/auction.rs
- crates/driver/src/infra/solver/mod.rs
- crates/solver/src/liquidity.rs
- crates/solver/src/liquidity/order_converter.rs
Add driver configuration in order to determine sending native token to solvers as @MartinquaXD suggested:
- current WETH address and keep inserting unwrap interactions (pre PR implementation)
- send 0xeeee address but keep inserting unwrap interactions
- send 0xeeee and let solver handle unwraps entirely
> Add driver configuration in order to determine sending native token

- crates/driver/src/domain/quote.rs
Some solver returned a quote with the buy price being 0 which caused the driver to panic.
Used `.checked_div()` to avoid panics when the sell or buy price is zero.
compiler
> [TRIVIAL] Use checked div when construction a quote

- crates/autopilot/src/domain/eth/mod.rs
A follow up from https://github.com/cowprotocol/services/pull/2709
Refactors `autopilot::domain::eth` file.
> [EASY] Use derive from/into in autopilot

- crates/autopilot/src/domain/competition/mod.rs
- crates/autopilot/src/domain/settlement/mod.rs
- crates/autopilot/src/run_loop.rs
`Score` deserves it's own type. NonZeroU256 seemed fine, however NonZero(eth::Ether) is even better.
> [EASY] Uniform score type

- crates/driver/openapi.yml
Marks the price field as nullable as this is often the case.
> mark price as nullable

- crates/e2e/src/setup/services.rs
- crates/shared/src/price_estimation.rs
- crates/shared/src/price_estimation/external.rs
- crates/shared/src/price_estimation/factory.rs
- crates/shared/src/trade_finding.rs
- crates/shared/src/trade_finding/external.rs
Enforce timeout for the quote logic in the API in case colocated drivers don't enforce a timeout.
> [Not That Trivial] Enforce timeout for the quote logic in the API

- crates/driver/src/infra/solver/dto/solution.rs
- crates/driver/src/tests/setup/blockchain.rs
- crates/e2e/tests/e2e/database.rs
- crates/shared/src/trade_finding.rs
- crates/shared/src/trade_finding/external.rs
Quote query: Fix the quote deadline to match the POST timeout
> [EASY] Quote query: Fix the quote deadline to match the POST timeout

- .github/workflows/release.yml
Check for changes job was wrongly implemented. The PR fixes that.
> Release job check for changes fix

- crates/autopilot/src/on_settlement_event_updater.rs
In case there are no owners, empty list should be forwarded further instead of yielding error.
> Hotfix cowamm

- crates/autopilot/src/arguments.rs
- crates/driver/src/boundary/mod.rs
- crates/shared/src/event_handling.rs
- crates/shared/src/sources/balancer_v2.rs
- crates/shared/src/sources/balancer_v2/pool_fetching/pool_storage.rs
- crates/shared/src/sources/balancer_v2/pool_init.rs
- crates/shared/src/sources/uniswap_v2/pool_fetching.rs
- crates/solver/src/liquidity.rs
Updates Rust to the latest version.
> Rust 1.80.0

- crates/orderbook/openapi.yml
- crates/solvers/openapi.yml
Defines a missing quote specification in the OpenAPI schema. Noticed by https://github.com/cowprotocol/services/pull/2809#discussion_r1698283403
> PriceImprovement quote in OpenAPI

- crates/shared/src/price_estimation/native/coingecko.rs
Use full precision in CoinGecko so we do the calculations with all the possible decimals.
- Use full precision in CoinGecko
1. Unit test
> [EASY] Use full precision in CoinGecko

- crates/autopilot/src/run_loop.rs
While testing the progress bar v2 @alfetopito never saw the `Solved` state (called `considered` internally).
This state indicates that some solver tries to settle your order, it just didn't provide the best overall solution. In terms of the progress bar this means your order will likely soon be settled.
It looks like currently we only store the `considered` flag for the winning solution but not ALL solutions. This PR changes that.
> Store considered order events label for all considered orders

- crates/autopilot/src/solvable_orders.rs
- crates/e2e/tests/e2e/cow_amm.rs
@MartinquaXD I believe you wrote the test, do you remember why this specific pool was added to the list?
> Fix failing e2e test for cow amms

- crates/autopilot/src/solvable_orders.rs
In the previous PR https://github.com/cowprotocol/services/pull/2888 I forgot to cover one "effectful" operation with metrics.
> [TRIVIAL] Missing auction update stage metric

- crates/shared/src/price_estimation/buffered.rs
We must subscribe before we send the request, so we get the `rx` pointing to the current memory point, this way we avoid losing the result for the corner case in which the request is sent between the `unbounded_send()`  and the `subscribe()`
1. Regression test
> Fix the subscriber position for buffered native prices

- crates/contracts/src/storage_accessible.rs
- crates/shared/src/signature_validator/simulation.rs
The newly added metrics show that filtering invalid signatures can be quite slow. Since I don't see any low hanging fruit to speed up the simulation code let's just at least memoize the bytecode we pass to the simulation function since that never changes anyway.
This skips hex-decoding the contract bytecode on every simulation.
existing e2e tests should continue to work
> Memoize bytecode

- crates/database/src/auction_participants.rs
Similarly to https://github.com/cowprotocol/services/pull/2926, inserts auction participants to the DB in batches to speed up the process since this is executed inside the runloop critical path.
> Insert auction participants in batches

- crates/driver/src/domain/competition/solution/fee.rs
Haris noticed we are missing logs for volume based fees in the driver.
> [EASY] Add log for volume based fee

- crates/e2e/tests/e2e/order_cancellation.rs
Did not address one of the flaky assertions after @sunce86 [pointed it out](https://github.com/cowprotocol/services/pull/2944#issuecomment-2330853786).
> Remove another flaky assertion

- crates/autopilot/src/infra/persistence/mod.rs
- crates/e2e/src/setup/services.rs
- crates/e2e/tests/e2e/ethflow.rs
- crates/e2e/tests/e2e/order_cancellation.rs
Time for fixing a few lints introduced in rust 1.81
> [TRIVIAL] Fix clippy warnings of 1.81

- crates/autopilot/src/boundary/order.rs
- crates/autopilot/src/domain/auction/order.rs
- crates/autopilot/src/infra/persistence/dto/order.rs
- crates/autopilot/src/run_loop.rs
- crates/autopilot/src/shadow.rs
For autopilot domain, all orders are limit orders and therefore OrderClass is not needed.
> Cleanup order class in autopilot

- crates/driver/src/infra/solver/dto/solution.rs
Fixes https://github.com/cowprotocol/services/issues/2588
External solvers will be reminded once more about this before going live.
> [EASY] Remove score from solvers API

- crates/autopilot/src/run_loop.rs
Since the pre-processing job was removed(https://github.com/cowprotocol/services/pull/2960), this metric doesn't make sense anymore.
> [TRIVIAL] Drop auction preprocessing metric

- crates/database/src/fee_policies.rs
- crates/database/src/order_execution.rs
Apparently, Postgresql optimal way of matching data against large input is using INNER JOIN:
https://stackoverflow.com/questions/24647503/performance-issue-in-update-query
So, the benchmark for the problematic [order](https://aws-es.cow.fi/_dashboards/app/data-explorer/discover#?_a=(discover:(columns:!(log,log_level),isDirty:!f,sort:!()),metadata:(indexPattern:'86e4a5a0-4e4b-11ef-85c5-3946a99ed1a7',view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-10T11:46:17.292Z',to:'2024-09-10T13:48:25.292Z'))&_q=(filters:!(),query:(language:kuery,query:'log:%20%229649c7739ced0ea0fb0ecd8c41c81100%22'))) on arbitrum is:
1. Current implementation: ~1.5s - 3s
2. WHERE .. IN: same as (1)
3. INNER JOIN: 100ms-300ms
4. grouping by order_uid: same as (3)
That said, I chose …
> Improve performance of fee policies and fees

- crates/autopilot/src/solvable_orders.rs
As was proposed in another PR(https://github.com/cowprotocol/services/pull/2988#discussion_r1759499872), removes code duplication in the auction update stage time metric computation.
> [EASY] Auction update stage time metric minor refactoring

- crates/autopilot/src/run_loop.rs
Revert https://github.com/cowprotocol/services/pull/2999 since the consumers of the database table are having performance issues.
Save only fee policies from reported solutions.
> Revert to save only policies from solutions

- crates/autopilot/src/database/competition.rs
- crates/autopilot/src/infra/persistence/mod.rs
- crates/autopilot/src/run_loop.rs
Noticed while browsing the code.
> [TRIVIAL] Save surplus capturing jit order owners function naming fix

- .github/nitpicks.yml
- Nudges author to think about backwards compatibility when openapi.yml changes.
- Reminds to make DB migration revertable.
> OpenAPI change reminder

- crates/alerter/src/lib.rs
> Random change

- crates/alerter/src/lib.rs
- crates/rate-limit/src/lib.rs
> Hotfix CI job

- crates/solvers-dto/src/lib.rs
> A random change

- crates/autopilot/src/run_loop.rs
Inflight orders need to be handled before the auction is saved to database and s3, so that saved auction is equal to what is sent to solvers.
> Inflight orders are part of auction cutting

- crates/shared/src/order_validation.rs
Fixes: #3286 (issue provides all the necessary context)
Executes multiple token transfer tests to cover multiple mutually exclusive implementation quirks
TODO
I think temporarily deploying this to staging and seeing that a SELL USDL order can be created should be sufficient.
Alternatively you could probably run the cow playground and do the manual test without deploying to staging.
> Make USDL tradeable

- crates/driver/src/infra/solver/mod.rs
Sometimes the driver only gets to the point of sending the `/solve` request to the solver **after** the deadline has passed. This can happen when the driver's pre-processing takes an unusual amount of time.
Of course we should investigate how we can prevent these outliers from happening at all but having this safe guard makes sense regardless.
Don't send `/solve` request to the solver if the deadline has already been exceeded.
> Terminate before sending timed out /solve request

- crates/driver/src/domain/competition/mod.rs
Currently `/settle` function of the `driver` is using potentially outdated gas price to settle solutions onchain. This gas price was determined at the solving time.
Now we refresh the gas price just before we process settle, so the transaction is submitted considering the latest state of the gas price.
None
> Refresh gas price before settle executions

- crates/driver/src/domain/competition/order/mod.rs
- crates/driver/src/infra/solver/dto/auction.rs
- crates/driver/src/tests/cases/quote.rs
- crates/driver/src/tests/cases/settle.rs
- crates/driver/src/tests/setup/blockchain.rs
- crates/driver/src/tests/setup/driver.rs
- crates/driver/src/tests/setup/solver.rs
- crates/e2e/tests/e2e/cow_amm.rs
- crates/shared/src/price_estimation/native_price_cache.rs
Rust [1.86](https://blog.rust-lang.org/2025/04/03/Rust-1.86.0.html) got released and brought some `clippy` lints with it.
> [TRIVIAL] Fix clippy lints

- crates/autopilot/src/domain/auction/mod.rs
- crates/autopilot/src/infra/persistence/dto/auction.rs
- crates/autopilot/src/infra/persistence/mod.rs
- crates/autopilot/src/infra/solvers/dto/solve.rs
- crates/autopilot/src/run_loop.rs
- crates/autopilot/src/shadow.rs
- crates/e2e/src/setup/services.rs
- crates/orderbook/src/dto/auction.rs
This reverts commit 9d842f159c690dd4f5713b41648466930dc64af1 due to a failure in the shadow competition.
> Revert "autopilot: Add solve deadline to the S3 auction (#3348)"

- crates/contracts/build.rs
Adds the missing Polygon ethflow contract deployment info.
> [TRIVIAL] Add Polygon ethflow contract

- crates/autopilot/src/database/onchain_order_events/ethflow_events.rs
During one of the investigations, it was noticed that the autopilot sometimes struggles to resolve the start index block hash for different contracts. This PR introduces a simple retry mechanism to avoid redundant pod restarts. 3 retries with a 500ms delay between each one.
> [EASY] Retry mechanism for searching the start index

- crates/autopilot/src/database/onchain_order_events/ethflow_events.rs
- crates/autopilot/src/infra/solvers/mod.rs
- crates/autopilot/src/run.rs
- crates/autopilot/src/run_loop.rs
- crates/autopilot/src/shadow.rs
- crates/cow-amm/src/registry.rs
- crates/ethrpc/src/block_stream/mod.rs
- crates/orderbook/src/run.rs
- crates/shared/src/gas_price_estimation.rs
- crates/shared/src/price_estimation/native_price_cache.rs
- crates/shared/src/token_list.rs
As a continuation of adding instruments throughout the service as seen in https://github.com/cowprotocol/services/pull/3520 and https://github.com/cowprotocol/services/pull/3519 this PR is adding instrumentation for `autopilot`.
> Instrument autopilot functions

- crates/contracts/build.rs
- crates/contracts/src/alloy.rs
- crates/contracts/src/errors.rs
- crates/contracts/src/lib.rs
- crates/driver/src/infra/liquidity/config.rs
- crates/shared/src/sources/swapr.rs
As the title states
Usual tests
> Migrate ISwaprPair to alloy

- crates/contracts/build.rs
- crates/contracts/src/alloy.rs
- crates/contracts/src/lib.rs
- crates/driver/src/tests/setup/blockchain.rs
- crates/e2e/src/setup/deploy.rs
- crates/e2e/src/setup/onchain_components/mod.rs
- crates/e2e/tests/e2e/cow_amm.rs
- crates/e2e/tests/e2e/limit_orders.rs
- crates/e2e/tests/e2e/partially_fillable_balance.rs
- crates/e2e/tests/e2e/partially_fillable_pool.rs
- crates/e2e/tests/e2e/protocol_fee.rs
- crates/e2e/tests/e2e/replace_order.rs
- crates/e2e/tests/e2e/solver_participation_guard.rs
Migrates the UniswapV2Factory to alloy
E2E tests
> Migrate UniswapV2Factory to alloy

- Cargo.lock
- Cargo.toml
Updates the https://github.com/cowprotocol/ethcontract-rs crate to a version that includes this change: https://github.com/cowprotocol/ethcontract-rs/pull/984
> Update ethcontract crate version

- crates/contracts/build.rs
- crates/contracts/src/alloy.rs
- crates/contracts/src/lib.rs
- crates/shared/src/price_estimation/trade_verifier/mod.rs
> Migrate Spardose to alloy

- crates/contracts/build.rs
- crates/contracts/src/alloy.rs
- crates/contracts/src/lib.rs
- crates/contracts/src/macros.rs
- crates/shared/src/price_estimation/trade_verifier/mod.rs
Migrates the Trader SC to alloy
> Migrate Trader to alloy

- Cargo.lock
- crates/autopilot/src/database/onchain_order_events/mod.rs
- crates/autopilot/src/infra/blockchain/contracts.rs
- crates/contracts/build.rs
- crates/contracts/src/alloy.rs
- crates/contracts/src/lib.rs
- crates/e2e/src/setup/deploy.rs
- crates/e2e/tests/e2e/ethflow.rs
- crates/e2e/tests/e2e/hooks.rs
- crates/orderbook/Cargo.toml
- crates/orderbook/src/run.rs
- crates/shared/src/order_validation.rs
Migrate HooksTrampoline into alloy
Existing tests
> Migrate HooksTrampoline into alloy

- README.md
> chore: add a link to the github workflow

- crates/order-validation/src/banned.rs
Adds a module doc to banned.rs, covers the absolute basic about the module
> [Trivial] mod-docs for order-validation::banned

- crates/orderbook/src/orderbook.rs
Some docs for the orderbook functions
> Docs for Orderbook functions

- crates/contracts/build.rs
- crates/contracts/src/alloy.rs
- crates/contracts/src/lib.rs
- crates/driver/src/domain/competition/solution/encoding.rs
- crates/driver/src/infra/blockchain/contracts.rs
- crates/driver/src/tests/setup/blockchain.rs
- crates/driver/src/tests/setup/driver.rs
- crates/driver/src/tests/setup/solver.rs
- crates/e2e/src/setup/deploy.rs
- crates/e2e/src/setup/onchain_components/mod.rs
Migrate FlashLoanRouter into alloy
regular tests
> Migrate FlashLoanRouter into alloy
