cowprotocol/services

crates/autopilot/src/driver_model.rs
crates/autopilot/src/lib.rs
crates/autopilot/src/run_loop.rs
crates/driver/src/domain/competition/auction.rs
crates/driver/src/domain/quote.rs
crates/driver/src/infra/api/routes/solve/dto/auction.rs
crates/driver/src/infra/api/routes/solve/mod.rs
crates/driver/src/infra/blockchain/mod.rs
crates/driver/src/infra/tokens.rs
crates/driver/src/tests/setup/solver.rs

Follow up to https://github.com/cowprotocol/services/pull/1770
As discussed [here](https://github.com/cowprotocol/services/pull/1770#pullrequestreview-1581196291) it's more correct to move all the fetching of all token metadata that only enables certain optimisations but are not part of the core protocol into the driver.
e2e tests

Move token info fetching entirely into driver

---

crates/shared/src/baseline_solver.rs
crates/solvers/src/boundary/baseline.rs
crates/solvers/src/tests/baseline/buy_order_rounding.rs

Follow up to #1761
This PR adjusts the Baseline solver algorithm to iterate on progressively larger sell amounts in an attempt to traverse from an order's sell token to its buy token ensuring that the executed buy amount is enough to cover the buy order.
This is needed because some baseline liquidity (notable Balancer weighed pools) are "unstable", meaning that if we compute the input amount `X` required for an exact output amount `Y`, then using the exact same pool state compute the output amount `Y'` for an exact input amount `X`, it can happen that `Y' < Y`, meaning that the executed interactions would not generate enough tokens to cover the buy order.
Adjusted E2E test to demonstrate that the path with the better price (over an unstable Balancer pool) is used.

Baseline: Converge To Sufficient Sell Amount

---

Cargo.lock
crates/driver/Cargo.toml
crates/driver/src/boundary/settlement.rs
crates/driver/src/domain/competition/order/mod.rs
crates/driver/src/domain/competition/solution/settlement.rs
crates/driver/src/domain/competition/solution/trade.rs
crates/driver/src/domain/quote.rs
crates/driver/src/infra/solver/dto/auction.rs
crates/driver/src/util/conv/mod.rs
crates/driver/src/util/conv/u256.rs

The driver should rely less and less on shared crates.
This PR removes the dependency on the `number-conversion` crate.
Also instead of having free functions for everything I moved the conversion logic into the `U256Ext` trait to make things a bit nicer to read (hopefully).
`conv::u256` and the remaining code relied on 3 functions that were still missing in the driver crate. These have been copied from `number-conversions`.
CI, e2e tests

Remove number-conversion dependency

---

crates/driver/src/boundary/liquidity/balancer/v2/stable.rs
crates/driver/src/boundary/liquidity/balancer/v2/weighted.rs
crates/driver/src/boundary/liquidity/swapr.rs
crates/driver/src/boundary/liquidity/uniswap/v2.rs

In an effort to reduce the drivers dependencies on `shared` to a minimum I copied over the `GAS_PER_SWAP` constants into the specific liquidity module.
Maybe it would be a good idea to re-evaluate these, though.

Don't depend on shared::price_estimation

---

crates/driver/src/infra/api/mod.rs
crates/driver/src/infra/tokens.rs

I noticed that every `Solver` has its own `tokens::Fetcher` instance which doesn't really make sense.
The token info fetching cache is append only and will always receive the same data across different `Solver` instance. Also all solvers will end up fetching the info for the same tokens so it makes the most sense to have 1 instance globally to let solvers profit off of a shared cache.

Share token fetcher

---

crates/shared/src/balancer_sor_api.rs

It seems that the old Balancer SOR API is actually working on Gnosis Chain now. This would help us with a bunch of headaches around Karpatekey's liquidity provision needs as the SOR solver supports all Balancer pools.
Run with orderbook on GChain with just Baseline and BalancerSor as estimators. See that selling WETH for wxDAI works (with Balancer being the winning solver). 
Once merged I plan to enable Balancer as a solver (and then price estimator) on staging

Allow Balancer SOR solver on Gnosis Chain

---

crates/shared/src/api.rs
crates/shared/src/price_estimation.rs
crates/shared/src/price_estimation/competition.rs
crates/shared/src/price_estimation/trade_finder.rs
crates/shared/src/trade_finding.rs
crates/shared/src/trade_finding/external.rs

Related to the alert https://cowservices.slack.com/archives/C037PB929ME/p1692593972494599
When orderbook sends quote request to colocated driver (that we now use for quoting on staging) and the driver does not respond in a timely manner, `DeadlineExceeded` error is returned back.
For this particular error I think we should have a separate error type in orderbook api since it does not belong to any other type and it shouldn't be traced with `tracing::error` log level since drivers theoretically can spend as much time as they want.

Handle deadline error for colocated driver

---

crates/autopilot/src/solvable_orders.rs
crates/shared/src/price_estimation/competition.rs
crates/shared/src/price_estimation/native_price_cache.rs

This should reduce a good chunk of native price estimates we are making to 0x. Currently, we cache native price estimates, but only when the response was a success. This was mainly because we don't want to poison the cache with errors, if there is hope to recover in a subsequent request. 
While this is true for some errors, it is not really true for others. If no price estimator found any liquidity for a token at time t (and none of them were rate limited), it is unlikely they will find liquidity shortly after. Yet, we keep sending out requests to the upstream API as its NoLiquidity response isn't cached anywhere.
This PR changes the priority with which we merge price estimation errors from different estimators into a single top level one (by severity) and then adds logic for which errors …

Cache native price estimates for which there is no liquidity

---

crates/driver/src/boundary/quote.rs
crates/driver/src/boundary/settlement.rs
crates/driver/src/domain/competition/solution/interaction.rs
crates/driver/src/domain/competition/solution/mod.rs
crates/driver/src/domain/eth/allowance.rs
crates/driver/src/infra/blockchain/mod.rs
crates/driver/src/infra/blockchain/token.rs
crates/driver/src/infra/solver/dto/solution.rs
crates/driver/src/infra/tokens.rs

This PR just proposes a small refactor in the `driver` to make code that uses ERC-20s easier. I also flattened the `Spender` type, since having the token tied to the spender felt a bit awkward.
It introduces a `blockchain::token::Erc20` type for fetching ERC-20 token information.
Rust CI - tests continue to pass.

Refactor ERC-20 Interactions in Driver

---

crates/driver/src/boundary/liquidity/balancer/v2/mod.rs
crates/driver/src/boundary/liquidity/uniswap/v3.rs
crates/driver/src/boundary/mempool.rs
crates/driver/src/boundary/settlement.rs
crates/driver/src/domain/eth/mod.rs
crates/driver/src/infra/blockchain/mod.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/config/mod.rs
crates/driver/src/run.rs
crates/driver/src/tests/setup/solver.rs

This PR does a refactor for a code smell that was irking me for a while.
The `config::file` module contains _private_ types used just for parsing TOML configurations for the driver and turning them into their `infra::${component}::Config` counterparts. This separation follows a pattern we have in the `driver` code where we separate DTOs and data models from the actual types used within the codebase (it adds boilerplate, but I am in general fond of this).
There were 2 exceptions to the above rule: contract addresses and liquidity configuration. This is because the default configuration values for these are **network dependent**. This PR changes configuration file loading to be network aware, and makes all of the `config::file` module types private (as they should be IMO). For this, w
As a …

Refactor Driver Configuration Initialization

---

crates/driver/src/boundary/liquidity/balancer/v2/mod.rs
crates/driver/src/boundary/liquidity/balancer/v2/weighted.rs
crates/driver/src/domain/liquidity/balancer/v2/weighted.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/liquidity/config.rs
crates/driver/src/infra/solver/dto/auction.rs
crates/shared/src/sources/balancer_v2/pool_fetching.rs
crates/shared/src/sources/balancer_v2/pool_fetching/registry.rs
crates/shared/src/sources/balancer_v2/pools/common.rs
crates/shared/src/sources/balancer_v2/pools/liquidity_bootstrapping.rs
crates/shared/src/sources/balancer_v2/pools/weighted.rs
crates/shared/src/sources/balancer_v2/swap.rs
crates/shared/src/sources/balancer_v2/swap/fixed_point.rs
crates/shared/src/sources/balancer_v2/swap/weighted_math.rs
crates/solver/src/liquidity.rs
crates/solver/src/liquidity/balancer_v2.rs
crates/solver/src/solver/baseline_solver.rs
crates/solver/src/solver/http_solver/settlement.rs
crates/solvers/src/api/dto/auction.rs
crates/solvers/src/boundary/liquidity/weighted_product.rs
crates/solvers/src/domain/liquidity/weighted_product.rs
crates/solvers/src/tests/baseline/bal_liquidity.rs
crates/solvers/src/tests/baseline/buy_order_rounding.rs
crates/solvers/src/tests/baseline/mod.rs

Fixes #1763 
Currently, there are 4 versions of weighted pools:
* **original** (called `v0` in code): The original weighted pool implementation with the original weighted pool math. This is what was already implemented in Rust.
* **v2**: This version uses the same math as the original, but was deprecated because of a security issue (in fact, we do not index these pools at all).
* **v3**: This version introduces a few new features. Notably, they modify the `FixedPoint::pow{Up,Down}` functions to early exit on specific inputs (for example, `FixedPoint::powUp(a, 1.0)` will just return `a`, where previously it would do math to compute the exponentiation which resulted in a small error).
* **v4**: Uses `CREATE2` for pool creation, the math is identical to V3.
As you can see, between V0 and …

Multiple Balancer Weighted Pool Versions

---

crates/autopilot/src/on_settlement_event_updater.rs
crates/e2e/src/setup/services.rs
crates/model/src/quote.rs
crates/shared/src/account_balances/cached.rs
crates/shared/src/account_balances/web3.rs
crates/shared/src/baseline_solver.rs
crates/shared/src/event_handling.rs
crates/shared/src/sources/balancer_v2/swap/stable_math.rs
crates/shared/src/sources/uniswap_v3/pool_fetching.rs
crates/solver/src/settlement.rs
crates/solver/src/settlement/settlement_encoder.rs
crates/solver/src/solver/http_solver/buffers.rs
crates/solver/src/solver/naive_solver.rs
crates/solver/src/solver/single_order_solver.rs

Fixes new clippy lints of `Rust 1.72.0`.
Mostly:
* remove unnecessary `#` from string literals
* use `try_fold()` instead of `fold()`
* omit `.into_iter()` when function takes `T: IntoIterator`
* don't use `vec![]` when simply array is enough

Fix clippy warnings for Rust 1.72.0

---

crates/driver/src/boundary/liquidity/balancer/v2/mod.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/liquidity/config.rs
crates/shared/src/sources/balancer_v2/graph_api.rs
crates/shared/src/sources/balancer_v2/pool_fetching.rs
crates/shared/src/sources/balancer_v2/pools.rs
crates/shared/src/sources/balancer_v2/pools/composable_stable.rs
crates/shared/src/sources/balancer_v2/pools/liquidity_bootstrapping.rs

This PR adds indexing logic for composable stable pools. Notably, composable stable pools need to fetch their scaling factors, as they are "dynamic" and change on chain as a result of their "rate providers" changing.
Note that I left some "TODOs" for enabling composable stable pools on startup by default. These are removed in #1812. 
Added a unit test to verify indexing logic.

Index Composable Stable Pools

---

crates/shared/src/price_estimation/http.rs
crates/shared/src/sources/balancer_v2/pools/common.rs
crates/shared/src/sources/balancer_v2/pools/liquidity_bootstrapping.rs
crates/shared/src/sources/balancer_v2/swap.rs
crates/solver/src/liquidity.rs
crates/solver/src/solver/http_solver/instance_creation.rs
crates/solvers/src/boundary/legacy.rs
crates/solvers/src/tests/baseline/bal_liquidity.rs
crates/solvers/src/tests/baseline/buy_order_rounding.rs

This PR adds composable stable pool support in the `solvers` crate. Specifically:
* It adds logic for the baseline solver to be able to compute input and output amounts for composable stable pools.
* It adds conversion logic for composable stable pools so that they can be supported as regular stable pools by legacy HTTP solvers (a.k.a. Quasimodo).
Composable stable pools are very similar to regular stable pools with the exception of:
* scaling factors are "dynamic" (see #1810 PR which adds indexing logic to fetch these dynamic scaling factors). This is not a problem for our current stable pool implementation, since #1802 already implements the required changes to allow for arbitrary scaling factors.
* they always include their own BPT token in the pool tokens. Note that these BPT tokens …

Support Composable Stable Pools in Solvers

---

crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/liquidity/config.rs
crates/shared/src/sources/balancer_v2/pool_fetching.rs

This is a follow up to #1810 which enables composable stable pools by default.
Use a co-located driver and verify that composable stable pools are indexing and producing solutions!
First, use [the Balancer V2 subgraph](https://thegraph.com/hosted-service/subgraph/balancer-labs/balancer-v2) to identify pools to use for each version of composable stable pool:
```graphql
{
pools(
first: 100
where: {
factory: "${FACTORY}"
swapEnabled: true
isPaused: false
}
) {
id
tokens {
address
balance
}
}
}
```
Then, configure the driver to only have composable stable pool liquidity and issue quotes for these token pairs:
```toml
[[solver]]
name = "baseline"
endpoint = "http://127.0.0.1:7872/"
account = "0x0000000000000000000000000000000000000000000000000000000000000001"
relative-slippage = "0.1" …
```

Enable Composable Stable Pools

---

crates/contracts/build.rs

Since the Shapella hardfork landed on Gnosis Chain, we no longer need a different address for the hooks trampoline 🎉. 
For more context see https://github.com/cowprotocol/hooks-trampoline/pull/6.
Contract code is identical on Mainnet and Gnosis Chain.
```shell
rpc='{ "id": 1,"jsonrpc": "2.0","method": "eth_getCode", "params": ["0x01dcb88678aedd0c4cc9552b20f4718550250574", "latest"] }'
diff -u --color \
<(curl -s https://mainnet.infura.io/v3/$INFURA_PROJECT_ID --data "$rpc" | jq '.result') \
<(curl -s https://rpc.gnosischain.com/ --data "$rpc" | jq '.result')
```

Update `HooksTrampoline` Address

---

crates/shared/src/arguments.rs
crates/shared/src/paraswap_api.rs
crates/shared/src/price_estimation/factory.rs
crates/shared/src/price_estimation/paraswap.rs
crates/shared/src/trade_finding/paraswap.rs
crates/solver/src/run.rs
crates/solver/src/solver.rs
crates/solver/src/solver/paraswap_solver.rs

To allow configuring a reverse proxy to fine-tune how many requests we send to their API.
I also noticed that we weren't yet sending the partner field on transaction building requests.
CI

Parametrize Paraswap UI

---

crates/e2e/src/setup/services.rs
crates/solver/src/solver.rs

Fixes #1791, #901
Adds a `None` SolverType which allows for the `solver` binary to run only against an external solver.

Add None solver and allow to be set if external solver is set

---

crates/shared/src/api.rs
crates/shared/src/http_solver.rs
crates/shared/src/price_estimation/http.rs

So we don't error log on those somewhat expected errors (currently classified at "Other"). Probably needs a hotfix to get alerts channel under control.

Properly classify http_solver timeout errors

---

crates/shared/src/trade_finding/paraswap.rs

Paraswap rate limit responses are currently not properly converted into rate limit errors. This PR replaces the catch all case in the enum to make sure the compiler forces us to think about this conversion if we add another Paraswap error type.

Properly classify Paraswap rate limits

---

crates/autopilot/src/lib.rs
crates/orderbook/src/run.rs
crates/shared/src/arguments.rs
crates/shared/src/signature_validator.rs
crates/shared/src/signature_validator/arguments.rs

Follow up to #1827 
This PR adds the required simulation options to enable simulation-based ERC-1271 signature verification in order to support smart contract orders that do required setup as pre-hooks.
An example of this would be to have a Composable CoW order be created as a pre-hook and traded in the same transaction. With account abstraction, this would allow for gasless smart orders!
Will share a manual test once completed. Tx hash or it didn't happen!

Enable Simulation-Based ERC-1271 Signature Validation

---

crates/shared/src/price_estimation/zeroex.rs
crates/shared/src/trade_finding/zeroex.rs
crates/shared/src/zeroex_api.rs
crates/solver/src/solver/zeroex_solver.rs

In trying to run the orderbook locally to reproduce an issue, I discovered that since 0x changed their API to require an access key, we can no longer run some of the tests.
This PR fixes that by changing the 0x API `Default` implementation to read the URL and API key from environment variables.
Running the 0x tests with a configured API key now work.

Configure 0x For Tests

---

crates/shared/src/code_simulation.rs
crates/shared/src/price_estimation.rs
crates/shared/src/price_estimation/factory.rs
crates/shared/src/tenderly_api.rs

This PR does a few of things:
- Adds `TRACE` logs to Tenderly API implementation (this was used to figure out how the `id` could be extracted from the Tenderly simulation response).
- Parses the `id` field from the simulation result
- Builds and logs the URL for the simulation if it was saved.
Run the orderbook - make sure to enable saving on trade simulations:
```shell
cargo run -p orderbook -- --trade-simulator Tenderly --tenderly-save-successful-trade-simulations true
```
Then, issue a verified quote:
```shell
curl -s http://localhost:8080/api/v1/quote -X POST -H 'content-type: application/json' --data '@-' <<JSON | jq
{
"from": "0xa03be496e67ec29bc62f01a428683d7f9c204930",
"sellToken": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
"buyToken": …
```

Log Tenderly Simulation URL

---

crates/shared/src/http_solver/model.rs
crates/solver/src/settlement.rs
crates/solver/src/settlement_post_processing/mod.rs
crates/solver/src/settlement_rater.rs
crates/solver/src/solver/http_solver/settlement.rs

After https://github.com/cowprotocol/services/pull/1843, this is another initiative to make `Settlement` cleaner for the needs of porting the risk/score calculation to colocated driver.
Now the `score` is non-optional, with the default value `Score::RiskAdjusted` which is equivalent to `score: None` (from the POV how the protocol handles `score: None`) but more explicit.
Note: ~~Initially I wanted to make the score non optional in the `SettledBatchAuctionModel` during deserialization, but I couldn't make piece between #[flatten] and #[default] on untagged enum. If anyone knows about any workaround let me know.~~ Added custom deserializator

Settlement score mandatory

---

crates/driver/src/domain/competition/order/mod.rs
crates/driver/src/domain/competition/solution/trade.rs

This PR fixes asset flow verification issue that was causing partially fillable limit order to not settle.
The reason for this is two-fold:
- The existing asset flow verification algorithm was originally implemented with fill-or-kill limit orders in mind. This means it was under the assumption that the solvers were seeing the "synthetic" orders with the protocol-computed fee amount already discounted from the order. This means that the `Execution` that was being computed was the "real" input/output amount with the protocol computed surplus fees "staying" the settlement contract (for the purpose of asset flow verification). 
- Now surplus fees are computed by solvers and the algorithm that the solver uses **makes it so the fee stays in the buy token when then order is fully executed**. …

Fix Asset Flow Verification

---

crates/solvers/src/domain/order.rs
crates/solvers/src/domain/solver/dex/mod.rs

This PR fixes DEX aggregator API based solvers to not try and solve liquidity orders.
Rust CI - `UserOrder` logic is already tested.

Don't Match Liquidity Orders Against Onchain Liquidity

---

crates/shared/src/http_solver/model.rs

Fix after https://github.com/cowprotocol/services/pull/1846
One of the solvers is sending `score: null` and it fails deserialization. This PR lands on a much simpler logic to support this edge case.

Fix score deserialization

---

crates/autopilot/src/run_loop.rs

Looks like we were sending `Default::default()` to the driver for the executed amount for partially fillable orders 🤦.
This PR fixes that (using existing shared code).
Trivial change - CI continues to pass.
In the future, we should add an E2E test settling a partially fillable order in parts.

Send Executed Order Amounts to Driver

---

crates/driver/src/infra/simulator/tenderly/dto.rs
crates/driver/src/infra/simulator/tenderly/mod.rs

It turns out, we were ignoring whether or not the Tenderly simulation would revert when analyzing the simulation (where the calling code would expect a revert to produce an `Err` and not an `Ok`).
This PR fixes that by inspecting the Tenderly `status` bool from the response.
Not sure how to test this beyond a manual test. Would be nice to do an E2E test with Tenderly, but that would be prone to sporadic failures.
Some manual testing, here is a [detected revert](https://dashboard.tenderly.co/shared/simulation/ea10454c-fe53-494a-9025-b4f6eec694c5):
```
2023-09-09T12:11:08.252Z  INFO request{id="152"}:/solve{solver=mybologna auction_id=8842275}: driver::infra::observe: discarded solution: settlement encoding failed id=Id(0) err=Simulation(Tenderly(Revert(SimulationId("ea10454c-fe53-494a-9025- …
```

Detect Tenderly Simulation Reverts

---

.github/workflows/deploy.yaml

Because we are currently getting
```
POST /images/ghcr.io/cowprotocol/services:main/rollout 404
```
and in my original [tests](https://github.com/cowprotocol/k8s-autodeploy/pull/2), I escaped the route as well

Fix autodeploy

---

.github/workflows/deploy.yaml

It's not working as we are not passing the escaped string into the handler which doesn't yield any matches. @nlordell created a better fix here: https://github.com/cowprotocol/autodeploy-action/pulls

Revert 1863

---

crates/database/src/orders.rs
crates/e2e/tests/e2e/partially_fillable_pool.rs
crates/model/src/order.rs
crates/shared/src/db_order_conversions.rs

Our executed fee values in the order metadata were not accurate for partially fillable limit orders with multiple fills.
Now we are summing the executed fees for all trade executions so it should be good now.

Sum up executed fees

---

crates/shared/src/signature_validator.rs
crates/shared/src/signature_validator/simulation.rs
crates/shared/src/signature_validator/web3.rs

Context: https://cowservices.slack.com/archives/C0361CDD1FZ/p1694595411953299
We need to convert web3 error first to `ExecutionError` so the reverts are properly classified so that our error conversion method properly classify revert as `SignatureValidationError::Invalid`

Fix error handling for signature validator

---

crates/shared/src/price_estimation/competition.rs

The docs for `select_all` say:
> There are no guarantees provided on the order of the list with the remaining futures. They might be swapped around, reversed, or completely random.
When simplifying the price API I was not aware of this and didn't take any precautions to account for any unstable order of the returned futures.
I checked the implementation of `select_all` and it uses `Vec::swap_remove()` under the hood which definitely messes with the order of the returned futures and the indices.
It is possible that this is the reason why we saw weird 95th percentile quoting latency. The new code returns the index along side the quote result and does not use the index returned by `select_all` at all.

Account for unstable order of `select_all`

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/run.rs
crates/e2e/src/setup/services.rs
crates/orderbook/src/arguments.rs
crates/orderbook/src/run.rs
crates/shared/src/price_estimation.rs
crates/shared/src/price_estimation/factory.rs
crates/shared/src/price_estimation/native.rs
crates/shared/src/price_estimation/native/oneinch.rs

Now that we have everything set up, we can actually allow configuration of "Native only" price estimators. For this we change the type that the native price estimators value takes to its own type that can be either a generic price estimator or a "native only" one.
We pass all built-in native price estimators separately into the factory method (this allows us to still use the external solvers as backup estimators).
```
cargo run --bin orderbook -- --node-url <your dappnode>--native-price-estimators Baseline,OneInchSpotPriceApi --baseline-sources UniswapV2 --one-inch-spot-price-api-key <your api key> 
```
And
```
curl localhost:8080/api/v1/token/0x6810e776880c02933d47db1b9fc05908e5386b96/native_price
{"price":0.06223952453884784}
```
observing
```
winning price estimate …
```

Configure one inch spot price estimator

---

crates/autopilot/src/arguments.rs
crates/shared/src/price_estimation.rs
crates/shared/src/price_estimation/factory.rs

In order to configure colocated driver price estimators (which as far as the orderbook/autopilot are concerned are merely strings) we need to allow for less strict typing when specifying NativePriceEstimators. Basically a native price estimator is either a builtin static typed one or just an arbitrary string, which the factory later hopes to find in one of the many ways generic price estimator can be specified in the current code base (builtin, legacy and co-located).
run the orderbook with `--native-price-estimators Baseline,mysolver --price-estimators Baseline --price-estimation-drivers 'mysolver|http://localhost:11088/mysolver'` 
Make a request, observe
```
2023-09-25T17:48:58.344Z DEBUG request{id="1"}: shared::price_estimation::competition: new price estimate …
```

Allow native price estimators to be arbitrary strings

---

crates/contracts/src/storage_accessible.rs
crates/driver/src/domain/competition/auction.rs
crates/driver/src/domain/competition/order/mod.rs
crates/driver/src/domain/eth/mod.rs
crates/driver/src/infra/blockchain/contracts.rs
crates/driver/src/infra/blockchain/mod.rs
crates/driver/src/infra/blockchain/token.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/observe/mod.rs
crates/driver/src/tests/cases/example_config.rs
crates/driver/src/tests/setup/blockchain.rs
crates/driver/src/tests/setup/mod.rs
crates/driver/src/tests/setup/solver.rs
crates/e2e/tests/e2e/colocation_ethflow.rs
crates/e2e/tests/e2e/ethflow.rs
crates/e2e/tests/e2e/main.rs
crates/e2e/tests/e2e/refunder.rs

This PR adds balance simulation to the driver.
This enables the `driver` to continue to work with orders that require pre-interactions for setting up balances (such as EthFlow). In addition - the pesky EthFlow exception was removed from the `driver` crate entirely 🎉! In fact, the `driver` no longer cares at all about the EthFlow contract address.
Added E2E test to verify that EthFlow orders are still executed. They use pre-interactions to ensure the balance is available, so we check that our new simulation logic actually works! Existing hooks E2E test continues to pass.
<details><summary>You can also apply this patch to make the test fail:</summary>
```diff
diff --git a/crates/driver/src/domain/competition/auction.rs b/crates/driver/src/domain/competition/auction.rs
index …
```

Simulate Balances with PreInteractions In Driver

---

crates/shared/src/price_estimation/competition.rs

The new staged racing price estimator executes each stage sequentially no matter what. However, if the `successful_results_for_early_return` is larger than the current stage, it is clear that this stage alone won't be able to yield an early result and we may as well start the next stage in parallel (as we will send requests to all its estimators in any case)
This may become relevant if we configure the generic price estimator to also use stages for fast estimations. In this case, we still want all requests to be sent out in parallel for optimal quotes (where we require all estimators to return a result)
Added a unit test

Combine stages for high thresholds

---

crates/driver/src/boundary/settlement.rs
crates/model/src/solver_competition.rs
crates/shared/src/http_solver/model.rs
crates/solver/src/settlement_rater.rs
crates/solvers/src/boundary/legacy.rs

Implements https://github.com/cowprotocol/services/issues/1898
Implemented in a separate PR so it doesn't gets merged too soon (next week release is too soon for this change _I think_)
As per [discussion](https://cowservices.slack.com/archives/C036JAGRQ04/p1695637642640269), score discount is deprecated.
To be merged next week, so it becomes a part of weekly release ~10th of October @harisang

Remove score discount

---

crates/driver/src/infra/blockchain/gas.rs
crates/driver/src/infra/blockchain/mod.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/config/mod.rs
crates/driver/src/run.rs
crates/driver/src/tests/setup/solver.rs
crates/solver/src/settlement_submission/submitter.rs

Fixes task 2 from https://github.com/cowprotocol/services/issues/1893
Alternative to https://github.com/cowprotocol/services/pull/1840
Based on the configuration of the driver, if private networks are used for settlement submission, auction `gas_price` needs to be boosted. This is to set the same value of `gas_price` for ranking the solutions, as well as for the starting value for settlement submission (what will be the end value of gas price is something we don't know in advance).
`score_cap` removal not related to this PR, I just noticed that it's a dead code (in previous PR `score_cap` was moved to `autopilot`).
I decided not to waste time fixing this for the non-colocated driver, since the colocation will be activated soon and this issue is not high priority one.

Fix auction gas price

---

crates/autopilot/src/run_loop.rs

Follow up to #1914 
This PR just removes the unnecessary `collect` in the `flat_map` closure.
CI.

Avoid Collecting Driver Solutions in RunLoop

---

crates/orderbook/openapi.yml

Fixes the OpenAPI yaml description for down-stream consumers.
1. Attempt to place the same order twice.
2. Observe correct API response per `openapi.yml`.
Fixes #1928

fix: openapi for duplicated orders

---

crates/driver/src/boundary/liquidity/mod.rs
crates/driver/src/domain/competition/auction.rs
crates/driver/src/domain/competition/mod.rs
crates/driver/src/domain/quote.rs
crates/driver/src/infra/liquidity/fetcher.rs
crates/driver/src/infra/liquidity/mod.rs
crates/e2e/src/setup/onchain_components.rs
crates/e2e/tests/e2e/colocation_quoting.rs
crates/e2e/tests/e2e/main.rs

This PR was my take on recent liquidity fetching for the driver. Unfortunately, I did not see #1924 when I started working on it, but I believe some of my proposed changes are worthwhile including, so I rebased it onto the aforementioned PR.
In particular, this PR (just like the one its based on) uses recent instead of latest liquidity for quoting. This improves latency of quotes.
E2E test that verifies liquidity cache is not being updated for the `/quote` request.

Fetch Recent Liquidity for Quotes

---

crates/driver/src/domain/competition/auction.rs
crates/driver/src/domain/competition/mod.rs
crates/driver/src/domain/quote.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/solver/mod.rs

This PR makes a **hacky** (but IMO pragmatic) change proposal to the driver. In particular, in our current setup we share a `driver` instance across solvers that both use and don't use liquidity. This is an issue because solvers that don't need liquidity will end up waiting for liquidity that they don't use, increasing solving and quoting latency for those solvers.
The way this was imagined to work was to set up separate `driver` instances for solvers with different liquidity requirements. However, the downside to this is that those multiple `driver` instances don't share other valuable caches (balances, token infos, etc.). In addition, this adds additional complexity in the infrastructure setup (multiple drivers to deploy, multiple drivers as sources for logs, etc.).
The solution is …

Configuration To Skip Liquidity Fetching for Solver

---

crates/autopilot/src/run_loop.rs
crates/autopilot/src/shadow.rs

This PR refactors the autopilot runloop to add some additional observability to the solver competition. This will allow us to have a better idea of how individual solvers are behaving.
As a note on the code and how to record metrics - I created methods on the `Metrics` type in order to increment/observe things. I'm not 100% happy with this, but wanted to see what others think in terms of legibility. 
The code should be covered by existing E2E tests in the services.

Observability To Colocated Auction Runloop

---

crates/autopilot/src/run.rs
crates/driver/src/boundary/liquidity/balancer/v2/mod.rs
crates/orderbook/src/run.rs
crates/shared/src/sources/balancer_v2/pool_fetching.rs
crates/shared/src/token_info.rs
crates/solver/src/run.rs

In debugging with @fleupold on Friday, we noticed that the token info fetcher was potentially locking up concurrent quotes for certain price estimators, notably the ParaSwap and Quasimodo estimator that make use of token information (decimals specifically). This is caused by two things:
1. The token info cache will hold an `async` Mutex for the entire fetching of token information.
2. We are querying token info for `0xeee...eee` in the autopilot which will always fail and not get included in the cache, meaning it will always hold the lock for a node roundtrip.
The combination of these two issue causes quotes that need token information to execute not fully concurrently. In particular, if quote 1 would need token info for A and quote 2 for B, then quote 2 will need to wait for token info …

Adjustments to Token Info Fetcher

---

crates/solvers/src/domain/solution.rs
crates/solvers/src/domain/solver/baseline.rs
crates/solvers/src/domain/solver/dex/mod.rs
crates/solvers/src/domain/solver/naive.rs
crates/solvers/src/tests/balancer/market_order.rs
crates/solvers/src/tests/baseline/buy_order_rounding.rs
crates/solvers/src/tests/baseline/internalization.rs
crates/solvers/src/tests/baseline/mod.rs
crates/solvers/src/tests/paraswap/market_order.rs
crates/solvers/src/tests/zeroex/market_order.rs

Built-in solver engines (baseline, DEX aggregator, etc.) under the legacy `solver` would internalize interactions for eligible tokens when the settlement contract had sufficient buffers.
This PR adds this functionality to the co-located solver engines.
CI, added new tests, adjusted old tests which now internalize interactions (as expected).

Solver Engines Should Internalize Using Buffers

---

docker-compose.yaml

If I run `docker-compose up` in my system, I get an error:
<details><summary>Cannot create container for service migrations: invalid mount config for type "bind": invalid mount path: 'database/sql' mount path must be absolute</summary>
```
$ docker-compose up
Creating network "services_default" with the default driver
Creating services_chain_1 ... 
Creating services_adminer_1 ... 
Creating services_chain_1      ... done
Creating services_adminer_1    ... done
Creating services_db_1         ... done
ERROR: for migrations  Cannot create container for service migrations: invalid mount config for type "bind": invalid mount path: 'database/sql' mount path must be absolute
ERROR: Encountered errors while bringing up the project.
```
</details>
The path is now explicitly relative. This makes …

Use explicit relative path for migrations folder in docker-compose

---

crates/orderbook/openapi.yml

This PR fixes a typo in an `openapi.yml` enum. This is required for generation by downstream consumers. 
1. Verify tests continue to pass.

fix: openapi typo

---

Cargo.lock
README.md
crates/observe/Cargo.toml
crates/observe/src/tracing.rs

This reverts commit 8be3d0d9b01dc49d310247e31c5e7227b05c5a60.
We are seeing issues with tracing spans not being printed and some logs not showing up locally, that started around the time #1915 was deployed. 
I tried reconstructing the difference in the way the registry and subscriber works but I cannot see any (other than the writer logic which is inverted due to type-checker complaints). Both implementations use a default registry with an env filter and then the format layer inside (and unless `tokio_unstable` is provided neither use a console_subscriber).
Since this is affecting our ability to observe behavior, I think it's best to revert.

Revert "Add support for connecting tokio-console to binaries (#1915)"

---

crates/solvers/src/infra/dex/paraswap/dto.rs
crates/solvers/src/tests/paraswap/market_order.rs
crates/solvers/src/tests/paraswap/out_of_price.rs

We are seeing a lot of rate limits in the Paraswap solver likely because we are not setting the partner in the price query. This PR fixes this. We were already setting it in the transaction query.

[Trivial] Set Paraswap partner in price query

---

crates/solvers/src/api/dto/auction.rs
crates/solvers/src/api/mod.rs
crates/solvers/src/boundary/legacy.rs
crates/solvers/src/domain/auction.rs
crates/solvers/src/domain/solver/baseline.rs
crates/solvers/src/domain/solver/naive.rs

It turns out that we forgot to add `auction=$id` tracing spans to the `solvers` API handler. This PR does that to make debugging easier.
Note that we need to manually get the current span and move it into the new thread (and can't use `tracing::Instrumented::in_current_span`) because the blocking task gets executed on a separate thread outside of the `tokio` thread-pool which doesn't properly propagate spans.
Run locally to see the span:
```
2023-10-11T15:14:17.261Z TRACE request{id="9"}:/solve:auction{id=quote}: solvers::domain::solver::baseline: finding route order=0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 request=Request { sell: Asset { amount: 1000000000000000000, token: …
```

Auction ID to `solvers` Tracing Span

---

crates/driver/src/domain/competition/mod.rs
crates/driver/src/infra/api/error.rs
crates/driver/src/infra/api/routes/solve/dto/solved.rs
crates/driver/src/infra/observe/mod.rs
crates/driver/src/tests/cases/asset_flow.rs
crates/driver/src/tests/cases/internalization.rs
crates/driver/src/tests/cases/negative_scores.rs
crates/driver/src/tests/cases/settle.rs
crates/driver/src/tests/cases/solver_balance.rs
crates/driver/src/tests/setup/blockchain.rs
crates/driver/src/tests/setup/mod.rs

We recently added the ability for a driver to return multiple solutions. With this, we should no longer return an error when no solutions are found but an empty vector.
This was prompted by the general noisiness in metrics and logs for "regular" behaviour for the solvers.
Driver tests assert an "OK" response with empty solutions instead of errors.

Reduce Error-ness of not Finding Solutions

---

crates/autopilot/src/run_loop.rs

We are currently not finding a lot of settlement transactions after telling the driver to settle but don't have a simple log that ties those missing transactions to auction ids.
added a log

Emit logs for not finding settlement tx in time

---

crates/driver/src/infra/config/file/load.rs
crates/solvers/src/infra/config/dex/file.rs

Slippage tolerance in the solver is parsed using standard U256::from_str which interprets the string in base 16. 40000000000000000 (0.04ETH) thus becomes 73ETH causing us to set very high slippage tolerance.
This PR hot-fixes the parsing to use our custom base 10 serializer.
I noticed that we re-implement U256 parsing both in the driver as well as in the solver (and we recently added an implementation in the number crate). Ideally we unify the use. It’s also a bit confusing that we define slippage in both the driver as well as the solver (it’s needed in the driver to encode the baseline liquidity interactions)
It would also be great if we can get the linter yell at us if we ever try to serialise a U256 with the default serialiser (I’m not sure how to achieve this though) as this has been …

Fix solver slippage parsing

---

crates/solvers/src/infra/dex/balancer/mod.rs
crates/solvers/src/infra/dex/oneinch/mod.rs
crates/solvers/src/infra/dex/paraswap/dto.rs
crates/solvers/src/infra/dex/paraswap/mod.rs
crates/solvers/src/infra/dex/zeroex/mod.rs
crates/solvers/src/tests/mod.rs
crates/solvers/src/util/http.rs
crates/solvers/src/util/mod.rs
crates/solvers/src/util/serialize/mod.rs
crates/solvers/src/util/serialize/never.rs

This PR unifies HTTP handling in the `solvers` crate in way that:
- All HTTP requests automatically trace relevant information (method, URL, body, status code, etc.) while preserving the callsite's module path in the log event (useful for filtering, so you can enable `trace` JUST for a specific DEX aggregator API for example).
- Improved error handling:
1. We first try to parse with an API specific error type - this allows us to extract well-formed errors
2. In the case that we got an HTTP success but failed to parse the response data, emit a JSON error
3. In the case we got an HTTP error status code, emit an HTTP status error
CI tests DEX aggregator with mocked services, so we can be confident that it continues to work with this refactor.
Supersedes #1941

Unify HTTP handling in the solvers crate

---

crates/driver/src/boundary/mempool.rs
crates/driver/src/domain/mempools.rs
crates/driver/src/infra/blockchain/gas.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/mempool/mod.rs

Renames `Flashbots` submission to `MEVBlocker` in `driver` crate. Now the `Flashbots` is only mentioned in `boundary` part of the `driver` which is allowed.

[TRIVIAL] Rename Flashbots in Colocated Driver

---

crates/driver/src/boundary/mempool.rs

Adds mempool kind to every submission log, similar to what we have in non-colocated driver.
Didn't want to implement `Debug` nor `Display` just so to avoid any future misusage of ? and % in printing.

Add instrument for submission kind

---

crates/driver/example.toml
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs

We struggled a lot with correctly configuring the submission arguments because they were not parsed the same way other arguments were. This PR makes handling of those args the same as other args.
- rename `MEVBlocker` -> `MevBlocker` such that the kebab-case version is now `mev-blocker` and not `m-e-v-blocker`
- use `deny_unknown_arguments` because that would have helped noticing that we are setting arguments that don't even get used
- apply `#[serde(rename_all = "kebab-case")]` to submission strategy enum fields to turn expected arguments from snake_case to kebab-case (like for everything else)
- updated `example.toml` to mention all arguments correctly
Run the driver locally with the example file and see that it gets correctly parsed

Kebab case for submission args and updated example.toml

---

crates/autopilot/src/database/competition.rs
crates/database/src/order_execution.rs
crates/database/src/orders.rs
crates/e2e/tests/e2e/colocation_partial_fill.rs
crates/orderbook/src/database/solver_competition.rs

The computation of surplus fees for partially fillable limit orders happens delayed in the co-located world. This is because at the time of solution ranking, the autopilot doesn't have access to the executed amounts for each order (something that #1949 will hopefully address). We therefore wait to populate the surplus fee until the settlement (and thus the different order specific clearing prices which incorporate the fee) has been observed on-chain.
The logic that then computes the fee loads and updates the existing executions from the DB. However, it simply assumes there is no surplus fee computation if a "solver fee" is set:
https://github.com/cowprotocol/services/blob/efa7c756ff9e58b8ae3258d5715f86e2ee04185f/crates/autopilot/src/decoded_settlement.rs#L336-L338
If we look at the code …

Allow solver fee to be None

---

crates/contracts/build.rs

Our backend fails to compile using the nightly compiler. For some reason formatting the code generated for our contract bindings fails with `rustfmt` on nightly.
Usually I would say that we should not change our code base to appease the nightly compiler but in this case we only stop formatting auto generate code that nobody (?) looks at anyway. And since this issue seems to have blocked some people in the past I think it's an OK trade-off.
`cargo +nightly build` does not fail

Workaround for nightly build

---

crates/driver/src/boundary/mempool.rs
crates/driver/src/infra/observe/mod.rs

Currently our logs about submitting to the chain are quite noisy.
Turn [logs](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/doc/ea511870-d9b3-11ed-a9d0-a17451f01cc1/cowlogs-staging-2023.10.18?id=T6JwQosBGP6wkTcjXqUM) from:
```
mempool=Mempool { config: Config { additional_tip_percentage: 0.05, gas_price_cap: 1000000000000.0, target_confirm_time: 30s, max_confirm_time: 120s, retry_interval: 2s, kind: MEVBlocker { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("mevblockerrpc.barn.cow.fi")), port: None, path: "/", query: None, fragment: None }, max_additional_tip: 5000000000.0, use_soft_cancellations: true } } }
```
into:
```
mempool=Mempool(MEVBlocker)
```

Less noisy mempools logs

---

crates/driver/src/domain/competition/solution/settlement.rs
crates/driver/src/domain/mempools.rs
crates/driver/src/infra/observe/mod.rs

Ideally we can query a specific auction ID in kibana and get from a concise overview of what happened in the auction only by looking at INFO + logs (DEBUG may be somewhat noisy, TRACE is off by default).
Currently when looking e.g. at [this auction](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/8yS6J) we can see a lot of noisy info logs telling us about solvers submitting empty solutions, and their solver engines receiving the auction and fetching liquidity.
At the same time, we don't see information about the runners up solutions (unless they fail) in order to be able to easily reproduce them in Tenderly or Phalcon.
This PR improves this
- Log auction ID in execute call (this allows to get the auction_id from the tx_hash in a single INFO level request)
- demote some …

Colocation logging improvements

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/run.rs
crates/autopilot/src/run_loop.rs

The autopilot waits until a transaction is found onchain after submitting a transaction to the driver. The waiting time is now configurable.
The default value is the former hardcoded value: we can merge this PR before adding a new variable to our configurations.
Changes are untested, however this shouldn't be an issue since the changes are small and simple.
Closes #881.

Configurable autopilot wait time until settlement is detected onchain

---

crates/shared/src/price_estimation/factory.rs
crates/shared/src/url.rs
crates/solvers/src/boundary/legacy.rs

Fixes https://github.com/cowprotocol/services/issues/1988
Added a helper function to split a URL into base and path which is used for the `legacy` solver adapter.
added a unit test

Fix url splitting

---

crates/solvers/config/example.paraswap.toml
crates/solvers/src/infra/dex/paraswap/dto.rs
crates/solvers/src/tests/paraswap/market_order.rs
crates/solvers/src/tests/paraswap/out_of_price.rs

The paraswap solver issues a lot of [warnings](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-19T09:19:08.195Z',to:'2023-10-19T09:28:29.622Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ea511870-d9b3-11ed-a9d0-a17451f01cc1,key:kubernetes.container_name,negate:!f,params:(query:paraswap),type:phrase),query:(match_phrase:(kubernetes.container_name:paraswap)))),grid:(columns:('@timestamp':(width:164))),index:ea511870-d9b3-11ed-a9d0-a17451f01cc1,interval:auto,query:(language:kuery,query:'log:%20%22It%20is%20not%20allowed%20to%20have%20limit-orders%20Dex%20or%20paraswappool%20Dex%20in%20route%22'),sort:!(!('@timestamp',desc)))):
```
It is not allowed to …
```

Correctly exclude paraswap dexs

---

crates/solvers/src/domain/dex/mod.rs
crates/solvers/src/domain/solver/dex/mod.rs

@sunce86 [suggested](https://github.com/cowprotocol/services/pull/1960/files#r1363834421) to use the more accurate simulated gas amount for DEX swaps for the gas computation.
Instead of computing the score before turning the swap into a solution (which is where we get the accurate gas) we now also compute the score when turning the swap into a solution.

Use simulated gas for score computation

---

crates/driver/src/boundary/mod.rs
crates/driver/src/boundary/score.rs
crates/driver/src/boundary/settlement.rs
crates/driver/src/domain/competition/mod.rs
crates/driver/src/domain/competition/score.rs
crates/driver/src/domain/competition/solution/mod.rs
crates/driver/src/domain/competition/solution/settlement.rs
crates/driver/src/infra/observe/mod.rs
crates/driver/src/infra/solver/dto/solution.rs
crates/driver/src/tests/cases/score_competition.rs
crates/solver/src/run.rs
crates/solver/src/settlement.rs
crates/solver/src/settlement_rater.rs
crates/solvers/src/api/dto/solution.rs
crates/solvers/src/boundary/legacy.rs
crates/solvers/src/domain/solution.rs
crates/solvers/src/domain/solver/baseline.rs
crates/solvers/src/domain/solver/dex/mod.rs

No new functionality (actually fixes bug, because before this we did not check the validity of score if provided by solver as is, we did the checks only for risk adjusted scores).
Moves out score calculation out of the boundary settlement.
A step forward for https://github.com/cowprotocol/services/issues/1973 and prerequisite for implementing task #4 from https://github.com/cowprotocol/services/issues/1891
- Added objective_value calculation on boundary settlement
- Added score forwarding on boundary settlement
- With these two, score calculation is moved out to domain::settlement
- Score calculator moved to boundary::score and used by ☝️ 
- These two allowed to define domain::score::Error and propagate errors properly.

Refactor score calculation

---

crates/autopilot/src/run.rs
crates/autopilot/src/run_loop.rs

We were made aware that we are currently sending *a lot* of auctions on xdai staging. This is because the auctions are mainly empty (or solvers quickly return an empty solution) and then our run_loop sleeps for a hardcoded amount of 1s, which is way to short.
This PR makes this value configurable. It reuses the existing `auction_update_interval` which decides how often we prepare a new auction. Maybe this value should be separate, but at least we shouldn't dispatch auctions more often than we update them (otherwise we may dispatch the same auction multiple times which is likely not going to change the outcome)
- Make the sleep between run_loops configurable
- Deduct the time the run loop has take from this value to make sure we don't wait for a long time if a solution was found and mined …

Make times between auction run_loops configurable

---

crates/solvers/src/boundary/legacy.rs
crates/solvers/src/tests/legacy/market_order.rs

Solvers already submit self computed fee amounts even for orders that still work with a protocol specified fee (e.g. market orders). See this barter response for instance: http://jsonblob.com/1164883806913421312
The code currently rejects those solutions with "invalid trade execution" errors. This PR makes the legacy adapter compliant with the current system where we ignore the fee_amount for orders that don't require them (rather than erroring if it specified)
- Instead of erroring when a surplus fee is specified although the solver doesn't determine the fee we now always use the protocol fee instead
- adjust unit test to demonstrate the response is now accepted
Unit test
Fixes #1996

Fix Legacy Solver

---

crates/driver/src/domain/eth/mod.rs

Drop the `access_list` field from the `Debug` impl because it's pretty noisy and not very helpful for debugging purposes.

Drop access list from `eth::Tx` `Debug` impl

---

crates/autopilot/src/run_loop.rs

https://github.com/cowprotocol/services/pull/1999 had the unfortunate side effect that we spammed a few [alerts](https://cowservices.slack.com/archives/C037PB929ME/p1697812387457109) whenever the driver was not able to settle a solution.
We now only `warn` whenever we can't parse the success response. We didn't introduce, expect and parse any specific error format because eventually drivers will be run externally and maybe not all of them run a driver compliant with the error response spec all the time.
If we simply print the parsing error we'll get all the data we can get out of the response anyway.

Parse /settle errors and only warn about them

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/run.rs
crates/autopilot/src/run_loop.rs
crates/autopilot/src/shadow.rs
crates/driver/src/domain/competition/mod.rs
crates/driver/src/infra/blockchain/mod.rs
crates/driver/src/run.rs
crates/driver/src/tests/setup/mod.rs
crates/driver/src/tests/setup/solver.rs
crates/e2e/src/setup/services.rs

Fixes #2007. The preferred solution described in that issue was not straight forward to implement.
It expected the `autopilot` to call `/reveal` from the highest scoring solution to the lowest scoring one to simulate it in order to avoid cases where a solver wins the auction with a solution that would revert by now.
The issue was that this requires the `autopilot` to know the address of every solver which would be a significant change.
Instead this PR implements a strategy on the `driver` side that a rational actor would be expected to follow as well.
All solvers know when they have to return a solution at the latest. Because a solution can be more accurate the closer it was computed to the time it is supposed to be executed it makes sense for all solvers to delay their response as much …

Wait for solve deadline

---

.github/workflows/pull-request.yaml
crates/e2e/src/nodes/forked_node.rs
crates/e2e/src/nodes/local_node.rs
crates/e2e/src/nodes/mod.rs
crates/e2e/src/setup/mod.rs
crates/observe/src/panic_hook.rs
docker-compose.yaml

Ever since we replaced `hardhat` with `anvil` we got flaky tests.
The issue seems to be related to deadlocks inside `anvil`. It's possible that these deadlocks could be related to running the same node instance for all tests and resetting it over and over again.
Drop `anvil` from the `docker-compose` file and instead spawn a fresh `anvil` instance for every `e2e` test.
Rerun CI a couple of times and :pray: that we don't see flaky errors?

Dont reset node during test

---

.github/workflows/pull-request.yaml

[`nextest`](https://nexte.st/) is overall nicer than the built-in `cargo test`. It's faster, has more knobs to tweak and specifically built with CI in mind.
CI should be running the same tests. The only difference is that some test jobs no longer output all the logs but only the logs of failed tests which I find pretty useful because those logs can get very noisy.
inspect new [output](https://github.com/cowprotocol/services/actions/runs/6638204181/job/18034529435?pr=2014) of the CI jobs

Use nextest for CI

---

crates/autopilot/src/arguments.rs

Prints missing arguments for trusted tokens.
Need this to make sure arguments are set properly: https://github.com/cowprotocol/infrastructure/pull/817

Print trusted tokens arguments

---

crates/driver/src/domain/competition/mod.rs
crates/driver/src/infra/observe/mod.rs
crates/driver/src/infra/solver/mod.rs

Pretty fix: moves the check to main competition::solve where all the checks are done.

Move duplicated ids check to competition::solve

---

crates/solver/src/liquidity/slippage.rs

If some external API returns a `0` amount for a buy order it will pass the `execution_respects_order` check and will cause a panic in this slippage computation due to div by 0.
Returns errors when slippage computation would encounter any div by zero (simply use `.checked_div()`).
All unit tests should continue to pass

Fix div by 0 in slippage computation

---

crates/driver/src/domain/competition/mod.rs
crates/driver/src/infra/notify/mod.rs
crates/driver/src/infra/notify/notification.rs
crates/driver/src/infra/observe/metrics.rs
crates/driver/src/infra/observe/mod.rs
crates/driver/src/infra/solver/dto/notification.rs
crates/driver/src/infra/solver/mod.rs
crates/solvers/src/api/routes/notify/dto/notification.rs
crates/solvers/src/boundary/legacy.rs
crates/solvers/src/domain/notification.rs
crates/solvers/src/domain/solution.rs

Populates `SolverRejectionReason::RunError(SolverRunError::Timeout)`.
The easiest way to implement this was to use already handled timeout from the http request sent from `driver` to `solvers`.

Colocation notify - solver engine timeout

---

crates/shared/src/http_solver.rs

The current logic to build the `/notify` URL doesn't handle URLs that contain multiple path segments correctly.
Take this http solver URL for example:
`https://miep.cow.solver/1/solve?api_key=1234#row=3`
which consists of the base `https://miep.cow.solver` and the `solve_endpoint` `/1/solve?api_key=1234#row=3`.
The old logic would have computed the notify endpoint to be `https://miep.cow.solver/notify` whereas `https://miep.cow.solver/1/notify?api_key=1234#row=3` actually makes more sense. (`/notify` as a sibling to `/solve`).
Always make `/notify` a sibling of `/solve` (including all query parameters and fragments).
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5d4168862014d3876c28c19153b4267c

build /notify URL respecting multiple path segments

---

crates/driver/src/boundary/score.rs
crates/driver/src/domain/competition/score.rs
crates/driver/src/domain/competition/solution/settlement.rs

Implements proper error handling when building `Score` from `ZeroU256`.
Accidentally, this was done through `eth::NonZeroU256::from` and then the error was converted to `anyhow::Error`, but what we actually want is to convert to `score::Error::ZeroScore`.
It was noticed in [this log](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/doc/ea511870-d9b3-11ed-a9d0-a17451f01cc1/cowlogs-staging-2023.10.31?id=_bRBh4sBQgsUfyaRQinM).

Properly propagate errors for zero scores

---

crates/autopilot/src/arguments.rs
crates/shared/src/arguments.rs
crates/solver/src/arguments.rs

@fhenneke noticed that our `score_cap` is [parsed wrongly](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/doc/c0e240e0-d9b3-11ed-b0e6-e361adffce0b/cowlogs-prod-2023.11.01?id=icFRiosBGP6wkTcjJhYX).
Value `1e16` is parsed as `18446744073709551616` due to decimal/hexadecimal misconfiguration.

Fix parsing score_cap

---

crates/shared/src/sources/uniswap_v3/graph_api.rs
crates/shared/src/sources/uniswap_v3/pool_fetching.rs

When restarting a pod we sometimes get alerts stating that the last block that we successfully ran our maintenance tasks on lags behind the most recent block we saw.
This [log](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-01T09:59:38.245Z',to:'2023-11-01T10:05:23.271Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,key:kubernetes.container_name,negate:!f,params:(query:mainnet-solver-prod),type:phrase),query:(match_phrase:(kubernetes.container_name:mainnet-solver-prod)))),grid:(columns:('@timestamp':(width:164))),index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,interval:auto,query:(language:kuery,query:'mainnet%20and%20 …

Debug univ3 maintenance times

---

crates/shared/src/http_solver.rs

Add `chain_id` to the query variables on the `/notify` request. We would appreciate this for the Enso solver as all of our infra is multi chain by default. With this we can monitor which chain the notification relates to.
Originally I wanted to add a `metadata` field to the `AuctionResult`, but this accomplishes the same thing and requires no model changes.
Add `chain_id` to the query variables on the `/notify` request.
Couldn't find an existing `/notify` tests, if they do exist please let me know and I can add some assertions. It is also just a really small change...
https://github.com/cowprotocol/services/issues/1891#issuecomment-1779295895

Add chain_id to /notify query string

---

crates/driver/src/domain/competition/auction.rs
crates/driver/src/domain/eth/balances.rs
crates/driver/src/domain/eth/mod.rs
crates/driver/src/infra/api/mod.rs
crates/driver/src/infra/api/routes/solve/mod.rs
crates/driver/src/infra/observe/mod.rs

When the driver receives a `/solve` request it fetches the balances for all traders in the auction. The outcome of this exclusively depends on the current block so duplicating this work for every configured solver does not make sense.
This will result in fewer RPC requests and probably also in a faster auction pre-processing time.
The solvers are not really contending on a lock but they are using the same underlying buffered `Web3` type. This is configured to allow up to 10 parallel batch requests with 20 individual requests each. These 200 requests can probably be easily saturated when 10 solvers fetch balances for ~1000 orders which means there will be some solvers who have to wait for the backpressure to resolve.
Introduce shared cache for balances which gets updated when the solver …

Cache balances in driver

---

crates/solvers/src/domain/solver/baseline.rs

Baseline solver iterates through orders from `auction` and executes some logic for each order in a synchronous way. It checks the deadline before each order. It could happen that the new order logic begins to execute 1ms before the deadline and lasts arbitrary amount of time (500ms?) and significantly break the deadline.
This code adds a checker if the deadline is reached in the main thread, and if it is, ends the background work prematurely and returns whatever was executed up until that point.
Example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0e23fa016153883faad8b0e7148b4dfa

Respect deadline in Baseline solver

---

crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/solver/mod.rs
crates/driver/src/tests/setup/solver.rs

Makes the solver http time buffer configurable. 
This indeed seems like a value we want to setup once and never touch again, which why I don't feel strong to add parameter for this (instead of just updating the hard coded value). 
OTOH, we need this configurable at least until further notice.

Configurable http time buffer

---

crates/driver/src/infra/blockchain/token.rs

The driver has a routine to prioritize orders and filter orders based on the balance the trader currently has.
With the introduction of pre-interactions this check became much trickier because a user might not have any sell_tokens at the moment but unstakes the needed tokens in a pre-interaction. Because of that we introduced a way to get the actual tradable balance by simulating a balance check using a helper contract.
This is very accurate but unfortunately also very slow. (~10s just for fetching the balances of all traders in an auction)
Luckily most of our orders don't have pre-interactions so we can fall back to a simpler and faster way to query the current balance.
Reimplement parts of the balance query of [balances.sol](https://github.com/cowprotocol/services/blob/main/crates/contra …

Speed up balance fetching

---

crates/driver/src/domain/competition/solution/settlement.rs
crates/solver/src/settlement_submission.rs

The point of gas limit factor is to take into consideration possible small changes in gas estimation from block to block during submission.
However, recently seasolver submitted solutions on gnosis chain that have a significant amount of gas refunds. Gas refunds are refunded at the very end of the execution in the EVM, so if the gas limit is set too low, peak gas usage during EVM execution can exceed it and return `OutOfGas` error.
Setting the factor to `2.0` seems safe, since I don't think nothing catastrophic can happen even if we spend double gas in case of an error.
Adjusted factor for both submission but also for colocated driver settlement encoding where factor is used to calculate the required eth balance of solver. Although the latter one doesn't seem necessary, I decided to do it …

Increase gas limit

---

crates/shared/src/url.rs

During colocation prod test, quasilabs endpoint was misconfigured. In the meantime, I also noticed that it is misconfigured in the staging also.
Quasilabs is the only solver that has endpoint authorization defined as `https://user:pass@host.com/solve`. Based on the current splitting of paths, user and pass get lost. This PR keeps the user and pass as part of the `base`.
Updated unit test.

Fix Quasilabs URL configuration

---

crates/solvers/src/boundary/legacy.rs
crates/solvers/src/domain/solver/legacy.rs

Timeouts in legacy solvers are handled inside `solvers` crate and in those cases empty solutions vector is sent to `driver`, leading to these errors being classified in the `driver` as `empty` solutions instead of `timeout`. The consequence of this is that legacy solvers are not properly notified.
This PR sends the `timeout` notification directly from within `legacy` solver so there is no ambiguity. Note that there is no way for `driver` to know this is a `timeout`, so additional `empty` notification will be sent, but afterwards, so it can be ignored by `legacy` solvers.

Notify timeout early

---

crates/driver/src/infra/blockchain/token.rs

Using a dummy web3 to send RPC requests causes [panics](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(log),filters:!(),grid:(columns:('@timestamp':(width:164))),index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,interval:auto,query:(language:kuery,query:'mainnet%20and%20(log:%20%22panicked%22)'),sort:!(!('@timestamp',desc)))).
Instead we use a somewhat ugly way to get at the web3 instance that was used to build the ERC20 token instance.

Add workaround to get actual web3 instance instead of dummy version

---

crates/solver/src/liquidity_collector.rs

We currently have an issue that some solvers receive only uni v2 based liquidity and usually at most 1 solvers receives balancer or uni v3 based liquidity. This is caused by the too simplistic initialization logic inside `BackgroundInitLiquiditySource`. It was written at a time when it would not be queried in parallel (for which the implementation would be fine) but for the new driver (which can query it multiple times in parallel) it results in wrong liquidity availability.
The issue is basically that the old code used `try_lock` because it assumed only the background task running a (potentially) slow initialization logic could use it in parallel. In that case we wanted to return an empty result early.
However with the new code an initialized liquidity source might be locked because it …

Use OnceCell to manage liquidity source initialization

---

crates/driver/src/domain/competition/mod.rs
crates/driver/src/infra/notify/mod.rs
crates/driver/src/infra/notify/notification.rs
crates/driver/src/infra/simulator/mod.rs
crates/driver/src/infra/solver/dto/notification.rs
crates/driver/src/run.rs
crates/solvers/src/api/routes/notify/dto/notification.rs
crates/solvers/src/boundary/legacy.rs
crates/solvers/src/domain/notification.rs

Fixes https://github.com/cowprotocol/services/issues/2018

Add block number to simulation error

---

crates/solvers/config/example.legacy.toml
crates/solvers/src/boundary/legacy.rs
crates/solvers/src/domain/solver/legacy.rs
crates/solvers/src/infra/config/legacy.rs
crates/solvers/src/tests/legacy/mod.rs

Adds an ability to configure GZIP compression of HTTP requests in each legacy solver.
A new boolean `gzip_requests` config field.
k8s manifest PR https://github.com/cowprotocol/infrastructure/pull/859 which is required to be deployed first
TBD: would it be possible to test it in staging with any solver?
Fixes #916

Add legacy solvers requests compression config

---

crates/autopilot/src/solvable_orders.rs
crates/shared/src/api.rs

While working on dockerizing the e2e tests I noticed that we can run into an annoying race condition caused by caching balances in 2 places (balancer fetcher and solvable orders).
Given this scenario:
1. start solvable orders block
2. it notices a new block appeared so it asks the balance fetcher for the new balances
3. balancer fetcher did not yet see the new block so it returns the old unchanged balances
4. solvable orders caches old balances
This case is not a big deal in production but I'm fairly confident this causes our flaky e2e tests. Because those e2e tests only produce blocks when a tx needs to get mined we can encounter the scenario where that test waits for an order to be settled which will never happen because the `autopilot` never noticed that the user has the required …

Avoid double balance caching race condition

---

crates/autopilot/src/database/on_settlement_event_updater.rs
crates/database/src/settlement_observations.rs

Fixes current issue we have in gnosis chain staging, where deep reindexing happened and on_settlement_event_handler doesn't handle it properly.

Fix storing settlement observations

---

crates/solvers/src/domain/solution.rs
crates/solvers/src/domain/solver/legacy.rs

I don't find empty solutions useful in driver/solvers communication. Currently, all solvers except legacy solvers return empty vector when they can't find a solution, while legacy sends empty solution:
https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/ldj1i
I find it hard to read. Solvers should be consistent.
This PR changes legacy solver to send no solutions to the driver.
I still we should still keep the proper handling of empty solutions in the `driver` since we won't control the solvers forever.

Don't send empty solutions to the driver

---

crates/driver/src/domain/competition/auction.rs
crates/driver/src/domain/competition/order/mod.rs
crates/driver/src/tests/cases/merge_settlements.rs
crates/driver/src/tests/cases/negative_scores.rs
crates/driver/src/tests/cases/order_prioritization.rs

I noticed that when placing a too optimistically quoted order on Gnosis Chain (which cannot fill) and later placing another more realistic order on top, the second order only gets filled once the first one is expired or cancelled. This is because the driver filters out the second order as it looks like the user only has balance for the first. However, in theory we should sort orders by their expected chance of filling (taking the external auction prices into account), meaning the second order with a more lax limit price should have priority over the first order:
https://github.com/cowprotocol/services/blob/fd7f12dded72359c087be6f3c04b898241c3eb20/crates/driver/src/domain/competition/auction.rs#L176-L195
The root cause seems to be that likelihood wasn't implemented correctly, which this PR …

Fix order likelihood logic

---

crates/driver/src/domain/quote.rs

We are seeing a lot of WARN logs for orders that can't be quoted a la:
> driver::infra::observe: failed to quote order order=Order { tokens: Tokens { sell: TokenAddress(ContractAddress(0xf939e0a03fb07f59a73314e73794be0e57ac1b4e)), buy: TokenAddress(ContractAddress(0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2)) }, amount: TargetAmount(100000000000000000), side: Buy, deadline: Deadline { driver: 2023-11-23T07:58:46.894119698Z, solvers: 2023-11-23T07:58:45.995982488Z } } err=QuotingFailed(ClearingSellMissing)
This is because some solvers instead of returning no solution return the "trivial" solution if they cannot solve the auciton:
> solvers::api::routes::solve: auction_id=Quote solutions=[Solution { id: Id(0), prices: ClearingPrices({}), trades: [], interactions: [], score: …

[Trivial] filter out empty solutions when quoting

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/database/order_events.rs
crates/autopilot/src/lib.rs
crates/autopilot/src/periodic_db_cleanup.rs
crates/autopilot/src/run.rs
crates/database/src/lib.rs
crates/database/src/order_events.rs
database/sql/V057__add_timestamp_index_to_order_events.sql

Add a background task that periodically drops order events from DB that are very old (configurable).
Added integro-test
Implements the first task of the #1977

Periodic order events table clean up

---

crates/driver/src/boundary/liquidity/balancer/v2/mod.rs
crates/solver/src/liquidity/balancer_v2.rs
crates/solver/src/settlement_simulation.rs

The new driver is using a huge amount of memory. One low hanging fruit is to slightly redesign the internals of balancer v2 liquidity. Currently all those stable and weighted pools contain big pieces of data that don't change and are duplicated.
For other liquidity sources this was handled by having an `Inner` component that contains that data which is shared with `Arc`s across all liquidity components.
This PR applies that same pattern for balancer stable and weighted pools.
Just the compiler since it's only a minor refactor

Reduce memory used for balancer v2 liquidity

---

crates/driver/src/infra/observe/mod.rs

This log is creating issues with Kibana ([context](https://cowservices.slack.com/archives/C036PMLUPQF/p1701088972191479)). Moreover it is redundant (printed once per driver) and the same information can be recovered from the autopilot who also logs the current auction.

[Trivial] Do not log full auction

---

crates/e2e/tests/e2e/colocation_quoting.rs
crates/shared/src/recent_block_cache.rs

Our `RecentBlockCache` works like this:
1. somebody requests liquidity
2. cache checks if it's already known
3. if it's not in the cache query the blockchain
4. store in cache
5. remember requested liquidity source for updating it in the background
Whenever we see a new block we fetch the current liquidity for all the liquidity sources and write them to the cache together with their block. We have a max cache duration. Whenever the cached state exceeds that duration we remove the oldest entries.
This implementation uses unnecessarily much memory in 2 ways:
1. We can fetch liquidity for quotes. For those requests it's okay to return liquidity that is not 100% up-to-date. However, we still remember the requested liquidity source for future updates. This is not great because we can receive …

Reduce memory consumption of `RecentBlockCache`

---

crates/driver/src/infra/tokens.rs
crates/e2e/src/setup/colocation.rs
crates/e2e/tests/e2e/colocation_buffers.rs
crates/e2e/tests/e2e/main.rs

Addresses the bug that we currently fetch settlement buffer balances once per token and don't update them in between auctions, which can lead to solutions relying on outdate internal buffer balance information and thus incorrectly marking interactions as internalizable causing simulation to fail.
This approach is a bit wasteful, as token balances only really change when a settlement trading this token is included on-chain. However, getting that information in this component is non-trivial. Moreover, some tokens exhibit custom balance logic (e.g. rebasing tokens) which could update the contract balance even without a settlement taking place.
If we deem this approach too inefficient, I would suggest we restrict the number of tokens we cache (using an LRU cache) and re-fetch all relevant …

Update settlement contract balances in background task

---

crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs

We have two "grouped" configuration parameters on the driver's solver-engine config: Slippage and Timeouts. Currently one is specified as a sub-struct while the other one is flattened into the top level struct.
From a data model perspective, I think grouping related config fields together helps us keep the high level config clean. At the same time, configuring the nested config in `toml` leads to verbose files a la
```toml
[[solver]]
name = "mysolver" # Arbitrary name given to this solver, must be unique
endpoint = "http://0.0.0.0:7872/"
absolute-slippage = "40000000000000000" # Denominated in wei, optional
relative-slippage = "0.1" # Percentage in the [0, 1] range
account = "0xB9332b6301e5983272c30dd5b48a4e3B1664511b"
[solver.timeouts]
http-time-buffer-milliseconds = 500 …
```

[Easy] Unify driver's slippage and timout config

---

.github/workflows/deploy.yaml

I noticed our auto-deploy jobs are frequently timing out in the services repo: https://github.com/cowprotocol/services/actions/workflows/deploy.yaml, which is due to our k8s deployment being too slow (currently [~7 minutes](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/DylSb)) for all pods to restart. https://github.com/cowprotocol/autodeploy-action/pull/39 made the timeout for the requests configurable (before it was hardcoded to 6 minutes). This PR uses this config value.
Observe deploy job succeeding after this PR is merged.

[Easy] Configure autodeploy request timeout

---

.github/workflows/deploy.yaml

So that specifying a timeout actually does something ([current state](https://github.com/cowprotocol/services/actions/runs/7090939360/job/19301626088)), the current version doesn't include https://github.com/cowprotocol/autodeploy-action/pull/39

[Trivial] Bump autodeploy version

---

.github/workflows/deploy.yaml
crates/driver/src/domain/eth/mod.rs
crates/driver/src/infra/simulator/enso/dto.rs
crates/driver/src/infra/simulator/enso/mod.rs

Without this settlements that are sending the native asset to a smart contract fail simulations, because they run out of gas.
Access lists are supported by temper: https://github.com/EnsoFinance/temper

Enso access lists

---

crates/autopilot/src/run.rs
crates/autopilot/src/run_loop.rs

Although the `autopilot` currently waits until the `driver` reports that the settlement was mined the auction of the next run loop might not yet be aware that the orders of the previous settlement were solved.
If a solver then tries to solve those orders again it will run into simulation failures.
We now filter out in-flight orders from the auction if it was built before the block where the in-flight orders were settled.

Filter in-flight orders

---

crates/shared/src/arguments.rs
crates/shared/src/gas_price_estimation.rs

Since the GnosisSafe isn't working and is not available as a gas estimator anymore (as detailed [here](https://github.com/cowprotocol/gas-estimation/pull/12)), I removed all code related to it.
- Remove GnosisSafe gas estimator code 
CI.
This PR should not be merged before [this](https://github.com/cowprotocol/infrastructure/pull/909) is.
Related to issue #2094.

Remove GnosisSafe gas estimator

---

crates/driver/src/infra/observe/metrics.rs
crates/driver/src/infra/observe/mod.rs

Needed to replace this [alert](https://cowservices.slack.com/archives/C036ZGSCJNP/p1701783487316099)
Note, that this doesn't include information about the solver that is submitting the solution. I don't think this is necessarily required, so I didn't add it.

[Trivial] Record mempool submission metrics in driver

---

crates/autopilot/src/database.rs
crates/database/src/lib.rs

Noticed that the rows count query for the `order_events` table takes **150-200+ seconds** both in staging and prod. The proposal is to try out using rough row count estimation for large tables.
`SELECT COUNT(*) ...` is replaced with `SELECT reltuples FROM pg_class WHERE relname='{table}';` for the `order_events` table.
Will analyze metrics to understand how often Postgres updates the statistics without manually triggering `ANALYZE`. 
In case statistics update happens often enough, the same approach could be considered for other tables where very often row count update is not necessary.

Optimize rows count metrics

---

crates/autopilot/src/run.rs
crates/autopilot/src/run_loop.rs

Executes order events db insert operation in parallel in order to propagate the auction among solvers as soon as possible. The same approach could be used in other parts of the application since this operation takes a while.
Logs observation
Relates to https://github.com/cowprotocol/services/issues/2095

Run order events insertion in parallel

---

crates/autopilot/src/run_loop.rs

Implements logic similar to what we currently have in the solver crate to track how many orders were part of a solution that didn't end up winning. This can be used to populate alerts like [this one](https://g-0263500beb.grafana-workspace.eu-central-1.amazonaws.com/d/oPiE1Ennz/alerts-prod?editPanel=10&tab=query&orgId=1).
https://github.com/cowprotocol/services/blob/1b585b5b08a34fe57e7c53cc6d9514c8daa7d5e6/crates/solver/src/analytics.rs#L19-L47
Observice Grafana

Report metrics for matched but unsettled orderes

---

.github/workflows/pull-request.yaml

TOML parsing errors on CI/CD are not displayed and make it hard to investigate. 
This PR will show the parsing error assuming that all the configs used for testing contain dummy data only.

Allow TOML error trace

---

crates/driver/src/boundary/settlement.rs
crates/driver/src/domain/competition/solution/trade.rs
crates/driver/src/tests/cases/fees.rs
crates/driver/src/tests/cases/mod.rs
crates/driver/src/tests/setup/driver.rs
crates/driver/src/tests/setup/mod.rs
crates/e2e/src/setup/colocation.rs
crates/e2e/src/setup/services.rs
crates/shared/src/account_balances/cached.rs
crates/shared/src/event_handling.rs
crates/shared/src/recent_block_cache.rs
crates/solver/src/settlement_access_list.rs

Market orders currently return incorrect executed amounts (cf. #2150) because we report the fee amount solvers are supposed to use for scoring (which add the 0.002 ETH gas subsidy we currently apply on user orders to compensate the gas overhead in the settlement contract). 
However, this fee amount is only used for scoring (to avoid solutions getting rejected because of negative scores) and is not what the user actually pays.
Newly added tests
Fixes #2150

Use unscaled user fees for executed amounts

---

Cargo.lock
crates/autopilot/src/run.rs
crates/driver/Cargo.toml
crates/driver/example.toml
crates/driver/src/boundary/liquidity/balancer/v2/mod.rs
crates/driver/src/boundary/liquidity/uniswap/v3.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/liquidity/config.rs
crates/e2e/src/setup/colocation.rs
crates/orderbook/src/run.rs
crates/shared/src/arguments.rs
crates/shared/src/price_estimation/http.rs
crates/shared/src/sources/balancer_v2/graph_api.rs
crates/shared/src/sources/balancer_v2/pool_fetching.rs
crates/shared/src/sources/uniswap_v3/graph_api.rs
crates/shared/src/sources/uniswap_v3/pool_fetching.rs
crates/shared/src/subgraph.rs
crates/solver/src/run.rs

This PR aims to fix [2105](https://github.com/cowprotocol/services/issues/2105)
The subgraph base url is read from the environment variables.
All unit tests still pass

Make subgraph URL's configurable

---

crates/driver/src/domain/competition/mod.rs
crates/driver/src/infra/observe/mod.rs

Once a solver is done merging and post-processing solutions, we continue simulating their best solution candidate upon arrival of new blocks to make sure they are still valid. We void the solution candidate if simulation fails.
However, simulation may fail for two reasons:
1. An actual revert
2. Some other error (e.g. HTTP errors or the like)
While both are lethal for generating to solution candidate in the first place (as we need to get the gas estimate from the simulation for ranking), only actual reverts should cause a solution to be evicted in the final phase. In case we have a network error, we can just be "optimistic" and assume the outcome of the simulation hasn't changed.
CI and 🤞 as we don't have a way to test/mock simulations as part of e2e tests and this issue seems to be too …

[Easy] Only void solutions that fail due to reverts

---

crates/autopilot/src/run_loop.rs

We already have a grafana dashboard to track the time every driver spends in `/solve` but the default prometheus histogram buckets are not really suitable to get useful information out of this metric.
Adjust the metric to have 1 bucket for every second in the deadline.

Adjust /solve time buckets

---

crates/alerter/src/lib.rs

I was looking into why we did not receive an emergency alert during the MEVBlocker outage last week. It turns out that our alert pod broke when 0x started requiring API keys.
As a consequence, all our API calls received 401 errors and we thus didn't identify any solutions as unsettleable. This issue was raises as an alert in the barn alert channel (since the alerter itself only runs in staging), but didn't catch attention.
It didn't show up before, because the alerter only attempts to query 0x when there are no settlements for a longer period of time (which usually doesn't happen). Therefore this issue could only be identified when an outage was actually in progress.
This PR focusses on fixing the use of the 0x API. I think we should also revisit how we ensure that the alert pod is …

Configure alerter with 0x API Key

---

.github/workflows/pull-request.yaml

Our [forked node](https://github.com/cowprotocol/services/actions/workflows/pull-request.yaml) tests are very flaky, likely because we use a public archive node.
CI

Use NodeReal Archive Node for forked tests

---

crates/shared/src/price_estimation.rs

The current default argument of `native_price_estimators` is an invalid value. This can be seen by running the autopilot without any argument:
```
$ cargo run --bin autopilot
[...]
native_price_estimators: GenericPriceEstimator("GenericPriceEstimator(\"Baseline\")")
[...]
```
This is because the default is generated with `default_values_t`, which "Requires std::fmt::Display that roundtrips correctly with the [Arg::value_parser](https://docs.rs/clap/latest/clap/struct.Arg.html#method.value_parser) or #[arg(value_enum)]" ([source](https://docs.rs/clap/latest/clap/_derive/index.html#arg-attributes)).
This PR changes the string representation to work according to the docs remark.
A negative of this change is that we technically can't distinguish between …

Consistent string representation of NativePriceEstimators

---

README.md
crates/contracts/artifacts/TestnetUniswapV2Router02.json
crates/contracts/build.rs
crates/contracts/src/lib.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/liquidity/config.rs
crates/model/src/lib.rs
crates/shared/src/bad_token/token_owner_finder/blockscout.rs
crates/shared/src/network.rs
crates/shared/src/price_estimation/native.rs
crates/shared/src/sources.rs
crates/shared/src/sources/balancer_v2/pool_fetching.rs
crates/shared/src/sources/uniswap_v2.rs
crates/solver/src/settlement_submission/submitter.rs
crates/solvers/src/domain/eth/chain.rs

This PR provides everything needed for making the services work on Sepolia. This almost exclusively means populating the contract crate with relevant addresses on Sepolia and directly related changes.
The main problem with Sepolia is the lack of liquidity, even compared to Görli. The only liquidity source we have available is a third-party Uniswap v2 deployment where I deployed some liquidity myself.
We also have Balancer, but I need to sort things out with the subgraph URL (see [2139](https://github.com/cowprotocol/services/pull/2139)) so this will happen in a later PR.
- New contract addresses for Sepolia.
- New Uniswapv2-like liquidity source on Sepolia (`TestnetUniswapV2`) and related ignored test. Router, factory and pair are exactly the same as on vanilla mainnet except for two …

Add Sepolia testnet

---

.devcontainer/Dockerfile

This additional package is required to successfully compile the `openssl-sys` crate.

Add pkg-config

---

crates/driver/src/boundary/mempool.rs
crates/driver/src/boundary/settlement.rs

We are currently paying a pretty high tip for some [trivial settlements](https://etherscan.io/tx/0x25f2edcb2473120ce0583277af48a1241fc30629649856ebcd34ce23e9b04bbb) that are submitted via the public mempool (since they don't carry revert risk). 
While we do enforce 0 additional tip for public mempool submission, we also submit each trivial transaction via the MEVBlocker mempool strategy, which allows setting a higher tip.
If a transaction is available to a builder with both a high and a low tip, a profit maximizing builder will always chose the high tipping one.
Not really e2e testable since we cannot cover MEVBlocker behavior, but we should see cheaper settlements for internalized trades in staging

Don't pay additional tip for non revertable transactions

---

crates/shared/src/price_estimation.rs

I wanted to know how this parameter is used and I realized it isn't.
It's still a valid argument for the `solver` binary however.
- Remove price estimator argument `quasimodo_solver_url`.
Code compiles.

Remove unused argument quasimodo_solver_url from price estimation

---

crates/autopilot/src/arguments.rs

On startup, we want to print all arguments that were passed to any of our binaries.
However, sometimes we add new arguments but we forget to add them to the `Display` implementation.
This PR refactors the code so that the compiler throws an error if some arguments are missing.
- Enforce usage of all arguments when implementing `Display` in the autopilot.
- Add a few missing arguments to the `Display` implementation.
I'll do the same for all other binaries if this PR is approved and merged.
Code should compile.

Enforce all available api arguments are printed

---

crates/shared/src/sources/balancer_v2/graph_api.rs

Fixes https://github.com/cowprotocol/services/issues/2204
By filtering out pools that basically don't have meaningful liquidity we reduce the number of pools from ~1300 to ~500 and also eliminate problematic pools (with old problematic tokens).
Play with unit test `balancer_subgraph_query`

Filter out useless pools

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/run.rs
crates/autopilot/src/solvable_orders.rs

Initiative to simplify autopilot parameters so we can move them to `toml` format.
This factor is 1 for quite some time and there is no plan to use it. Also, with moving to all orders being limit orders, it becomes useless.

Remove fee_objective_scaling_factor

---

crates/driver/src/domain/time.rs
crates/driver/src/infra/observe/mod.rs

Despite increasing the auction-solving share the average solving time for external solvers didn't increase. This PR adds a debug log that should allow us further pin down where the issue lies.
Observe log statement locally.
#2211

[Trivial] log deadline

---

crates/alerter/src/lib.rs
crates/autopilot/src/solvable_orders.rs
crates/database/src/orders.rs
crates/shared/src/db_order_conversions.rs

When investigating some outliers in our "Time to happy moo SLI" (e.g. [this order](https://explorer.cow.fi/orders/0x726d843841bc013fe38fc5be3a874d39c1dadea594779aa0e13f8f5aab6f65d897681034cc9fa3e5d562c25ef40a09033cae5380658d45ce?tab=overview)) I noticed that we currently classify presign orders as valid even if they are not yet signed. This is because they are filtered out in the solvable orders SQL query and not inside the solvable orders updating logic
Expect to see accurate time to happy moo metric for order that take some time to be presigned

Classify orders with invalid signature as invalid

---

crates/driver/src/domain/competition/mod.rs
crates/driver/src/domain/competition/solution/mod.rs
crates/driver/src/domain/quote.rs
crates/driver/src/domain/time.rs
crates/driver/src/infra/notify/mod.rs
crates/driver/src/infra/observe/mod.rs
crates/driver/src/infra/solver/dto/auction.rs
crates/driver/src/infra/solver/mod.rs
crates/driver/src/tests/setup/solver.rs
crates/solvers/src/api/routes/notify/mod.rs
crates/solvers/src/domain/auction.rs
crates/solvers/src/domain/solver/baseline.rs

There seems to be an issue with the deadline we are passing down to solvers leading to timeouts while still having significant time left for postprocessing. Take Laertes in barn auction 8222857 for instance:
> 2023-12-29T09:37:47.818Z DEBUG request{id="2710"}:/solve{solver=laertes-solve auction_id=8222857}: driver::infra::observe: computed deadline deadline=Deadline { driver: 2023-12-29T09:38:02.090509218Z, solvers: 2023-12-29T**09:38:00**.663289792Z } timeouts=Timeouts { http_delay: Duration { secs: 0, nanos: 500000000 }, solving_share_of_deadline: Percent(0.9) }
> 2023-12-29T09:37:49.476Z TRACE request{id="2710"}:/solve: solvers::api::routes::solve: auction=Auction { id: Solve(8222857), ... deadline: Deadline(2023-12-29T**09:37:58**.702187297Z}
...
> 2023-12-29T09:37:58.738Z  WARN …

Simplify deadline passing

---

crates/driver/src/infra/solver/mod.rs

We are seeing panics in barn upon unwrapping the deadline when sending the requests to solver. We shouldn't panic if the time is up.
Observe no more panics in barn

[Trivial] Fix timeout panic

---

crates/driver/src/infra/solver/dto/notification.rs
crates/driver/src/infra/solver/mod.rs
crates/driver/src/util/http.rs
crates/solvers/Cargo.toml
crates/solvers/src/api/routes/notify/dto/notification.rs

Notification calls from the driver to solver engines are currently failing due to:
> Failed to deserialize the JSON body into the target type: invalid type: map, expected variant identifier at line 1 column 143
I broke this with #2192 where I missed adding the flatten directive on the driver dto.
Run e.g. the partial fill colocation test case. See warning before adjusting the dto and now no longer see it.

Fix notify dto

---

crates/refunder/src/arguments.rs
crates/shared/src/arguments.rs

Reduce code repetition by implementing `Display` on the logging argument rather than printing out each field of the struct each time.
- New `Display` implementation
- Removed custom printout on base `Display` implementation
Run something with just default arguments, for example:
<details><summary>cargo run --bin autopilot</summary>
```
2024-01-03T10:35:41.879Z  INFO autopilot::run: running autopilot with validated arguments:
ethrpc_max_batch_size: 100
ethrpc_max_concurrent_requests: 10
ethrpc_batch_delay: 0ns
block_stream_poll_interval: 5s
tenderly_user: None
tenderly_project: None
tenderly_api_key: None
log_filter: warn,autopilot=debug,driver=debug,orderbook=debug,solver=debug,shared=debug
log_stderr_threshold: error
node_url: http://localhost:8545/
[...]
```
</details>

Implement Display for logging arguments

---

crates/autopilot/src/infra/blockchain/mod.rs
crates/autopilot/src/run.rs

https://github.com/cowprotocol/services/pull/2206 created a new blockstream for use in the autopilot, which isn't using the shared arguments for its poll interval (instead it hard codes the poll interval at 10x the rate the current block stream operates). Moreover, it kept the existing block stream around leading to 2x the `eth_getBlockByNumber` requests (even if it used the same rate). This is causing extra load on our nodes, leading to intermittent timeouts.
CI

[Hotfix] less aggressive current block stream in autopilot

---

crates/driver/src/domain/competition/auction.rs
crates/driver/src/tests/cases/mod.rs
crates/driver/src/tests/cases/multiple_drivers.rs
crates/driver/src/tests/setup/driver.rs
crates/driver/src/tests/setup/mod.rs

For performance reason we use a future that is shared across requests for different solver engine instances when prioritising orders. However, this future returns the entire auction instead of just the list of orders. This means that other aspects of the auction, such as deadline are also shared across solver instances.
This leads to solver engines that are configured with a specific deadline to sometimes receive auctions with deadlines that are configured for a different solver engine.
Added an integration test, which is failing before that change
Fixes #2211

Fix deadline

---

crates/database/src/onchain_invalidations.rs
crates/database/src/orders.rs
crates/e2e/tests/e2e/ethflow.rs

We are trying to collect events throughout the lifecycle of all orders for analytics and alerting reasons. It seems that we have missed native ETH flow orders (which get indexed inside the autopilot) leading to inconsistent lifecycles for some orders (e.g. missing creation or cancellation events)
Adjusted the ethflow e2e test

Ethflow order events

---

crates/driver/src/boundary/liquidity/zeroex.rs
crates/shared/src/price_estimation/factory.rs
crates/shared/src/trade_finding.rs
crates/shared/src/trade_finding/external.rs
crates/shared/src/zeroex_api.rs
crates/solver/src/run.rs

We are currently using the default HTTP timeout (10s) for non-external price estimators (1Inch, 0x, Paraswap, Balancer) which may lead to bad quote latencies in case their APIs are facing issues (cf. recent alerts)
We don't have unit tests covering this and usually third party APIs are much faster than this, so this is hard to test. Basically we expect to see a slight increase in worst case quote latency once deployed.

Enforce timeout for DEX solver price estimators

---

crates/alerter/src/lib.rs

Fixes alerter so it works with two different order types:
- one from api/v1/order
- other from api/v1/auction
Consequence of https://github.com/cowprotocol/services/pull/2246

Support new order type in alerter

---

crates/autopilot/src/run.rs
crates/driver/src/boundary/mempool.rs
crates/driver/src/infra/blockchain/gas.rs
crates/driver/src/infra/blockchain/mod.rs
crates/driver/src/run.rs

We are seeing some issues with `eth_feeHistory` requests timing out. It turns out that both autopilot as well as driver are each creating two instances of the NativeGasEstimator which is making these calls. These instances can be shared within the pod to reduce this type of request.
CI

Consolidate NativeGasEstimators

---

.github/workflows/deploy.yaml

This change will allow us to build arbitrary branches in the repo to test branches on staging before merge.
1. Fork the repo
2. Go to actions > deploy > Run workflow
3. Example [here](https://github.com/ahhda/services/actions/runs/7476869122)

Add workflow dispatch to docker build

---

crates/autopilot/src/solvable_orders.rs

Follow up for https://github.com/cowprotocol/services/pull/2220
First filter out orders with invalid signatures so we don't have to call bad token detection on them.

First filter invalid signatures

---

crates/driver/src/domain/competition/mod.rs
crates/driver/src/infra/notify/mod.rs
crates/driver/src/infra/notify/notification.rs
crates/driver/src/infra/solver/dto/notification.rs
crates/shared/src/http_solver/model.rs
crates/solvers/openapi.yml
crates/solvers/src/api/routes/notify/dto/notification.rs
crates/solvers/src/boundary/legacy.rs
crates/solvers/src/domain/notification.rs

`Seasolver` reported that some solutions were rejected for no visible reason. It turned out that if post-processing is timed out, we currently don't notify solvers about that.
Notify solvers on post-processing timed out.
TBD

Notify solvers on post-processing timed out

---

crates/shared/src/oneinch_api.rs
crates/shared/src/paraswap_api.rs
crates/shared/src/zeroex_api.rs

It is a bit difficult to debug quote requests from our reverse proxy right now as the requests don't pass in the request id header used in our backend. This PR sets the `X-REQUEST-ID` header in the request so that it can be logged in nginx for easier debugging.

Add Request ID header to quote requests for easier debugging

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/domain/fee/mod.rs
crates/autopilot/src/infra/persistence/dto/order.rs
crates/driver/openapi.yml
crates/driver/src/domain/competition/order/fees.rs
crates/driver/src/domain/competition/solution/fee.rs
crates/driver/src/infra/api/routes/solve/dto/auction.rs
crates/driver/src/tests/setup/driver.rs
crates/e2e/tests/e2e/protocol_fee.rs
crates/orderbook/src/dto/order.rs

Renames FeePolicy variant from `priceImprovement` to `surplus`, since it better explains the current implementation of the protocol fee in the driver.
Context: 
https://github.com/cowprotocol/services/pull/2213#pullrequestreview-1814990012
https://cowservices.slack.com/archives/C05N1FNP3MX/p1704971316558629
I expect shadow solver to fail again until next release.

Rename `priceImprovement` to `Surplus`

---

crates/autopilot/src/boundary/order.rs
crates/autopilot/src/domain/auction/order.rs
crates/autopilot/src/infra/persistence/dto/order.rs
crates/autopilot/src/solvable_orders.rs
crates/driver/openapi.yml
crates/driver/src/domain/competition/order/mod.rs
crates/driver/src/domain/competition/solution/fee.rs
crates/driver/src/domain/quote.rs
crates/driver/src/infra/api/routes/solve/dto/auction.rs
crates/driver/src/tests/setup/driver.rs
crates/orderbook/src/dto/order.rs

Fixes https://github.com/cowprotocol/services/issues/2256
Simple renaming from `fee_policies` to `protocol_fees` to make sure the reader knows that the policies are used for protocol fee calculation.

Rename fee policies

---

.github/workflows/release.yml

The automated release action didn't trigger a deployment job, because
> When you use GITHUB_TOKEN in your actions, all of the interactions with the repository are on behalf of the Github-actions bot. The operations act by Github-actions bot cannot trigger a new workflow run.
Test Repository: https://github.com/fleupold/weekly-release-action/actions

Add personal access token to release action

---

crates/autopilot/src/boundary/mod.rs
crates/autopilot/src/infra/mod.rs
crates/autopilot/src/infra/solvers/mod.rs
crates/autopilot/src/lib.rs
crates/autopilot/src/run.rs
crates/autopilot/src/run_loop.rs
crates/autopilot/src/shadow.rs
crates/autopilot/src/util/mod.rs

Third part of the https://github.com/cowprotocol/services/pull/2188
Moves driver_api to a separate `solvers` module in `infra`.
Next up, moving the driver dtos into `infra`.

Move driver_api to `infra`

---

crates/autopilot/src/run_loop.rs

The newly added code for the liveness probe reports unhealthy if we skip too many empty auctions after another.
Also update last processes auction timestamp when we skip an auction because it's empty.

Fix liveness probe

---

crates/autopilot/src/on_settlement_event_updater.rs

This PR addresses the issue identified in Sepolia where `total_surplus` was not computed correctly due to missing `order_uids` in the `order_execution` table. This miscomputation was a consequence of [recent changes](https://github.com/cowprotocol/services/pull/2190) in the workings of the `order_execution` table. The identified problem impacted the `/api/v1/users/{address}/total_surplus` endpoint, leading to lower-than-expected surplus values. This fix aims to ensure accurate surplus computation by addressing the data retrieval process in the database.
After thorough consideration, it was decided to go with the option of reverting the change and saving `order_executions` for all trades. The alternative of building a complicated subquery was deemed overly complex and unnecessary, …

Store all orders in `order_execution` table

---

crates/autopilot/src/on_settlement_event_updater.rs

Follow up for https://github.com/cowprotocol/services/pull/2305
My oversight where I suggested to just remove the filter. What we actually want to do here is to still have all order executions to be saved to db table `order_executions` (to have properly calculation of `/api/v1/users/{address}/total_surplus`) but also, save the surplus_fee of 0 for market orders because they don't have the surplus fee.

Zero surplus fee for market orders

---

crates/e2e/tests/e2e/app_data.rs
crates/orderbook/src/quoter.rs
crates/orderbook/src/run.rs

Now that everyting is in place (see #2297, #2298) we can also load app data override in the order quoter
Adjusted the e2e test. Before we were seeing the warning show up twice (for quote and the expected unknown hash), now we no longer see the warning for the quote.

Share app data registry

---

crates/e2e/src/setup/services.rs
crates/orderbook/openapi.yml
crates/orderbook/src/api/post_order.rs
crates/orderbook/src/arguments.rs
crates/orderbook/src/run.rs
crates/shared/src/order_validation.rs

Whenever we implement a new feature we make usually enable it by setting a CLI flag.
However, at some point the flags are thoroughly tested and do not get disabled anymore.
IMO there is no longer a need to temporarily disable eip-1271 or presign signatures so I disabled their feature flags.
Delete dead code
Test should still pass

Always enable all signature types

---

crates/e2e/src/setup/services.rs
crates/orderbook/src/arguments.rs
crates/orderbook/src/run.rs
crates/shared/src/order_validation.rs

Limit orders are now a critical part of the service. Being able to disable the feature is no longer useful.
Delete dead code
CI, tests should still pass

Always enable limit orders

---

crates/autopilot/src/run_loop.rs

We had one oncall alert where a lot of unsettled solutions were reported.
I noticed that this metric contains duplicated orders, meaning, if one solver solves solution A and 10 other solvers solve solution B we will have 10 unsettled solutions. 
Now, only unique solutions will be reported.

Report only unique unsettled orders

---

.github/workflows/pull-request.yaml
crates/contracts/build.rs
crates/e2e/src/setup/colocation.rs
crates/e2e/src/setup/deploy.rs
crates/e2e/src/setup/services.rs
crates/e2e/tests/e2e/limit_orders.rs

Added a Gnosis Chain e2e forked test. We have e2e Gnosis Chain tests at Enso and this small upstream change will help remove a lot of our boilerplate and would help other solvers run Gnosis Chain e2e tests.
- `FORK_URL` has been replaced by `FORK_URL_MAINNET` and `FORK_URL_GNOSIS`, which should be updated in GitHub secrets.
- Added HoneySwap addresses under UniswapV2 contracts in `crates/contracts/build.rs` as they have the same ABI and can then use the same `Contracts` struct across Mainnet and Gnosis Chain tests.
- A `default_pool_code` function that returns the pool code for the `Contracts` struct depending on the new `chain_id` value.
- A limit order test that runs against Gnosis Chain.
The `test-forked-node` CI job will test this. Locally I ran `FORK_URL_MAINNET="<secret>" …

Add gnosis chain e2e forked test

---

crates/autopilot/src/boundary/mod.rs
crates/autopilot/src/domain/fee/mod.rs
crates/shared/src/order_validation.rs

Quote sell amount and quote buy amount were substituted.
🤷

Fix bug for fee market price check

---

crates/e2e/src/setup/services.rs

Allow custom timeout for the http client in `e2e`'s `services`. This means we can use the helper functions in `services` without needing to copy them into our own codebase and change the timeout.
-  `new_with_timeout` constructor added to `Services` impl. 
Tested in Enso's e2e tests.

Allow custom timeout for e2e services' http client

---

crates/shared/src/order_quoting.rs
crates/shared/src/price_estimation.rs
crates/shared/src/price_estimation/balancer_sor.rs
crates/shared/src/price_estimation/baseline.rs
crates/shared/src/price_estimation/external.rs
crates/shared/src/price_estimation/factory.rs
crates/shared/src/price_estimation/http.rs
crates/shared/src/price_estimation/native.rs
crates/shared/src/price_estimation/oneinch.rs
crates/shared/src/price_estimation/paraswap.rs
crates/shared/src/price_estimation/sanitized.rs
crates/shared/src/price_estimation/trade_finder.rs
crates/shared/src/price_estimation/trade_verifier.rs
crates/shared/src/price_estimation/zeroex.rs

Mostly moves code around and introduces trait for trade verification which will later be used for unit tests.
Also adds the `verified` flag to quotes but at this point this flag is not yet used for anything.
Originally part of https://github.com/cowprotocol/services/pull/2271 and changes were manually tested there.
CI
Fixes: https://github.com/cowprotocol/services/issues/2310

Move TradeVerifier into separate file and add trait

---

crates/autopilot/src/on_settlement_event_updater.rs
crates/e2e/tests/e2e/univ2.rs

We got stuck indexing https://etherscan.io/tx/0x45a80857fb7c7e56375617ac7a5427903a95a2ff41f302ce3527a91fcee695b4 because we cannot decode the auction id from the calldata (it's not encoded).
Added an e2e test which is failing on current main.

Insert default auciton id when we cannot decode it from the auction

---

crates/driver/src/domain/mempools.rs
crates/driver/src/infra/mempool/mod.rs
crates/driver/src/infra/notify/mod.rs
crates/driver/src/infra/observe/mod.rs

We are seeing some risky settlements being submitted via the public mempool in staging (e.g. https://etherscan.io/tx/0xb47602e564a46203b3df944677aae6f5436d22219c0b1c4b136501eaee15d163)
This is because the new submission logic doesn't ensure we don't submit revertable transactions via MEVBlocker only.
Unfortunately MEVBlocker submission isn't covered by end to end test and neither driver tests.

Don't submit risky settlements in public mempool for domain submissions

---

.github/workflows/pull-request.yaml
crates/e2e/src/nodes/mod.rs

- increase `anvil` start up timeout to `20s` because for some reason it can be super slow using a xdai fork url
- introduced a concurrency group for the forked node test since we experienced some rate limiting from the archive node RPC we use for mainnet
- use `--nocapture` for forked node tests to always get the entire logs to make it easier to debug when something unexpected happens
forked tests should hopefully pass in CI

More reliable forked_node tests

---

crates/autopilot/src/database/on_settlement_event_updater.rs
crates/database/src/events.rs
crates/database/src/order_execution.rs
crates/database/src/orders.rs
database/README.md
database/sql/V059__add_block_number_order_execution.sql

Adds `block_number` column to db table `order_execution`.
This is to make the table reorg friendly, meaning, whenever reorg happens, event updater will also delete all entries in this table that are from reorged block.
This enables us to remove the delay of 64 blocks in the `OnSettlementEventUpdater` component. Removal will be implemented in a separate PR so that it can be easily reverted if need be.

Add block_number to order_execution

---

crates/driver/src/infra/blockchain/gas.rs
crates/driver/src/tests/cases/settle.rs
crates/driver/src/tests/setup/driver.rs
crates/driver/src/tests/setup/mod.rs

Integration test for #2337
Checkout `v2.243.1`, see test failing there.

Test that settlements with revert risk aren't submitted via public mempool

---

crates/driver/src/boundary/mempool.rs
crates/driver/src/domain/competition/solution/settlement.rs
crates/driver/src/domain/eth/gas.rs
crates/driver/src/infra/blockchain/gas.rs
crates/driver/src/infra/mempool/mod.rs
crates/driver/src/tests/cases/multiple_drivers.rs
crates/driver/src/tests/cases/solver_balance.rs
crates/driver/src/tests/setup/blockchain.rs
crates/driver/src/tests/setup/mod.rs

We are seeing a bunch of simulation failures of seasolver on GnosisChain due to `InsufficientBalance`. Those only show up after their solution has been chosen as the winning one and is trying to settle, thus delaying settlements by one auction (or potentially more if their solver keeps winning). 
This stems from the fact that the current `required_balance` method, which we check during solution simulation, doesn't use the `maxFeePerGas` (which is 1000 gwei) but instead some multiple of the current base fee (<1 gwei on Gnosis Chain). However, the RPC node requires an account to have at least `gasLimit * maxFeePerGas` ETH of balance in order to accept its transaction.
This would lead to a balance requirement of ~15xDAI on Gnosis Chain (many orders of magnitude more than is actually needed …

Limit maxFeePerGas to reasonable value

---

database/sql/V060__app_data_overrides.sql

We want to start forbidding orders with unknown app data hashes. Before we can do this, we want to make sure we have defaults set for most valid orderflow (to not break integrations).
This PR adds a migration for the missing hashes that were observed in the past week.
Ran migrations locally

Migration to fill in missing but legit AppDataHashes

---

.github/workflows/stale.yml

In an effort to help us drive half finished PRs to completion fast, I'm proposing to enable the following github action which will nag us if a PR is open for more than 7 days and automatically close issues after another 7 days.

Add stale bot workflow

---

crates/e2e/tests/e2e/ethflow.rs
crates/model/src/quote.rs
crates/orderbook/openapi.yml
crates/orderbook/src/api/post_quote.rs
crates/orderbook/src/quoter.rs
crates/shared/src/order_quoting.rs

We received some questions via discord that were struggling getting quote requests to work with swagger because of the following error "UnuspportedOrderType".
The reason for this is that in our swagger definition `partiallyFillable` defaults to true, however in code it is required to be set to false (we hardcode the order type for quotes to `Market` [here](https://github.com/cowprotocol/services/blob/130ef0b1a7b75a62a2731860b26a02f7a51a4cdb/crates/shared/src/order_quoting.rs#L589) and market orders cannot be partially fillable due to fees).
Given that the field carries no entropy, this PR removes `partiallyFillable` from the `OrderQuoteRequest` and it's documentation to avoid this confusion going forward.
Existing unit test

Remove partial fill flag on quote request

---

crates/e2e/src/setup/onchain_components.rs
crates/e2e/tests/e2e/partial_fill.rs
crates/e2e/tests/e2e/partially_fillable_pool.rs
crates/e2e/tests/e2e/protocol_fee.rs
crates/e2e/tests/e2e/solver_competition.rs
crates/e2e/tests/e2e/univ2.rs

Since https://github.com/cowprotocol/services/pull/2340 is stable, we can remove the waiting for 64 blocks in tests.
Updated tests

[TRIVIAL] Remove unnecessary minting in tests

---

crates/autopilot/src/on_settlement_event_updater.rs

Related to staging alert: https://cowservices.slack.com/archives/C037PB929ME/p1707099846201309
Since `EventHandler` and `OnSettlementEventUpdater` are racing to update on each new block, in case the reorg happens and `OnSettlementEventUpdater` is faster, it will potentially catch an event containing tx hash that was reorged.
This PR lowers the severity of this issue (we don't want slack alerts for this). This is a temporary fix until we make event handling pipelined.

No alert if reorg happens

---

crates/autopilot/src/database/onchain_order_events.rs
crates/autopilot/src/run.rs
crates/e2e/tests/e2e/ethflow.rs
crates/model/src/order.rs

Fixes https://github.com/cowprotocol/services/issues/2356
Adjusted existing tests. Added check for `executed_surplus_fee` for signed zero fee ethflow order.

Eth flow zero fee fix order class

---

crates/autopilot/src/solvable_orders.rs

https://github.com/cowprotocol/services/pull/2354 collapsed these logs into one but did not check that there was even an order filtered out. This led to many logs stating that no order was filtered out for a given reason.

Omit empty filter log

---

crates/model/src/format.rs
crates/model/src/lib.rs
crates/model/src/solver_competition.rs

Some of the logs still contained calldata logged as an array of integers instead of a hex string. This is fixed by using `Derivative` to only overwrite the `Debug` implementation of these fields specifically.
For this I copied and slightly adjusted 1 helper function from the `shared` crate to not make the `model` crate depend on `shared` just for that.
Look into the logs of the local node tests.

Log call data as hex string

---

database/README.md
database/sql/V062__settlements_auction_id_index.sql

@fhenneke [reported](https://github.com/cowprotocol/solver-rewards/pull/337) that the batch rewards query takes forever once we removed the `auction_transaction` table.
https://github.com/cowprotocol/solver-rewards/pull/334
This should be fixed by adding the index on `auction_id` on `settlements` table.
Execute batch rewards on staging db to verify the speed.

Add index on auction id

---

crates/shared/src/price_estimation.rs
crates/shared/src/price_estimation/competition/mod.rs
crates/shared/src/price_estimation/competition/quote.rs
crates/shared/src/price_estimation/factory.rs

To roll out quote verification to prod we might want to toggle the verification process and acting on the verified flag with 2 separate knobs.
This PR adds the knob to prefer verified quotes in the price competition.
Add new CLI flag
Added unit test for sorting logic

Add flag to prefer verified quotes

---

crates/shared/src/price_estimation/factory.rs
crates/shared/src/price_estimation/http.rs

So far quote verification was heavily geared towards price estimation via drivers. But if we want to try out verification in prod to get a good idea on how well the feature works we should also add support for the legacy http price estimators.
Applies existing pattern of putting a `TradeFinder` into a `TraderEstimator`. This design seems overall pretty convoluted to me but this is just the last stretch before we can finally move towards quotes via drivers so it doesn't seem reasonable to introduce yet another adapter pattern to make the price estimation hierarchy work somehow.
The only estimators remaining that are incompatible with quote verification is the baseline and balancer solver. I think it's reasonable to not implement the same thing for those and instead use the data from all …

Make legacy http estimators compatible with quote verification

---

crates/autopilot/src/solvable_orders.rs

When we build the auction in the autopilot we filter out orders that are unlikely to be filled to shrink the auction to a more manageable size.
One step is to filter out fill-or-kill orders where the owner doesn't have enough sell_token for all of the open orders. The new logic sorts orders by `creation_timestamp` (desc) to first use the user's existing balance on recent orders rather than old ones. 
Fixes: #1997

Prioritize newer orders in auction

---

crates/shared/src/code_simulation.rs
crates/shared/src/price_estimation/factory.rs
crates/shared/src/price_estimation/trade_verifier.rs
crates/shared/src/tenderly_api.rs

It's possible that we see either failed simulations or simulations that return vastly different `out_amount` or `gas` costs. For these it would be useful to manually check with tenderly to make sure that this was not a logic error in our code.
Initially I just wanted to just log the calldata and block so you can manually recreate the simulation with tenderly but then I remembered that we also use 2 fake contracts in the simulation which would be super annoying (maybe impossible?) to set up using the tenderly UI.
We already had code that immediately simulated a tx using tenderly and only logged a link to the simulation but IIRC indiscriminately creating simulations with tenderly was pretty expensive and we don't really know upfront which simulations might be interesting to look at so we …

More logging for verified quotes

---

crates/shared/src/tenderly_api.rs

The new simulation request logs are working nicely already. This PR just makes it slightly more ergonomic by immediately opening the URL in your default browser so you don't have to copy and paste it.

Immediately open simulation url

---

.github/workflows/pull-request.yaml
crates/driver/src/domain/competition/auction.rs
crates/orderbook/src/ipfs_app_data.rs
crates/shared/src/price_estimation/trade_finder.rs
crates/solver/src/solver/single_order_solver.rs

New rust version => new enforced clippy warnings
- broke up overly complex match statements
- replace hand rolled `Arc::unwrap_or_clone()` with newly stabilized function
- added github run step before using `rust-cache` as recommended [here](https://github.com/Swatinem/rust-cache/blob/master/README.md?plain=1#L11-L13) to ensure we are using the latest stable version
CI

Update for 1.76

---

crates/driver/src/domain/competition/solution/fee.rs
crates/driver/src/domain/competition/solution/mod.rs
crates/driver/src/domain/competition/solution/trade.rs
crates/driver/src/infra/solver/dto/solution.rs

Only refactor, no new functionalities added.
I've extracted the calculation of surplus **in surplus token** into separate function. Since this new function is not strictly related to `solution::fee` and since it will be reused for rank by surplus feature, I moved it to the `solution::trade` file where it belongs.
The rest of surplus functionalities needed strictly for `solution::fee`, like `surplus_in_sell_token` is kept in that file.

Refactor surplus calculation

---

crates/autopilot/src/arguments.rs

We need to be able to set lists of contracts and for that we need to use value delimiters.

Use value delimiter to be able to set lists

---

crates/driver/src/infra/blockchain/mod.rs

Today we started seeing simulation errors caused by:
> 2024-02-15T10:16:19.713Z ERROR request{id="9"}:/solve{solver=mysolver auction_id=4076}: driver::infra::observe: discarded solution: settlement encoding id=Id(0) err=Simulation(Other(Blockchain(Web3(Rpc(Error { code: ServerError(-32000), message: "failed to apply transaction: 0xa5c722a26ff6b2b573f98e1d3f14285feb469411fa300139e9b7d25995ad756f err: intrinsic gas too low: have 21000, want 32220", data: None })))))
Usually when you create a tx to simulate or create access lists for you only set the `gas` value if you want to avoid the tx costing more than that. If you leave it empty "a sensible default" should be picked by the node. It looks like that logic stopped working for some reason (still unclear why because AFAIK we didn't update …

Set high default gas for access list estimation

---

.clippy.toml
Cargo.lock
crates/contracts/src/lib.rs
crates/e2e/src/setup/deploy.rs
crates/shared/src/bad_token/trace_call.rs
crates/shared/src/code_simulation.rs
crates/shared/src/gas_price_estimation.rs
crates/shared/src/price_estimation/http.rs
crates/shared/src/sources/swapr/reader.rs
crates/shared/src/sources/uniswap_v2.rs
crates/solver/src/settlement_access_list.rs
crates/solver/src/settlement_submission.rs
crates/solver/src/settlement_submission/dry_run.rs
crates/solver/src/settlement_submission/submitter/public_mempool_api.rs

Fixes: https://github.com/cowprotocol/services/issues/2414
* replaces all `.net().version()` calls with `.eth().chain_id().await?.to_string()`
* adds custom clippy lint forbidding the old `version()` function
* updates the dependencies to make use of `ethcontract` [0.25.5](https://github.com/cowprotocol/ethcontract-rs/releases/tag/v0.25.5) which applies the same change
Locally ran the services with `https://freerpc.merkle.io/` as the RPC which was previously not possible because that didn't expose the `net` module.
Checked that the clippy lint works:
```
Checking orderbook v0.1.0 (/Users/martin/work/backend/side/crates/orderbook)
Checking autopilot v0.1.0 (/Users/martin/work/backend/side/crates/autopilot)
warning: use of a disallowed method `web3::api::Net::version`
--> …
```

Remove usage of `net` RPC module

---

crates/driver/src/boundary/liquidity/balancer/v2/mod.rs
crates/driver/src/boundary/liquidity/swapr.rs
crates/driver/src/boundary/liquidity/uniswap/v2.rs
crates/driver/src/boundary/liquidity/uniswap/v3.rs
crates/driver/src/boundary/liquidity/zeroex.rs
crates/driver/src/domain/competition/auction.rs
crates/driver/src/domain/competition/mod.rs
crates/driver/src/domain/competition/solution/settlement.rs
crates/driver/src/infra/api/mod.rs
crates/driver/src/infra/blockchain/mod.rs
crates/driver/src/infra/liquidity/fetcher.rs
crates/driver/src/infra/simulator/mod.rs
crates/driver/src/infra/tokens.rs
crates/ethrpc/src/http.rs
crates/ethrpc/src/instrumented.rs
crates/ethrpc/src/lib.rs

Currently we don't have a good understanding of which subsystem or tasks issue lots of RPC requests. To address this I slightly changed how metrics get collected in the `ethrpc` transport implementation.
- move metrics from `http` transport into `instrumented` and make it composable
- move constant internals of `Ethereum` struct into `Arc`ed `Inner` to allow cheap copies
- instrumented `driver` calls as a PoC for the approach (if you'd like I can pull that out into a separate PR)
Overall the `Transport` and `BatchTransport` traits don't compose very well so the implementation ended up a bit weird. But overall I think it's mostly reasonable.
Instead of collecting all metrics under the same label we can now construct hierarchical metrics for RPC requests. These hierarchical metrics look …

Fine grained metrics for RPC calls

---

Dockerfile

#2426 introduce a bug as these files are no longer available in `cargo-build`, nor are they needed.
1. CI/CD

fix: dockerfile for deploy

---

crates/shared/src/account_balances/simulation.rs
crates/shared/src/bad_token/token_owner_finder.rs
crates/shared/src/price_estimation/factory.rs
crates/shared/src/signature_validator/simulation.rs
crates/shared/src/sources/balancer_v2/pool_fetching.rs
crates/shared/src/sources/uniswap_v2.rs
crates/shared/src/sources/uniswap_v3/pool_fetching.rs

Follow up to #2420 also adding RPC metrics for autopilot and api.
Ran services locally to see the additional metrics

Add RPC metrics for api and autopilot

---

Dockerfile
crates/driver/src/domain/mempools.rs
crates/driver/src/infra/mempool/mod.rs

Might make #2431 obsolete.
While debugging why we sometimes end up with un-cancelled settlement transactions, I noticed that some runloops don't show any logs from the driver's `settle` call indicating some kind of stuckness ([logs](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/GJFG4)).
It turns out that the default behavior of `ethcontracts` when sending transactions is to wait for inclusion (cf. [code](https://docs.rs/ethcontract/latest/src/ethcontract/transaction.rs.html#66)).
The logic however was written under the assumption that we return as soon as the tx has been submitted to the mempool (and is still pending). Otherwise, we wouldn't be able to e.g. cancel the tx as soon as we see it failing simulations.
Existing test suite (re-enabling native submission logic …

[Solution Submission] Return as soon as tx has been submitted to mempool

---

crates/solvers/src/api/routes/solve/mod.rs

Removes logging the whole auction in solvers crate since it's overwhelming the logs.
Related to https://github.com/cowprotocol/infrastructure/pull/1147#pullrequestreview-1898466895

[TRIVIAL] Remove solvers auction log

---

crates/shared/src/price_estimation/instrumented.rs

Currently it's a bit finicky to figure out which logs where emitted from which estimator in the orderbook/autopilot.
This PR adds the estimator name to all logs emitted by an instrumented estimator.

Add estimator name to trace

---

crates/shared/src/trade_finding.rs

Currently the interactions inside the verification struct don't get logged as hex string (e.g. [here](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/doc/c0e240e0-d9b3-11ed-b0e6-e361adffce0b/cowlogs-prod-2024.02.29?id=TpHs9I0B0oMg6dJLZ2f5)).
Start logging them as hex string.

Log calldata as hex string

---

crates/shared/src/price_estimation/trade_verifier.rs

Currently we use `Debug` logging for these `BigRational` which ends up like: `Ratio { numer: 0, denom: 1 }`
Switches over to use `Display` formatting which ends up with a regular integer.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b3144bb588fa03c517bfc1eeaea378a4

Use display logging for BigRational

---

crates/driver/src/domain/competition/solution/settlement.rs
crates/driver/src/infra/blockchain/mod.rs
crates/driver/src/tests/cases/settle.rs
crates/driver/src/tests/setup/mod.rs

Gnosis Chain recently [voted](https://forum.gnosis.io/t/proposal-to-mitigate-nft-spam-on-gnosis-chain-reduced-block-gas-limit/7450) the gas limit down from 30M to 17M. However, it seems as if some validators are still running with higher target gas limits, thus occasionally upvoting the gas limit again (cf. [this block](https://gnosisscan.io/block/32712562) for instance with limit 17016600).
This can lead to issues with our solution submission logic in case of very large settlements (>1/2 block gas limit). Normally we specify the limit of the settlement transaction at 2x the extimated gas amount (capped at the block gas limit). If the most recent block had 17.01M gas capacity, we chose a cap of 17.01M which may get rejected if the next block's validator has their node configured with a …

[Easy] Avoid GasLimitExceeded errors on Gnosis Chain

---

crates/solver/src/settlement/settlement_encoder.rs

See #2457 for the discussion.
The settlement contract computes the buy amount for sell orders by rounding up the division of the uniform buy price (cf. https://github.com/cowprotocol/contracts/blob/main/src/contracts/GPv2Settlement.sol#L389-L391).
The fact that the settlement encoder doesn't do this can lead to solutions getting rejected by the driver, which would be perfectly fine from the settlement contract's point of view.
Existing unit tests (may need some updates, waiting for CI to tell me)
Fixes #2457

Ceil buy amount computation in settlement encoder

---

crates/database/src/orders.rs
crates/e2e/tests/e2e/limit_orders.rs
crates/orderbook/src/database/orders.rs
crates/shared/src/order_validation.rs

Only check for order limits when the orders are class "Limit". I kept the legacy code/behavior, in order not to make a regression breaking change.
- Only do the order limit check if the order is class "Limit" and it is not "in-market"
1. Unit test
2. e2e test
Fixes #2433

Do not count "in-market" orders for the order limit #2433

---

crates/database/src/orders.rs

Do an `inner join` instead of `left join` in order not to have nullable quotes in case they do not exist.
This query will be removed with https://github.com/cowprotocol/services/issues/2469 
Do an `inner join` instead of `left join` in order not to have nullable quotes in case they do not exist. This way it does not error in case of missing quote (it won't be counted, as it is a liquidity order anyway).
1. CI
2. e2e

Hotfix: Make OrderWithQuote as inner join in order not to get nullable quotes

---

crates/shared/src/price_estimation/trade_verifier.rs

When the an order has `receiver: 0x000..000` the smart contract will send the proceeds to the owner of the order (see [here](https://github.com/cowprotocol/contracts/blob/main/src/contracts/libraries/GPv2Order.sol#L102-L107)).
This was currently not respected in the simulation logic when tracking the funds of the `receiver`.
Track balances of `owner` when `receiver == 0x0000`.
I specifically did not want to overwrite the owner in the `Verification` struct because that would diverge the execution of the simulation from what would actually happen more.
Example simulation from xdai: https://dashboard.tenderly.co/gp-v2/production/simulator/fe44ac0d-21a6-46ba-b0a8-b7edebe059ad
Noticed via alert: https://cowservices.slack.com/archives/C0371SB243E/p1709656851339479

[trivial] Fix quote verification when receiver is 0 address

---

crates/autopilot/src/boundary/order.rs
crates/autopilot/src/domain/auction/mod.rs
crates/autopilot/src/domain/auction/order.rs
crates/autopilot/src/domain/mod.rs
crates/autopilot/src/infra/persistence/dto/fee_policy.rs
crates/autopilot/src/infra/persistence/dto/order.rs
crates/autopilot/src/infra/persistence/mod.rs
crates/autopilot/src/infra/solvers/dto/solve.rs
crates/autopilot/src/run_loop.rs
crates/autopilot/src/shadow.rs

Part 1 of https://github.com/cowprotocol/services/pull/2436

[EASY] Rename auction id

---

Cargo.lock
Cargo.toml
crates/autopilot/Cargo.toml
crates/autopilot/src/solvable_orders.rs
crates/shared/Cargo.toml
crates/shared/src/price_estimation/native_price_cache.rs

Currently restarting the services can be a risky and unpredictable thing. The reason is that for an order to be part of the auction we need to have the buy and sell token's native prices. When we restart the system the native price cache is empty and we need to populate it again to make existing orders appear in newly built auctions.
We already had some code that prioritizes fetching prices of tokens traded by `Market` orders. However, since we made all orders `Limit` orders this optimization became useless.
Until we reclassify limit orders as market orders (if they were in market at the time of creation) we need some other way to prioritize native prices again.
Assume orders created in the last 30 minutes (hardcoded; but I think that's okay) are market orders. For those orders the more …

Improve native price fetch order

---

crates/shared/src/price_estimation/trade_finder.rs

I initially classified errors coming from verification incorrectly. `ProtocolErrors` will actually get logged as errors which leads to these [alerts](https://cowservices.slack.com/archives/C0371SB243E/p1709821653091049).
However, if we have to discard a quote because it's actually not good the estimator is actually at fault.
Those errors will not lead to alerts. Also the user will receive a `400` response (no liquidity) instead of `500` (internal server error).
Turned `TooInaccurate` error into an `EstimatorError` instead of `ProtocolError`.

Turn verification error into estimator error

---

crates/driver/src/infra/observe/mod.rs

A separate log for when the mempool is disabled is nice to have - to avoid printing WARN log and the whole settlement data, and since it's not an actual error.

[EASY] Separate log for disabled mempool

---

crates/driver/src/domain/competition/solution/settlement.rs

Especially on Gnosis Chain we sometimes have very large settlements (e.g. https://gnosisscan.io/tx/0xa7a3230bcd139b050c192cb4dceada5af94caf6bb2c9f29a4736240e4df4ab74). Our current strategy is to set the gas limit to 2x the estimated gas to allow in fluctuations between estimated and actually required gas (this approach stems from a time when we used `eth_estimateGas` which wasn't very accurate).
The default block building algorithm works roughly like this:
- While remaining space in the block
- Pick the highest paying transaction from the public mempool whose gas limit doesn't exceed remaining block space
- Try to include it and update remaining space with actually used gas
Importantly, block producers don't simulate or try to estimate the actual gas usage before deciding whether to …

[Easy] Set max gas_limit for a settlement at 1/2 block gas limit

---

crates/driver/src/domain/competition/mod.rs
crates/driver/src/domain/competition/solution/fee.rs
crates/driver/src/domain/competition/solution/scoring.rs
crates/driver/src/tests/cases/protocol_fees.rs

Rank by surplus implementation for the Price Improvement fee policy.
To properly calculate both `native_surplus ` and `native_protocol_fee`, the `surplus` function was refactored into `surplus_over_limit_price` where limit sel/buy amounts should be provided explicitly. 
`fee::adjust_quote_to_order_limits` function is used to adjust the limit amounts in case of the Price Improvement fee policy.
Either my understanding is incorrect or `fee_from_volume` function doesn't work correctly for the `max_volume_factor=1.0`. For the sell order kind, it returns `inf` and for the buy, the factor is adjusted into `0.5`, which is not really expected.
I tested it by adding some logs and running protocol fee driver tests.
Fixes #2466

Rank by surplus price improvement

---

crates/driver/src/domain/competition/solution/scoring.rs

Instead of printing order sell and buy tokens and amounts (which can be derived from other logs), now we print executed amount and custom prices which give sufficient data to reconstruct the whole surplus calculation and see what went wrong.
This is related to a few surplus calculation errors that happened in prod, which are most likely caused by solving market order at the very own limit order price, causing our price conversions to return smaller amounts due to potential rounding error, and consequently, cheched_sub returning None on those very small differences.
This change would give us more light on what actually happens.
Not launch blocking.

[EASY] Fix surplus scoring error

---

crates/autopilot/src/infra/solvers/dto/solve.rs
crates/driver/openapi.yml
crates/driver/src/domain/competition/mod.rs
crates/driver/src/domain/competition/solution/mod.rs
crates/driver/src/domain/quote.rs
crates/driver/src/infra/api/routes/quote/dto/quote.rs
crates/driver/src/infra/api/routes/solve/dto/solved.rs
crates/driver/src/infra/solver/dto/solution.rs
crates/driver/src/tests/setup/mod.rs
crates/e2e/tests/e2e/onchain_settlement.rs
crates/shared/src/price_estimation/http.rs
crates/shared/src/price_estimation/trade_verifier.rs
crates/shared/src/trade_finding.rs
crates/shared/src/trade_finding/external.rs
crates/shared/src/trade_finding/oneinch.rs
crates/shared/src/trade_finding/zeroex.rs
crates/solvers-dto/src/solution.rs
crates/solvers/openapi.yml
crates/solvers/src/api/routes/solve/dto/solution.rs
crates/solvers/src/boundary/legacy.rs
crates/solvers/src/boundary/naive.rs
crates/solvers/src/domain/eth/mod.rs
crates/solvers/src/domain/solution.rs
crates/solvers/src/tests/baseline/bal_liquidity.rs
crates/solvers/src/tests/baseline/buy_order_rounding.rs
crates/solvers/src/tests/baseline/direct_swap.rs
crates/solvers/src/tests/baseline/internalization.rs
crates/solvers/src/tests/baseline/partial_fill.rs

Fixes: https://github.com/cowprotocol/services/issues/2516
Introduce `gas` field to let solvers tell us how much gas they estimate the execution of the quote or settlement to cost. Now if a solver does not provide a gas estimate but we can also not estimate the gas on our own by simulating we discard the quote entirely.
Note that I didn't add any gas estimation logic for the `naive` solver since we currently only need the `gas` estimate for quotes which `naive` is not able to generate.
For good support we also need to patch the `solvers` repository to add gas estimates provided by dex APIs in their solution.
Adjusted e2e tests to make them pass again.

Optional gas estimate on solution

---

crates/solvers/src/domain/solution.rs
crates/solvers/src/tests/naive/extract_deepest_pool.rs
crates/solvers/src/tests/naive/filters_out_of_price_orders.rs
crates/solvers/src/tests/naive/matches_orders.rs
crates/solvers/src/tests/naive/reserves_too_small.rs
crates/solvers/src/tests/naive/rounds_prices_in_favour_of_traders.rs
crates/solvers/src/tests/naive/without_pool.rs

When computing a score for a solution using a gas estimate we should also update the gas estimate of the whole settlement not just the score.
Adjusted naive solver e2e tests

Update gas when setting score with gas

---

crates/shared/src/event_handling.rs

Related to oncall issue where our system failed to index some settlements/trades. The only reason I could think of at the moment is that it was some intermittent issue with the node which answered with empty Vec of events. All other error execution paths are already covered in the code.

Add log for fetched events

---

Cargo.lock
crates/autopilot/Cargo.toml
crates/autopilot/src/domain/fee/mod.rs
crates/autopilot/src/domain/fee/policy.rs
crates/e2e/tests/e2e/limit_orders.rs
crates/e2e/tests/e2e/protocol_fee.rs

Apply partner fee specified in the `appData`.
- Overwrite any fee policy with the partner fee if specified in the `appData`
- The fee factor is calculated as `bps / 10000`
1. e2e test
Fixes #2502

Apply partner fee from appData

---

crates/driver/src/tests/cases/protocol_fees.rs
crates/driver/src/tests/setup/driver.rs
crates/driver/src/tests/setup/mod.rs

Scoring doesn't support `factor=1.0`, so some of the test values were changed.
Fixes #2522

Rank by surplus tests

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/domain/fee/mod.rs
crates/autopilot/src/domain/mod.rs
crates/autopilot/src/run.rs
crates/autopilot/src/solvable_orders.rs
crates/e2e/tests/e2e/protocol_fee.rs

We should make configurable in the autopilot the maximum partner fee amount.
- Introduce a new configuration parameter in the autopilot for the partner fee max cap with a default value 0.01
- Enforce the configured partner fee max cap
1. e2e test
2. unit test
Fixes #2554

Make the partner fee max cap configurable in autopilot

---

crates/autopilot/src/solvable_orders.rs

Currently it's a bit hard to see from the logs whether orders filtered for a specific reason increase, decrease or stay constant.
Not only log which orders got filtered for a reason but also how many in total.

[EASY] Print filtered order count

---

.github/workflows/pull-request.yaml

When running CI on PR github does something unexpected. It does actually **NOT** run on the last commit of the PR (i.e. HEAD) but rather checks out the target branch (usually `main`) and merges the HEAD into it.
Most of the time this either works without issues or results in a merge conflict causing the CI to not start at all.
However, when the HEAD commit can be merged into the target branch without merge conflicts **BUT WITH BREAKING CHANGES NEVERTHELESS** you get build or test execution issues that can not be reproduced by just using your branch locally.
For more info check out the investigation on [slack](https://cowservices.slack.com/archives/C0375NV72SC/p1712179673286249?thread_ts=1712177157.374909&cid=C0375NV72SC).
Configures checkout action to pull HEAD instead of the merge …

Run CI on HEAD commit instead of merge commit

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/domain/fee/mod.rs
crates/autopilot/src/run.rs
crates/autopilot/src/solvable_orders.rs
crates/e2e/tests/e2e/protocol_fee.rs

Allow configuring contracts which are exempt from protocol fees.
Our CoW AMM experiment is placing a lot of limit orders, some of which are being classified as out of market orders (mainly because they are partially fillable and usually a bit larger than what is currently fillable at the specified price).
It therefore pays significant protocol fees, impacting it's own PnL
- Configure the driver to accept whitelisted address for protocol fee discount
- Skip protocol fee for whitelisted addresses
1. e2e tests
2. unit tests
Fixes #2461

Allow whitelisting addresses for protocol fees discounts

---

crates/shared/src/price_estimation/factory.rs
crates/shared/src/price_estimation/native.rs
crates/shared/src/price_estimation/native/oneinch.rs

OneInchSpotPrice estimator assumes that all tokens have 18 decimals. In order for `NativePriceEstimateResult` to be populated as expected, we need to divide the response by number of the decimals for each specific token.
USDC example: https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/EFIxv
Here we can see that result was divided by 1e18 instead of 1e6, since USDC has 6 decimals.
Existing tests

Fix decimals for OneInchSpotPrice estimator

---

crates/shared/src/price_estimation/native/oneinch.rs

Follow up to https://github.com/cowprotocol/services/pull/2603.
10**24 doesn't fit into a `u64` so we were still dividing by the wrong base.
compute base using big int which does not result in an over flow see [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6321e0b405f0e6ff0f469b5a8ecedbc1).
tested using rust playground ☝️

Use BigInt to compute unit

---

crates/driver/src/domain/competition/mod.rs

It turns out we were not actually sorting solutions in descending but in ascending score when merging them. This is not an issue per se as - given enough time - all solutions get simulated and the one with the highest score gets picked (for this there are tests).
However, if there are a lot of solution candidates (more than we have time to encode), the ordering matters for prioritisation.
Since this aspect only happens when we run out of time it's quite hard to test. Not sure if it's necessary. If you have an idea please let me know.

Actually sort descending 🙈

---

crates/autopilot/src/database/on_settlement_event_updater.rs
crates/autopilot/src/database/order_events.rs
crates/autopilot/src/infra/persistence/mod.rs
crates/autopilot/src/run_loop.rs

Currently we are indexing the Traded events after the driver reports that it settled the solution. However, it can happen that the solver thinks it failed to submit a solution but actually succeeded.
Index order event labels when we are indexing the on-chain events.
1. regression tests
Fixes #2530

Index Traded order event labels based on on-chain data

---

crates/ethrpc/src/http.rs

Add a request id header for the RPC requests.
This PR adds the following request HTTP headers on RPC requests:
- `X-RPC-Request-Id` - The unique ID of the RPC request.
- `X-Request-Id` - The top level request id passed as a request header for the RPC request generated.
I couldn't find a suitable way to test this. Maybe, it would be useful to create tests for the RPC request execution and assert that those headers are been sending.
Fixes #2519

Add request id header for rpc requests

---

crates/driver/src/domain/competition/mod.rs
crates/driver/src/domain/competition/solution/settlement.rs
crates/driver/src/domain/mempools.rs

In order to move the settlement encoding logic from the boundar module/legacy solver crate into the domain it helps to first isolate the call to encode into a single place. This will then allow us to wrap this invocation behind a conditional config variable to control the rollout (once implemented)
CI
First step of #2215

Isolate Settlement Encoding logic

---

crates/driver/src/boundary/liquidity/uniswap/v3.rs

While working on https://github.com/cowprotocol/services/pull/2629 and benchmarking different solutions I noticed that we actually don't spawn the maintenance task that updates the univ3 pool states in the driver.
Spawn task to update pool states

Update uniswapv3 pool states

---

crates/driver/src/boundary/liquidity/uniswap/v3.rs
crates/shared/src/http_solver/model.rs
crates/shared/src/price_estimation/http.rs
crates/shared/src/sources/uniswap_v3/pool_fetching.rs
crates/solver/src/liquidity.rs
crates/solver/src/liquidity/uniswap_v3.rs
crates/solvers/src/boundary/legacy.rs

Uniswap V3 liquidity contains a lot of state and currently we deep clone the entire state of a pool that is needed as liquidity for a quote or an auction.
Store univ3 pool state in an Arc. That way cloning becomes dirt cheap. The only slight annoyance is that updating the cached state becomes a bit weird.
Arcs can be tricky to update because theoretically any number of threads might have access to the same memory. Luckily `Arc::make_mut()` is a thing. That allows us to get mutable access to the Arc if we are the only one using it at the time or it will clone the content and give us mutable access to that. That way updating the pool state at least stays very cheap whenever it can.
Correctness is covered by existing unit tests
Performance was measured with a local benchmark.
As you can see …

Make UniswapV3 state clones cheap

---

crates/driver/src/boundary/liquidity/uniswap/v3.rs
crates/shared/src/http_solver/model.rs
crates/shared/src/price_estimation/http.rs
crates/shared/src/sources/uniswap_v3/pool_fetching.rs
crates/solver/src/liquidity.rs
crates/solver/src/liquidity/uniswap_v3.rs
crates/solvers/src/boundary/legacy.rs

Reverts cowprotocol/services#2629
There are 2 code paths which append events to a given checkpoint state:
1. during maintenance (where we actually update the one big cached state that we maintain)
2. when fetching liquidity and the current state is later than the checkpoint state
Previously this was no issue because `2` cloned the relevant state so the underlying cached state was unaffected.
With the PR that now gets reverted both code paths modify the same underlying state which means some updates can be applied multiple times which corrupts the underlying state.

Revert "Make UniswapV3 state clones cheap"

---

crates/observe/src/tracing.rs

Currently panic logs emitted from the driver bleed into the preceeding log because we don't emit the current date which is used by fluentd to split multi line strings.
Now we also set the tracing related panic handler when we call the reentrant tracing initialization function.
Tested locally by triggering a test panic and checking the logs. (note the timestamp at the start of the log)
```
2024-04-22T14:56:29.840Z ERROR observe::tracing: thread 'main' panicked at /Users/martin/work/backend/main/crates/driver/src/run.rs:46:5:
test panic
stack backtrace:
0: std::backtrace_rs::backtrace::libunwind::trace
at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
1: std::backtrace_rs::backtrace::trace_unsynchronized
at …
```

Also init tracing panic handler in reentrant function

---

crates/shared/src/sources/uniswap_v3/pool_fetching.rs

The task to fetch the missing uni v3 pools currently also does stuff when all pools have been fetched.
These calls take 80ms-150ms and and issue at least 3 logs the don't add anything.
Early return when no pools need to be fetched.

[EASY] Avoid empty update

---

Cargo.lock
Cargo.toml
crates/app-data-hash/Cargo.toml
crates/database/Cargo.toml
crates/database/src/orders.rs
crates/driver/Cargo.toml
crates/e2e/Cargo.toml
crates/e2e/src/api/zeroex.rs
crates/e2e/tests/e2e/liquidity.rs
crates/ethrpc/Cargo.toml
crates/model/src/order.rs
crates/observe/Cargo.toml
crates/orderbook/Cargo.toml
crates/s3/Cargo.toml
crates/s3/src/lib.rs
crates/shared/Cargo.toml
crates/shared/src/zeroex_api.rs
crates/solver/Cargo.toml
crates/solver/src/liquidity.rs
crates/solvers/Cargo.toml

Bump crates to the latest versions
- Bump crates to the latest versions
- Unify in the `workspace` all the crates which are used in at least twice

Bump crates to the latest versions

---

Cargo.toml

After a long session of debugging together, @MartinquaXD discovered that the latest anyhow is always printing the full trace.
Revert back to anyhow 1.0.76
1. regression tests

Downgrade anyhow

---

Cargo.lock
Cargo.toml

Enforce always anyhow version to 1.0.76 so it does not include the full trace for every error

Enforce anyhow version

---

crates/contracts/build.rs
crates/contracts/src/lib.rs

Adds arbitrum address for all contracts that are available there to `build.rs`.
Updates tests that assert which contract is available on which networks.
This change was already deployed on an arbitrum staging stack and I was able to settle a solution with it (plus some incoming changes).

Add arbitrum contract addresses

---

crates/shared/src/network.rs
crates/shared/src/price_estimation/native.rs
crates/shared/src/sources.rs
crates/solvers/src/domain/eth/chain.rs

Adds arbitrum as a supported chain in the backend and sets reasonable defaults for it to make it the backend start up with a minimal configuration.
Already deployed on arbitrum staging stack and used to settle an order.

Add default values for arbitrum

---

crates/driver/src/domain/competition/solution/settlement.rs

This is to ensure we can soft rollout in production (keeping the original encoding but warning cases in which the two don't match)
Run the driver in shadow mode, see solutions being produced and no error log happening
Prepares rollout of #2215

Log domain settlement even when using boundary encoding

---

crates/autopilot/src/run.rs
crates/orderbook/src/run.rs
crates/shared/src/bad_token/token_owner_finder.rs
crates/shared/src/bad_token/trace_call.rs

The bad token test finds an address that holds a good amount of tokens and tries to send some amount of that to the settlement contract and back again. Afterwards it checks that when we send X tokens the receiver actually got X tokens and not some smaller amount to filter out tokens with fee on transfer behavior.
Because the token balance assertion is `if owner sends X tokens to the settlement contract the settlement_contract has X tokens more` it obviously fails when `owner == settlement_contract` because the balance for good tokens will also not change flagging them incorrectly as fee on transfer tokens.
Filter out the settlement contract in the `TokenFinder` implementation.

Don't use settlement contract as token owner for bad token test

---

crates/driver/src/domain/competition/mod.rs
crates/shared/src/recent_block_cache.rs
crates/shared/src/sources/balancer_v2/pool_fetching/pool_storage.rs

Lint fails on most recent master with newest rust version
Fix clippy warnings
CI

[Easy] Fix clippy for rust v1.78

---

crates/driver/src/boundary/settlement.rs
crates/driver/src/domain/competition/solution/encoding.rs
crates/driver/src/domain/competition/solution/mod.rs
crates/driver/src/domain/competition/solution/settlement.rs

This is not technically required for correct encoding, however, we are currently seeing a lot of "boundary settlement does not match domain settlement domain" warnings, not because the encoding is different, but because clearing prices are sorted in the legacy encoding:
https://github.com/cowprotocol/services/blob/1f019389f5fa8e873d785bba13b0a51c1833b6ad/crates/solver/src/settlement/settlement_encoder.rs#L113
Run in shadow mode and see warning log not show up even if trade doesn't happen to sell the lexicographically smaller token.

[Trivial] Sort clearing price vector

---

crates/driver/src/infra/blockchain/mod.rs

Otherwise, we get "gasPrice must be non-zero after london fork" when simulating against geth nodes ([code](https://github.com/ethereum/go-ethereum/blob/86a1f0c39494c8f5caddf6bd9fbddd4bdfa944fd/internal/ethapi/transaction_args.go#L220))
CI still passes

Simulate/AccessList generation with None instead of Some(0) gas price

---

crates/autopilot/src/run.rs
crates/e2e/tests/e2e/main.rs
crates/e2e/tests/e2e/quote_verification.rs
crates/orderbook/src/run.rs
crates/shared/src/price_estimation/factory.rs
crates/shared/src/price_estimation/trade_verifier.rs
crates/shared/src/trade_finding.rs

Follow up to https://github.com/cowprotocol/services/pull/2690. With this PR we would be ready to do correct zeroex RFQ simulations for any tx.origin other than `0x000` and other key addresses (e.g. trader, settlement contract, authenticator, ...).
Decode trade interaction calldata for zeroex RFQ related function calls to figure out which `tx.origin` is expected for the trade. Then override the solver address, authenticator and solver balance accordingly.
Note that the change to the override code needs to be done regardless if we want to support solvers signing RFQ orders for addresses nobody has the PK for (they have security concerns). But in a follow up PR we can make the tx origin override configurable per solver so we can get rid of all the zeroex calldata decoding stuff.
Verified …

Generic zeroex RFQ simulation

---

crates/autopilot/src/run.rs
crates/driver/src/domain/quote.rs
crates/driver/src/infra/api/routes/quote/dto/quote.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/solver/mod.rs
crates/e2e/tests/e2e/quote_verification.rs
crates/orderbook/src/run.rs
crates/shared/src/price_estimation/factory.rs
crates/shared/src/price_estimation/http.rs
crates/shared/src/price_estimation/trade_verifier.rs
crates/shared/src/trade_finding.rs
crates/shared/src/trade_finding/external.rs

Fixes https://github.com/cowprotocol/services/issues/2692
Removes all the zeroex specific RFQ interaction detection again. Technically it was more correct before but this is a lot of code to generically detect a case which we know only happens for a single solver which should resolve the issue end of month so let's not overthink it.
Now we can configure in the `driver` per solver which `tx_origin` should be used to verify the quotes. That way external solvers can tell us for which random address they sign their quotes for and we just configure it in the infra config.
Adjusted existing test

Quote overrides tx origin

---

.devcontainer/Dockerfile
crates/shared/src/tenderly_api.rs

The `curl` version installed in the the dev containers does not support the `--json` flag. That's why we use `--data` and set the appropriate header instead.
Also installed `xdg-utils` in the container to get `xdg-open`.
Executed a command taken from prod modified according to the PR and successfully ran it in the dev container.

Make simulation curl command compatible with dev container

---

crates/driver/src/infra/blockchain/mod.rs
crates/driver/src/infra/simulator/mod.rs
crates/driver/src/infra/simulator/tenderly/dto.rs
crates/driver/src/infra/simulator/tenderly/mod.rs
crates/driver/src/run.rs
crates/ethrpc/src/current_block/mod.rs
crates/shared/src/price_estimation/trade_verifier.rs

Fixes https://github.com/cowprotocol/services/issues/2696
Usually if you don't set a gas price for an `eth_call` "a sane default" should be picked by the node. This either does not work with the nodes we use or simulating with state overrides is an exception to the rule.
Read gas price in `CurrentBlockStream` and use the gas price of the most recent block for quote simulations.
e2e tests should still work as the gas price should not affect the gas used computed during the verification simulation.

Set gas price for quote simulations

---

Cargo.lock
crates/autopilot/src/infra/blockchain/mod.rs
crates/driver/src/boundary/liquidity/mod.rs
crates/driver/src/infra/blockchain/mod.rs
crates/e2e/tests/e2e/quote_verification.rs
crates/ethrpc/Cargo.toml
crates/ethrpc/src/current_block/mod.rs
crates/orderbook/src/run.rs
crates/shared/src/current_block.rs
crates/shared/src/price_estimation/http.rs

On networks with a very high block frequency we can get into troubles when using the auto batching http transport for the RPC requests.
With this PR we construct an fresh unbuffered `Web3` instance specifically for the `CurrentBlockStream`.
e2e tests should still work

Unbuffered block stream

---

crates/driver/src/infra/persistence/mod.rs
crates/driver/src/infra/solver/mod.rs

After checking the changes in staging, @fhenneke requested for the data to be stored as a JSON and not as a serialized string.

Store the auction with liquidity as a JSON and not as a string

---

crates/ethrpc/src/current_block/mod.rs

When building a fresh unbuffered web3 transport for the current block stream in #2707 I forgot to instrument it which means we can no longer see how many requests originate from that component.
Instruments the block stream instance again (now even with a custom component label)
Ran locally and checked the generated metrics:
```
curl http://localhost:9586/metrics | rg currentBlockStream                                                          ─╯
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 24985  100 24985    0     0  6557k      0 --:--:-- --:--:-- --:--:-- 8133k
gp_v2_api_rpc_requests_complete{component="base_currentBlockStream",method="eth_getBlockByNumber"} 4 …
```

[EASY] Instrument currentblockstream web3 instance again

---

crates/driver/src/infra/blockchain/gas.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/config/mod.rs
crates/driver/src/run.rs
crates/driver/src/tests/setup/solver.rs

In the process of adapting for Arbitrum compatibility, we encountered issues with gas price estimation. The default gas price estimator in our driver provided values significantly higher than what the RPC endpoint returns, resulting in orders being created with insufficient fees. This discrepancy led to solvers being unable to find profitable solutions due to excessively high gas prices.
The gas price estimator in the driver is currently hardcoded, while the autopilot/orderbook allows for flexible selection of the gas price estimator. This inconsistency has caused orders to be created with a low fee while solvers receive instructions based on a much higher gas price, preventing them from finding viable solutions.
This change will allow us to use a Web3-based estimator, which provides more …

Gas estimator driver config

---

crates/driver/src/infra/config/file/mod.rs

The gas estimator type seemingly can't be deserialized with the `untagged` attribute.
While I was at it I also made sure variants get renamed to kebab cast
* remove untagged property
* renamed variants to kebab case
tested change locally. The strings "web3" and "native" can now be deserialized.

[EASY] Remove untagged enum property

---

README.md
crates/orderbook/openapi.yml
crates/shared/src/bad_token/token_owner_finder/blockscout.rs

Update docs regarding Arbitrum one and remove Goerli references.
Also added arb1 endpoint to blockscout config.
1. Check readme
2. Check api docs

feat: arbitrum one docs

---

crates/solvers/openapi.yml

This has created confusion to multiple solver teams. Hope this PR does what it is supposed to.

Fix "calldata" typo in solver/driver api description

---

crates/driver/src/infra/solver/dto/auction.rs
crates/driver/src/tests/setup/solver.rs
crates/solvers-dto/src/auction.rs
crates/solvers/openapi.yml
crates/solvers/src/tests/baseline/bal_liquidity.rs
crates/solvers/src/tests/baseline/buy_order_rounding.rs
crates/solvers/src/tests/baseline/direct_swap.rs
crates/solvers/src/tests/baseline/internalization.rs
crates/solvers/src/tests/baseline/limit_order_quoting.rs
crates/solvers/src/tests/baseline/partial_fill.rs
crates/solvers/src/tests/naive/extract_deepest_pool.rs
crates/solvers/src/tests/naive/filters_out_of_price_orders.rs
crates/solvers/src/tests/naive/limit_order_price.rs
crates/solvers/src/tests/naive/matches_orders.rs
crates/solvers/src/tests/naive/reserves_too_small.rs
crates/solvers/src/tests/naive/rounds_prices_in_favour_of_traders.rs
crates/solvers/src/tests/naive/swap_less_than_reserves.rs
crates/solvers/src/tests/naive/without_pool.rs

The solvers would need to know the JIT-order surplus capturing addresses (see e.g. https://github.com/cowprotocol/services/issues/2715#issuecomment-2130855593). For that the owner addresses are propagated to the solvers in the auction json.
Propagate the list of surplus capturing JIT-order owners to the solvers in the auction json.

Propagate the surplus capturing JIT-order owners to the solvers

---

crates/contracts/build.rs

There were issues with liquidity fetching. It turned out that the Uniswap V2 contract addresses were incorrect.
Update the addresses taken from https://docs.uniswap.org/contracts/v2/reference/smart-contracts/v2-deployments
Tested locally

Uniswap V2 contract addresses fix

---

.github/workflows/pull-request.yaml
crates/e2e/src/nodes/mod.rs
crates/e2e/src/setup/mod.rs
crates/e2e/tests/e2e/protocol_fee.rs

https://github.com/foundry-rs/foundry/issues/8035 changed `anvil` to compute the gas price differently. This seems like a breaking change since under some conditions the new logic computes a different gas price than the original one.
This broke 2 of our tests which both involve waiting for the system to flush out cached liquidity data to generate new quotes. For `e2e::e2e quoting::local_node_test` it was enough to just bump the `--base-fee` to `1` (without breaking any other test) and for `e2e::e2e protocol_fee::local_node_combined_protocol_fees` I needed to make the condition to detect flushed liquidity stricter.
Instead of waiting for any change in quotes (which are now triggered too early because of tiny changes in the gas price) we now wait for the quote to be at least twice as good …

Fix CI after foundry update

---

crates/shared/src/price_estimation/factory.rs

When quote verification was fresh it made sense to have special logging for verified estimators to debug things. But now all estimators are always verified and the `_verified` postfix makes it so that you don't get to see all the logs in kibana when you just search for `<estimator>` (`<estimator>_verified` logs would not show up).

[TRIVIAL] Simplify estimator logs

---

Cargo.lock
Cargo.toml
crates/e2e/Cargo.toml
crates/s3/Cargo.toml

Updates all dependencies within the constraints of `cargo.toml`.
Also updates forked version of `warp` to latest commit.
Ideally we'd like to get rid of `warp` altogether since it's no longer really maintained but this requires a bunch of changes in the `api` so until then we should at least update the version as long as it's easy to do.

Run `cargo update`

---

crates/autopilot/src/domain/competition/mod.rs
crates/autopilot/src/run_loop.rs

Currently solvers that get deny listed by the circuit breaker due to rule violations still receive `/solve` and subsequent `/settle` calls by the autopilot.
Discards any solution returned by `/solve` where the given submission address is currently deny listed. Since these solutions will no longer get ranked in the competition we'll also not call `/settle` for them anymore.
e2e tests should still pass
I didn't add the test case that verifies that a deny listed solver actually gets their solutions removed but if that doesn't work this PR would not make it worse than the status quo.

Discard deny listed solver solutions

---

crates/ethrpc/src/buffered.rs

Follow up to the https://github.com/cowprotocol/services/pull/2750
2 subsequent numbers should not be compiled into a range.

[EASY] Exclude 2 subsequent numbers from the range

---

Cargo.lock
crates/model/Cargo.toml
crates/model/src/auction.rs
crates/model/src/order.rs
crates/model/src/quote.rs
crates/model/src/ratio_as_decimal.rs
crates/model/src/signature.rs
crates/model/src/solver_competition.rs
crates/model/src/trade.rs
crates/shared/src/lib.rs
crates/shared/src/sources/uniswap_v3/pool_fetching.rs
crates/shared/src/tenderly_api.rs
crates/shared/src/test_utils.rs

[As suggested in another PR](https://github.com/gnosis/solvers/pull/39#discussion_r1645701146), extracts partial json assertion macro into the `shared` crate to use across crates/repos.
> This pull request's key enhancement is the introduction of macros for partially asserting the contents of POST requests. This method allows us to validate the request structure and static fields while excluding the dynamically generated random values from the assertion checks.
Also, this macro produces meaningful error instead of generic `left json is not equal to right json`, which saves some time when dealing with json structure changes and failing tests.
Once merged, [this PR](https://github.com/gnosis/solvers/pull/39) can be closed.

Partial json assertion macro

---

crates/ethrpc/src/http.rs

Noticed that we don't populate `x-request-id` for non-batched RPC calls. Looks like that is the reason.

[TRIVIAL] `x-request-id` header typo fix

---

crates/shared/src/bad_token/token_owner_finder.rs
crates/shared/src/bad_token/token_owner_finder/blockscout.rs

Blockscout's public API has 50RPS globally which is rate limited at the moment. To avoid that, an API key can be used with a 10RPS allowance.

Blockscout API key

---

.cargo/config.toml
Cargo.lock
Cargo.toml
README.md
crates/alerter/src/lib.rs
crates/autopilot/src/run.rs
crates/driver/src/infra/cli.rs
crates/driver/src/infra/observe/mod.rs
crates/driver/src/run.rs
crates/driver/src/tests/setup/mod.rs
crates/e2e/src/setup/mod.rs
crates/ethrpc/src/current_block/mod.rs
crates/observe/Cargo.toml
crates/observe/src/panic_hook.rs
crates/observe/src/tracing.rs
crates/orderbook/src/ipfs.rs
crates/orderbook/src/run.rs
crates/refunder/src/lib.rs
crates/shared/src/arguments.rs
crates/shared/src/bad_token/trace_call.rs
crates/shared/src/maintenance.rs
crates/solvers/src/infra/cli.rs
crates/solvers/src/run.rs

This PR attempts to bring back the [tokio console](https://github.com/tokio-rs/console) integration from https://github.com/cowprotocol/services/pull/1915 which can be useful to debug specific tasks.
The first time we tried to add the tokio console we no longer saw all the logs. They got drop mysteriously. Since then a lot of time has passed and possibly this is no longer an issue. To stay on the cautious side I changed the original PR to make the console an opt-in feature. That way we don't have to recompile the whole binary and redeploy it. We just have to remove the `--enable-tokio-console true` flag.
BTW if you are running `tmux` and it doesn't look like on the screenshots (e.g. graphs in the detail views are missing) the culprit is likely a misconfiguration in your `.tmux.config` …

Tokio console

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/run.rs
crates/autopilot/src/run_loop.rs

It seems the field `additional_deadline_for_rewards` is not used anywhere. It is used to calculate the `block_deadline` which is stored in the database as part of the competition. But it seems it has no other effect. Maybe is it legacy code?
Fully remove `additional_deadline_for_rewards`.

(Proposal):  Remove additional_deadline_for_rewards

---

crates/cow-amm/src/registry.rs

Switches from `Mutex` to `RwLock` allow readers not to block the registry storage.

[EASY] Registry storage RwLock

---

crates/shared/src/order_validation.rs

We tried to debug why a user could not create an order although their account seemingly has the required balance and allowance set.
So far my best guess is that they signed the order creation struct, changed a value and then didn't update the signature.
In that case we would recover an address as the owner from for the order which is not that user's address.
But since the user didn't set the `from` value in their request (which would cause an error if `from != recovered_owner`) it's not very straight forward to debug this.
Now we always print which address we recovered as the owner of an order to make future investigations easier.

Log which owner was recovered from an order creation request

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/infra/blockchain/contracts.rs
crates/autopilot/src/run.rs
crates/autopilot/src/run_loop.rs
crates/autopilot/src/solvable_orders.rs
crates/cow-amm/src/cache.rs
crates/cow-amm/src/registry.rs
crates/driver/example.toml
crates/driver/src/domain/competition/auction.rs
crates/driver/src/infra/blockchain/contracts.rs
crates/driver/src/infra/blockchain/mod.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/run.rs
crates/driver/src/tests/setup/solver.rs
crates/e2e/src/setup/colocation.rs
crates/e2e/tests/e2e/cow_amm.rs

Currently we try to automatically load the `CowAmmLegacyHelper` contract in the autopilot and driver. This is convenient in terms of writing code but does not allow to disable indexing cow amms.
This is particularly problematic if the staging and prod driver generate orders for the same CoW AMMs. In that case these 2 environments are racing each other which could lead to many reverts when both environments try to rebalance the same CoW AMM.
Now we can pass the cow amm configs (start_block, factory, helper) via configuration parameters.
This allows us to also run the driver without generating orders in staging and also adds the necessary features to support the balancer pools out of the gate.
Now as soon as the helper contract is ready we can just update the configs in the infra and start …

Pass CoW AMM configs via args

---

Cargo.lock
crates/orderbook/Cargo.toml

Removes `axum` dependency from the orderbook crate since it is not used there.

[TRIVIAL] Remove orderbook's `axum` dependency

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/domain/fee/mod.rs
crates/autopilot/src/run.rs
crates/autopilot/src/solvable_orders.rs
crates/e2e/tests/e2e/cow_amm.rs
crates/e2e/tests/e2e/protocol_fee.rs

Remove `protocol_fee_exempt_addresses` since now we can index the CoW AMM addresses. And rename `surplus_capturing_jit_order_owners` to `cow_amms`.
- Remove `protocol_fee_exempt_addresses` and use the indexed CoW AMMs for the fee exemption
- Change the name from `surplus_capturing_jit_order_owners` to `cow_amms`
1.  Driver tests
2. e2e tests

(Proposal) Remove exempt fee addresses

---

crates/autopilot/src/infra/persistence/dto/quote.rs
crates/orderbook/src/database/fee_policies.rs

While testing https://github.com/cowprotocol/services/issues/2642, @fhenneke noticed a discrepancy in the quote fee amount between the new API and Auction JSON, where the former looks more correct since it doesn't use `f64` calculation: https://github.com/cowprotocol/services/blob/quote-fee-adjustment/crates/orderbook/src/database/fee_policies.rs#L91-L103
The same calculation approach is now used in both places.

Quote fee adjustment

---

crates/shared/src/price_estimation.rs
crates/shared/src/price_estimation/factory.rs
crates/shared/src/price_estimation/native.rs
crates/shared/src/price_estimation/native/coingecko.rs
crates/shared/src/price_estimation/native/oneinch.rs

Implement a native prices fetch from CoinGecko. As we see in the issue https://github.com/cowprotocol/services/issues/2814, we are getting many orders rejected because we do not have native prices for many tokens. And the cache of outdated tokens keeps growing over time. In order to solve this, we add CoinGecko as a native price fetcher too.
This PR standalone (without infrastructure PR) doesn't have any impact, as CoinGecko must be configured as a native price   estimator source.
The PR can already prove if fetching prices from CoinGecko improves the cache and the order errors rate, but the following changes are needed in upcoming PRs:
- Instead of fetching prices from all the sources at one, have a primary method for fetching prices (CoinGecko) and fallback methods (solvers + 1inch)
- …

Implement CoinGecko for fetching native prices

---

crates/autopilot/src/domain/auction/order.rs
crates/autopilot/src/domain/settlement/auction.rs
crates/autopilot/src/domain/settlement/mod.rs
crates/autopilot/src/domain/settlement/solution/mod.rs
crates/autopilot/src/domain/settlement/solution/trade.rs
crates/autopilot/src/on_settlement_event_updater.rs

Ports [newest changes](https://github.com/cowprotocol/services/blob/main/crates/autopilot/src/on_settlement_event_updater.rs#L241-L244) for surplus calculation to new domain objects used for surplus calculation.
We have two rules:
1. Only orders that were part of the `Auction` are eligible for contributing to surplus of a settlement.
2. Other than that, orders are eligible if their owner is part of the `Auction`.
Will have a test where score will be compared to driver computed score once all PRs are merged.

Autopilot refactor 1/3: Support surplus capturing orders

---

crates/autopilot/src/domain/eth/mod.rs
crates/autopilot/src/domain/settlement/mod.rs
crates/autopilot/src/domain/settlement/observation.rs
crates/autopilot/src/domain/settlement/solution/mod.rs
crates/autopilot/src/domain/settlement/solution/trade.rs
crates/autopilot/src/on_settlement_event_updater.rs

Ports building observation data which is supposed to be saved to the database.
Equivalent to: https://github.com/cowprotocol/services/blob/main/crates/autopilot/src/on_settlement_event_updater.rs#L243-L260
Added Observation object printing to `OnSettlementEventUpdater`

Autopilot refactor 2/3: Build Observation object

---

crates/autopilot/src/database/onchain_order_events.rs

When looking into adding a log statement when on chain orders are parsed (to debug time to happy moo), I noticed that the `append_events` and `replace_events` logic in the on chain order handler use exactly the same code except for the following block, which is only present in `replace_events`:
```rust
database::onchain_broadcasted_orders::mark_as_reorged(
&mut transaction,
*range.start() as i64,
)
.await
.context("mark_onchain_order_events failed")?;
database::onchain_invalidations::delete_invalidations(
&mut transaction,
*range.start() as i64,
)
.await
.context("invalidating_onchain_order_events failed")?;
```
Combining this logic remove code duplication and allows for easier adjusting of the logic.
CI
Please double check my reasoning that `replace_events` indeed mirror the exact logic …

Combine onchain order event handling logic

---

crates/autopilot/src/database/onchain_order_events.rs
crates/autopilot/src/run_loop.rs

It is currently very hard to retrieve a native ETH flow orders quote. At the same time the autopilot is flooded with relatively useless "saving order competition logs" (this data is better visualised using the [API](https://api.cow.fi/docs/#/default/get_api_v1_solver_competition__auction_id_)
Run code locally, see new logs

[Trivial] Improve autopilot logging to debug execution speed

---

crates/driver/src/domain/competition/solution/mod.rs
crates/driver/src/tests/cases/merge_settlements.rs
crates/driver/src/tests/cases/mod.rs
crates/driver/src/tests/setup/mod.rs

Furucombo people noticed the scaling of prices in the driver is not working properly.
Example auction: 9172009
[Example log](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/doc/c0e240e0-d9b3-11ed-b0e6-e361adffce0b/cowlogs-prod-2024.07.23?id=cpXk3JABP0v0FZqw807z) of two solutions that should have been merged.
The `fn scaling_factor` function description is correct:
> /// Given two solutions returns the factors with
> /// which prices of the second solution would have to be multiplied so that the
> /// given token would have the same price in both solutions.
which means, we need to calculate `factor = first_price / second_price` so that `factor` represents the number with which `second_price` should be multiplied to get `first_price`

Fix scaling factor in driver

---

crates/autopilot/src/run_loop.rs

We have been seeing an increasing number of alerts about insufficient settlement throughput (specifically on Gnosis Chain). From what I can tell this is mainly due to jit orders with tiny amounts not being considered by more sophisticated (external) solvers and thus increasing this metric.
The easiest fix is to simply exclude those orders from the metric.
Alternatively, we could also define a "surplus threshold" and ignore orders that have very little surplus. However, I think since these jit orders are passive liquidity and our "settlement throughput" metric intends to be user facing, filtering these orders out completely seems like a good and simpler choice
Once deployed in prod, expect much reduced logs of the form

Filter jit orders for settlement throughput metric

---

crates/autopilot/src/domain/settlement/mod.rs
crates/autopilot/src/infra/persistence/mod.rs
crates/autopilot/src/on_settlement_event_updater.rs

Second and third match cases substituted place (code diff shows it a bit unfortunately). 
`settlement data already recorded for this auction` should have a higher priority. The example when this is important is when staging (which is frontrunning production with `auction_id` by ~270 days) reports `solution submitted by solver other than the winner` in cases when it processes production tx with an `auction_id` that is already processed by staging 270 days ago:
https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/nsx2A
Instead, it should first check if the settlement is already processed and skip the settlement, while `solution submitted by solver other than the winner` is a serious violation that should indicate something is wrong (although we currently don't act on it).

Fix already recorded data for auction_id

---

crates/shared/src/price_estimation/native/coingecko.rs

Fixes the CoinGecko URL introduced in https://github.com/cowprotocol/services/pull/2841
We cannot do `.to_string()` to `H160` types!
1. Unittest

Fix CoinGecko URL

---

Cargo.lock
crates/shared/Cargo.toml
crates/shared/src/sources/uniswap_v2.rs
crates/shared/src/sources/uniswap_v2/pool_fetching.rs

We have been using [HashSetDelay](https://docs.rs/delay_map/latest/delay_map/hashset_delay/struct.HashSetDelay.html) incorrectly. The expiration time is only respected if the set is turned into a stream and awaited on (it will return `Err` for expired items).
This interface is very clunky and doesn't really serve our use case.
Existing tests pass. Also, in the next PR I will add an e2e test that actually relies on the non-existent pool cache to be reset (as liquidity appears throughout the lifetime of the test)

Fix NonExistentPoolMap

---

crates/orderbook/openapi.yml

Lower case CompetitionOrderStatus types
Response is lower cased. [Example](https://barn.api.cow.fi/sepolia/api/v1/orders/0x00b398add57a13185949207383bdedecd5fd5f566c7273d62746273eb7565d225b0abe214ab7875562adee331deff0fe1912fe4266acef0c/status):
```
{"type":"traded","value":[{"solver":"baseline","executedAmounts":{"sell":"88000000000000000000","buy":"247730171894119905"}},{"solver":"quasimodo","executedAmounts":{"sell":"88000000000000000000","buy":"250215016055879850"}}]}
```
However, types on open api definition are capital cased:
Which makes clients depending on it to derive wrong types.
Check corresponding openapi docs

fix: lowercase orderbook CompetitionOrderStatus types to match real output

---

Cargo.lock
crates/autopilot/src/run.rs
crates/orderbook/src/run.rs
crates/shared/Cargo.toml
crates/shared/src/price_estimation/factory.rs
crates/shared/src/price_estimation/native/coingecko.rs

CoinGecko does not support fetching native prices for xdai (meaning prices of tokens against wxDai price). So, it is needed to calculate the native price by also fetching the wxDai native price.
- For xdai network, do two requests in order to properly calculate the native price
1. Unit test

CoinGecko: Fix xdai native prices

---

crates/autopilot/src/on_settlement_event_updater.rs

Moves committing to database bellow the temporary added code that builds the domain::Settlement because domain:Settlement reports `WrongEnvironment` for each settlement if settlement is already processed (saved to database).
This is needed to test the new Settlement code.

[TRIVIAL] Move commit to bottom of OnSettlementEventUpdater

---

crates/autopilot/src/domain/settlement/mod.rs
crates/autopilot/src/domain/settlement/solution/mod.rs
crates/autopilot/src/domain/settlement/solution/trade.rs

Related to discussion in the issue: https://github.com/cowprotocol/services/issues/2862#issuecomment-2270980569
Use external price vector to convert "fee in surplus token" into "fee in sell token" (instead of uniform clearing prices).
This is important so that we make sure that it's always true:
`total_fee = executed_surplus_fee + protocol fees`
If we use uniform clearing prices for `executed_surplus_fee` and external prices for `protocol fees` I think above equation won't stand.
Existing unit test

Use external prices for conversion of fees in autopilot

---

crates/shared/src/price_estimation/trade_finder.rs
crates/shared/src/request_sharing.rs
crates/shared/src/trade_finding/external.rs

This PR ended up being a small collection of improvements all related to request sharing in the hopes of improving the memory leak situation.
- replace all uses of `.shared()` with `.shared_or_else()` to delay the construction of shared futures as much as possible (might result in a reduction of the leaked memory 🤞)
- drop `.shared()` altogether because it's less powerful than `.shared_or_else()` and can use excessive memory
- finally the unit test is able to assert that the original future and shared cached future indeed point to the same underlying future
- added a metric to count all cached items across all individual request sharing structs
Either this shows a constant increase which suggests that we leak memory by not cleaning up the map (and keeping strong references to the shared …

Few improvements for request sharing

---

crates/autopilot/src/domain/eth/mod.rs
crates/autopilot/src/domain/settlement/mod.rs
crates/autopilot/src/domain/settlement/solution/mod.rs
crates/autopilot/src/domain/settlement/solution/trade.rs
crates/autopilot/src/on_settlement_event_updater.rs
crates/driver/src/domain/competition/solution/scoring.rs

Implements task ~2~  1 from https://github.com/cowprotocol/services/issues/2862:
> Extend order_execution with a field that contains a list of executed protocol fees in surplus token, together with the surplus token address
`autopilot::domain::Settlement` now exposes breakdown of protocol fees in surplus token.
Applies the same refactoring to driver, to keep the code 1:1 (and also to use driver tests to confirm no bugs were introduced).

Protocol fees breakdown

---

crates/shared/src/request_sharing.rs

The metrics added in https://github.com/cowprotocol/services/pull/2880 shows for a fact that the `RequestSharing` cache grows over time. However, all these allocations are currently counted with a single metric.
Instead of tracking all cached items with a single gauge we now track per `RequestSharing` instance which maybe points us to a very bad offender giving us an idea what to look out for.

Fine grained cache metrics

---

crates/shared/src/bad_token/trace_call.rs

This is a pretty hacky PR, but given that we didn't manage to get rid of bad token detection in the last quarter and it's not clear when we will find the ressources for it, I feel the impact this change can have may be worth its ugliness.
There are a lot of tokens (e.g. stETH, eUSD, oETH, etc.) whose transfer logic is based on "shares" (cf. eUSD [transfer implementation](https://etherscan.io/token/0x97de57ec338ab5d51557da3434828c5dbfada371#code#F3#L355)). The logic to convert shares into token amounts requires a division which can lead to off by one error: 
<details>
<summary>Relevant solidity code</summary>
```solidity
function balanceOf(address _account) public view returns (uint256) {
return getMintedEUSDByShares(_sharesOf(_account));
}
function _transfer(
address _sender,
address …
```

Add 1wei tolerance for bad token detection

---

crates/autopilot/src/domain/competition/mod.rs
crates/autopilot/src/infra/solvers/mod.rs
crates/autopilot/src/run.rs
crates/autopilot/src/run_loop.rs
crates/e2e/src/setup/colocation.rs
crates/e2e/src/setup/onchain_components.rs
crates/e2e/src/setup/services.rs
crates/e2e/tests/e2e/buffers.rs
crates/e2e/tests/e2e/cow_amm.rs
crates/e2e/tests/e2e/jit_orders.rs
crates/e2e/tests/e2e/limit_orders.rs
crates/e2e/tests/e2e/liquidity.rs
crates/e2e/tests/e2e/order_cancellation.rs
crates/e2e/tests/e2e/solver_competition.rs
crates/shared/src/arguments.rs

This PR add an additional optional config value for solvers in the autopilot, which aims at preventing solvers that are highly specialised at certain token pairs to get picked as an auction winner with an order execution that is violating EBBO or other fairness constraints.
An example for this is this [recent settlement](https://explorer.cow.fi/tx/0x1a482783a9eb243a007196913ce2b2bb86a110d7e3d1e4807a4ff679007c3629?tab=orders), which triggered an EBBO violation. The winning solver was the only one bidding for the orders that sell _PYUSD_ and _crvCVXETH_ creating enough surplus on these two orders to win the overall auction.
However, due to outdated liquidity sources on their end, the execution for the last sDAI -> crvUSD order was terrible triggering a violation of the rules of the …

Fairness check

---

crates/autopilot/src/boundary/order.rs
crates/autopilot/src/domain/auction/order.rs
crates/autopilot/src/domain/fee/mod.rs
crates/autopilot/src/infra/persistence/dto/fee_policy.rs
crates/autopilot/src/infra/persistence/dto/order.rs
crates/driver/src/infra/api/routes/solve/dto/auction.rs

Fixes DTOs after https://github.com/cowprotocol/services/pull/2897.
Also, uses optional values in `autopilot` only and sends default values to the driver.
> [!IMPORTANT]
> This PR should be reverted together with https://github.com/cowprotocol/services/pull/2897 after the next weekly release.

[EASY] Use optional values in autopilot only

---

crates/e2e/tests/e2e/limit_orders.rs
crates/shared/src/order_validation.rs

#2854 added the ability to place orders without having a valid quote. The goal was to support limit orders for sizes that aren't covered by any on chain liquidity (and thus yield NoLiquidity as an error).
When looking at the logs however, we can see that the majority of orders that are placed are placed due to other (non liquidity related) quoting errors such as internal server errors etc.
We shouldn't allow order placement in those cases
Technically, we might even want to differentiate between native price estimates (which are required for the order to land in the auction) and missing liquidity on the route, but that's a larger change.
Adjusted the e2e test

Only allow order placements without quotes if there is NoLiquidity

---

crates/autopilot/src/run_loop.rs
crates/autopilot/src/solvable_orders.rs

> In order to move towards one price per token per block we need to remove inefficiencies in our run loop to make sure it can run within 2-4s (to leave sufficient time for the solvers).
Achieves the following:
1. **How long after the block's timestamp does the run loop start**: `single_run_delay` metric.
2. **How long does it take until solve is called on the solvers:** `auction_preprocessing_time` metric.
3. **How long does solver take:** This can be done using the existing `solve` metrics(by calculating the MAX value among solvers for the last N seconds).
4. **How long does reveal take:** Seems like the current `reveal` metric wasn't used, so I updated its type to `Histogram`.
5. **How long does post-processing (writing the competition to the DB) take:** `auction_postprocessing_time` …

Run loop additional metrics

---

crates/autopilot/src/run_loop.rs
crates/autopilot/src/solvable_orders.rs

New run loop metrics were introduced in #2888. Currently, we have them on staging only(GPv2 -> Autopilot Co-location Runloop section), and some of them are not really useful because the size of some buckets is too large.
Use default buckets for metrics that spend less than 2s in general for all the operations.
Use larger buckets for the `current_block_delay` metric since most of the time it gets above the current 12s limit.
Prod deployment would probably require more bucket adjustments. Some of the metric might be merged in a single one with different labels.

[EASY] Runloop metrics buckets adjustments

---

crates/shared/Cargo.toml
crates/shared/src/price_estimation/factory.rs
crates/shared/src/price_estimation/native/coingecko.rs

Fixes: https://github.com/cowprotocol/services/issues/2887
Adjust returned native token prices when the quoted token has a different amount of decimals than the native token to be inline with all other native price estimator implementations.
Additionally I also removed the option to quote without denominating in any token mainly to reduce complexity.
Added an `ignored` unit test that checks that prices make sense.
Also compared prices returned for `wxdai` and `usdc` with prices logged in our infra.

Adjust coingecko prices based on token decimals

---

crates/driver/src/infra/notify/mod.rs
crates/driver/src/infra/notify/notification.rs
crates/driver/src/infra/solver/dto/notification.rs

One of the main source for confusion for solvers that aren't running their own driver are Settlement failures where they don't understand why the settlement failed. Recently a lot of teams asked us to investigate instances where it turned out that their settlement simply was included before the deadline.
This PR creates an explicit notification subtype for it so that solvers can self-diagnose this case. cc @bram-vdberg

[Easy] Explicit Solver Notification for expired settlements

---

crates/autopilot/src/domain/eth/mod.rs
crates/autopilot/src/domain/settlement/solution/mod.rs
crates/autopilot/src/domain/settlement/solution/trade.rs
crates/driver/src/domain/competition/solution/scoring.rs

Fix rounding issues for volume based fee policies (a follow up for https://github.com/cowprotocol/services/pull/2857)

Change logic how network fee is calculated

---

crates/ethrpc/src/block_stream/mod.rs

Adds new field `observed_at` to `BlockInfo` which shows when the system became aware of the new block. This can be useful for synchronizing on because there are actually very few guarantees on the `timestamp` field provided by ethereum and it's also only precise to a second.
Part of https://github.com/cowprotocol/services/pull/2906 separated out for easier reviewing.
- adds `observed_at` to `BlockInfo`
- custom impl for `Default` and `PartialEq` to handle `observed_at`
tests should still pass

`observed_at` on `BlockInfo`

---

crates/driver/src/infra/api/routes/settle/mod.rs

While working on a PR to synchronize the runloop to the blockstream I noticed that the autopilot currently waits till 1 block past the deadline. When changing that to aborting on the deadline block tests started to fail because we no longer submitted the cancellation on-chain. The reason is that the `/settle` handle stops running in the driver when the `autopilot` aborts the call due to reaching the deadline.
Run `/settle` handler in a background task to ensure that we correctly submit the settlement or cancellation even if the autopilot aborts the `/settle` call.
e2e test should continue to work

Handle `/settle` in background task

---

crates/autopilot/src/run_loop.rs

Historical context:
Initially we wanted to save all auction prices so we can reconstruct the whole auction object if needed.
Then, I implemented the optimization that we save prices only for orders that appear in the winning solution, with the assumption that this is all we will need. 
However, this assumption changed with cow amm implementation, where cow amm orders do not exist in the auction, therefore we are unable to determine their sell/buy tokens and save token prices for those cow amm orders.
Consequently, missing prices cause failure in score computing, where for all surplus capturing orders (cow amm orders) we need to have auction prices.

Save all auction prices

---

crates/autopilot/src/solvable_orders.rs

Bad token detection sometimes takes an unreasonable amount of time. An attempt to speed up this a bit is to execute operations for each order in parallel.
The whole `filter_unsupported_tokens` could be executed in parallel together with other orders filtering functions. Subject of a separate PR.

Detect bad tokens in parallel

---

crates/autopilot/src/run_loop.rs
crates/e2e/tests/e2e/univ2.rs

Currently all orders that are part of any solution are marked as considered. This seems to be problematic for the progress bar feature because the winning solution can report `Considered` for a split second and then `Executing` because those state get stored in very quick succession.
Since this state is not used for anything backend related and it doesn't seem crazy useful to store `Considered` and `Executing` for the same order this PR makes it so that we only store `Considered` for **non-winning** solutions.
- store `Considered` only for **non-winning** solutions
- store `Considered` states **after** filtering out "unfair" solutions
e2e tests should still pass
@alfetopito let me know if you want to have this merged for the progress bar or not

Make `Considered` state more useful

---

.github/workflows/pull-request.yaml

The forked e2e tests are overall pretty useful but the public nodes we've used so far have been pretty flaky which leads to people not paying too much attention when a forked test fails for a good reason.
- I changed the github secrets to use self hosted nodes which should be more reliable
- removed the concurrency limit on the tests as we don't have to adhere to any compute limits anymore
forked tests should still work

Remove concurrency limit on forked e2e tests

---

crates/autopilot/src/boundary/mod.rs
crates/autopilot/src/infra/blockchain/mod.rs
crates/autopilot/src/run.rs

Currently, ethrpc values are hardcoded. It makes sense to start using values from arguments to adjust them using infra. No config change is required since the same ones are used in the pulumi config.

[EASY] Use autopilot ethrpc config from args

---

crates/database/src/auction_prices.rs

Since all the native prices are stored instead of just the ones the winning solution won, this process takes much more time than before.
Store prices in batches should speed up this.

Insert auction prices in batches

---

crates/autopilot/src/database/onchain_order_events/ethflow_events.rs
crates/autopilot/src/run.rs
crates/ethrpc/src/block_stream/mod.rs

https://github.com/cowprotocol/services/pull/2906 moved refund indexer maintenance into the solvable orders cache update loop. When there are no ethflow refunds in the DB or the last refund is very old, the refund indexer tries to fetch all the blocks, which might execute for more than 10 minutes, resulting in autopilot restarts and the whole protocol being stuck.
Change the behavior of calculating the starting index for refund indexer. If a recent eth-flow refund exists **within the last day**, it prioritizes this. Otherwise, it falls back to the most recent block from broadcasted orders. Then select the highest value among the value calculated in the previous step, settlement contract block and configured `ethflow_indexing_start`.
Staging.

Handle ethflow_refunds empty table case

---

crates/cow-amm/src/amm.rs
crates/cow-amm/src/cache.rs
crates/shared/src/arguments.rs

Currently the `autopilot` maintenance loop can get stuck when the configured cow amm helper contract does not support a found contract with this error:
```
2024-09-03T06:13:17.420Z  WARN autopilot::maintenance: failed to run background task successfully err=method 'tokens(address):(address[])' failure: contract call reverted with message: None
Caused by:
contract call reverted with message: None
```
So far we have been retrying this error over and over although the call to detect which tokens the pool is trading will never work if an amm is misconfigured or generally not supported by the helper contract.
Differentiate between retryable and fatal errors while indexing the amms and retry or skip this pool respectively.
Set up sepolia configuration locally and checked that we don't get stuck …

Handle fatal errors when indexing cow amms

---

crates/autopilot/src/maintenance.rs
crates/autopilot/src/run.rs

Indexing refunds is not strictly necessary to have all relevant state for building the next auction. That's why it's okay to move that logic off of the critical path.
This should resolve the start up issues we've been seeing on arbitrum staging where we have to reindex lots of blocks because the blocktime is so fast and we don't do refunds regularly. However, we should still find a better way to store the blocks we already indexed to avoid these issues in general.
Index refund events in a separate background task again.

Move refund indexing back into background task

---

crates/orderbook/src/arguments.rs
crates/shared/src/arguments.rs
crates/shared/src/bad_token/token_owner_finder.rs
crates/shared/src/price_estimation.rs
crates/shared/src/tenderly_api.rs

Improve the groups for `ethplorer` and `blockscout` inspired by the CoinGecko configuration done in: https://github.com/cowprotocol/services/pull/2909
1.Unit test

[EASY] Improve config group for blockscout and ethplorer

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/run.rs
crates/orderbook/src/arguments.rs
crates/orderbook/src/run.rs
crates/shared/src/arguments.rs
crates/shared/src/bad_token/cache.rs

Implement a prefetch for the token quality cache (similar to what we do in the native prices cache). This ensures that we always keep the cache updated.
- Change the `std::sync::Mutex` for a `tokio::sync::RwLock`, improving the performance
- Add to the orderbook and autopilot configuration the field `token_quality_cache_prefetch_time` in order to configure the prefetch time for token quality cache
- Change the `maintenance_timeout` in order to ensure its sampling time against `token_quality_cache_prefetch_time`
1. Unit test

Prefetch tokens quality cache

---

crates/e2e/tests/e2e/order_cancellation.rs

The e2e test to check that cancellations work was [flaky](https://github.com/cowprotocol/services/actions/runs/10696856101/job/29652879019) for a while now. It's possible that this happens more frequently after we merged the runloop refactor but IIUC the underlying issue must have been present (and known) forever.
The test previously asserted that the **last** order event after a cancellation was the cancellation itself.
However, if an order makes it into the auction before getting cancelled it will make it through the runloop (where we store the `ready` event) before we notice that the order was cancelled when building the **next** auction:
1. order gets put into auction
2. order gets cancelled (store `cancellation` event)
3. order progresses through runloop (store `ready` event)
4. …

Fix flaky cancellation test

---

crates/database/src/jit_orders.rs
crates/database/src/orders.rs
crates/e2e/src/setup/services.rs
crates/e2e/tests/e2e/jit_orders.rs
crates/orderbook/src/database/orders.rs

A follow up for https://github.com/cowprotocol/services/pull/2920
Implements [https://api.cow.fi/mainnet/api/v1/transactions/{tx_hash}/orders](https://api.cow.fi/docs/#/default/get_api_v1_transactions__txHash__orders) for JIT orders.
updated e2e test

Get JIT orders by tx

---

crates/database/src/jit_orders.rs

Fixes the conversion from JIT order to `model::Order`.
`settlement_contract` is hardcoded. Although easiest, this is bad for at least two reasons:
1. When settlement contract is redeployed, this will be a bug.
2. Not testable. e2e test infrastructure might have a different address for settlement contract etc.
Overall just seems wrong. Alternative is to add a new field to `jit_orders` database table and populate it from autopilot. Some effort to just pass around the field that is not used that much anyway 🤷‍♂️ 
Let me know WDYT.

Fix jit orders conversion

---

crates/database/src/jit_orders.rs

A follow up for https://github.com/cowprotocol/services/pull/2941 that handles an edge case:
`jit_orders` database table is potentially containing:
1. normal jit orders (orders that do not exist in orderbook)
2. orders that exist in the orderbook but do not exist in the auction (so called out-of-auction settled user trades).
This PR excludes (2) so that API function `get_orders_for_tx` doesn't return duplicated values for (2), since those exist in both `orders` and `jit_orders` tables.
Existing e2e tests.

Exclude orderbook orders from jit orders

---

crates/autopilot/src/infra/persistence/mod.rs
crates/database/src/byte_array.rs
crates/database/src/orders.rs

A suggestion to unify SQL queries mentioned in the https://github.com/cowprotocol/services/pull/2923 didn't work out. Postgres converts common table expressions into subqueries, which affects the performance. Also, with this approach, indexes cease to be utilized. As a result, it executes in 1.2-1.5s instead of ~200ms.
Tried so far(nothing helped):
- JOIN with CTE instead of using `WHERE IN (rowset)`
- Use `WITH cte AS NOT MATERIALIZED`
- Replace CTE with a subquery.
- Convert CTE result into ARRAY(has the best performance, but still 2-3 times slower than separated queries).
Revert to the separated queries that execute in ~200ms total.
Restored DB tests.

Separate `solvable_orders_after` query

---

crates/autopilot/src/solvable_orders.rs

Currently, it is impossible to detect some of the changes due to the poorly detailed buckets.

[TRIVIAL] More precise auction update total time metric buckets

---

crates/autopilot/src/run.rs
crates/autopilot/src/run_loop.rs

Removes the inflight orders cache because it should no longer be needed since we switched to blocking the runloop until we found the tx mined on-chain.
Just delete all code related to inflight orders.
e2e tests should still work

Remove inflight orders cache

---

crates/shared/src/account_balances/simulation.rs

Speed up autopilot balance fetching the same way it was done in the `driver` crate(#2045) in order to improve runloop performance.
> Reimplement parts of the balance query of [balances.sol](https://github.com/cowprotocol/services/blob/main/crates/contracts/solidity/Balances.sol?rgh-link-date=2023-11-07T00%3A14%3A31Z#L59-L76) using simple eth_calls and use that for any order group that does not contain any pre-interactions.
Existing e2e tests.
Driver and autopilot share the same logic inside. It probably makes sense to keep everything in the shared crate only.

Speed up autopilot balance fetching

---

crates/autopilot/src/domain/competition/mod.rs
crates/autopilot/src/infra/persistence/mod.rs
crates/autopilot/src/run_loop.rs
crates/autopilot/src/solvable_orders.rs
crates/ethrpc/src/block_stream/mod.rs

Mostly a refactor with a few changes to improve observability.
Refactors:
* move fairness checks and solutions sorting into `competition` to have it return the final state of the competition
* combine a bunch of logic to report on the proposed solutions into `report_on_solutions()`
* rename `solve()` to `try_solve()` and introduce a new function `solve()` that does all the error handling to make `competition()` leaner
Observability:
* `info` log whenever we see a new block
* log which solver proposed a solution for which order (to have a holistic view on the auction in the autopilot without having to stitch together driver logs
* record `Executed` order events together with `Considered` as suggested [here](https://github.com/cowprotocol/services/pull/2921#discussion_r1728621248) to have a …

Refactor runloop slightly

---

crates/autopilot/src/infra/persistence/mod.rs
crates/autopilot/src/solvable_orders.rs

The latest prod release showed that quotes fetching is one of the most expensive operations in the incremental solvable orders cache update.
This can be slightly improved by fetching quotes for only newly created and placed onchain orders

Autopilot: fetch only relevant quotes

---

crates/autopilot/src/database/auction.rs
crates/database/src/auction.rs

Alternative to https://github.com/cowprotocol/services/pull/2972 to be tested in order to speed up the auction replacement process.
- Replaces `TRUNCATE` with `DELETE` which should be more performant for small tables
- Uses a single combined SQL query.
> [!IMPORTANT]
> Should not be merged until a positive impact is confirmed.

Replace auction using a single SQL query

---

crates/autopilot/src/domain/settlement/mod.rs
crates/autopilot/src/domain/settlement/trade/math.rs

`fee_in_ether` is practically only used to store result into `settlement_observations.fee` field, which is used by solver team.
We calculate the total fee in surplus token, as a first step always. Now, instead of using uniform clearing prices to convert that fee to sell token, and then into Ether using external prices, we go directly from surplus token -> Ether:
before: `surplus token -> sell token -> Ether`
after: `surplus token -> Ether`
This is just a small step of moving all fees to be expressed over surplus token and remove conversions to sell token.
@fhenneke please would like your approval first since you work with this result.

Use surplus token for total fee calculation

---

crates/autopilot/src/maintenance.rs
crates/autopilot/src/run_loop.rs

The dropped metric actually duplicates the service maintenance time metric:
https://github.com/cowprotocol/services/blob/e84102090d6fecfbd4e967d09f2e0df5d2e951ac/crates/autopilot/src/run_loop.rs#L773-L776

[TRIVIAL] Drop redundant maintenance metric

---

crates/e2e/tests/e2e/partial_fill.rs
crates/orderbook/src/orderbook.rs

So far the order status endpoint had a pretty bad UX flaw:
If an order was traded we blindly return the latest competition data. This is correct when the endpoint gets called right after the settlement happened but wrong if it gets called a long time after the settlement.
Also discussed in this [slack thread](https://cowservices.slack.com/archives/C07BQJHK2E8/p1725912352749109).
The simple solution is to first check the `trades` table for the given order and return the competition data of the auction an order was executed the first time.
For any other label we can do the same thing we always did (return latest competition data).
I stumbled over this when I wanted to migrate the e2e tests to `--run-loop-mode=sync-to-blockchain` which triggered this exact error in an e2e test case.
With the …

Stable results for traded orders in `/status` endpoint

---

crates/autopilot/src/maintenance.rs

Since the syncronized runloop mode was enabled, the maintenance task is on the critical auction preparation path now, which takes some time. New metrics should help finding the most expensive operations in order to find a way to optimize them.
A new HistogramVec metric with the `stage` label.
Grafana.

Runloop maintenance stage metrics

---

crates/autopilot/src/infra/solvers/dto/solve.rs
crates/driver/openapi.yml
crates/driver/src/domain/competition/mod.rs
crates/driver/src/domain/competition/solution/settlement.rs
crates/driver/src/infra/api/routes/solve/dto/solved.rs
crates/driver/src/tests/setup/mod.rs

Fixes https://github.com/cowprotocol/services/issues/2839
Adds additional order data to each `Solve` response. This includes order's sell token, sell amount, buy token, buy amount and side. This is needed for two reasons:
1. Cow amm orders do not exist in the Auction, so we need this data to calculate the score of a solution at a competition time. This is to unblock https://github.com/cowprotocol/services/pull/2730/files
2. To allow selecting multiple winners for combinatorial auctions. To be more specific, for each winner, next winner has to have tokens that are not used in first winner, and to know which tokens are those, we need to provide sell token and buy token for cow amm orders.
Existing tests. Locally, I made sure that both old and new versions are properly deserialized on …

Enrich Solve response

---

crates/autopilot/src/infra/persistence/mod.rs
crates/autopilot/src/run_loop.rs

Currently fee policies are saved only for winning solution.
This PR saves fee policies for all auction orders. This is needed for at least two reasons:
1. As discussed [in the PR](https://github.com/cowprotocol/services/pull/2980#issuecomment-2354990062), fee policies will be needed for all proposed solutions during a competition so that the score could be reconstructed in circuit breaker.
2. [For historical get_auction](https://github.com/cowprotocol/services/issues/2844).

Save fee policies for all auction orders

---

crates/autopilot/src/run.rs
crates/autopilot/src/run_loop.rs

If an order is placed right after the auction cut, the user will wait for the whole runloop until their order gets picked up.
- Start preparing a new auction once a winning solution is found.
- For this, the in-flight orders cache had to be restored.
- `settlement_queues` controls FIFO ordered settlement executions for each driver separately. The maximum length of the queue is naturally defined by the settlement block deadline.
- Store drivers as `Vec<Arc<infra::Driver>>` to have access to them from the background task.
The `/solve` request for the next auction is now sent while waiting for the current auction settlement.

Cut auctions in parallel

---

crates/bytes-hex/Cargo.toml

I detected this issue while i was trying to run `unit test` under an individual crate `bytes-hex`. 
I mean to execute `cargo build` or `cargo test` right under `./crates/bytes-hex`. well, as `bytes-hex` is a crate, it's supposed to compile sucessfully & do unit tests independently.  but it cannot even compile.
with an error like:
```
296:8
|
296 | pub fn decode<T: AsRef<[u8]>>(data: T) -> Result<Vec<u8>, FromHexError> {
|        ^^^^^^
note: the item is gated behind the `alloc` feature
```
but I also realized the unit tests working well in github Actions. then i forked the code and test a few more scenarios, for examples, if you modify the `Cargo.toml` in the root directory, changing 
`members = ["crates/*"]`
into 
`members = ["crates/bytes-hex"]`
then the github actions will fail with …

fix: enable `alloc` feature on `hex` crate

---

.config/nextest.toml

Some [test](https://github.com/cowprotocol/services/actions/runs/10935547840/job/30357491587?pr=3000) in the CI got stuck when testing a completely harmless PR.
To keep the logs of the CI relatively clean we only log the actual output of a test if it fails.
At the moment stuck tests run forever and don't get terminated by `nextest` which means we can't recover how far into the test we got before it got stuck which could help to figure out what the issue is.
configures `nextest` to warn about a test being slow for every minute of runtime and aborts it after 4 minutes.
This will then result in logs being printed.
Ran some tests locally with a very low `period` which produced the desired behavior.

Abort stuck tests

---

crates/database/src/settlement_observations.rs
crates/e2e/tests/e2e/database.rs
database/README.md

Fixes https://github.com/cowprotocol/services/issues/2992
`settlement_scores::fetch` will be updated once the https://github.com/cowprotocol/services/pull/2980 is merged.
Existing univ2 e2e test.

[EASY] Update most_recent_cip_20_data

---

crates/autopilot/src/domain/competition/mod.rs
crates/autopilot/src/infra/solvers/dto/solve.rs
crates/autopilot/src/run_loop.rs

A follow up for https://github.com/cowprotocol/services/pull/2984 where we added a new format of /solve response, after which there were two ways to submit /solve response.
This PR deprecates the old way and uses only the new format and adjusts the autopilot domain code to use it (which is needed so we can finally merge https://github.com/cowprotocol/services/pull/2730
Will not merge it until all solvers switch to new format.

Use only new format of solve response

---

crates/autopilot/src/run_loop.rs

When we briefly stored all fee policies for a given auction in the post processing it increased the time for that critical section quite significantly.
That change was removed since then but the learning still stands that these operations might as well happen in parallel.
Run the 3 DB inserts futures of the run loop post processing in parallel.
It's a very small change so the e2e tests should be sufficient

[EASY] Parallelize post processing in run loop

---

crates/shared/src/event_handling.rs

Recently we moved some event indexing onto the hot path for auction building. This turned out to be surprisingly slow (500ms - 750ms) quite often [[1](https://g-0263500beb.grafana-workspace.eu-central-1.amazonaws.com/d/bdva97ea9wni8e/autopilot-runloop?orgId=1&from=now-12h&to=now&var-network=mainnet&var-datasource=5An5Ejq4k&var-driver=All&var-runloop_maintenance_stage=settlement_indexer&var-auction_update_stage=All&editPanel=14)]. Judging by the logs the prod mainnet autopilot entered the event indexing logic ~24K times [[2](https://aws-es.cow.fi/_dashboards/app/data-explorer/discover#?_a=(discover:(columns:!(log,log_level),isDirty:!f,sort:!()),metadata:(indexPattern:'86e4a5a0-4e4b-11ef-85c5-3946a99ed1a7',view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24h, …

EventIndexing: add fast path for multiple new blocks without reorg

---

crates/autopilot/src/database/onchain_order_events.rs

It annoys me to no end that you have to search different words for order creation depending on whether it was indexed by the autopilot or submitted by the user via the orderbook.
I don't know how much time I already wasted searching for ethflow orders because these logs are different!
**rant over**
Makes the onchain order indexing log use the same words as the orderbook.

[TRIVIAL] Improve logs for created ethflow orders

---

crates/autopilot/src/boundary/events/settlement.rs
crates/autopilot/src/domain/settlement/mod.rs
crates/autopilot/src/domain/settlement/observer.rs
crates/autopilot/src/domain/settlement/on_event.rs
crates/autopilot/src/lib.rs
crates/autopilot/src/run.rs
crates/database/src/settlements.rs

`OnSettlementEventUpdater` was previously refactored and ended up being dependent on `domain` and `infra` objects only. 
That means it is ready to be moved to a proper place inside `domain`.
Existing e2e tests.

Move settlement updater

---

crates/autopilot/src/domain/competition/mod.rs
crates/autopilot/src/infra/solvers/dto/solve.rs
crates/autopilot/src/run_loop.rs

Not sure what was the original reason to have two structs here (Solution and SolutionWithId), but anyway, it doesn't exist anymore and we should have a single struct for `Solution`.
This is a preliminary cleanup for implementing some basic validation rules on `competition::Solution` object, like uniqueness of <solution_id, solver> within Auction, existence of all clearing prices for all user order and surplus capturing JIT orders etc...
Existing e2e tests.

Cleanup competition::Solution

---

crates/autopilot/src/database/auction.rs
crates/autopilot/src/domain/auction/mod.rs
crates/autopilot/src/domain/mod.rs
crates/autopilot/src/infra/persistence/dto/auction.rs
crates/autopilot/src/infra/persistence/dto/mod.rs
crates/autopilot/src/infra/persistence/mod.rs
crates/autopilot/src/infra/shadow/orderbook/mod.rs
crates/autopilot/src/infra/solvers/dto/solve.rs
crates/autopilot/src/run_loop.rs
crates/autopilot/src/shadow.rs
crates/autopilot/src/solvable_orders.rs
crates/e2e/src/setup/services.rs

I got very frustrated by the fact that we have two versions of Auction object in autopilot domain:
1. `domain::Auction`
2. `domain::AuctionWithId`
and as a cherry on top, we almost never use `domain::AuctionWithId`, but instead use a pair of `<domain::auction::Id, domain::Auction>` throughout the whole runloop logic. Also, I never actually had an easy understanding why and where exactly auction has / doesn't have ID. This is my attempt to make thing cleaner (although not 100% clean).
Now, let's agree that `domain::Auction` has become the main Auction object which has ID, and we want to use this object everywhere in the autopilot. The small, isolated part of the autopilot code (SolvableOrdersCache which actually builds the auction object but without ID) is now marked by using …

Main Auction object has id

---

crates/autopilot/src/run_loop.rs

After switching to the sync-to-blockchain run loop mode, this metric is no longer populated, while a prod alert is still configured for it.
Populate the metric, making the alert work again.
Observe Grafana.

[EASY] Recover solvable orders cache update metric

---

crates/e2e/src/setup/services.rs

Recently we changed default values for the native price cache which led to some tests failing.
The problem seems to be that we can no longer reliably fetch native prices for some tokens.
With https://github.com/cowprotocol/services/pull/2987 we now have an easy way to make sure that all the native prices that can be there will be there. So I just enabled the feature and at least one of the problematic tests passed right away.
Will check CI if other tests are still problematic.
Edit: Seems to fix the forked nodes tests but some driver tests are still [flaky](https://github.com/cowprotocol/services/actions/runs/11121979135/job/30902264434?pr=3029)
This is the test

Fix flaky forked nodes tests

---

crates/autopilot/src/run_loop.rs
crates/autopilot/src/solvable_orders.rs

The code is not used anymore since this is now a part of the maintenance task.

[EASY] Drop solvable orders cache update background task

---

Cargo.lock
crates/shared/Cargo.toml
crates/shared/src/price_estimation/native_price_cache.rs

This PR addresses the last known issues with native price fetching: lock contention and spikes of expired orders.
https://github.com/cowprotocol/services/pull/2987 made it such that we can now fetch missing prices while building the auction. However, the implementation resulted in too much lock contention. Previously we locked the cache once and returned all relevant prices and now we lock it at least once per fetched price.
To fix that we first use the optimized function which only takes one lock and then we use the generic implementation that locks on every token. Since we started initializing the native price cache by loading prices from the DB we should rarely have many prices expire together so this should be fine.
Already confirmed to be working with a hotfixed prod release.
So far …

Native price fetching finishing touches

---

crates/autopilot/src/domain/eth/mod.rs
crates/autopilot/src/infra/persistence/mod.rs
crates/database/src/trades.rs
crates/orderbook/src/database/fee_policies.rs

JIT orders have a primary key `<block_number, log_index>` in `jit_orders` table. However, currently we use a single settlement event to save multiple JIT orders to database from `settlement::Observer`, which leads to only first JIT order being saved, while all others (if they exist) are skipped by an "[ON CONFLICT DO NOTHING](https://github.com/cowprotocol/services/blob/main/crates/database/src/jit_orders.rs#L158)" on insertion.
Instead of using a single settlement event, we now fetch all trade events that are associated with a settlement, match them to JIT orders, and then use trade events for PKs of JIT orders in database.
Updated database unit test to prove that sql query is correct.
Existing e2e should prove no regression bugs were introduced.

Fix JIT orders saving

---

crates/autopilot/src/database/competition.rs
crates/database/src/solver_competition.rs
crates/model/src/solver_competition.rs
crates/orderbook/src/database/solver_competition.rs

A breaking change of SolverCompetitionAPI, which now potentially returns more than 1 transaction associated with the competition (will notify all teams on slack soon).
Resolves one of the points from https://github.com/cowprotocol/services/issues/2830#issuecomment-2346083664
Refactored unit test to prove it works and that no regression issues were introduced.
Existing e2e test for solver competition proves that competition is properly returned.

Fix solver competition loading for multiple winners

---

crates/driver/src/domain/competition/auction.rs
crates/driver/src/domain/competition/order/mod.rs
crates/driver/src/domain/competition/solution/mod.rs
crates/driver/src/infra/api/routes/solve/dto/auction.rs
crates/driver/src/infra/solver/dto/auction.rs
crates/driver/src/tests/cases/settle.rs
crates/driver/src/tests/setup/driver.rs
crates/driver/src/tests/setup/solver.rs

With https://github.com/cowprotocol/services/pull/2961, we made sure only Limit orders are sent to driver for solving. For quoting, driver still uses Market orders, and removing this is captured with https://github.com/cowprotocol/services/issues/2543, and resolving this would allow us to completely remove `class` type in driver.
But for now, I think we don't use Liquidity type for anything. Liquidity orders are not part of the Auction, so solvers also cant refer to them in their solutions, so I think removing them is not even a breaking change. 
Still checking if we want to remove them from the solvers API as well. edit: went down a rabit hole of removing from solvers API and since the code change is huge, will do it in a separate PR.
Would allow for cleaner implementation of …

Remove Liquidity orders from Driver

---

crates/solvers-dto/src/auction.rs
crates/solvers/openapi.yml
crates/solvers/src/api/routes/solve/dto/auction.rs
crates/solvers/src/boundary/naive.rs
crates/solvers/src/domain/order.rs
crates/solvers/src/domain/solver/baseline.rs
crates/solvers/src/tests/naive/swap_less_than_reserves.rs

A follow up for https://github.com/cowprotocol/services/pull/3058
Removes Liquidity order type from solvers API.
Solvers PR: https://github.com/gnosis/solvers/pull/77

Remove Liquidity order type from Solvers

---

crates/autopilot/src/run.rs
crates/observe/src/panic_hook.rs
crates/observe/src/tracing.rs

Rust 1.82 was released and caused 2 warnings:
* `PanicInfo` was deprecated in favour of `PanicHookInfo`
* code after function returning `!` is now marked as unreachable

[TRIVIAL] Fix Rust 1.82 warnings

---

crates/autopilot/src/infra/solvers/dto/solve.rs
crates/autopilot/src/shadow.rs
crates/driver/openapi.yml
crates/driver/src/infra/api/routes/solve/dto/solved.rs
crates/driver/src/tests/setup/mod.rs

Related to https://github.com/cowprotocol/services/issues/3064
This PR enables driver to send either string or integer for `solution_id`. 
This PR marks the start of transition period. Once the PR is merged, external solvers will be asked to:
1. Start sending `solution_id` as integer in `/solve` response.
2. Implement receiving either string or integer for `solution_id` on `/reveal` and on `/settle`.
Once done, backend will have a [follow up](https://github.com/cowprotocol/services/issues/3072) where we will definitely switch to using integers in all three endpoints and https://github.com/cowprotocol/services/issues/3064 will be fixed.
Manually checked that both versions are properly serialized/deserialized.

Solution_id is integer

---

crates/autopilot/src/run_loop.rs
crates/autopilot/src/shadow.rs
crates/e2e/src/setup/colocation.rs
crates/e2e/src/setup/services.rs
crates/e2e/tests/e2e/buffers.rs
crates/e2e/tests/e2e/cow_amm.rs
crates/e2e/tests/e2e/jit_orders.rs
crates/e2e/tests/e2e/limit_orders.rs
crates/e2e/tests/e2e/liquidity.rs
crates/e2e/tests/e2e/order_cancellation.rs
crates/e2e/tests/e2e/solver_competition.rs

Implements e2e test for multiple winners per auction feature.
Verifies that:
1. Two winners are selected
2. Winning solutions trade disjoint tokens
3. Two `/settle` calls are sent and two transactions are mined.
4. Two settlements are indexed and dependent data is properly saved to database.
Added test.

Multiple winners e2e test

---

crates/autopilot/src/run_loop.rs

In a discussion with the solver team, several different algorithms were proposed to pick winners.
https://www.notion.so/cownation/Rewards-for-multiple-winners-1218da5f04ca80f2a59ed8f0174b3a69?pvs=4#1228da5f04ca8050ac31e965b120709d
> We choose winners iteratively:
> 
> 1. Choose solutions with largest score from remaining solutions as next winner.
> 2. Choose largest score of solutions with overlap to winner as reference score. The reward is winning score - reference score, the penalty is reference score.
> 3. Remove all remaining solutions which have token pairs in common with the winner. Whenever a solution is filtered in this procedure, additionally use all token pairs of that filtered solution for filtering remaining solutions. 
> 4. Repeat.
Currently, the best option is "second price …

Update winners picking logic

---

crates/autopilot/src/maintenance.rs
crates/autopilot/src/run_loop.rs

Currently restarts on arbitrum are slow enough to cause emergency alerts. The reason is that we still don't persist indexed cow amms so we re-index everything from scratch. As a workaround until we store cow amms in the DB which makes syncing to the tip very fast after a restart I moved the cow amm indexing into a background task that will not block starting new auctions.
The effect is that as we continue to index cow amms after a restart more and more cow amms will show up in the auction.
CI and test on staging to see that restarts are fast again and cow amms eventually show up

Index cow amms in background task

---

crates/driver/example.toml
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/solver/mod.rs
crates/driver/src/util/http.rs

Since October 6th we see alerts like `Failed to buffer the request body: length limit exceeded` indicating that the response returned by multiple solvers (`oneinch`, `zeroex`, `paraswap`, `balancer`) is too big for the driver.
It's unclear why this suddenly started happening on a Sunday where nothing gets released or why it only seems to affect dex solvers but making the max response size configurable seems like a reasonable thing to do regardless.
* Made drivers response size limit configurable and increased the default value by 3x.
* Added trace log to print responses that exceed the limit to easily debug this the next time this happens (disabled by default but be temporarily enabled without restarting the pod)
e2e test covers parsing of the new config parameter

[EASY] Bump response size limit

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/run.rs
crates/autopilot/src/run_loop.rs

Fixes https://github.com/cowprotocol/services/issues/3063
With full colocation, we need to have a limit on the number of solutions a solver can propose per auction.

Limit number of accepted proposed solutions

---

crates/driver/src/domain/competition/mod.rs

The majority of solutions that get discarded due to failing encoding/simulating/scoring are actually merged solutions. These solutions get merged by the driver and not by the solver. The driver does it naively so it's not really surprising that it tries to merge solutions which are incompatible (e.g. they could use the same liquidity source).
To avoid alerting on false positives the solver has no control over we now only report solutions that come directly from the solver in a non-working state (i.e. only 1 sub-solution contained).

[EASY] Don't report encoding errors for merged solutions

---

Cargo.lock
Cargo.toml
crates/alerter/Cargo.toml
crates/alerter/src/main.rs
crates/autopilot/Cargo.toml
crates/autopilot/src/main.rs
crates/driver/Cargo.toml
crates/driver/src/main.rs
crates/orderbook/Cargo.toml
crates/orderbook/src/main.rs
crates/refunder/Cargo.toml
crates/refunder/src/main.rs
crates/solvers/Cargo.toml
crates/solvers/src/main.rs

I looked more into the supposed memory leak and noticed that the system allocator requires unreasonable amounts of memory compared to [mimalloc](https://www.google.com/search?client=firefox-b-d&q=mimalloc+github) so I replaced it for all the binaries.
Here we can see the memory footprint of the api pod with `mimalloc` (green) and the system allocator (yellow). The served traffic is the same but the system allocator continues to require more and more memory - probably because it's worse at dealing with memory fragmentation than `mimalloc`.

Replace system allocator with mimalloc

---

crates/autopilot/src/database/onchain_order_events.rs
crates/orderbook/src/api/post_order.rs
crates/shared/src/order_validation.rs

A fix on top of the https://github.com/cowprotocol/services/pull/3096 for easier reviewing.
We want to always compute the fresh quote when provided quote_id is not found in database. This is now enabled for all orders, not just for ETHFlow orders.
A bit more context can be found https://github.com/cowprotocol/services/pull/3096#issuecomment-2446885623
Existing tests updated.

Always compute fresh quote when not found

---

crates/autopilot/src/database/auction.rs
crates/autopilot/src/database/onchain_order_events.rs
crates/database/src/quotes.rs
crates/e2e/src/setup/onchain_components.rs
crates/e2e/tests/e2e/protocol_fee.rs
crates/e2e/tests/e2e/solver_competition.rs
crates/orderbook/src/api/post_order.rs
crates/orderbook/src/database/quotes.rs
crates/shared/src/order_quoting.rs
crates/shared/src/order_validation.rs

This reverts commit cea22f679c68eac1cfe8649bc3c8f2ea7c9aed98.
Then implements https://github.com/cowprotocol/services/pull/3100
Reverts the change introduced by the PR https://github.com/cowprotocol/services/pull/3054
Apparently the current implementation is not good at recovering the right quote as it sometimes finds the quote that is too old, while the order was intended to be created with the most recent quote.
A different fix is implemented to actually continue using quote_id, but compute the fresh quote if quote_id cant be found.

Revert "Use quote id just for debugging (#3054)"

---

crates/shared/src/price_estimation/competition/native.rs
crates/shared/src/price_estimation/native.rs

Currently some solvers are reporting nonsensical results for native prices.
Changes the native price competition to ignore subnormal values (e.g. infinities, and undefined byte patterns) and non-positive values. This still leaves plenty of room for incorrect values but at least the obviously wrong values get eliminated by that.
added a unit test

Ignore nonsensical native prices

---

Cargo.lock
crates/model/Cargo.toml
crates/model/src/auction.rs
crates/model/src/order.rs
crates/model/src/quote.rs
crates/model/src/ratio_as_decimal.rs
crates/model/src/signature.rs
crates/model/src/solver_competition.rs
crates/model/src/trade.rs
crates/shared/src/lib.rs
crates/shared/src/sources/uniswap_v3/pool_fetching.rs
crates/shared/src/tenderly_api.rs
crates/testlib/Cargo.toml
crates/testlib/src/json_matching.rs
crates/testlib/src/lib.rs

Moves `shared::test_utils` into `testlib::json_matching` to reduce the scope of the `shared` crate.

Move JSON asserts into `testlib`

---

crates/autopilot/src/run_loop.rs

In order to improve our settlement throughput alerting I'd like to plot the number of orders we settle per minute over time (to be able to compare it with the "matched but unsettled" ones.
I don't think there is a way to get this information from the existing autopilot metrics so adding this counter to the `settle_ok` call.
See new metrics exposed in prometheus logs

[Easy] Settled order count metric

---

crates/driver/openapi.yml

PR #3113 added new field to /reveal and /settle requests but `openapi.yml` file wasn't updated. This PR adds missing field definition to `openapi.yml` file.

[TRIVIAL] Updated `driver` OpenApi after PR #3113 

---

crates/autopilot/src/run_loop.rs

2 colocated solvers reported that `/settle` requests were sent after the deadline. The expected behaviour is that on each new block a new auction is cut. So for each new settlement the deadline should be the `auction.block + settlement_deadline`. It turned out that this is not the case and after the auction cut, the deadline is calculated as `current_block + settlement_deadline`. E.g(deadline config is `3`):
- Auction cut at block 10 in the end of the round.
- New block 11 is mined.
- Only then the deadline is calculated as 11+3=14.
- The next auction is being cut at block 11 and the deadline for the next settlement is also 11+3=14.
- The first settlement gets executed in the end of the block 13 round.
- A new block 14 gets mined and the next settle call is sent after the deadline.
This …

Do not settle after the deadline

---

crates/shared/src/arguments.rs

The config is not used. The following one should be used instead:
https://github.com/cowprotocol/services/blob/11df525171919ea584f6d1e36be92c35bb72ed3e/crates/driver/src/infra/config/file/mod.rs#L523-L571
Requires https://github.com/cowprotocol/infrastructure/pull/2250 to be merged first.

[TRIVIAL] Drop unused Balancer pool deny list config

---

crates/autopilot/src/domain/fee/mod.rs
crates/autopilot/src/domain/fee/policy.rs
crates/autopilot/src/infra/persistence/dto/auction.rs
crates/autopilot/src/infra/persistence/dto/order.rs
crates/autopilot/src/infra/shadow/orderbook/mod.rs
crates/driver/src/infra/solver/dto/auction.rs

During some debugging sessions, it was noticed that having implicit conversions overcomplicate code navigations. The proposal is to use explicit `from/into_domain` functions for general types.
The PR touches only Auction and FeePolicy structs at the moment. But once bumped into the same issue with any other struct, a follow-up should be opened.

Reduce Try/TryFrom implementations for general types

---

crates/app-data/src/app_data.rs
crates/autopilot/src/infra/solvers/dto/solve.rs
crates/chain/src/lib.rs
crates/driver/src/tests/setup/mod.rs
crates/driver/src/util/serialize/hex.rs
crates/driver/src/util/serialize/u256.rs
crates/model/src/order.rs
crates/model/src/quote.rs
crates/model/src/signature.rs
crates/number/src/serialization.rs
crates/shared/src/baseline_solver.rs
crates/shared/src/lib.rs
crates/shared/src/price_estimation/native_price_cache.rs
crates/shared/src/trade_finding/mod.rs
crates/solver/src/liquidity/slippage.rs
crates/solvers-dto/src/lib.rs

Fixes the code to satisfy `clippy`.
Some Derivative annotations were replaced with custom implementation due to the following weird error, which I couldn't mute even with `#[allow(clippy::needless_lifetimes)]`.
```
53 | #[derive(Clone, PartialEq, Eq, Hash, Default, Serialize, Derivative)]
|                                                          ^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
= note: `-D clippy::needless-lifetimes` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::needless_lifetimes)]`
= note: this error originates in the derive macro `Derivative` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Align with the updated Rust

---

crates/e2e/tests/e2e/limit_orders.rs
crates/e2e/tests/e2e/replace_order.rs

Fixes flaky e2e test by starting autopilot only once all the orders are created. Locally, these failures are almost impossible to reproduce since all the orders, in most cases, belong to a single auction, while this is not the case on CI.

Fix flaky e2e test

---

crates/driver/openapi.yml
crates/orderbook/openapi.yml
crates/solvers/openapi.yml

Formats all the OpenAPI yaml.
`openapi-cli` was used at first to automatically address most of the critical issue. Then `prettier`, just to format the yaml. In the future, `prettier` should be enough.

OpenAPI yaml files formatting

---

.github/workflows/pull-request.yaml
.spectral.yaml
crates/driver/openapi.yml
crates/orderbook/openapi.yml
crates/solvers/openapi.yml

Adds the `spectral` linter. `prettier` should be used as formatter.
The formatter is applied in https://github.com/cowprotocol/services/pull/3144.
~~`@redocly/openapi-cli` is chosen because it provides both a linter and a built-in formatter while other linters suggest using `prettier`, which provides less robust option compared to the `openapi-cli`.~~ Since the tool is depricated, switched to `spectral` + `prettier`.
Fixes #2971

OpenAPI formatting linter

---

crates/shared/src/price_estimation/trade_verifier.rs
crates/shared/src/price_estimation/trade_verifier/balance_overrides.rs

This PR is the first in a stack to add a system for overriding balances so that more quotes can be verified.
One limitation with the current quote verification system, is that it requires that the `from` account in the quote has the sell token balance available (or available after a pre-hook is executed) in order for the quote to be properly verified. This isn't always possible for all flows (and notably flows at Safe, where transactions to prepare the balance happens at the same time as the `setPreSignature` transaction executes, so after the quote).
The overall solution I would propose (hopefully a pragmatic one that isn't considered _too_ hacky) would be enable special handling for the most commonly traded tokens, by configuring for each token how the storage slot is computed for the …

Introduce Component for Balance Overrides

---

crates/e2e/tests/e2e/quote_verification.rs
crates/shared/src/price_estimation/trade_verifier.rs

@nlordell's recent PR stack enabled the use case where a real trader (wallet is connected in the frontend) does not have the required balances by faking balances.
But with the new ability to fake balances for many tokens we can even go one step further.
If we know how to fake balances for the given sell token AND no wallet is connected (i.e. `verification.from.is_zero()`) we simply generate a random address and use that as the trader with fake balances.
Using a non-zero address is important because many token transfer functions don't like sending tokens to or from the zero address.
This should prevent the annoying UX where you sometime see a really good (unverified) price when your wallet is not connected and end up seeing worse (but verified) prices after you connect your wallet.
added …

Verify quotes from zero address

---

crates/driver/src/infra/api/routes/mod.rs
crates/driver/src/infra/api/routes/reveal/dto/solution.rs
crates/driver/src/infra/api/routes/settle/dto/solution.rs

A follow up for https://github.com/cowprotocol/services/pull/3071
This PR allows reference driver to receive both integer and strings for solution id, on `/reveal` and `/settle` endpoints. Note how this PR implements task 2 from the [linked pull request](https://github.com/cowprotocol/services/pull/3071). This is done in this PR as a separate step to give time to colocated solvers using reference driver to update on time.
If we were to just switch to using integer, colocated drivers would incur downtime.
Next step is final step to use integer ONLY in both autopilot and driver, once we made sure all colocated solvers updated their driver.
The code is copy paste of already tested code.

Reveal and settle to receive integer solution id

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/domain/fee/mod.rs
crates/autopilot/src/run.rs
crates/e2e/tests/e2e/limit_orders.rs
crates/e2e/tests/e2e/protocol_fee.rs

This config was added for one purpose only - to coordinate with accounting team when and how to turn on the feature - reference https://github.com/cowprotocol/services/pull/2595#pullrequestreview-2001563041
Since battled tested, this can be removed now.
Will create the PR for infrastructure as well. Edit: https://github.com/cowprotocol/infrastructure/pull/2394
e2e tests

[TRIVIAL] Remove enable_multiple_fees config

---

crates/driver/src/domain/mempools.rs

ATM, it is not possible to understand whether a settlement cancellation tx succeeded. This PR adds logs with the cancellation tx hash, so it will be possible to check the transaction on chain later. Also, additional context is added when working with the cancellation tx submission since, currently, it is impossible to distinguish between the actual settlement tx submission error.

[EASY] Improve settlement tx cancellation logging

---

crates/orderbook/openapi.yml

We forgot to add `base` to the openapi spec so it doesn't show up in the network selection tab as reported by a user.
adds the 2 new URLs to the openapi spec

[EASY] Add base url to open api

---

crates/database/src/solver_competition.rs

Fixes a bug where transaction hashes from different environment (prod/staging) are shown on solver competition endpoint.
Example: https://api.cow.fi/mainnet/api/v1/solver_competition/9861815
Here, transaction `0xb608f1e2a644befda65a6a87ce6b93fc8a3441d9729b8ce4b2a2db02c1247e60` is from production enviroment and valid one, while `0xc85cd0ad8e3aac389836a71da9795bdd1bedce7b21da1950b48f93165c9f6be8` is from staging environment and mistakenly added to result.
The reason why this happens is:
1. The solver competition with the same `auction_id` can be saved in both environments, regardless if the competition ended up with mined settlement (which is fine).
2. `settlement::Observer` saves the relationship <auction, settlement> even for settlements from another environment (this is a decision made …

Fix solver competition reading

---

crates/database/src/jit_orders.rs
crates/database/src/orders.rs

Fixes failing of queries when orders with multiple order executions are queried from database.
Introduced in https://github.com/cowprotocol/services/pull/2966
trust me bro
will be tested on staging since all staging pods are down

Limit subquery results to 1

---

crates/driver/src/domain/competition/bad_tokens/simulation.rs

Currently, it is impossible to understand which exactly of the order's tokens was considered `bad` when it's quality is taken from the cache. Once this log is added, it will be possible search for bad token detection logs using either sell or buy token address.

[TRIVIAL] Log bad token address

---

.github/workflows/pull-request.yaml
crates/e2e/tests/e2e/replace_order.rs

Fixes the `local_node_replace_order` e2e test. Currently, the whole protocol stack is getting started in the beginning. After creating a first order and before sending a replacement one, a new block is minted, which starts the auction preparation mechanism. Sometimes, the auction gets prepared before the replacement order is placed, making the test fail. This PR removes this redundant block mining request.
A test run of the change: https://github.com/cowprotocol/services/actions/runs/12502462800?pr=3183 (failed due to the GH action execution timeout; all the tests passed).

Fix a flaky e2e test

---

crates/driver/src/domain/competition/bad_tokens/simulation.rs

The new bad token detection in the driver identified some sell tokens as unsupported although they are perfectly fine 
([example order](https://barn.explorer.cow.fi/orders/0x2e8eccaad6313a1a2282bed349331a580319854ae9f448aa7290cf5c42ce4d6e9fa3c00a92ec5f96b1ad2527ab41b3932efeda5869442680?tab=overview))
The reason is probably that the test transfer the bad token detection currently always uses the order's full signed sell amount. This will fail if the user created a partially fillable order where the sell amount exceeds their current balance.
Adjusted the test transfer to only transfer the `order.partial.available` amount (when applicable). This value takes partial fills of the given order and the user's current balance into account.

Bad token detection: only transfer as much as is available

---

.github/workflows/pull-request.yaml

It seems like running the driver tests in a single-thread mode fixes the issue with accidentally stuck tests(https://github.com/cowprotocol/services/actions/runs/11141574437/job/30962723813). During a couple of runs using the flaky runner job, not a single driver test failed. The only disadvantage is that these tests execute now 5m instead of 2m.

Fix driver tests flakiness

---

.github/workflows/pull-request.yaml

In order to avoid confusion when forked-node tests fail on external contributor PRs due to the absence of access to some secrets, let's avoid running this job on forked repos.

[TRIVIAL] Do not run forked-node tests for external contributions

---

crates/driver/src/domain/competition/bad_tokens/metrics.rs
crates/driver/src/infra/api/mod.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/solver/mod.rs

The metrics based bad token detection has not been tested with real data yet so actively filtering out tokens based on it is pretty risky. If the logic is too naive or simply has a bug we might filter out a bunch of tokens which are actually good which could reduce the throughput of the system drastically.
To increase the confidence in the system this PR introduces a log only mode for the metrics based bad token detection.
In that mode no tokens will be filtered out based on the metrics but we already get logs indicating this tokens would get filtered out by it.
When we start running this mode in prod we should hopefully see 2 things:
1 good tokens don't get filtered out
2 tokens which currently cause alerts like `Driver Run Error Rate Too High` should be flagged by the logic
`2` would …

Add log-only mode for metrics based bad token detection

---

crates/driver/src/domain/competition/bad_tokens/metrics.rs
crates/driver/src/domain/competition/bad_tokens/mod.rs
crates/driver/src/infra/api/mod.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/solver/mod.rs

Currently the bad token detection based on metrics will mark tokens as unsupported forever. This is problematic for tokens which only have issues temporarily. For example this can happen when the most important pool for a token gets into a weird state or when a token gets paused or a while.
Adjusts the logic to freeze tokens for a configurable period of time. Once the freeze period is over we give the token another chance (even if the stats indicate that it's currently unsupported). To not run into issues when a token is always bad the logic was built such that 1 more `bad` measurement is enough to freeze the token again.
That way we can safely configure a very high `min_measurements` without having periods where a token that was flagged as bad can issues again because we need to get a …

only mark tokens as unsupported based on metrics for a limited time

---

crates/driver/src/domain/competition/bad_tokens/cache.rs
crates/driver/src/domain/competition/bad_tokens/metrics.rs
crates/driver/src/domain/competition/bad_tokens/mod.rs
crates/driver/src/domain/competition/bad_tokens/simulation.rs

Sparked by this [discussion](https://github.com/cowprotocol/services/pull/3205#discussion_r1901647654) I think that using `Option<Quality>` is a bit implicit.
I adjusted the bad token detection code to use `Quality::Unknown` where possible to make it more explicit what the strategy thinks about a token.
This makes some of the code more verbose so I'm not super sold on this change yet. Let me know if you think this improves things.

Introduce Quality::Unknown variant

---

crates/driver/src/domain/mempools.rs
crates/driver/src/infra/notify/mod.rs
crates/driver/src/infra/observe/mod.rs

Add block number to mempool_executed logs, so we can simulate failed submissions in order to debug the reason of the failure.

Add block number to mempool_executed logs

---

.github/workflows/pull-request.yaml

After https://github.com/cowprotocol/services/pull/3201, the forked-node tests are no longer triggered on the `main` branch since the filter is configured for pull requests only. This PR fixes this.

[TRIVIAL] Run forked-node tests on main

---

crates/autopilot/src/infra/solvers/dto/reveal.rs
crates/autopilot/src/infra/solvers/dto/settle.rs
crates/autopilot/src/run_loop.rs
crates/autopilot/src/shadow.rs
crates/driver/src/domain/competition/mod.rs
crates/driver/src/infra/api/routes/reveal/dto/reveal_request.rs
crates/driver/src/infra/api/routes/reveal/mod.rs
crates/driver/src/infra/api/routes/settle/dto/settle_request.rs
crates/driver/src/infra/api/routes/settle/mod.rs

This is a continuation of the previous PR #3131 which added `auction_id` field as optional on the driver `/settle` and `/reveal` requests. Because this is API breaking change we had to wait for Solvers teams to updated their driver version, so they will support new `auction_id` field. 
Current PR changes `auction_id` field from optional to mandatory and starts sending it from the autopilot.
This is mainly port of PR #3113 which introduced API break (and was reverted with PR #3131) on to the current main branch: updated driver and autopilot DTOs, added code to use these new fields and added additional condition on driver side to verify if provided `solution_id` is competing in provided `auction_id`.
OpenAPI definition is already up to date.
Existing tests, esp. …

Added `auction_id` field to `/settle` and `/reveal` driver requests.

---

crates/driver/src/infra/blockchain/mod.rs

While this PR would give us revert detection reproducible with tenderly it also leads to an overly optimistic revert protection. Meaning on average future reverts get detected too late which would result in solvers losing a lot of money.
This was noticed by an external solver running the original PR in production and seeing their rewards vanish due to increased reverts.
See this [thread](https://cowservices.slack.com/archives/C0690QX4R5X/p1736368423899369?thread_ts=1736279159.869429&cid=C0690QX4R5X) for reference.

Revert executing `eth_estimateGas` and `eth_createAccessList` on the latest block

---

crates/autopilot/src/database/onchain_order_events/mod.rs
crates/shared/src/sources/balancer_v2/swap/fixed_point/logexpmath.rs

Fixes compilation on the latest stable rust version.

Support rust 1.84.0

---

crates/driver/src/domain/competition/bad_tokens/metrics.rs
crates/driver/src/domain/competition/bad_tokens/simulation.rs
crates/driver/src/infra/api/mod.rs
crates/driver/src/infra/observe/metrics.rs
crates/driver/src/infra/observe/mod.rs
crates/driver/src/run.rs

Adds Prometheus metrics for driver's bad token detector strategies, so it will be possible to show how many tokens were marked as `bad` by each solver and strategy. It would be helpful to identify solvers that perform as not expected and to analyze the work of each detection strategy individually.
Create 2 grafana panels: the one that shows detected tokens by solver and another - by strategy.
Added `hotfix` label to deploy it asap.

Bad token detector metrics

---

.github/workflows/hotfix.yml

There was a typo in the GH token name.

[TRIVIAL] Hotfix GH job typo fix

---

.github/nitpicks.yml

https://github.com/cowprotocol/services/pull/3223 caused breaking the SAFE client even though they did not actually use the field.
In the future, all API changes (without exception) need to be communicated with
1. Frontend team
2. Safe team

[TRIVIAL] Adjust message for breaking API changes

---

crates/app-data/src/app_data.rs
crates/e2e/tests/e2e/app_data.rs

Fixes: https://github.com/cowprotocol/services/issues/3214
Extend appdata format with `flashloan` field explained in the linked issue.
added an e2e test that shows it's now possible to create an order that contains flashloan hints in the appdata.

Flashloan appdata

---

crates/orderbook/src/api/get_trades.rs

The API expects camelCase query parameters and parses them into snake_case Rust identifiers. Therefor  the `API` actually expects the query parameter `orderUid` and not `order_uid` which should be reflected in the error message.
Updated error message to be correct from the perspective of the API consumer not the backend internals.
The error message also now uses `or` instead of `and` to more strongly indicate that only 1 parameter is expected. This was not obvious when a user provided the arguments `order_uid` and `owner` and was surprised that the request returned results for different orders.

[TRIVIAL] Fix API error message

---

crates/autopilot/src/infra/solvers/mod.rs
crates/autopilot/src/run_loop.rs
crates/driver/src/domain/competition/mod.rs
crates/driver/src/infra/api/mod.rs
crates/driver/src/infra/api/routes/settle/mod.rs
crates/driver/src/infra/solver/mod.rs
crates/e2e/src/setup/solver/mock.rs
crates/ethrpc/src/buffered.rs
crates/ethrpc/src/http.rs
crates/observe/src/request_id.rs
crates/observe/src/tracing.rs
crates/orderbook/src/run.rs
crates/shared/src/trade_finding/external.rs
crates/shared/src/zeroex_api.rs
crates/solvers/src/api/mod.rs

Alternative to https://github.com/cowprotocol/services/pull/3247
All of the context still applies to this PR.
But instead of looking up the request id from the task local storage we are now able to look it up from the tracing span.
When I introduced the request id feature I already wanted to have it work this way but I was not able to get it working.
Finally after some more research I figured out that this can be accomplished by implementing a custom tracing layer which makes the request id available for lookup later on.
Now the request id is easily available wherever a the current span or any of it's parents contains the request id.
This means we no longer have to worry about 2 different ways of making important data available when spawning a new task.
* reworked request_id handling to …

Request tracing without task local storage

---

.github/workflows/playground-check.yaml
playground/docker-compose.fork.yml

It was noticed by @ahhda that the test playground CI job [started to fail constantly](https://github.com/cowprotocol/services/actions/runs/12898722916). Seems like one of the nightly [foundry-rs releases](https://github.com/foundry-rs/foundry/releases) was the main reason for this. Even though the [stable](https://github.com/foundry-rs/foundry/releases/tag/stable) release is marked as `latest`, according to the logs, a dev version of `anvil` was used.
https://github.com/cowprotocol/services/actions/runs/13018157686?pr=3254

Use foundry stable version in the playground docker image

---

crates/driver/src/domain/competition/auction.rs

The auction preprocessing job runs only once for each auction, which is achieved by using a mutex where other threads wait until the running job is completed. The `total` metric was placed incorrectly outside the lock, accumulating a lot of useless information where the preprocessing is already done, and other threads just read the value. This PR fixes it by only populating the metric when the async job is really executed.

Driver's auction preprocessing `total` metric fix

---

crates/autopilot/src/run_loop.rs

Fixes: #3264
Not only filters out in-flight orders from the auction but also `surplus_capturing_jit_order_owners` (i.e. cow amms) to help solvers avoid reverts caused by multiple different solvers trying to rebalance the same pool right after each other.
Luckily the `OrderUid` already contains the order owner so we only need to adjust the filtering logic.

Filter in-flight cow-amms

---

Cargo.lock

https://rustsec.org/advisories/RUSTSEC-2025-0004
Also updated yanked crates `bytes` and `futures-util`.

Fix crate vulnerabilities

---

crates/autopilot/src/database/mod.rs
crates/database/Cargo.toml
crates/database/src/lib.rs

This reverts commit 070ae356ef59471aaee012e813196c98f0c1732a.
Revert his commit as it makes slow the update of the metric

Revert "[EASY] Update used DB tables list (#3266)"

---

crates/autopilot/src/infra/blockchain/mod.rs
crates/autopilot/src/run.rs

Since Alchemy is used as one of the failover providers and it doesn't support buffered debug RPC API, it is important to use unbuffered transport when sending `debug_traceTransaction` calls. Otherwise, this leads to failed RPC calls.
The easiest workaround is to use 2 separate transports for different purposes. The current approach is not really flexible since it is not configurable, but in order to keep it simple, this should be acceptable.

Use unbuffered transport for the Debug RPC API

---

crates/autopilot/src/run_loop.rs

Add "timeout" to the settle metric. This allows us to differentiate when the error is caused by the driver not submitting the TX on time (submission deadline).
This allows us to have better metrics and filter it by the reason.

autopilot: Add "timeout" to the settle metric

---

.github/workflows/playground-check.yaml
playground/Dockerfile.chain
playground/Dockerfile.cowswap
playground/docker-compose.fork.yml

`playground-chain-1` container health check was failing due to lack of `wget` in Foundry image.
[Link](https://github.com/cowprotocol/services/actions/runs/13445138497) to the successful job with this PR fixes.
- Added new `Dockerfile.chain` file which installs `wget` in the Foundry image. On 13.02.2025 Foundry changed `stable` tag on their image ([link](https://github.com/foundry-rs/foundry/pkgs/container/foundry/355379131?tag=stable)) to image without `wget` which is used in the healthcheck script. From that time our `playground-check` job started to fail.
- Added storing of healthcheck logs in artifacts in case of job failure for easier issue analysis.
- Disable use of NX Cloud cache for cowswap dockerfile build (`yarn build` command), as there are errors in the job log and local build …

Fixed playground check job

---

crates/autopilot/src/domain/competition/participation_guard/db.rs

The metric wasn't incremented, so the graph is not working properly atm.

[TRIVIAL] Fix banned solvers metric

---

crates/autopilot/src/domain/competition/participation_guard/db.rs

Currently, the log produces a lot of noise and should not be printed on the empty collection.

[TRIVIAL] Do not log on the found misbehaving solvers empty collection

---

crates/database/src/solver_competition.rs

In one of the previous PRs, I removed the ordering which actually broke the logic.
https://github.com/cowprotocol/services/pull/3263#discussion_r1967467775
I actually can't remember why I decided to do so...

DB-based solver participation guard query fix

---

crates/autopilot/src/arguments.rs
crates/e2e/src/setup/services.rs

Switches to camel-case since it is already used in most of the cases.

[TRIVIAL] `requested-timeout-on-problems` config camel-case

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/domain/competition/participation_guard/db.rs
crates/autopilot/src/infra/persistence/mod.rs
crates/database/src/solver_competition.rs

Currently, the db-statistics-based solver participation guard might ban a solver that won only 1 or 2 times in the last 100 auctions and failed to settle them. This is a very sensitive threshold, where the suggestion is to start considering the solver as low-settling that won at least 3 auctions among 100 latest. The value is configurable and currently equals the non-settling guard default config.

[EASY] Min won auctions participation guard threshold

---

crates/contracts/build.rs

By now there are official uniswap v2 deployments. Adding these addresses here should allow us to use the `uniswap-v2` preset for liquidity indexing on sepolia in the driver.
Addresses copied from [here](https://docs.uniswap.org/contracts/v2/reference/smart-contracts/v2-deployments) and already tested in staging.

[TRIVIAL] Add univ2 contract addresses for sepolia

---

crates/driver/src/infra/config/file/mod.rs
crates/e2e/src/setup/colocation.rs

Config indeed had to be changed to be properly parsed (As Ilya already pointed out in [previous PR](https://github.com/cowprotocol/services/pull/3316).
Added gas estimator config into e2e setup, so you can try out with "native" as well.

Fix driver gas estimator config reading

---

crates/database/src/solver_competition.rs
crates/e2e/tests/e2e/replace_order.rs
crates/orderbook/openapi.yml
crates/orderbook/src/api/post_order.rs
crates/orderbook/src/arguments.rs
crates/orderbook/src/database/solver_competition.rs
crates/orderbook/src/orderbook.rs
crates/orderbook/src/run.rs
crates/orderbook/src/solver_competition.rs

We want to allow users to "edit" orders, implemented by canceling a previous order when creating a new one. We have a `replacedOrder` property for this.
One concern is that this could lead to double spending when the old order is part of the current auction and the winning solver intends to settle it.
The goal of this PR is to mitigate this issue as much as possible by checking whether any solver has bid on the original order in the last few auctions. The POST `/orders` method now returns a `400 Bad Request` in that case.
A follow-up PR can extend this logic to the cancellation endpoint. In this case, instead of rejecting the cancellation outright, we may prefer to return a warning message instead.
- Added a new database operation `load_latest_competitions` to fetch all the competitions …

Return error on order replacement when it's not safe

---

crates/orderbook/openapi.yml

Since we switched to dynamically computed fees and enforcing a signed `fee` amount of 0 the order's fee fields got quite confusing.
Updated openapi docs to explain the fields better.

Update information about fee fields in openapi docs

---

crates/driver/src/domain/eth/mod.rs
crates/driver/src/domain/mempools.rs
crates/driver/src/infra/blockchain/mod.rs
crates/driver/src/infra/observe/metrics.rs
crates/driver/src/infra/observe/mod.rs

New metric that saves the number of blocks passed between the first submission attempt and the block at which the error is detected.
This metric should tell us more whether the error is caused by MEVBlocker being down and not processing transactions (in this case we would expect high value for blocks passed) or it's caused by high price volatility which should result in revert in one or two blocks just after the submission started (in most cases).

Save blocks passed since first submission attempt

---

Cargo.lock
crates/app-data/src/app_data.rs
crates/autopilot/Cargo.toml
crates/autopilot/src/domain/fee/mod.rs

Add support for multiple partner fees.
- Support for multiple partner fees
- Backwards compatibility
- The partner fees are squashed into one partner fee, so it is easier to apply the max cap
1. Unit tests
NOTE: Because of the partner fees being squashed into one and abstracting that to a single function for better unit testing, I saw no benefit of adding an e2e to it, but I am open to it if you see it fit.

Add support for multiple partner fees

---

crates/driver/src/infra/blockchain/contracts.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/solver/dto/auction.rs
crates/driver/src/infra/solver/mod.rs
crates/driver/src/tests/setup/solver.rs

Addresses https://github.com/cowprotocol/services/pull/3330#pullrequestreview-2697722134 by fetching the default lender from `contracts` driver config.
@squadgazzz would you prefer it this way, so that the default lender is always implicit -> first lender in the list of <lender, wrapper> pairs.

Fix default lender - improvement

---

crates/driver/src/infra/blockchain/contracts.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/solver/dto/auction.rs
crates/driver/src/infra/solver/mod.rs
crates/driver/src/tests/setup/solver.rs

This PR makes the driver configuration for flashloans more production-ready.
Using MAKER(SKY) address as hardcoded default lender doesn't make sense anymore, because SKY only lends DAI token. If, instead, we wanted to replace it with AAVE or some other lender that lends all sorts of tokens, then it means this lender has to be deployed on all networks we support.
With that, it makes most sense to not have a hardcoded default lender and just define it in the infra, which should avoid weird bugs.

Fix flashloan default lender

---

crates/orderbook/src/api/post_order.rs
crates/orderbook/src/orderbook.rs
crates/shared/src/order_validation.rs

As a first step to improve the quote competition visualization for a specific order, this PR updates the order creation log by including the selected quote solver address, which eliminates the redundant step of searching for this data in either logs or db. If the initiative gets approved, this can be improved by logging the solver's name. However, this would require additional work to build a mapping between the solver's address and its name.
Observe the logs.

[EASY] Log order quote's solver

---

crates/orderbook/src/api/get_order_status.rs
crates/orderbook/src/orderbook.rs

Right now we return internal error when the solver competition was not found.
Return `NOT_FOUND` (404) error instead of internal error (500) when there solver competition was not found for the given order.
1. Regression test
The change is fairly simple, I assume adding an e2e test for this is a little bit of an overkill, but I am open to the idea too.

orderbook: Return 404 for get order status when competition was not found

---

crates/driver/src/domain/competition/solution/encoding.rs

@mrnaveira did some manual testing of the flashloan feature on sepolia which showed a small bug in the flashloan related interactions injected into the settlement by the driver. This [simulation](https://dashboard.tenderly.co/shared/simulation/899885c7-0cb0-4cfa-ad19-1eb7208ecd61) showed that the transfer of the flashloan repayment amount from the settlement contract to the flashloan helper contract did not work because the correct approvals were set.
Instead of injecting another `approve()` transaction we can turn the `transferFrom()` into `transfer()` because the transfer happens in the context of the settlement contract and the spender is also the settlement contract.
This is more gas efficient and easier to understand.
- convert `transferFrom()` into `transfer()`
To test this change …

Fix flashloan encoding

---

crates/database/src/ethflow_orders.rs
crates/e2e/tests/e2e/refunder.rs
crates/refunder/src/arguments.rs
crates/refunder/src/lib.rs
crates/refunder/src/refund_service.rs

A few similar eth-flow orders were not automatically refunded([example](https://explorer.cow.fi/arb1/orders/0x36a494c38ad0bab7c6f73187ba39df9293d4b9342fe7fa2830d56bf54436de8c552fcecc218158fff20e505c8f3ad24f8e1dd33cffffffff)) since the price specified in the order was a bit better than the quote's, as a result, the computed slippage was negative. The config currently supports the positive values only. This PR address this by allowing specifying the negative price deviations. This PR needs to be merged together with a corresponding infra PR since the config param was renamed.
Observe logs.

ETH-flow refunder: allow negative slippage orders

---

crates/contracts/artifacts/BalancerV3BatchRouter.json
crates/contracts/build.rs
crates/contracts/src/lib.rs

In order to support balancer v3 routes in the balancer solver we need to have the rust bindings for the balancer v3 BatchRouter contract (ABI taken from [here](https://github.com/balancer/balancer-deployments/blob/e94346b727530591252e2e9924068f1e4e0a6780/v3/tasks/20241205-v3-batch-router/artifact/BatchRouter.json)). This PR adds this in the services so the `solvers` repo can import the contract via the services dependency.
- just adds the ABI file and the boiler plate code to generate the bindings

Generate bindings for balancer v3 BatchRouter

---

crates/autopilot/src/domain/eth/mod.rs
crates/autopilot/src/domain/settlement/mod.rs
crates/autopilot/src/domain/settlement/observer.rs
crates/autopilot/src/domain/settlement/transaction/mod.rs
crates/autopilot/src/infra/blockchain/mod.rs
crates/autopilot/src/infra/persistence/mod.rs
crates/database/src/settlements.rs
crates/e2e/tests/e2e/flashloans.rs
crates/ethrpc/src/extensions.rs

After a flash loan is settled, the solver address stored in database (`settlements` table) is actually the flash loan router address instead of the solver submission address.
This PR fixes it by analyzing the callstack to determine which address is actually a solver:
- We start from `tx.from` and go down to the `settle()` call.
- For each caller address we check if it corresponds to a solver (by calling `GPv2AllowListAuthentication.is_solver`).
- The actual solver that triggered the transaction will be the first authenticated address in that chain.
Then, when the Observer indexes a settlement transaction, the found address is used to overwrite the `settlement::solver` column.
Changes affect the `autopilot` crate:
- Created a `TransactionAuthenticator` trait to decouple the solver …

Fix wrong solver address saved to database on flash loans

---

crates/autopilot/src/domain/auction/mod.rs
crates/autopilot/src/infra/persistence/dto/auction.rs
crates/autopilot/src/infra/persistence/mod.rs
crates/autopilot/src/infra/solvers/dto/solve.rs
crates/autopilot/src/run_loop.rs
crates/autopilot/src/shadow.rs
crates/e2e/src/setup/services.rs
crates/orderbook/src/dto/auction.rs

Add solve deadline to the S3 auction as requested by the solver team.
- Add solve deadline to the S3 auction
- Move the deadline calculation from the request code to the cut auction code
1. Regression test

autopilot: Add solve deadline to the S3 auction

---

crates/driver/example.toml
crates/driver/src/domain/competition/auction.rs
crates/driver/src/domain/competition/mod.rs
crates/driver/src/domain/competition/solution/encoding.rs
crates/driver/src/domain/competition/solution/fee.rs
crates/driver/src/domain/competition/solution/mod.rs
crates/driver/src/domain/competition/solution/scoring.rs
crates/driver/src/domain/competition/solution/settlement.rs
crates/driver/src/domain/eth/mod.rs
crates/driver/src/domain/time.rs
crates/driver/src/infra/api/mod.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/config/mod.rs
crates/driver/src/run.rs
crates/driver/src/tests/cases/jit_orders.rs
crates/driver/src/tests/cases/protocol_fees.rs
crates/driver/src/tests/setup/driver.rs
crates/driver/src/util/conv/u256.rs
crates/e2e/src/setup/colocation.rs

Implements the necessary changes for this upcoming [CIP](https://forum.cow.fi/t/cip-draft-updating-score-definition-for-buy-orders/2930).
I also created https://github.com/cowprotocol/services/pull/3343 as a follow up PR for the same logic but on the autopilot side (eventually we should have 1 code shared across autopilot and driver).
- refactor (hopefully simplify) logic to compute scores for trades
- moved logic to multiple `U256` with a fractional `f64` into `U256Ext`
- added boilerplate to switch to the new scoring logic when the `deadline` of a `/solve` requests is past the cutover date
Added a unit test based on the order that sparked the CIP. (@harisang confirmed that the new values are correct)
Updated our e2e tests to use the new scores everywhere and verified that the new values …

New logic to compute scores of buy order trades

---

crates/autopilot/src/domain/eth/mod.rs
crates/autopilot/src/domain/settlement/mod.rs
crates/autopilot/src/domain/settlement/trade/math.rs
crates/autopilot/src/domain/settlement/trade/mod.rs
crates/autopilot/src/util/conv.rs

Follow up to #3340
Implements the same refactor to the fee and score computation but in the autopilot. Note that we currently don't make use of the `score()` function in the autopilot (except in tests) so we can immediately switch to the new scores for buy orders without worrying about breaking compatibility.
- implements new buy order score login in the autopilot
- refactors fee and score computation in autopilot to use `eth::SurplusTokenAmount` instead of `eth::Asset` wherever possible
existing tests based on actual historic auctions still pass
I just needed to adjust 1 test case since the new logic is slightly more accurate. Instead of `to_eth(user_surplus) + to_eth(fees)` we now do `to_eth(user_surplus + fees)` which does one fewer conversions, avoiding the loss of precision of the …

Refactor scores autopilot

---

crates/e2e/tests/e2e/limit_orders.rs
crates/orderbook/src/database/orders.rs
crates/shared/src/db_order_conversions.rs

Currently we always expose the metadata of an order's quote. This basically contains the execution plan used to generate the quote. If this is made public while an order is still fillable you could theoretically have a solver that just tries to copy the quote's execution plan. That could lead to quoters not providing their best solution because they are afraid that the copy solver would snipe their order.
If we only show the execution plan after an order is no longer fillable this strategy will no longer work and the incentives of the quote competition remain unchanged (compared to never showing the execution plan like we did before).
We now hide a quote's `metadata` until an order is no longer fillable.
Adjusted an existing e2e test

Hide quote execution plan

---

crates/orderbook/src/api/post_quote.rs
crates/shared/src/order_quoting.rs
crates/shared/src/order_validation.rs

Currently, it's quite difficult to understand why a quoting competition failed. All the estimators use the same error struct and much more time than anticipated needs to be spent to find the cause of the problem.
The issue that inspired me to open this PR was the unstable quoting results for a particular token pair. If I filter the logs by this pair, with this PR, I will easily see the list of all the errors and can decide what the majority of the causes are. With any extra step, this won't be possible(as right now). I would need to get the request ID each time. This is a very annoying problem in other backend components, which is much harder/impossible to address.
Observe logs.
Sampled log:
```
2025-04-25T10:23:39.841Z  WARN request{id="1"}: orderbook::api::post_quote: post_quote error …
```

[PoC] Improve price estimation error

---

crates/driver/src/boundary/liquidity/balancer/v2/mod.rs
crates/driver/src/boundary/liquidity/uniswap/v3.rs
crates/driver/src/infra/config/file/load.rs
crates/driver/src/infra/config/file/mod.rs
crates/driver/src/infra/liquidity/config.rs
crates/solver/src/liquidity_collector.rs

Currently our subgraph based liquidity sources (balancer v2, uniswap v3) fetch the list of known pools only on startup. This currently leads to frequent requests why some pool does not get indexed (e.g. baseline router is not returning quotes although there is a pool it could use).
The optimal solution would be to build our indexing logic such that it only queries pools that were created since we last checked. However, that would be pretty involved and overall it doesn't make much sense to spend much effort on liquidity indexing since none of the competitive solvers use our indexed liquidity anyway.
To keep the effort to a minimum I adjusted the `BackgroundInitLiquiditySource` logic such that it can be configured to periodically rerun the initialization logic. This is effectively …

Reinit subgraph liquidity sources

---

.github/workflows/pull-request.yaml

Seems like the latest `foundry` release (v1.1.0) introduced a bug in anvil that causes our forked e2e tests to fail.
It looks like there is some sort of race condition that can cause `anvil` to get stuck (perhaps deadlock?) after an `evm_mine` call. This is based on observations from this [test run](https://github.com/cowprotocol/services/actions/runs/14878604711/job/41781127003?pr=3377).
Here we can see that at some point our calls to our price estimators are timing out after 5s. Exactly 5s before that we see that `anvil` started to process an `evm_mine` request but never finished (finished requests result in logs like `finished processing request` from the `tower` crate).
Screenshot to avoid logs from the job getting deleted in the future.
Reverts back to foundry 1.0.0 (only for forked …

Revert back to `foundry v1.0.0` for forked e2e tests

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/run_loop.rs
crates/autopilot/src/shadow.rs

It doesn't make sense to allow the value `0` for `--max-winners-per-auction` and `--max-solutions-per-solver` so we switched from `usize` to `NonZeroUsize`.

Trivial: Use NonZeroUsize for CLI args

---

crates/autopilot/src/database/competition.rs
crates/autopilot/src/domain/competition/mod.rs
crates/autopilot/src/domain/competition/winner_selection/max_score.rs
crates/autopilot/src/domain/competition/winner_selection/mod.rs
crates/autopilot/src/run_loop.rs
crates/e2e/tests/e2e/limit_orders.rs

Extracts the arbitration logic into a new trait which allows swapping out the core logic with combinatorial auctions using CLI arguments. This is an alternative to https://github.com/cowprotocol/services/pull/3359 which simplifies a few things.
Reverts back current logic to always return just 1 winning solver. While the DB is able to handle multiple winners there is no reward mechanism in place for the current logic so we can't enable it in practice anyway.
This causes multi winner tests to fail. Since this is, again, still not used in production and a follow up PR brings back multi winners with combinatorial auctions I decided to simply comment out these tests.
I also turned `RunLoop::competition()` into `RunLoop::fetch_solutions()` which only fetches the solutions and applies the …

Abstract winner selection

---

crates/autopilot/src/run_loop.rs

Recently we experienced some serious degradation when we needed to use a fallback node provider which had high latency. This resulted in up to 4s between the autopilot cutting an auction and the drivers receiving the request. The reason was that the participation guard (to check whether a solver is eligible to participate in the current auction) awaits an RPC request before we send out the `/solve` request to the driver.
Additionally it looked like these individual RPC requests were not batched together by our auto batching logic. The end result basically looked like what you would expect from this code:
```rust
for driver in &drivers {
if !check_allowed().await {
anyhow::bail!("solver deny listed");
}
tokio::task::spawn(driver.send_request())
}
```
There are a few things which we need to …

Run participation guard in background

---

crates/driver/src/infra/observe/mod.rs

When logging the number of pools collected for each liquidity source we collect them into a map to print a small overview.
Currently the order in which these sources get printed is not stable because we use a `HashMap`.
Replace `HashMap` with `BTreeMap` to have a consistent iteration and therefore logging.

Trivial: log liquidity sources consistently

---

crates/autopilot/src/infra/solvers/dto/solve.rs
crates/autopilot/src/infra/solvers/mod.rs
crates/autopilot/src/run_loop.rs
crates/autopilot/src/shadow.rs

Follow up to https://github.com/cowprotocol/services/pull/3386 since that actually did not resolve the issue.
We still have the problem where the first driver can see an auction sometimes multiple seconds before the last driver.
It turns out the problem is how we send out the requests. There are 2 main problems with our current approach:
1. the request is huge and we re-serialize it for each driver (this can take ~200ms)
2. we serialize the request in our main task
Both issues combined lead to the autopilot getting blocked for 200ms per driver. In the grand scheme of things this effectively turns our request sending from concurrent to serial. So if we have 20 solvers the last one could see the auction ~4s later than the first driver.
I tackled `1` by introducing a new type that serializes …

Optimize `/solve` request serialization

---

crates/driver/src/infra/blockchain/contracts.rs
crates/driver/src/infra/blockchain/token.rs

Currently we store a few redundant pieces of information in the `Erc20` type. We create many instances of this type and these redundant fields bloat the memory usage. Since the type already contains the `Ethereum` type which holds all the necessary contract instances we can just look them up there instead.
- moved `Balances` helper contract into `Ethereum`
- dropped `balances`, `vault_relayer` and `vault` fields from `Erc20`
no logic changes -> e2e tests should be sufficient

Remove redundant data from `Erc20` type

---

crates/autopilot/src/run_loop.rs

After experimenting a bit more with the autopilot submission logic I settled on spawning a task per solve request in the autopilot. The impact can be seen somewhat in the baseline solver solving time (left before, right after the change) where data points higher up are better (more time to compute solutions).
Spawn a separate task per solve request.
Tested in shadow mainnet and measured using metrics

Spawn a task per solve request

---

crates/app-data/src/app_data.rs
crates/driver/src/domain/competition/order/app_data.rs

To support flashloans in the reference driver we added the logic to lookup the full JSON that is associated with an appdata hash. The logic previously fetched the JSON from the orderbook and revalidated it.
Now one solver team reported that the appdata reported by the driver does not match the appdata shown in the explorer.
This is the case for <https://api.cow.fi/xdai/api/v1/app_data/0xf249b3db926aa5b5a1b18f3fec86b9cc99b9a8a99ad7e8034242d2838ae97422>. When we manually rehash the data stored in the backend we arrive at the hash `0x0fa8041819d62080e9d0ba2285696640270550336299729a441dfdceceac509d` instead of `0xf249b3db926aa5b5a1b18f3fec86b9cc99b9a8a99ad7e8034242d2838ae97422` which indicates the we somehow associated the hash incorrectly in the DB.
While this is an issue and we would …

Only parse and not re-hash appdata

---

crates/driver/src/infra/observe/metrics.rs
crates/driver/src/infra/observe/mod.rs
crates/driver/src/infra/solver/mod.rs

Currently we don't have good data on how long solvers have to compute their solution. We do have a dashboard that shows the remaining time as observed by the solver engine. While this is the most accurate way to measure this we also only have data for very few solvers.
- measure remaining solve time right before driver starts sending the request.
- measure how long the solver needed to report back a solution
- deployed on shadow mainnet and checked the presence of the data with grafana

Add metrics for solve times in driver

---

crates/driver/src/domain/competition/auction.rs

The pre-processing step is shared for all connected solvers and makes up the majority of the latency introduced by the driver. Speeding this up will benefit all solvers connected to a reference driver.
I changed the order of operations slightly to break up dependencies allows us to run every async task concurrently.
Before the PR we fetched all cow amm orders, appended them to the list of all orders and then fetched the balances for those. That meant we can only fetch balances after we got all the cow amm orders. However, the fetched balances are only needed for things that don't apply to cow amm orders. We don't need to double check the balances of the cow amm order owners because the helper contract that generates the template orders already takes current balances into account.
So now …

Parallize pre processing further

---

crates/solvers/src/domain/solution.rs
crates/solvers/src/tests/cases/limit_order_quoting.rs

When testing on new networks where the settlement contract buffers are empty, baseline solver solutions couldn't be verified due to on-chain reverts that showed a 1 unit higher out amount calculated by the solver compared to the values returned by liquidity pools. After testing it with different liquidity pools separately(uniswap and balancer), it became apparent that there is an issue on the baseline's side.
When calculating the buy amount for sell orders, `ceil_div` was used, probably because the settlement contract uses it. But from the solver's perspective, it should be a `floor` operation to avoid providing too good solutions. This PR addresses it.
It is hard to validate on the existing networks, but pretty straightforward on new ones, such as Polygon. No more reverts with the …

[EASY] Fix baseline buy amount calculation

---

crates/driver/src/domain/competition/order/mod.rs
crates/driver/src/domain/competition/sorting.rs

The sorting of orders based on priority takes a non-trivial amount of time. I ran a few experiments and using `f64` instead of `BigRational` for the comparison speeds up the process visibly.
Replace `BigRational` with `OrdFloat` - a helper type which allows us to use a simple `f64` for sorting purposes.
Also since the `likelihood` function was only used in the sorting logic I moved it there.
Ran the experiment on shadow mainnet resulting in modest speed improvements.
This shows only the sorting step and indicates that it goes from 100-250 to the 50-100ms bucket.

Speed up order prioritization

---

crates/driver/src/boundary/mod.rs
crates/driver/src/infra/blockchain/contracts.rs
crates/driver/src/infra/blockchain/mod.rs
crates/driver/src/infra/cli.rs
crates/driver/src/run.rs
crates/driver/src/tests/setup/solver.rs

Currently the driver runs all rpc requests with a hardcoded 20, 10 for `max_requests_per_batch` and `max_concurrent_requests`. For other binaries, we override this value in infra to be 40, 20 (cf. [infra](https://github.com/cowprotocol/infrastructure/blob/43c42bae52e6c2b9d525e08b875321fdce8f7073/services/config/rpc.ts#L23))
At the same time we are seeing significant performance issues ([slack](https://cowservices.slack.com/archives/C0361CDD1FZ/p1747920216957199)) when not using RPC nodes that are inside our cluster. After inspecting the RPC performance itself our current assumption is that the added network latency from going over the internet is the root cause. This overhead should be controllable by batching more.
CI
#3409

Allow to specify rpc batching config in driver binary

---

.github/workflows/pull-request.yaml

After switching to the latest foundry release the forked tests became flaky again. Seems like I didn't run the tests often enough to verify that the new version is indeed stable.
Will try to debug the foundry
Switch back to foundry `v1.0.0` for forked tests.
Use flaky test runner to verify fix

Revert #3417 (switch foundry version)

---

crates/driver/src/domain/competition/mod.rs

Some solvers simulate their solutions internally and don't just wait for the driver to simulate their final solution. These solvers need to built custom handling for flashloan orders before they can solve them. To not have these solvers waste time on orders they will not be able to build working solutions for anyway I adjusted the driver to filter out flashloan orders if special support for them was disabled.
Don't send flashloan orders to solvers which don't have support for them. Since we first need to look up an order's appdata document to know whether it is a flashloan order or not the required config options are:
```
app-data-fetching-enabled = true # to fetch the appdata
orderbook-url = "https://api.cow.fi/mainnet/" # to fetch the appdata
flashloans-enabled = false # to filter …
```

Filter out unsupported flashloan orders

---

crates/autopilot/src/boundary/events/settlement.rs
crates/autopilot/src/database/ethflow_events/event_storing.rs
crates/autopilot/src/database/onchain_order_events/ethflow_events.rs
crates/autopilot/src/database/onchain_order_events/mod.rs
crates/autopilot/src/run.rs
crates/database/src/ethflow_orders.rs
crates/database/src/onchain_broadcasted_orders.rs

Currently, determining the start block of indexing ethflow events on fresh chains with no corresponding orders/refunds requires using an RPC node that has access to either the ethflow or settlement contract deployment blocks. 
When dealing with pruned full nodes as a primary transport, a solution for that could be to use an archive node for the initial start that will index all the old blocks, and then switch back to the pruned one. With the current implementation, that is not possible, which still requires access to either the ethflow db data or the contract deployment block. Another ethflow indexing start block or even "skip indexing" flag can be provided via the config to solve this, but the autopilot's logic remains outdated.
With #3075, this logic can be simplified by relying on the …

Simplify ethflow indexing start block search

---

crates/autopilot/src/domain/competition/mod.rs
crates/autopilot/src/domain/competition/winner_selection/combinatorial.rs
crates/autopilot/src/domain/competition/winner_selection/mod.rs

The `Arbitrator` trait expects the solutions to be sorted in a particular way: winners before losers, high scores before low scores.
This is currently not enforced. A wrong ordering will result down the line with solutions being stored in the wrong order in the solver competitions table. This results in the possibly wrong ordering in the solver competitions and order status API endpoints.
Effectively this now also ensures that the order status endpoint will do the right thing when we switch to combinatorial auctions.
Implement correct sorting in the combinatorial auctions implementation.
Assert ordering in unit tests.
Also adjusted unit tests to enforce winners to be specified in that same order as well. This was not needed but seems nicer for consistency. No such ordering was enforced …

Fix sorting of ranked solutions

---

crates/driver/src/domain/competition/order/mod.rs
crates/driver/src/domain/competition/solution/encoding.rs
crates/driver/src/domain/competition/solution/mod.rs
crates/driver/src/domain/competition/solution/trade.rs
crates/driver/src/infra/solver/dto/solution.rs
crates/driver/src/tests/cases/flashloan_hints.rs
crates/driver/src/tests/setup/blockchain.rs
crates/driver/src/tests/setup/mod.rs
crates/driver/src/tests/setup/solver.rs
crates/e2e/tests/e2e/cow_amm.rs
crates/e2e/tests/e2e/jit_orders.rs
crates/solvers-dto/src/solution.rs
crates/solvers/src/api/routes/solve/dto/solution.rs
crates/solvers/src/domain/solution.rs

The driver aims to abstract flashloan handling for orders completely away from the solver (if they don't want to handle that themselves). That means the driver should also offer a reasonable amount of protection.
Added a sanity check in the driver to verify that the funds paid by flashloan orders indeed cover the repayment cost of the flashloans.
It's admittedly a bit ugly to only detect this case when we encode the solution but that's currently the only place where we have all the necessary data.
Initially adjusted the flashloan e2e test to trigger the issue where the driver allows executing flashloans for orders which don't cover the repayment cost.
After the fix was implemented the driver refused to submit these problematic solutions.

Detect under funded flashloans

---

crates/autopilot/src/database/onchain_order_events/mod.rs
crates/autopilot/src/infra/blockchain/contracts.rs
crates/autopilot/src/run.rs
crates/database/src/orders.rs
crates/e2e/src/setup/services.rs
crates/e2e/tests/e2e/ethflow.rs
crates/orderbook/src/arguments.rs
crates/orderbook/src/run.rs
crates/shared/src/arguments.rs
database/README.md
database/sql/V085__interactions_unique_constraint.sql

Fixes: https://github.com/cowprotocol/services/issues/3388
Currently ethflow orders don't have their hooks executed. The reason is that ethflow orders don't get added to the order book via a REST API call which would execute the usual code paths. Instead the autopilot indexes events emitted from certain contracts and adds it to the orderbook that way. This executes a bunch of different code paths that actually didn't check the hooks at all.
- moved `--hooks-contract-address` into shared args because the `autopilot` now needs it too
- during ethflow event indexing we now fetch the associated appdata, parse it, and insert the trampolined hook interactions if there are any. This code is a bit awkward due to the existing abstractions. Ethflow orders are a special variant of the more generic …

Execute hooks of ethflow orders

---

crates/autopilot/src/run_loop.rs
crates/shared/src/bad_token/instrumented.rs
crates/shared/src/price_estimation/trade_finder.rs

Some of these warn statements are polluting our logs without actually triggering anything bad. This PR demotes them to debug logs for better signal/noise ratio
Once deployed, I hope the kibana logs are much more readable.

Demote some log statements from warn -> debug

---

crates/autopilot/src/database/competition.rs
crates/autopilot/src/domain/competition/participant.rs
crates/autopilot/src/domain/competition/winner_selection/combinatorial.rs
crates/autopilot/src/domain/competition/winner_selection/max_score.rs
crates/autopilot/src/domain/competition/winner_selection/mod.rs
crates/autopilot/src/infra/persistence/mod.rs
crates/autopilot/src/run_loop.rs
crates/autopilot/src/shadow.rs
crates/database/src/solver_competition.rs
crates/e2e/tests/e2e/solver_competition.rs
crates/model/src/solver_competition.rs
database/README.md
database/sql/V086__store_filtered_solutions.sql

Combinatorial auctions rely on a 2 step approach: (1) filter unfair solutions, (2) rank remaining solutions.
Currently we only store solutions that are left over after step `2` but for better observability and sanity checking individual auctions we should also store solutions that got filtered out in the first step.
- refactor `Arbitrator` logic to make it a bit nicer to work with
- DB migration to add `was_filtered` column to `proposed_solutions` table (+ update for README)
- store discarded solutions in 2 places:
- legacy JSON blob that stores the whole auction data
- `proposed_solutions` table
I added an e2e test that uses 2 solvers that return hand crafted solutions to ensure that one of them will be considered unfair and filtered out during the first phase of the combinatorial …

Store filtered out solutions in the DB

---

crates/orderbook/openapi.yml

The OpenAPI spec is not up to date with the data returned in the corresponding endpoint, as the endpoint returns multiple transaction hashes to support multiple winners (ref #3049) but the OpenAPI still defines it as a single value.
This PR updates the field to be an array and updated the name to match the field.

chore(OpenAPI): SolverCompetition transactionHash should be an array

---

crates/e2e/src/nodes/local_node.rs
crates/e2e/tests/e2e/place_order_with_quote.rs
crates/e2e/tests/e2e/replace_order.rs
crates/e2e/tests/e2e/submission.rs

The test was flaky, because the assertion needed to happen in a certain time window after the order was submitted and auction happened, but before the order was filled. 
There are 2 parts to the MR:
* first disable forging blocks after setup, then posting the order and initiating the auction by minting a single block, which takes us to the point where we can wait for the order to be bid on, but it will never get executed as that would require mining more blocks
* extending the test by allowing the order to be filled afterwards and making sure it can't be replaced

Fix replace order test flakiness

---

crates/driver/src/domain/liquidity/balancer/v2/weighted.rs

The metri team reported [[slack](https://cowservices.slack.com/archives/C036MD8ADMG/p1751385358082819)] that we couldn't compute a native price for `0x31b32b96049f8fd24969611252c4e44a1b4a07eb` on gnosis chain although there are 2 pools for that token:
* a uniswap v3 [pool](https://oku.trade/app/gnosis/pool/0x2cb844B91212a4a5a1C6c70F0304edED3e4E0b8A?isFlipped=false)
* a balancer v2 liquidity bootstrapping [pool](https://balancer.fi/pools/gnosis/v2/0x34414fd9af0d38a9f1cc69cd1abb8f1d4ddd9519000200000000000000000150) (LBP)
The subgraph we use for uniswap v3 doesn't index the first pool - we can't do anything about that. But the balancer subgraph has the second pool indexed.
The issue is that the weights of the balancer pool don't add up to 1 which causes us to discard that pool before we send …

Remove balancer weighted pools weights check

---

database/sql/V087__add_primary_key_to_order_events.sql
database/sql/V087__set_replica_identity_full_for_order_events.sql

This PR addresses a recurring database error that prevents the successful cleanup of old records from the `order_events` table.
> 2025-07-01T09:04:00.609Z  WARN order_events_cleaner: autopilot::periodic_db_cleanup: failed to delete order events before 2025-06-01 09:04:00.604091056 UTC err=Database(PgDatabaseError { severity: Error, code: "55000", message: "cannot delete from table \"order_events\" because it does not have a replica identity and publishes deletes", detail: None, hint: Some("To enable deleting from the table, set REPLICA IDENTITY using ALTER TABLE."), position: None, where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("execReplication.c"), line: Some(692), routine: Some("CheckCmdReplicaIdentity") })
This also enables us to use …

fix(database): Set replica identity for order_events

---

crates/observe/src/distributed_tracing/trace_id_format.rs

Some of our log processing components expect every new line to start with a timestamp and a recent change where we introduced trace ID in the beginning of lines broke this. This PR changes it so trace IDs are appended instead. 
New output looks like this:
```
2025-07-09T14:59:19.707Z  INFO current_block_stream: ethrpc::block_stream: noticed a new block number=22882375 hash=0xdc06af00cce033449905a942d578e2dadfdca6e8f5fd33a65ba394d084cbe318 [trace_id 282c260b4c4be165971c9aad02caa644]
```

Append trace id instead of prepending

---

crates/solvers/src/boundary/liquidity/concentrated.rs

In #3468, I forgot to remove a constant.

[TRIVIAL] Drop a redundant constant

---

crates/shared/src/signature_validator/simulation.rs

Recently I wanted to debug why a signature verification failed only to realize that the inputs only get printed after a successful simulation which defeats the purpose.
Emit log before unpacking the error.
compiler

[TRIVIAL] Fix signature verification log

---

crates/ethrpc/src/block_stream/mod.rs

Sometimes we have an issue with the stuck current block stream. The idea is to allow info-level logs. This PR raises the loop break log to the corresponding level to observe the error and to understand the cause of the problem better.

[EASY] Info log when exit the current block stream loop

---

crates/orderbook/src/database/trades.rs

`sqlx` panics when you try to pass `> u16::MAX` arguments in your query. This currently happens when somebody requests the trade history of the ethflow contract which has ~230K trades.
example [logs](https://aws-es.cow.fi/_dashboards/app/data-explorer/discover#?_a=(discover:(columns:!(log,log_level),isDirty:!f,sort:!()),metadata:(indexPattern:'86e4a5a0-4e4b-11ef-85c5-3946a99ed1a7',view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2025-07-10T19:22:58.372Z',to:'2025-07-10T20:31:49.345Z'))&_q=(filters:!(),query:(language:kuery,query:'2bfd91b81a897c0e21e06210fdbdbe41'))) showing the panic
To find the most likely culprit I ran this query:
```sql
SELECT encode(o.owner, 'hex') as owner, COUNT(*) AS trade_count
FROM trades t
JOIN orders o ON t.order_uid = o.uid
GROUP …
```

Return an error when we'd pass to many arguments in an SQL query

---

crates/database/src/solver_competition_v2.rs
crates/orderbook/src/database/solver_competition_v2.rs

Fixes an SQL issue mentioned in #3481:
> The following error was noticed in the logs:
> ```
> 2025-07-11T11:38:02.553Z ERROR request{id="881fab40fb9666ccd88bc5e7abb8ef06"}: orderbook::api::get_solver_competition_v2: load solver competition err=solver_competition::load_by_tx_hash
> 
> Caused by:
>     0: error occurred while decoding column 0: unexpected null; try decoding as an `Option`
>     1: unexpected null; try decoding as an `Option`
> ```
This change ensures that `load_by_tx_hash` handles cases where `settlements.auction_id` is NULL.
- Uses Option<i64> in the SQLx query to avoid runtime decoding errors when the column is null.
- Applies `.flatten()` to handle the Option<Option<_>> from fetch_optional. An alternative solution is to declare a wrapper struct, which contains an …

[EASY] Fix `solver_competition_v2::load_by_tx_hash` SQL query

---

crates/shared/src/arguments.rs

The span we start in make_span() for warp was not being displayed in logs, because we had `warn` set for the `observe` module in which the span originates. We want to display this span, because it contains a request ID, which makes it easy to correlate logs.

Enable spans from observe crate

---

Cargo.lock
Cargo.toml
crates/driver/src/domain/competition/auction.rs
crates/ethrpc/Cargo.toml
crates/ethrpc/src/alloy/instrumentation.rs
crates/ethrpc/src/alloy/mod.rs
crates/ethrpc/src/lib.rs

To aid a piecewise migration towards alloy we need to start by making the alloy `Provider` equivalent to our current `Web3` provider.
This PR implements the instrumentation aspect of our current transport. As a reminder this is what we want to support:
* providers can be "labeled" - every request coming through this provider should get this label
* you can take a labeled provider, attach another label to it, and get a new provider with both labels on it
* we collect metrics for each RPC request based on the provider it came from
- bump `itertools` to `0.14` to avoid a version conflict with `alloy`
- replace deprecated `group_by` call with equivalent `chunk_by`
- add `alloy` as a workspace dependency pinned to this upstreamed [commit](https://github.com/alloy-rs/alloy/pull/2672) because we …

Implement instrumentation layer with alloy

---

crates/e2e/src/setup/mod.rs
crates/observe/src/config.rs
crates/observe/src/panic_hook.rs
crates/observe/src/tracing.rs
crates/refunder/src/arguments.rs
crates/shared/src/arguments.rs

Follow up item of a post mortem.
During the post mortem it was discussed that we did not get any slack alerts despite emitting logs with the `error` log level. It was stated that it was a deliberate decision to stop emitting these errors as slack alerts due to noisy. However, my investigation suggests that this was not deliberate and the functionality simply broke in #2868.
The infra repo still configures `stderr_threshold` as `error` and the `stderr_threshold` config was never optional so some number of logs was always expected to go to stderr.
- fixed the bug that caused us to stop writing to stderr for logs that had the correct level
- made `stderr_threshold` optional and disabled by default
- converted `LevelFilter` config member arguments to `Level` as that can better express …

Fix `stderr_threshold` setting

---

crates/observe/src/tracing.rs

This field needs to be set on the layer as well as on the custom formatter as it's being propagated to other structs (not just the formatter). This was mistakenly removed in https://github.com/cowprotocol/services/pull/3491

Add ansi to fmt layer

---

crates/driver/src/domain/competition/auction.rs
crates/driver/src/domain/competition/mod.rs
crates/driver/src/domain/competition/solution/settlement.rs
crates/driver/src/infra/api/routes/solve/dto/solve_request.rs
crates/driver/src/infra/solver/mod.rs
crates/driver/src/util/http.rs
crates/solver/src/liquidity/balancer_v2.rs
crates/solver/src/liquidity/uniswap_v2.rs
crates/solver/src/liquidity/uniswap_v3.rs
crates/solver/src/liquidity/zeroex.rs
crates/solver/src/liquidity_collector.rs

To get more visibility into where we spend time the /solve endpoint we can instrument the functions in that flow and look up Grafana.
I deployed this branch to sepolia staging and looked up traces in Grafana.

Instrument drive solve fns

---

crates/ethrpc/src/block_stream/mod.rs

We investigated an issue where our event handling logic did not correctly handle a reorg on polygon. One idea was that we might be getting inconsistent block ranges from our node. This initially did not have much credibility because we assumed we use a specific `eth_` call for fetching a whole block range where inconsistencies would be very surprising.
However, we are actually just sending a batch RPC call with many `eth_getBlockByNumber n`, `eth_getBlockByNumber n+1`, ... With that logic the possibility of receiving inconsistent results from the node seems more likely.
In the specific case we debugged there were actually multiple reorgs happening on top of each other so perhaps the node processed some blocks between the eth calls leading to an inconsistent block range.
Updated `blocks()` …

Detect reorgs in block range

---

crates/shared/src/price_estimation/buffered.rs
crates/shared/src/price_estimation/native_price_cache.rs
crates/shared/src/price_estimation/sanitized.rs
crates/shared/src/price_estimation/trade_finder.rs
crates/shared/src/trade_finding/external.rs

Looking at [a sample trace](https://g-0263500beb.grafana-workspace.eu-central-1.amazonaws.com/explore?schemaVersion=1&panes=%7B%22is4%22%3A%7B%22datasource%22%3A%22aess0ehg3ludcb%22%2C%22queries%22%3A%5B%7B%22query%22%3A%22a5ff616eb36199c01b78cacfe18da481%22%2C%22queryType%22%3A%22traceql%22%2C%22refId%22%3A%22A%22%2C%22datasource%22%3A%7B%22type%22%3A%22tempo%22%2C%22uid%22%3A%22aess0ehg3ludcb%22%7D%2C%22limit%22%3A20%2C%22tableType%22%3A%22traces%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%221753364224905%22%2C%22to%22%3A%221753367824905%22%7D%7D%7D&orgId=1) I found that "estimator" is taking a long time, but most of the time is not accounted for. After going through the code I am led to believe it's the get_trade() function.

Instrument more i/o functions

---

crates/database/src/trades.rs
crates/ethrpc/src/extensions.rs
crates/orderbook/src/database/trades.rs

The instrument macro doesn't instrument a sync function that returns a future properly, we need to wrap that future in Instrument instead. This came up after looking at the values in Grafana where this span length was in microseconds.

Fix eth call and trades() instrumentation

---

crates/autopilot/src/solvable_orders.rs
crates/shared/src/price_estimation/native_price_cache.rs

* adds logs that should help with debugging https://github.com/cowprotocol/services/issues/3562
* I used `trace` level as we don't always want to have these logs enabled
* also replaces an if-block with an early return to reduce rightward drift
* uses `const` API to create a target duration
no logic changes - compiler and existing tests should suffice

[TRIVIAL] Native price cache logs

---

crates/database/src/orders.rs

In https://github.com/cowprotocol/services/pull/3542 we improved the performance of loading live orders on `autopilot` startup, but it turns out that this made the performance of counting orders per user worse: [grafana](https://g-0263500beb.grafana-workspace.eu-central-1.amazonaws.com/explore?schemaVersion=1&panes=%7B%22zj9%22:%7B%22datasource%22:%225An5Ejq4k%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22rate%28gp_v2_api_orderbook_database_queries_sum%7Btype%3D%5C%22count_limit_orders_by_owner%5C%22,%20network%3D%5C%22mainnet%5C%22%7D%5B5m%5D%29%20%2F%20rate%28gp_v2_api_orderbook_database_queries_count%7Btype%3D%5C%22count_limit_orders_by_owner%5C%22,%20network%3D%5C%22mainnet%5C%22%7D%5B5m%5D%29%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheu …

Use old live orders query for counting orders per user

---

README.md

Removes test-specific commands to avoid documentation rot
Read the README 😄

Remove test-specific commands from README

---

crates/driver/src/domain/competition/bad_tokens/mod.rs

`update_orders` is on the critical path inside the auction pre-processing phase. The majority of runtime was dictated by running `join_all` and allocating memory. This PR optimizes both of these things.
Instead of creating a future for all orders even when only 1 branch actually returns a future we now separate out only the futures that actually need to run.
Also instead of collecting results into different vectors we now reuse the original `orders` vector. First we discard the clearly unsupported and questionable orders (questionable orders are the ones that we run a future for) and later we put back the questionable orders that came back okay.
ran experiment on shadow environment and compared flamegraphs. I highlighted the `get_token_quality` function show how much more time is now …

Speed up `update_orders` pre-processing step

---

crates/driver/src/infra/blockchain/token.rs

Drops the `from` field from the access lists call since it currently fails on every chain. This logic was initially added when adapting services for the Lens chain, where `from` is required, but since access lists are not supported on ZKSync, we can simply remove it.

Drop `from` field from the access lists simulation call

---

crates/driver/src/infra/blockchain/token.rs

We currently get [logs](https://aws-es.cow.fi/_dashboards/app/data-explorer/discover#?_a=(discover:(columns:!(log,kubernetes.pod_labels.appClass,log_level,kubernetes.pod_labels.app),isDirty:!t,sort:!(!(timestamp,asc))),metadata:(indexPattern:'86e4a5a0-4e4b-11ef-85c5-3946a99ed1a7',view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2025-09-04T04:36:24.915Z',to:'2025-09-04T05:54:01.909Z'))&_q=(filters:!(),query:(language:kuery,query:'%22access%20list%22'))) of the node's `eth_createAccessList` method handler crashing. This is most likely due to the driver's request not specifying all the relevant data. At the very least we need `to` and `calldata`. Additionally `erigon` for gnosis chain expects `from` to be populated as well.
- specify the required pieces of data …

Fix eth_createAccessList call

---

crates/ethrpc/Cargo.toml
crates/ethrpc/src/alloy/mod.rs
crates/solver/Cargo.toml
crates/solver/src/liquidity/zeroex.rs

Removes the dummy alloy provider since it was overseen that a similar function already exists in `ethrpc::mock::web()` funciton.

[TRIVIAL] Remove dummy alloy provider

---

crates/ethrpc/Cargo.toml
crates/ethrpc/src/alloy/conversions.rs

Adds alloy's BlockId and BlockNumber conversions, which are required for further migration.

Alloy BlockId conversion

---

crates/contracts/Cargo.toml
crates/contracts/build.rs
crates/contracts/src/alloy.rs
crates/contracts/src/lib.rs
crates/e2e/Cargo.toml
crates/e2e/src/setup/mod.rs
crates/e2e/src/setup/onchain_components/alloy.rs
crates/e2e/src/setup/onchain_components/mod.rs
crates/e2e/src/setup/onchain_components/safe.rs
crates/e2e/tests/e2e/app_data.rs
crates/e2e/tests/e2e/app_data_signer.rs
crates/e2e/tests/e2e/banned_users.rs
crates/e2e/tests/e2e/buffers.rs
crates/e2e/tests/e2e/eth_integration.rs
crates/e2e/tests/e2e/eth_safe.rs
crates/e2e/tests/e2e/flashloans.rs
crates/e2e/tests/e2e/hooks.rs
crates/e2e/tests/e2e/order_cancellation.rs
crates/e2e/tests/e2e/place_order_with_quote.rs
crates/e2e/tests/e2e/quoting.rs
crates/e2e/tests/e2e/smart_contract_orders.rs
crates/e2e/tests/e2e/submission.rs
crates/e2e/tests/e2e/tracking_insufficient_funds.rs
crates/e2e/tests/e2e/uncovered_order.rs
crates/e2e/tests/e2e/vault_balances.rs
crates/ethrpc/Cargo.toml

Migrates the GnosisSafe* contracts to alloy-rs
Run all tests

Migrate GnosisSafe* contracts to alloy-rs

---

crates/ethrpc/src/alloy/mod.rs

Uses alloy's SimpleNonceManager to avoid needing to keep track of the nonces manually and basically do the same thing the nonce manager does.
N/A

Use alloy's SimpleNonceManager

---

crates/autopilot/src/database/competition.rs
crates/autopilot/src/infra/persistence/mod.rs
crates/autopilot/src/run_loop.rs
crates/database/src/solver_competition.rs

Currently saving solver competitions is quite slow (100ms-500ms with outliers going over 3s!). AFAICS the way we handle uploading the JSON is very suboptimal:
1. we do `serde_json::to_value()` while `sqlx` later does `serde_json::to_string()` - we might as well directly do the conversion to string ourselves
2. we block the runtime while we serialize the solver competition JSON. Instead we can offload the serialization to a blocking task and let it already do work while we continue with the other DB queries.
Upload the JSON by inserting a JSON string directly.
Offload the serialization to a blocking task and do the solver competition at the very end so we can already finish all the other DB queries in the mean time.
This required me to take the `SolverCompetition` as an owned value which …

Speed up saving solver_competitions

---

crates/contracts/Cargo.toml
crates/contracts/src/alloy.rs
crates/driver/Cargo.toml
crates/e2e/Cargo.toml
crates/e2e/src/setup/onchain_components/safe.rs
crates/e2e/tests/e2e/hooks.rs

As the name states. The send_and_watch function shortens it enough that the macro doesn't provide as much value in face of the cost of maintenance.
Run the existing tests

Remove alloy version of tx! macro

---

crates/contracts/src/alloy.rs
crates/contracts/src/lib.rs
crates/driver/src/infra/liquidity/config.rs
crates/shared/src/sources/swapr.rs
crates/shared/src/sources/uniswap_v2/mod.rs

Migrates the HoneyswapRouter SC to alloy
`fetch_honeyswap_pool` & the other tests

Migrate HoneyswapRouter to alloy

---

README.md

Updates the README to mention `just` commands that are used throughout the CI instead of the Github Actions source code directly.
CI commands mentioned in README.
N/A

Mention `just` commands in README

---

crates/shared/src/sources/uniswap_v3/graph_api.rs
crates/shared/src/sources/uniswap_v3/pool_fetching.rs

We currently filter UniV3 LPs based on `totalValueLockedETH`, which basically denominates raw `liquidity` in native token. For some of the pools, the subgraph shows `totalValueLockedETH=0`, which means that it can't find a path to denominate some tokens from the pool in the native token. That keeps some of the non-empty LPs unindexed.
Instead, rely on the raw `liquidity` value. We currently check for `totalValueLockedETH.is_normal()`, which allows up to the smallest possible f64, which is `~2.2250738585072014 × 10⁻³⁰⁸`, so using the raw liquidity amount shouldn't change any logic.

Filter UniV3 LPs based on raw liquidity

---

crates/contracts/build.rs
crates/contracts/src/alloy.rs
crates/contracts/src/errors.rs
crates/contracts/src/lib.rs
crates/driver/src/boundary/liquidity/uniswap/v2.rs
crates/driver/src/infra/blockchain/contracts.rs
crates/driver/src/tests/setup/blockchain.rs
crates/e2e/src/setup/onchain_components/mod.rs
crates/shared/src/sources/swapr.rs
crates/shared/src/sources/uniswap_v2/mod.rs
crates/shared/src/sources/uniswap_v2/pool_fetching.rs
crates/solver/src/interactions/uniswap_v2.rs
crates/solver/src/liquidity/uniswap_v2.rs

This reverts #3679 and #3685, which introduced a bug when using pancake-swap UniV2 liquidity source on BNB. The stacktrace is not clear, but disabling this liquidity source resolved the issue. It is not reproduced on other UniV2 presets, other than pancake-swap. So it needs to be investigated separately what causes those panics.
```
2025-09-22T08:58:12.122Z ERROR observe::tracing: thread 'main' panicked at /src/crates/driver/src/run.rs:197:10:
initialize liquidity fetcher: Boundary(failed to receive response from batching layer background task: Canceled
Caused by:
failed to receive response from batching layer background task: Canceled)
stack backtrace:
0: observe::tracing::tracing_panic_hook
at ./src/crates/observe/src/tracing.rs:183:21
1: <alloc::boxed::Box<F,A> as …
```

Revert #3679 and #3685

---

crates/autopilot/src/solvable_orders.rs

There was a small issue in https://github.com/cowprotocol/services/pull/3688. It only shortcutted the task to fetch the balances but it didn't adjust the logic that uses the now un-fetched balances to filter out orders.
now we actually don't run the order filtering logic based on balances depending on the new flag.

[TRIVIAL] Fix disable order filtering flag

---

crates/autopilot/src/domain/auction/mod.rs
crates/autopilot/src/domain/auction/order.rs
crates/autopilot/src/domain/eth/mod.rs
crates/autopilot/src/domain/fee/mod.rs
crates/autopilot/src/domain/settlement/auction.rs
crates/autopilot/src/domain/settlement/mod.rs
crates/autopilot/src/domain/settlement/trade/mod.rs
crates/autopilot/src/infra/persistence/mod.rs
crates/bytes-hex/src/lib.rs

Currently the autopilot's maintenance tasks that it runs between 2 auctions is very slow. The biggest time sink is currently indexing new settlement events. After some investigation it became apparent that the DB query we do to get all the necessary data for post-processing the auction is very slow (250ms - 500ms).
There are 2 reasons for that:
1. we fetch all the data from the given auction - not just what we actually need
2. we do multiple DB queries instead of doing 1 big query
Because this is a very important query I didn't go ahead and tested the performance in the actual cluster yet. ☝️ is just the status quo.
This PR addresses both of these issues. So far I only tested it with a few hand crafted test queries but they were in the ball bark of 1-2ms execution time.
Because we return …

Speed up settlement indexing

---

crates/autopilot/src/infra/persistence/mod.rs

I accidentally removed one useful metric in https://github.com/cowprotocol/services/pull/3654 see [here](https://github.com/cowprotocol/services/pull/3654/files#diff-2aa96c62abd5673078cf88346c59920ddf3563f6e6b2a8644dd3871c6431576dL333-L336).
Brings back the histogram timer for the `get_auction` DB query

[TRIVIAL] Bring back DB metrics

---

crates/autopilot/src/arguments.rs
crates/autopilot/src/database/events.rs
crates/autopilot/src/database/onchain_order_events/ethflow_events.rs
crates/autopilot/src/database/onchain_order_events/event_retriever.rs
crates/autopilot/src/database/onchain_order_events/mod.rs
crates/autopilot/src/maintenance.rs
crates/autopilot/src/run.rs
crates/contracts/build.rs
crates/contracts/src/alloy.rs
crates/contracts/src/lib.rs

Migrates the CowSwapOnchainOrders contract/events to alloy
Bigger PR due to tests being biiiiig
There's some places where a bunch of `.into_alloy()` can be found, I didn't change the existing types due to being pervasive and didn't add conversion methods that do this internally to avoid adding more layers where a small bug can be found, the diff comes bigger in lines but at least it's easier to compare side by side
E2E

Migrate CowSwapOnchainOrders to alloy

---

crates/contracts/build.rs
crates/contracts/src/alloy.rs
crates/contracts/src/lib.rs

Migrates BalancerQueries to alloy bindings. This SC is used in the gnosis solvers repo. That would require some tiny changes in that repo to support this.

[EASY] Migrate BalancerQueries to alloy

---

database/sql/V092___drop_auction_orders_table.sql

In #3747, the `auction_orders` table is dropped, but since we now run 2 autopilots in parallel on each service restart, dropping the table right away would cause panics in the currently active autopilot, which is not aware of the latest changes. This PR drops the migration that would need to be added only in the next release.
Since the previous PR was already merged, it has been applied on staging already, which now requires manually altering the `flyway_schema_history` on each chain before merging this PR 😓

Drop V092 Flyway migration
